### ISSUE TITLE
Fallback for Url : to another Url 

### ISSUE THREAD

**Issue by vsahu1986** [bumptech/glide#606] opened 2015-09-01 11:26 UTC
#454 
#456 
#451 

 
    Glide.with(getActivity()).load(Utils.getYoutubeUrl(density, getArguments().getString(VIDEO_ID))).asBitmap().error(R.drawable.ic_error_icon).into(glideImageView);

I wish I could get Exception listener for 404 

like if particular url returns 404 then retry with fallback url instead of drawable .

Example Url1 - http://img.youtube.com/vi/watsQDZ3KNw/sddefault.jpg

if Url1 returns 404 then fallback 

http://img.youtube.com/vi/watsQDZ3KNw/mddefault.jpg

I am using Youtube Image API , which does always have mddefault.jpg and higher version might not available .

**Comment by vipinhelloindia** [comment] 2015-09-01 12:22
+1

**Comment by TWiStErRob** [comment] 2015-09-01 19:31
> I wish I could get Exception listener for 404

How about `.listener()` and it's `onException` method? You can inspect the exception (`instanceof`, `getMessage().contains()`) and figure out what to do. It's not convenient, but possible.

> like if particular url returns 404 then retry with fallback url instead of drawable .

That's what #451 is there for, put a +1 on that.

**Comment by vsahu1986** [comment] 2015-09-02 05:22
Thanks @TWiStErRob , I will give it a try , 

I really concern about the convenient way for 404 status

**Comment by sjudd** [comment] 2015-09-02 14:56
Looks like a duplicate of #451

**Closed by sjudd** 2015-09-02 14:56 UTC

**Comment by vsahu1986** [comment] 2015-09-28 10:29
Hi, @TWiStErRob 

I agree on Exception we can check for HTTP 404 and retry , 
Is there any way to inject RetryHandler for Max retry count for particular URL . 

    public class GlideYoutubeImageView extends ImageView {

    public GlideYoutubeImageView(Context context) {
        this(context, null);
    }

    public GlideYoutubeImageView(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public GlideYoutubeImageView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);


    }

    @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        Drawable placeholder = getDrawable();
        if (placeholder instanceof AnimationDrawable) {
            ((AnimationDrawable) placeholder).stop();
            Glide.clear(this);
        }

    }


    @Override
    public void setImageBitmap(Bitmap bitmap) {
        if (bitmap != null) FadingDrawable.setBitmap(this, getContext(), bitmap);
    }

    public void setImageBitmapWithoutAnimation(Bitmap bitmap) {
        super.setImageBitmap(bitmap);
    }

    public void loadUrl(final float density, final String videoId) {
        Glide.with(getContext()).load(Utils.getYoutubeUrl(density, videoId)).asBitmap().error(R.drawable.ic_error_icon).listener(new RequestListener<String, Bitmap>() {
            @Override
            public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
                e.printStackTrace();
                Log.e("model",model);
                if (isFirstResource)
                    loadUrl(1.5f, videoId);// this will keeping on adding the same request again after exception until Imageview detached 
                return false;
            }

            @Override
            public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
                if (isFromMemoryCache) {
                    setImageBitmapWithoutAnimation(resource);
                } else {
                    setImageBitmap(resource);
                }
                return true;
            }
        }).into(this);
    }
}

**Comment by TWiStErRob** [comment] 2015-10-02 13:05
This is an *untested* alternative solution:
```java
Glide.with(context).load(new YouTubeVideo("watsQDZ3KNw")).into(imageView);

// TODO https://github.com/bumptech/glide/wiki/Configuration#creating-a-glidemodule
class YouTubeGlideModule implements GlideModule {
	@Override public void applyOptions(Context context, GlideBuilder builder) {
	}
	@Override public void registerComponents(Context context, Glide glide) {
		glide.register(YouTubeVideo.class, InputStream.class, new YTVModelLoader.Factory());
	}
}

class YouTubeVideo {
	String id;
	public YouTubeVideo(String id) {
		this.id = id;
	}
	public String getSDUrl() {
		return String.format(Locale.ROOT, "http://img.youtube.com/vi/%s/sddefault.jpg", id);
	}
	public String getMDUrl() {
		return String.format(Locale.ROOT, "http://img.youtube.com/vi/%s/mddefault.jpg", id);
	}
}

class YTVModelLoader implements StreamModelLoader<YouTubeVideo> {
	private final ModelLoader<String, InputStream> loader;
	public YTVModelLoader(ModelLoader<String, InputStream> loader) {
		this.loader = loader;
	}
	@Override public DataFetcher<InputStream> getResourceFetcher(final YouTubeVideo model, final int width,
			final int height) {
		return new DataFetcher<InputStream>() {
			private DataFetcher<InputStream> fetcher;

			@Override public String getId() {
				return model.id; // assuming that if SDUrl failed once, it'll fail the next time
				// so it's better to cache MDUrl in that case for this video, forever
			}

			@Override public InputStream loadData(Priority priority) throws Exception {
				try {
					fetcher = loader.getResourceFetcher(model.getSDUrl(), width, height);
					return fetcher.loadData(priority);
				} catch (Exception ex) {
					if (fetcher != null) {
						fetcher.cleanup();
					}
					fetcher = loader.getResourceFetcher(model.getMDUrl(), width, height);
					return fetcher.loadData(priority);
				}
			}

			@Override public void cleanup() {
				if (fetcher != null) {
					fetcher.cleanup();
				}
			}
			@Override public void cancel() {
				if (fetcher != null) {
					fetcher.cancel();
				}
			}
		};
	}

	static class Factory implements ModelLoaderFactory<YouTubeVideo, InputStream> {
		@Override public com.bumptech.glide.load.model.ModelLoader<YouTubeVideo, InputStream> build(Context context,
				GenericLoaderFactory factories) {
			return new YTVModelLoader(factories.buildModelLoader(String.class, InputStream.class));
		}
		@Override public void teardown() {
		}
	}
}
```

**Comment by vsahu1986** [comment] 2015-10-05 06:51
Looks Feasible to my Solution , will try it . Thanks @TWiStErRob

**Comment by vsahu1986** [comment] 2015-10-05 06:56
1 Assuming that if SDUrl failed once, it'll fail the next time - it is not always true , there could be timeout or network error or connection error , 
2  so it's better to cache MDUrl in that case for this video, forever , - If some how I could check it is HTTP_404

**Comment by TWiStErRob** [comment] 2015-10-05 08:46
I used default ModelLoader<String, InputStream> for convenience and POC, you can simply write your own DataFetcher and do any networking (even two requests one after the other, the key is what you return) with any library. Take a look at [HttpUrlFetcher](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/data/HttpUrlFetcher.java) which is returned by default.

**Comment by gemiren** [comment] 2016-10-14 06:58
Is there a way to check the cache when trying to load the fallback url? The example code works great but it always loads the fallback url over the network instead of checking for cache first.

**Comment by TWiStErRob** [comment] 2016-10-14 18:37
With this solution you can't check cache, because there's no Glide load going on. You can however download the fallback image(s) once to your app's directory and then return a fetcher that loads that File.

Alternatively look around the other issues which deal with similar problems, or create a new one if you think your use case is different.

**Comment by benibela** [comment] 2020-02-17 12:58
I have tried to use that above code in [my app](https://github.com/benibela/videlibri/blob/7b124dfba3e6345064ff9a7276ab857c3ed7645e/android/android/src/de/benibela/videlibri/CoverLoader.kt#L24-L130) with okhttp after converting it to kotlin, but it has a real high processor usage after loading an image (300% indefinitely on the emulator). 

How could that happen?
