### ISSUE TITLE
Glide placeholders load drawable resources with wrong context

### ISSUE THREAD

**Issue by bherbst** [bumptech/glide#4692] opened 2021-11-19 16:54 UTC
**Glide Version**: 4.12.0

**Device/Android Version**: Explicitly tested on Pixel 5 running Android 12, but this is applicable to all devices and Android versions.

**Issue details / Repro steps / Use case background**: 

When using a placeholder resource ID like so, Glide uses an unexpected Context to load the drawable:

```kotlin
val options = RequestOptions().placeholder(R.color.some_color_resource)
Glide.with(imageView.context)
   .load("http://the.url")
   .apply(options)
   .into(imageView)
```

I would expect this to use the imageView's context to load the Placeholder (which in most cases would be an `Activity`), but in fact it uses the application context to load the image.

This is because `SingleRequest` [uses `glideContext` to load the drawable](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/request/SingleRequest.java#L410).

The reason we discovered this is this behavior **does not work well with dark mode**. Specifically, if the device is currently in dark mode but an application has set itself to `MODE_NIGHT_NO` via `AppCompatDelegate.setDefaultNightMode()` then the placeholder will be incorrectly loaded from `values-night`.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
val options = RequestOptions().placeholder(R.color.some_color_resource)
Glide.with(imageView.context)
   .load("http://the.url")
   .apply(options)
   .into(imageView)
```

**values/colors.xml**:
```xml
<color name="some_color_resource">#ff000000</color>
```

**values-night/colors.xml**:
```xml
<color name="some_color_resource">#ffffffff</color>
```

**SampleApplication.kt**:
```kotlin
class SampleApplication : Application {
  override fun onCreate() {
    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)
  }
}
```

**Comment by bherbst** [comment] 2021-11-19 17:19
As a short term fix we are getting the Drawable instance ourselves via `ResourcesCompat.getDrawable()` instead of letting Glide manage getting the drawable.

**Comment by connyduck** [comment] 2022-04-26 20:08
Would be great if this could be fixed

**Comment by kiskunk** [comment] 2022-10-10 10:45
Still waiting for a fix.

**Comment by TWiStErRob** [comment] 2022-10-10 11:09
Seems like a duplicate of https://github.com/bumptech/glide/issues/3778 and https://github.com/bumptech/glide/issues/3751, PR for fix in https://github.com/bumptech/glide/pull/4842

**Comment by sjudd** [comment] 2022-10-10 17:42
Duplicate of #3751

Thanks @TWiStErRob

**Closed by sjudd** 2022-10-10 17:42 UTC
