### ISSUE TITLE
java.lang.NullPointerException at com.bumptech.glide.manager.RequestTracker.clearRequests (RequestTracker.java:80)

### ISSUE THREAD

**Issue by erichkleung** [bumptech/glide#347] opened 2015-02-18 19:14 UTC
Sorry I can't give more context as to how/when this happened, just got picked up by our crash tracker

Caused by: java.lang.NullPointerException
       at com.bumptech.glide.manager.RequestTracker.clearRequests(RequestTracker.java:80)
       at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:190)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:62)
       at com.bumptech.glide.manager.RequestManagerFragment.onDestroy(RequestManagerFragment.java:69)
       at android.app.Fragment.performDestroy(Fragment.java:1913)

**Comment by sjudd** [comment] 2015-02-18 19:22
Looks like a duplicate of #322. If you're on 3.5.1 or later, please re-open and fill out [the template][1].

[1]: https://github.com/bumptech/glide/issues/new?body=**Glide%20Version/Integration%20library%20(if%20any)**:%0A**Device/Android%20Version**:%0A**Issue%20details/Repro%20steps**:%0A%0A**Glide%20load%20line**:%0A%60%60%60%0AGlide.with(context)...%3B%0A%60%60%60%0A%0A**Stack%20trace**:%0A%60%60%60%0Apaste%20stack%20trace%20here%0A%60%60%60

**Closed by sjudd** 2015-02-18 19:22 UTC

**Comment by erichkleung** [comment] 2015-02-18 19:40
Oops, didn't find it when I tried to search for `clearRequests` or `RequestTracker`.  I'm on 3.5.0, I'll re-open if it persists.  Thanks again Sam, and great work on the library!

**Comment by sjudd** [comment] 2015-02-18 21:19
Sure no problem. Thanks for the report. I'd rather have a duplicate than not hear about an issue.
