### ISSUE TITLE
cannot start a load for a destroyed activity Glide

### ISSUE THREAD

**Issue by ominfowave** [bumptech/glide#2611] opened 2017-11-18 11:20 UTC
MainActivity has below code for load GIF first time it's working if I restart application it gets a crash for loading gif.

   ```
  ImageView imageViewGIF = navigationView.findViewById(R.id.imageViewGIF);
        Glide.with(this).asGif().load(R.drawable.gift_3).into(imageViewGIF);
```

but when I restart the app it gets  a crash for at loading of GIF
    ```
```
 Intent intent = new Intent(context, SplashActivity.class);
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK |          Intent.FLAG_ACTIVITY_CLEAR_TOP);
            startActivity(intent);
            finish();
```

```
application get a crash with below log.

     ```
   FATAL EXCEPTION: main
     Process: com.app.package, PID: 19360
     java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
         at android_support.qc.b(RequestManagerRetriever.java:298)
         at android_support.qc.a(RequestManagerRetriever.java:123)
         at android_support.ji.a(Glide.java:589)
```

i have used 
` `'com.github.bumptech.glide:glide:4.2.0'`` 
`'com.github.bumptech.glide:glide:4.3.1'`

both versions have the same issue

**Comment by sjudd** [comment] 2017-11-18 19:10
Duplicate of #803.

**Closed by sjudd** 2017-11-18 19:10 UTC
