### ISSUE TITLE
Canvas: trying to draw too large bitmap.

### ISSUE THREAD

**Issue by franvis** [bumptech/glide#3775] opened 2019-07-23 12:29 UTC
**Glide Version**: 4.9.0

**Device/Android Version**: Fails in several Samsung devices (95%) and a few of other brands (5%) (I managed to reproduce it in a Samsung Galaxy S8 and in a Google Pixel C tablet)

**Issue details / Repro steps / Use case background**: 
We are currently having several crashes with 
```
Canvas: trying to draw too large(156128256bytes) bitmap.
android.view.DisplayListCanvas.throwIfCannotDraw
```
This happens when loading images in AppCompatImageViews that are in a ViewPager. We managed to solve this disabling disk cache by adding ```.apply(RequestOptions().diskCacheStrategy(DiskCacheStrategy.NONE))```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
``` Kotlin
val thumbnailRequest = Glide
                .with(context)
                .load(lowResUrl)

            Glide.with(context)
                .load(highResUrl)
                .transition(withCrossFade())
                .thumbnail(thumbnailRequest)
                .into(this@ProductImageAtom)
```

**Why do we have to disable disk cache to prevent this crash? Is there another way of fixing this crash in our case?**

Thanks!

**Comment by liufsd** [comment] 2019-07-24 05:01
+1

**Comment by sjudd** [comment] 2019-07-25 16:05
If you're able to reproduce it in a test or a sample app let me know. Other than changing the inputs to the logic in Downsampler I'm not sure that disabling the disk cache should matter.

How large is the actual view?

**Comment by franvis** [comment] 2019-07-26 10:15
@sjudd Thanks for the answer. I'm able to reproduce it with our app. And definitely happens only when we have the disk cache enabled. As soon as I disabled it, goes smooth. I will try to make a sample app where you can also reproduce it, and will try upload also a video in the course of the following days. Will also give you more info about the view and the dimensions of the image itself when uploading the video as well.

**Comment by franvis** [comment] 2019-07-26 12:16
@sjudd Here I have a sample app that crashes with my case: https://github.com/franvis/glide-crash-sample
I tried it now with a Pixel 3XL emulator. Here you can also see a record of the app crashing, and also not crashing when I disable disk cache

Crashing
<img src="https://user-images.githubusercontent.com/11527358/61949274-932cd200-afaa-11e9-8820-7e2dd9aecd8c.gif" width="100">

Not crashing
https://user-images.githubusercontent.com/11527358/61951010-eb1a0780-afaf-11e9-9ca1-d1de50a758cd.gif

**Comment by liufsd** [comment] 2019-07-29 06:01
@franvis yes i have test your code and then crash on Pixel 3XL emulator. 
![image](https://user-images.githubusercontent.com/1910405/62024972-4f83d380-b209-11e9-8ddb-fe51d5808c7e.png)

**Comment by liufsd** [comment] 2019-08-01 05:21
@sjudd  hello ~ How to fix this issue ???

**Comment by franvis** [comment] 2019-08-08 08:04
@sjudd Hello!! Can you tell us a bit more about this?

**Comment by sjudd** [comment] 2019-08-14 16:45
Unfortunately I'm not able to reproduce the issue with the sample app. I don't see any difference in image sizes decoded with or without disk caching enabled.

My recollection is also that `throwIfCannotDraw` is not a crash, it just means the image won't render. Do you have a full stack trace for the crash?

**Comment by liufsd** [comment] 2019-08-15 01:45
@sjudd  Pixel 3XL emulator  will be crash . i have test  when you swipe image to the last item.

**Comment by franvis** [comment] 2019-08-26 15:18
@sjudd Hello! I'm still able to reproduce it with the sample app, by simply swiping it just crashes. Here you have a stacktrace of it:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.glidecrashsample, PID: 18529
    java.lang.RuntimeException: Canvas: trying to draw too large(354553696bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:233)
        at android.widget.ImageView.onDraw(ImageView.java:1434)
        at android.view.View.draw(View.java:21421)
        at android.view.View.updateDisplayListIfDirty(View.java:20298)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.draw(View.java:21424)
        at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
        at android.view.View.updateDisplayListIfDirty(View.java:20298)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.draw(View.java:21424)
        at com.android.internal.policy.DecorView.draw(DecorView.java:801)
        at android.view.View.updateDisplayListIfDirty(View.java:20298)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3601)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3409)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2746)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1714)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7587)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7343)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)`

**Comment by franvis** [comment] 2019-09-02 15:55
@sjudd Any news again?

**Comment by liufsd** [comment] 2019-09-03 01:56
nothing ?

**Comment by shpasha** [comment] 2019-09-04 09:31
I faced with this case too. When the image is narrow, in onResourceReady callback we can see, that resource have too large width and height. So possible solution its just use .override(screenWidth)

**Comment by Mouadabdelghafouraitali** [comment] 2019-09-08 18:47
I had the same issue,I ended using a custom width & height `into(new CustomTarget<Bitmap>(1800, 1800)`

**Comment by liufsd** [comment] 2019-09-16 02:44
@shpasha But. i need show origin image ~ ~ ~

**Comment by hike2008** [comment] 2019-09-16 09:02
How to fix this issue ?

**Comment by sjudd** [comment] 2019-09-17 00:53
Ok on a Pixel 3XL I was able to reproduce, here's the Downsampler logs:

```
09-16 17:52:23.823 V/Downsampler( 5636): Calculate scaling, source: [17x500], target: [1328x882], power of two scaled: [17x500], exact scale factor: 78.117645, power of 2 sample size: 1, adjusted scale factor: 78.11764526367188, target density: 2147483647, density: 27490379
09-16 17:52:23.824 V/Downsampler( 5636): Calculated target [1328x39059] for source [17x500], sampleSize: 1, targetDensity: 2147483647, density: 27490379, density multiplier: 78.11764
09-16 17:52:24.307 V/Downsampler( 5636): Decoded [1328x39059] ARGB_8888 (207481408) from [17x500] image/jpeg with inBitmap [1328x39059] ARGB_8888 (207481408) for [1328x882], sample size: 1, density: 27490379, target density: 2147483647, thread: glide-disk-cache-thread-0, duration: 484.04900299999997
```

**Comment by sjudd** [comment] 2019-09-17 01:26
Ah ok the disk cache strategy is red herring, it just makes it more likely that you'll have a race condition where the thumbnail request finishes more quickly than the non-thumbnail request. You can reproduce the crash with any disk cache strategy, it's just more likely with one than the other.

The actual issue is:

1. The thumbnail and primary requests are using different transformations. The thumbnail is using the default CENTER_OUTSIDE strategy, which aggressively upscales so that the image is larger in both dimensions than the requested image. The primary request is using FIT_CENTER based on the ImageView's scale type.
2. The low res url matches an image that's wildly out of proportion (17x500). To scale 17 up to the requested 1328 requires a very large scale factor, which, when mulitplied by 500, produces a very large image.

The simplest fix is to either use a more proportional image, or to explicitly set a more reasonable downsample strategy (FIT_CENTER, or even  CENTER_INSIDE).

There's some argument to be made that the thumbnails should also use the transformation based on the ImageView's scale type, but we've never done so in the past and it might be a subtle breaking change to start doing so now. 

I'll leave this open to consider making the thumbnail inherit the ImageView's transformation as well if a transformation isn't otherwise specified. #2964 already discusses avoiding upscaling by default.
09-16 18:14:22.080 V/Downsampler( 6736): Calculate scaling, source: [17x500], target: [1328x882], power of two scaled: [17x500], exact scale factor: 1.764, power of 2 sample size: 1, adjusted scale factor: 1.7640000581741333, target density: 2147483647, density: 1217394318
09-16 18:14:22.080 V/Downsampler( 6736): Calculated target [30x882] for source [17x500], sampleSize: 1, targetDensity: 2147483647, density: 1217394318, density multiplier: 1.764
09-16 18:14:22.082 V/Downsampler( 6736): Decoded [30x882] ARGB_8888 (105840) from [17x500] image/jpeg with inBitmap [30x882] ARGB_8888 (105840) for [1328x882], sample size: 1, density: 1217394318, target density: 2147483647, thread: glide-source-thread-3, duration: 2.780125

**Comment by sjudd** [comment] 2019-09-17 01:27
Actually I'm going to file a new issue for the transformation on thumbnails, will close this as otherwise broken as expected.

**Closed by sjudd** 2019-09-17 01:27 UTC

**Comment by zhanghai** [comment] 2019-09-23 05:54
I am using the default CENTER_OUTSIDE strategy and I still want to use it because of design reasons. 

Alternatively, can we add a reasonable limit for the DownSampler? Because loading a 39059 px tall bitmap just doesn't make sense.

**Comment by sjudd** [comment] 2019-09-24 01:21
You could avoid CENTER_OUTSIDE, use a non-scaling strategy, and upscale in the view itself? Or you can write your own DownsampleStrategy to meet whatever your requirements are. 

It's going to be hard to define a reasonable safe limit that applies to all loads in all applications.

**Comment by franvis** [comment] 2019-10-10 08:01
Hello @sjudd! I tried your possible solutions and changing the downsample strategy to centerInside() like 
```Glide.with(context)
                .load(highResUrl)
                .transition(withCrossFade())
                .thumbnail(thumbnailRequest)
                .centerInside()```
Still gives me a crash in the sample app I shared with you and we are having quite a lot of crashes in our production app as well... Any other suggestion or possible solution?

**Comment by franvis** [comment] 2019-10-18 14:25
> Hello @sjudd! I tried your possible solutions and changing the downsample strategy to centerInside() like
> 
> ```
> Glide.with(context)
>                 .load(highResUrl)
>                 .transition(withCrossFade())
>                 .thumbnail(thumbnailRequest)
>                 .centerInside()
> ```
> 
> Still gives me a crash in the sample app I shared with you and we are having quite a lot of crashes in our production app as well... Any other suggestion or possible solution?

@sjudd Moving to `fitCenter()` made the fix. Thanks!!

**Comment by VeerHan** [comment] 2020-10-07 11:28
> > Hello @sjudd! I tried your possible solutions and changing the downsample strategy to centerInside() like
> > ```
> > Glide.with(context)
> >                 .load(highResUrl)
> >                 .transition(withCrossFade())
> >                 .thumbnail(thumbnailRequest)
> >                 .centerInside()
> > ```
> > 
> > 
> > Still gives me a crash in the sample app I shared with you and we are having quite a lot of crashes in our production app as well... Any other suggestion or possible solution?
> 
> @sjudd Moving to `fitCenter()` made the fix. Thanks!!
Moving to fitCenter() does not work for me.

**Comment by Hamza417** [comment] 2021-05-06 12:30
Do not use `android:adjustViewBounds="true"` and `wrap_content` as widht and height parameter, on doing so Glide will draw full size image irrespective of the **ImageView**'s dimension which will ultimately cause this error.

**Comment by bhavin-qfonapp** [comment] 2022-04-14 09:21
> Do not use `android:adjustViewBounds="true"` and `wrap_content` as width and height parameter, on doing so Glide will draw full size image irrespective of the **ImageView**'s dimension which will ultimately cause this error.

@Hamza417 what if we need that? In my case I don't have height-width coming from api only image url and i have like image -text- gif 3 view types so i have to use `android:adjustViewBounds="true"` and `wrap_content` . so what to do in this scenario ?

**Comment by sucicf1** [comment] 2022-08-11 18:49
Hello, in my case I have solved that by doing the following:
1. added proguard rules
2. Changing from fragments or activity's context to imageview context inside glide command
3. and last but important in recyclerview adapter if you call getheight() or getwidth() on imageview then it returns 0 and used that in glide command. In my case imageviews size depends on other view in itemviews(they size is determined by wrap content). That causes something like https://github.com/bumptech/glide/issues/3775#issuecomment-833483907 Solved by setting width and height in glide command as fixed values (calculated by screen width or screen height and other hardcoded). My imageview continues to have variable size but now no out of memory

**Comment by yoviekaputra** [comment] 2022-12-07 03:17
hi @franvis , summary to solve this problem is implement like this, right?
```
Glide.with(context)
                .load(highResUrl)
                .transition(withCrossFade())
                .thumbnail(thumbnailRequest)
                . fitCenter()
```
btw, i couldn't access this link https://github.com/franvis/glide-crash-sample, error 404

**Comment by guppy-jonathan** [comment] 2023-03-03 08:51
> Do not use `android:adjustViewBounds="true"` and `wrap_content` as width and height parameter, on doing so Glide will draw full size image irrespective of the **ImageView**'s dimension which will ultimately cause this error.

I can reproduce the same crash with the following parameters.
1. The setting of the imageView is exactly same as mentioned in quote
2. The crash only happens in the device under Android 8 (a user report that it fixes after upgrading to Android 9) and 90% of crash happened in specific models of Sharp and one model of Samsung (and emulator).
3. The above solution (except the one mentioned proguard rules) didn't work for me.  And the other devices works well without crashes.

**Comment by divikiran** [comment] 2024-01-11 06:23
I use xamarin, I had to scale down images. Its the height and width of the images are the problem to Canvas

**Comment by RelaxPic** [comment] 2024-11-18 19:15
I tried debugging and found that it was com. bumptech.glide. load. engine LoadPath#loadWithExceptionList ， 

DecodePaths uses com. bumptech.glide. integration.avif AvifStreamBitmapDecoder, this decoder will result in images being super large.
