### ISSUE TITLE
Crash using compose GlideImage

### ISSUE THREAD

**Issue by stevie-patreon** [bumptech/glide#5013] opened 2023-01-27 19:12 UTC
**Glide Version**: '4.14.2'
**Glide Compose Version**: '1.0.0-alpha.1'

Reported in Firebase for various devices

**Issue details / Repro steps / Use case background**: 

We're using the compose version, which is where the issue seems to come from:

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
     GlideImage(
            model = imageUrl,
            contentDescription = contentDescription,
            contentScale = contentScale,
            modifier = modifier,
            requestBuilderTransform = {
                /* Workaround for GIFs: https://github.com/bumptech/glide/issues/4943 */
                requestBuilderTransform(it)
                    .optionalFitCenter()
            }
        )
```
`requestBuilderTransform` is usually just `{ it }`. `model` can be null.

```
Fatal Exception: java.lang.IllegalArgumentException
Failed requirement.
com.bumptech.glide.integration.ktx.Size.<init> (Flows.kt:380)
com.bumptech.glide.integration.compose.SizesKt.inferredGlideSize-BRTryo0 (Sizes.kt:36)
com.bumptech.glide.integration.compose.GlideImageKt$sizeObservingModifier$1.invoke-3p2s80s (GlideImage.kt:195)
com.bumptech.glide.integration.compose.GlideImageKt$sizeObservingModifier$1.invoke (GlideImage.kt:194)
androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s (LayoutModifier.kt:285)
androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s (BackwardsCompatNode.kt:343)
androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0 (LayoutModifierNodeCoordinator.kt:155)
```

**Comment by FunkyMuse** [comment] 2023-02-08 09:19
Same issue here

**Comment by sjudd** [comment] 2023-02-13 20:01
Duplicate of #4952

**Closed by sjudd** 2023-02-13 20:01 UTC
