### ISSUE TITLE
The new version 4.4.0 product a NoSuchMethod (No static method getFont()) Exception in Android Studio 3.0

### ISSUE THREAD

**Issue by shenhuanet** [bumptech/glide#2719] opened 2017-12-14 09:18 UTC
solve the exception is reduce the version.

**Comment by sjudd** [comment] 2017-12-14 18:07
Please always fill out the [issue template][1[ when filing new issues. 

Please provide the full error message and stack trace that you see. As far as I know Glide doesn't use ``getFront()``.

[1]: https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md

**Comment by tysheng** [comment] 2017-12-15 02:43
different support version led to this exception. I'm using the version 26, but Glide 4.4.0 is 27 inside

**Comment by rongbangou** [comment] 2017-12-16 08:12
I solve by this:
1.update to version 27 , change "compile 'com.android.support:appcompat-v7:27.0.2'" to "implementation 'com.android.support:appcompat-v7:27.0.2'" , change "compile 'com.android.support:design:27.0.2'" to "implementation 'com.android.support:design:27.0.2'"
2.delete  ".gradle" folder under your project
3.clean project , regbuild project , sync project

**Comment by Manikkumar1988** [comment] 2017-12-16 17:55
Even after updating to version 27,below crash happens to me

`java.lang.NoSuchMethodError: No virtual method iteratorWithAdditions()Landroid/arch/core/internal/SafeIterableMap$ListIterator; in class Landroid/arch/core/internal/SafeIterableMap; or its super classes (declaration of 'android.arch.core.internal.SafeIterableMap' appears in /data/app/challenge.ola.mani.com.maniola-1/base.apk)
                                                                                  at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:145)
                                                                                  at android.arch.lifecycle.LiveData.setValue(LiveData.java:293)
                                                                                  at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
                                                                                  at android.arch.lifecycle.LiveData$2.run(LiveData.java:108)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`

**Comment by sjudd** [comment] 2017-12-18 06:08
Duplicate of #2730

**Closed by sjudd** 2017-12-18 06:08 UTC
Labels: question, repro-needed

**Comment by sjudd** [comment] 2017-12-18 06:10
@Manikkumar1988 that looks like another support library version conflict? Maybe you're depending on the v26 version of some other support library component?

If anyone has any particular reason why they don't want to update to v27 of the support library let me know. Also let me know if excluding the support library transitive dependency in your Glide import in Gradle doesn't work. See the duplicate issue for a little more detail.

**Comment by giacomodeglinnocenti** [comment] 2018-01-02 10:57
Hi,
 I would like to continue using my version 26 for android APIs but need glide.

What's the latest glide release supporting API level 26?

Thanks

**Comment by giacomodeglinnocenti** [comment] 2018-01-02 11:09
Found 4.3.1 works as also mentioned in the duplicated issue.

Would be nice to have multiple supports or to found instructions in the readme.

Btw, thanks for this awesome library.
