### ISSUE TITLE
ImageView with match_parent width and wrap_content height

### ISSUE THREAD

**Issue by erikha1501** [bumptech/glide#1693] opened 2017-01-18 14:07 UTC
**Glide Version**:
Xamarin.Gilde 3.7.0

**Issue details / Repro steps / Use case background**: 
I've opened an issue here [https://github.com/bumptech/glide/issues/1664](#1664) about loading images with `match_parent` width and `wrap_content` height. As per Robert suggestion, I have refactored my code to use margin instead of padding. Since then, the height of a image is not set to padding size anymore but now it is constrained to image holder's height. Another bug I encountered is inconsistent image's size on subsequent load. Please see some screenshots down this post for illustration.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.With(context)
   .Load(currentPost.Embedded.WpFeaturedMedia.FirstOrDefault().SourceUrl)
   .DiskCacheStrategy(DiskCacheStrategy.All)
   .Placeholder(Resource.Drawable.placeholder)
   .Error(Resource.Drawable.placeholder_error)
   .Into(currentViewHolder.ThumbnailImage);
```

**Layout XML**:
```xml
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:auto="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    android:layout_margin="5dp"
    android:elevation="3dp"
    auto:cardCornerRadius="3dp"
    android:id="@+id/postcardviewitem_cardview_root"
    auto:cardBackgroundColor="@color/cardview_post_background">
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <ImageView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/postcardviewitem_imageview_thumbnailimage"
            tools:src="@android:drawable/ic_menu_gallery"
            android:adjustViewBounds="true"
            android:layout_alignParentTop="true"
            android:layout_marginTop="5dp"
            android:layout_marginBottom="5dp"
            android:layout_marginLeft="20dp"
            android:layout_marginRight="20dp" />
        <TextView
            android:text="Title"
            android:textAppearance="?android:attr/textAppearanceMedium"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/postcardviewitem_imageview_thumbnailimage"
            android:id="@+id/postcardviewitem_text_title"
            android:textColor="@color/cardview_post_title"
            android:paddingLeft="20dp"
            android:paddingRight="20dp"
            android:paddingTop="10dp"
            android:paddingBottom="5dp" />
        <TextView
            android:text="Author"
            android:textAppearance="?android:attr/textAppearanceSmall"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/postcardviewitem_text_title"
            android:id="@+id/postcardviewitem_text_author"
            android:textColor="@color/cardview_post_author"
            android:paddingLeft="20dp"
            android:paddingRight="20dp"
            android:paddingBottom="5dp" />
    </RelativeLayout>
</android.support.v7.widget.CardView>
```

**Example**:

![figure1](https://cloud.githubusercontent.com/assets/24774495/22066926/ae842142-ddc1-11e6-813b-caee856360ff.png)

**Comment by TWiStErRob** [comment] 2017-01-20 22:22
Duplicate of #363

**Closed by TWiStErRob** 2017-01-20 22:22 UTC
Labels: duplicate, question
