### ISSUE TITLE
GIF Loading order of operations

### ISSUE THREAD

**Issue by erchenger** [bumptech/glide#1503] opened 2016-10-06 16:54 UTC
For Glide 3.7.0 it looks like there is a bug in how GIF delays are processed. It appears that the delay is being retrieved from the wrong frame (one further than it should be). 

This does appear to be fixed in 4.0 but I would suggest possibly creating a fix for this before 4.0.0 release. I have a branch on a personal fork that has the fix implemented. It is really just a reordering of the code. Please see below for the code snippets of before and after.

Without fix:
```
 private void loadNextFrame() {
        if (!isRunning || isLoadPending) {
            return;
        }
        isLoadPending = true;

        gifDecoder.advance();
        long targetTime = SystemClock.uptimeMillis() + gifDecoder.getNextDelay();
        DelayTarget next = new DelayTarget(handler, gifDecoder.getCurrentFrameIndex(), targetTime);
        requestBuilder
                .signature(new FrameSignature())
                .into(next);
    }
```

With fix:
```
private void loadNextFrame() {
        if (!isRunning || isLoadPending) {
            return;
        }
        isLoadPending = true;

        long targetTime = SystemClock.uptimeMillis() + gifDecoder.getNextDelay();
        gifDecoder.advance();
        DelayTarget next = new DelayTarget(handler, gifDecoder.getCurrentFrameIndex(), targetTime);
        requestBuilder
                .signature(new FrameSignature())
                .into(next);
    }
```

I would like to submit a PR but would need a branch for 3.7.1 created. 

Thanks,
Elliott

**Comment by TWiStErRob** [comment] 2016-10-06 17:44
Dupe of #1060, already fixed in snapshot.

**Closed by TWiStErRob** 2016-10-06 17:44 UTC
Labels: bug, duplicate
