### ISSUE TITLE
Failed to resolve:glide-parent:library:unspecified

### ISSUE THREAD

**Issue by shenghaiyang** [bumptech/glide#1049] opened 2016-03-10 08:03 UTC
When i use ```com.github.bumptech.glide:okhttp3-integration:1.4.0``` ,then build error.And i do not find the package ```glide-parent``` in mvnrepository.
_glide version 3.7.0_

**Comment by TWiStErRob** [comment] 2016-03-10 10:21
Duplicate of #941.

Tip: Try to search for the exact error message in Google, you should've found that, though there are some other similar ones. To exact match you can put stuff in double-quotes

**Closed by TWiStErRob** 2016-03-10 10:21 UTC
Labels: bug, duplicate
