### ISSUE TITLE
Worthless request cancellation even if the new request is totally same as the previous one

### ISSUE THREAD

**Issue by ericxiewen** [bumptech/glide#1741] opened 2017-02-19 06:27 UTC
**Glide Version**: 3.7.0

**Integration libraries**: None

**Device/Android Version**: All devices

**Issue details / Repro steps / Use case background**:
Glide will always cancel previous request even if the new request is same as the previous one. Use Glide in list activity where each list item has a image view. After activity created, Glide requests (Glide.with(Activity.this).load(url).into(imageView)) are triggered by ListAdapter.getView() method. Before the requests are finished, call ListAdapter.notifyDataSetChanged(). Then ListAdapter.getView() will be called again, and the same Glide requests are sent out, the previous requests are all cancelled. But the cancellation is worthless since the requests are totally the same.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
// Code in Activity
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    // setup list adapter...
    // setup event listener...
}

// this method may be called after activity created immediately
protected void onEvent(Event event) {
    if (event...) {
        adapter.notifyDataSetChanged();
    }
}
```

```java
// Code in adapter
@Override public View getView(int position, View recycled, ViewGroup container) {
  final ImageView myImageView;
  if (recycled == null) {
    myImageView = (ImageView) inflater.inflate(R.layout.my_image_view, container, false);
  } else {
    myImageView = (ImageView) recycled;
  }

  String url = myUrls.get(position);

  Glide
    .with(myFragment)
    .load(url)
    .centerCrop()
    .placeholder(R.drawable.loading_spinner)
    .crossFade()
    .into(myImageView);

  return myImageView;
}
```

**Comment by TWiStErRob** [comment] 2017-02-19 12:51
I think you should consider taking a step back and noticing that you're doing an unnecessary full re-bind, which triggers the reloading the images and hence cancels them.

If you want to prevent re-binds consider using `hasStableIds`. The id could be as simple as the hashcode of the url in this case. It would probably be even a better approach to not bind anything until that even happens, since it sounds like it'll happen always and immediately (user may not even notice if you don't bind first).

As a simpler workaround you can store the current url in a named tag of the view to prevent re-loading; you just need to check if the tag is the same as the current bind, before firing the request.

**Comment by ericxiewen** [comment] 2017-02-19 14:35
Thanks for quick reply. You give a solution to prevent re-binds, but in some cases the re-binds are intended. For example, there was only summary information bound with the list view holder at beginning, the binds will fire asynchronous loading for detail information. And after different details loaded, re-binds are intended to render the new information.

About the workaround, it was what I decide to do. But it will make the code ugly and difficult to maintain. It's easy to forget to add or remove the url tag while the app become complicated and with deep view hierarchies. I think the best place to know and ignore the request is in Glide, that's why I create this issue to ask for any better solution.

**Comment by TWiStErRob** [comment] 2017-02-19 14:42
I agree that it complicates the code, but in most of the uses-cases Glide is used in I think cancel is the best we can do. Your case is special and I'm not sure if it's even architecturally possible to prevent inside Glide: for example equality of requests is not enough to decide, because the request may be forcing an image reload via `.diskCacheStrategy(NONE)`. This is just one example, there may be a lot of exceptions.

That being said a `.skipIfSameRequest(true)` may be a worthwhile addition. @sjudd what do you think about this enhancement, is it possible?

**Comment by ericxiewen** [comment] 2017-02-20 01:22
Yes, .skipIfSameRequest(true) is what I'm looking for. I think my case is common instead of special, there are many reasons to trigger re-binds (e.g. receive refresh event from backend, async data loading, new messages arrive, etc.) I have seen some implementation on github create a custom subclass of ImageView just for this workaround (named like GlideImageView). I think actually many users will never notice this issue since a worthless cancellation doesn't impact the final result.

After read on Glide code, I think it's possible to add .skipIfSameRequest(true). Each Request (subclasses) should implement equals(), and compares begin with most possible change things (like url). For most of cases, url will not be the same so first hit will get the result. And skipIfSameRequest is set to false by default, so there is no changes and performance loss.

**Comment by sjudd** [comment] 2017-02-21 00:12
I think it's fine to ignore identical requests, even by default. The original versions of Glide did this. 

@ericxiewen if you're interested in implementing this, I'd be happy to see a pull request. I think you can implement equality methods for one or more of RequestBuilder, SingleRequest, and the various options classes and get this to work.

**Comment by TWiStErRob** [comment] 2017-02-21 00:16
In that case (default to ignore) we probably need a `.forceIdenticalRequest(true)` to be able to make requests with `NONE` strategy.

**Comment by sjudd** [comment] 2017-02-21 00:23
@TWiStErRob can that be handled with a unique signature instead?

**Comment by TWiStErRob** [comment] 2017-02-21 00:42
I don't think that's a good idea, then it wouldn't be possible to have a signature and NONE cache at the same time. Actually it would be, but every user would have to modify their signature generation to work around this. (signature + NONE may seem weird, but I think in that case you can still hit the memory cache with the same signature)

**Comment by sjudd** [comment] 2017-02-21 00:46
Maybe I'm misunderstanding what the none cache is for? If you just want to make sure you've re-requested the image, using a new signature is the only way to do it?

**Comment by TWiStErRob** [comment] 2017-02-21 00:52
In my understanding `NONE` makes Glide make an origin request, regardless of what's in disk cache, but it'll hit memory cache if it's in there. Can't really think of a real world scenario for this though.

**Comment by TWiStErRob** [comment] 2017-02-21 00:53
I always think of `.signature` as a more general way to say `http://blah?signature=...`

**Comment by sjudd** [comment] 2017-02-24 16:10
Yeah you're right about the difference, I guess I just couldn't think of why anyone would want the behavior you describe for ``NONE``.

Since we've gotten a bit off track, the original idea here is valid. If we can implement equality checks for the options and the model, most of which are required anyway for caching to work, we can avoid cancelling an in progress request and restarting it.

If someone wants to try to take this on, I'd welcome the help.

**Comment by sjudd** [comment] 2017-11-12 23:00
Duplicate of #2194

**Closed by sjudd** 2017-11-12 23:00 UTC
Labels: enhancement, question
