### ISSUE TITLE
Unknown Issue -  Unable to load GlideDrawableImageViewTarget

### ISSUE THREAD

**Issue by shubham1992agg** [bumptech/glide#954] opened 2016-02-01 20:50 UTC
I found the following in crash in Crashlytics. Well, i don't really think that's an issue with Glide but still want's to clarify.

```ruby
Fatal Exception: java.lang.VerifyError:
Rejecting class com.bumptech.glide.request.target.GlideDrawableImageViewTarget because it failed compile-time verification
(declaration of 'com.bumptech.glide.request.target.GlideDrawableImageViewTarget' appears in /data/app/com.photos.instacollage-1/base.apk)
       at com.bumptech.glide.request.target.ImageViewTargetFactory.buildTarget(ImageViewTargetFactory.java:18)
       at com.bumptech.glide.Glide.buildImageViewTarget(Glide.java:297)
       at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:697)
       at com.bumptech.glide.DrawableRequestBuilder.into(DrawableRequestBuilder.java:448)
       at com.instacollage.fragments.selection.LocalPhotoGridFragment$GridAdapter.getView(LocalPhotoGridFragment.java:208)
       at android.widget.AbsListView.obtainView(AbsListView.java:2825)
       at android.widget.GridView.onMeasure(GridView.java:1064)
       at android.view.View.measure(View.java:18579)
       at android.support.v4.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:578)
       at android.view.View.measure(View.java:18579)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
       at android.view.View.measure(View.java:18579)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1488)
       at android.view.View.measure(View.java:18579)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:874)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
       at android.view.View.measure(View.java:18579)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
       at android.view.View.measure(View.java:18579)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at android.view.View.measure(View.java:18579)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
       at android.view.View.measure(View.java:18579)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2888)
       at android.view.View.measure(View.java:18579)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2250)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1306)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1548)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6641)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by TWiStErRob** [comment] 2016-02-01 21:02
Whoa, never seen this type of exception before.

Some small research yielded: https://code.google.com/p/android/issues/detail?id=80961
Workaround from comment 3: `android { buildTypes { debug { testCoverageEnabled false } } }`
Workaround from comment 19: `android { jacoco { version '0.7.4' } }`
Real fix from label `Target-1.2` on the issue: update you Android gradle plugin to `1.2+`
*see [release history](http://tools.android.com/recent) or [available binaries (click "View All" to see latest stable)](https://bintray.com/android/android-tools/com.android.tools.build.gradle/view)*

In case you don't use Gradle try using the latest build tools from the Android SDK.

**Comment by shubham1992agg** [comment] 2016-02-01 21:49
KK. Thanks.
Well, I don't have a way to test if above will work or not. And, my current Gradle plugin is 1.2.3

Apart from this issue, I would like to know, if Glide added feature to load images from assets or not?

**Comment by TWiStErRob** [comment] 2016-02-01 21:50
See #770

**Comment by TWiStErRob** [comment] 2016-02-01 21:52
How often did this exception come up? If only once or on one device: maybe someone was hacking the APK and your application caught it...?!

**Comment by shubham1992agg** [comment] 2016-02-01 22:02
This happened for two users having same device: SM-N900P
They got about 15 crashes. One had a rooted device and other non-rooted. 
Yeah, i am too looking to upgrade the same, but before doing that, I am looking to update my app this week.

**Comment by shubham1992agg** [comment] 2016-02-01 22:03
Are you sure that this will be the asset path for all android devices: "file:///android_asset/assetName". ?

**Comment by TWiStErRob** [comment] 2016-02-01 22:17
Yes, because it's hardcoded to be handled, see `UriLoader` calling `AssetUriParser`. There's no universal way to handle such Uris in Android. I think webkit's WebView started using it and it's now "mainstream" by most loaders.

**Comment by shubham1992agg** [comment] 2016-02-01 22:18
Great then, Thanks.

**Comment by TWiStErRob** [comment] 2016-02-01 22:22
I guess we can close this issue as we can't reproduce that stack trace. Feel free to reopen if you find a way or get more reports.

**Closed by TWiStErRob** 2016-02-01 22:22 UTC
Labels: non-library, question

**Comment by rodrigohsb** [comment] 2017-06-29 19:48
Hey! @TWiStErRob 

I'm facing this issue. I've tried to use as documentation:

`Glide.with(this)
                .load(R.raw.gif_example)
                .into(splashImg);`

with this dependencies:

`compile 'com.github.bumptech.glide:glide:4.0.0-RC1'`
`annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'`


Crash:

`br.com.wiz.corretor E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: br.com.wiz.corretor, PID: 8030
                                                                   java.lang.VerifyError: Rejecting class com.bumptech.glide.load.resource.gif.GifResourceDecoder$GifDecoderPool because it failed compile-time verification (declaration of 'com.bumptech.glide.load.resource.gif.GifResourceDecoder$GifDecoderPool' appears in /data/app/br.com.wiz.corretor-1/base.apk)
                                                                       at com.bumptech.glide.load.resource.gif.GifResourceDecoder.<clinit>(GifResourceDecoder.java:29)
                                                                       at com.bumptech.glide.load.resource.gif.GifDrawableLoadProvider.<init>(GifDrawableLoadProvider.java:27)
                                                                       at com.bumptech.glide.Glide.<init>(Glide.java:226)
                                                                       at com.bumptech.glide.GlideBuilder.createGlide(GlideBuilder.java:203)
                                                                       at com.bumptech.glide.Glide.get(Glide.java:155)
                                                                       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:62)
                                                                       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:53)
                                                                       at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:198)
                                                                       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:104)
                                                                       at com.bumptech.glide.Glide.with(Glide.java:653)
                                                                       at br.com.wiz.corretor.splash.activity.SplashActivity.showBranding(SplashActivity.java:54)
                                                                       at br.com.wiz.corretor.splash.presenter.SplashPresenterImpl.initWith(SplashPresenterImpl.java:26)
                                                                       at br.com.wiz.corretor.splash.activity.SplashActivity.setup(SplashActivity.java:46)
                                                                       at br.com.wiz.corretor.splash.activity.SplashActivity_.onViewChanged(SplashActivity_.java:79)
                                                                       at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
                                                                       at br.com.wiz.corretor.splash.activity.SplashActivity_.setContentView(SplashActivity_.java:48)
                                                                       at br.com.wiz.corretor.splash.activity.SplashActivity_.onCreate(SplashActivity_.java:38)
                                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by MrChriZ** [comment] 2017-08-24 18:04
Happening here too :(
