### ISSUE TITLE
Glide load images in disorder

### ISSUE THREAD

**Issue by shangmingchao** [bumptech/glide#1561] opened 2016-11-02 02:56 UTC
**Glide Version**: glide:3.7.0

**Integration libraries**: none

**Device/Android Version**: Galaxy Note3/SM-N9500 5.0

**Issue details / Repro steps / Use case background**: Glide load images in disorder.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
public class MyGlideModule implements GlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        MemorySizeCalculator calculator = new MemorySizeCalculator(context);
        int defaultMemoryCacheSize = calculator.getMemoryCacheSize();
        int defaultBitmapPoolSize = calculator.getBitmapPoolSize();

        int customMemoryCacheSize = (int) (0.3 * defaultMemoryCacheSize);
        int customBitmapPoolSize = (int) (0.3 * defaultBitmapPoolSize);

        builder.setMemoryCache(new LruResourceCache(customMemoryCacheSize));
        builder.setBitmapPool(new LruBitmapPool(customBitmapPoolSize));
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
    }
}
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@drawable/list_bg"
    android:orientation="horizontal">

    <TextView
        android:id="@+id/tv_rank"
        android:layout_width="50dp"
        android:layout_height="match_parent"
        android:gravity="center" />

    <ImageView
        android:id="@+id/iv_logo"
        android:layout_width="60dp"
        android:layout_height="50dp"
        android:layout_margin="5dp"
        android:contentDescription="@string/app_name" />

    <TextView
        android:id="@+id/tv_name"
        android:layout_width="100dp"
        android:layout_height="match_parent"
        android:gravity="center" />

</LinearLayout>
```

**Stack trace / LogCat**: none

Glide load images in disorder when I use `MyGlideModule`.
![disorder](https://github.com/shangmingchao/GlideTest/blob/master/screenshots/screenshot_1.png?raw=true)
Is there something wrong?
it's not happened without using `MyGlideModule` or in the Galaxy S4 device.
Here is the [Repo](https://github.com/shangmingchao/GlideTest).

**Comment by TWiStErRob** [comment] 2016-11-02 08:29
At first glance this sounds like a duplicate of #601, please give that a read and let me know what you think.

**Comment by shangmingchao** [comment] 2016-11-02 11:27
Thanks, It's really the same problem. It works well when I add `builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);`. I've been trying to put some breakpoint and debug it before this. I thought it might be the problem of cache key. But the url of Glide loaded is always correct, the picture are not display correctly.
It doesn't always reproduce, I also didn't notice the logs about OpenGL. Your workarounds is well-founded, I agree with and support that, and I hope someone can give a more detailed explanation.
Thanks again for your help.

**Closed** 2016-11-02 11:30 UTC
Labels: bug, duplicate, non-library
