### ISSUE TITLE
IllegalStateException: Already released

### ISSUE THREAD

**Issue by gemiren** [bumptech/glide#2696] opened 2017-12-08 05:19 UTC
**Glide Version**: 4.4

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
java.lang.IllegalStateException: Already released
at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(StateVerifier.java:44)
at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:518)
at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:217)
at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:322)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6247)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```
How can I catch this exception instead of letting it crash my app? Thanks.

**Comment by sjudd** [comment] 2017-12-08 06:35
I'm not sure there's any way for you to catch this. Are you able to reproduce it? If so, can you tell me how? Or provide a sample app that reproduces the issue?

**Comment by sjudd** [comment] 2017-12-11 15:23
Duplicate of #2689

**Closed by sjudd** 2017-12-11 15:23 UTC
Labels: bug, repro-needed
