### ISSUE TITLE
GlideApp not accecible

### ISSUE THREAD

**Issue by jack9394** [bumptech/glide#1982] opened 2017-05-31 10:01 UTC
I cannot access GlideApp thought i'm creating this class , is there anything missing?

**Glide Version**: 4.0.0 RC

**Integration libraries**: nothing

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
package mobi.foo.project.activity;

import android.content.Context;

import com.bumptech.glide.GlideBuilder;
import com.bumptech.glide.Registry;
import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.load.engine.cache.LruResourceCache;
import com.bumptech.glide.module.AppGlideModule;

/**
 * Created by Jack Lebbos on 5/31/2017.
 */
@GlideModule
public final class MyGlideModule extends AppGlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        super.applyOptions(context, builder);
        setMemoryCache(context, builder);
    }

    public MyGlideModule() {
        super();
    }

    @Override
    public void registerComponents(Context context, Registry registry) {
        super.registerComponents(context, registry);
    }

    public void setMemoryCache(Context context, GlideBuilder builder) {
        int memoryCacheSizeBytes = 1024 * 1024 * 20; // 20mb
        builder.setMemoryCache(new LruResourceCache(memoryCacheSizeBytes));
    }

    public void setDiskCache() {
        int diskCacheSizeBytes = 1024 * 1024 * 100; // 100 MB

    }

}
```

**Comment by sjudd** [comment] 2017-05-31 14:43
Duplicate of #1939, you're probably missing the annotationProcessor gradle dependency, see http://bumptech.github.io/glide/doc/download-setup.html#gradle

**Closed by sjudd** 2017-05-31 14:43 UTC

**Comment by jack9394** [comment] 2017-06-01 06:57
I am including it in my app but nothing happens.
This is my gradle file:
```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

//    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 25
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}
configurations.all {
    resolutionStrategy.force 'com.google.code.findbugs:jsr305:3.0.1'
}

dependencies {
    compile project(":libs:framework")
//    compile 'mobi.foo:framework:1.1.+'
    compile 'com.github.bumptech.glide:glide:4.0.0-RC0'
    compile 'com.github.bumptech.glide:compiler:4.0.0-RC0'

    compile 'com.android.support:support-v4:25.3.1'
}
```

**Comment by TWiStErRob** [comment] 2017-06-01 21:51
Please refer to this comment: https://github.com/bumptech/glide/issues/1982#issuecomment-305208633

**Comment by SubhashGaikwad** [comment] 2017-11-30 13:16
Please add @GlideModule  and clean and rebuild the project
