### ISSUE TITLE
Bitmap too large to be uploaded into a texture

### ISSUE THREAD

**Issue by MrJiYu** [bumptech/glide#581] opened 2015-08-15 03:23 UTC
Bitmap too large to be uploaded into a texture
I load image in GridView show this Warn

**Comment by TWiStErRob** [comment] 2015-08-15 08:34
Duplicate of #547.

**Closed** 2015-08-15 17:30 UTC

**Comment by Erdmana12** [comment] 2023-04-26 03:59
I'm interested, [octordle](https://octordle3.com) and this knowledge will help me with my work, so please share more information.
