### ISSUE TITLE
NullPointerException in the annotation compiler using kotlin-kapt plugin

### ISSUE THREAD

**Issue by xit0c** [bumptech/glide#3107] opened 2018-05-24 14:27 UTC
Android Studio 3.2 Canary 15
Build #AI-181.4668.68.32.4773949, built on May 10, 2018
JRE: 1.8.0_152-release-1136-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-43-generic

**Glide Version**: 4.7.1

**Device/Android Version**: All (compile-time error)

**compileSdkVersion/targetSdkVersion**: 'android-P'/'P'

**Using Kotlin (and kotlin-kapt plugin)**: Yes

**Repro steps**:
1. Create a new empty project with Kotlin support
2. Add `apply plugin: 'kotlin-kapt'` in `./app/build.gradle` and include Glide:
```gradle
implementation 'com.github.bumptech.glide:glide:4.7.1'
kapt 'com.github.bumptech.glide:compiler:4.7.1'
```
3. Refactor dependencies according to [AndroidX refactoring](https://developer.android.com/topic/libraries/support-library/refactor). AppCompat and ConstraintLayout should be the only interested ones (remember to update also the import statement in `MainActivity.kt` and the xml tag in `main_activity.xml`)
4. Add these 2 lines in `./gradle.properties` in order to use AndroidX (see [AndroidX release notes](https://developer.android.com/topic/libraries/support-library/androidx-rn))
```
android.useAndroidX=true
android.enableJetifier=true
```
5. Create a new `KotlinAppGlideModule.kt` like this (to use Glide generated API):
```kotlin
import com.bumptech.glide.annotation.GlideModule
import com.bumptech.glide.module.AppGlideModule

@GlideModule
class KotlinAppGlideModule: AppGlideModule() { }
```
6. Sync & Build

**Issue details**: the issue occurs only when using Kotlin and the kotlin-kapt plugin. Reproducing the steps above with `annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'` and a `JavaAppGlideModule.java` like this:
```java
import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.module.AppGlideModule;

@GlideModule
public class JavaAppGlideModule extends AppGlideModule { }
```
makes the error disappear. Does it mean that it is kotlin-kapt plugin's fault instead? I'm not sure if this is the case or if, somehow, my issue is related to [this one](https://github.com/bumptech/glide/issues/3080)

**Stack trace / LogCat**:
```
e: [kapt] An exception occurred: java.lang.NullPointerException
	at com.bumptech.glide.annotation.compiler.GlideGenerator.addReturnAnnotations(GlideGenerator.java:181)
	at com.bumptech.glide.annotation.compiler.GlideGenerator.overrideGlideStaticMethod(GlideGenerator.java:152)
	at com.bumptech.glide.annotation.compiler.GlideGenerator.access$200(GlideGenerator.java:72)
	at com.bumptech.glide.annotation.compiler.GlideGenerator$1.apply(GlideGenerator.java:134)
	at com.bumptech.glide.annotation.compiler.GlideGenerator$1.apply(GlideGenerator.java:127)
	at com.bumptech.glide.repackaged.com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:640)
	at com.bumptech.glide.repackaged.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.bumptech.glide.repackaged.com.squareup.javapoet.TypeSpec$Builder.addMethods(TypeSpec.java:567)
	at com.bumptech.glide.annotation.compiler.GlideGenerator.generate(GlideGenerator.java:119)
	at com.bumptech.glide.annotation.compiler.AppModuleProcessor.maybeWriteAppModule(AppModuleProcessor.java:105)
	at com.bumptech.glide.annotation.compiler.GlideAnnotationProcessor.process(GlideAnnotationProcessor.java:131)
	at org.jetbrains.kotlin.kapt3.ProcessorWrapper.process(annotationProcessing.kt:131)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:87)
	at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:45)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:257)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:212)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:95)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:97)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:84)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:374)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:64)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:365)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:130)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:161)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:63)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:405)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:920)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:98)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:950)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:919)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:404)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sjudd** [comment] 2018-05-24 22:43
This does seem like it's the same as the issue you linked, the failure occurs trying to find the VisibleForTesting annotation.

**Comment by xit0c** [comment] 2018-05-25 08:26
I see. So it seems like GlideGenerator is searching the `android.support.annotation.VisibleForTesting` annotation, which is in the `com.android.support:support-annotations` library. But, with the `android.enableJetifier` option set to `true` (as described [here](https://developer.android.com/studio/preview/features/#androidx_refactoring)), the annotations library is replaced by Gradle with the new `androidx.annotation:annotation:1.0.0-alpha1`, which has VisibleForTesting in `androidx.annotation.VisibleForTesting`. Could that be the cause of the failure?

**Comment by sjudd** [comment] 2018-05-25 14:09
Right that's the failure in the other issue. 

I'm not sure why the Java version works. Maybe something about dependency ordering in gradle?

**Comment by Raaowll** [comment] 2018-05-26 12:26
Hi, 

I am facing this same issue.

Android Studio 3.2 Canary

Glide Version: 4.7.1

Device/Android Version: All (compile-time error)

compileSdkVersion/targetSdkVersion: 'android-P'/'P'

Using Kotlin (and kotlin-kapt plugin): Yes

Repro steps:

1. Create a new empty project with Kotlin support

2. Add apply plugin: 'kotlin-kapt' in ./app/build.gradle and include Glide:

    implementation 'com.github.bumptech.glide:glide:4.7.1' 
    kapt 'com.github.bumptech.glide:compiler:4.7.1'

3. Refactor dependencies according to AndroidX refactoring. AppCompat and ConstraintLayout should be the only interested ones (remember to update also the import statement in MainActivity.kt and the xml tag in main_activity.xml)

4. Add these 2 lines in ./gradle.properties in order to use AndroidX (see AndroidX release notes)
    android.useAndroidX=true
    android.enableJetifier=true

5. Create a new KotlinAppGlideModule.kt like this (to use Glide generated API):
import com.bumptech.glide.annotation.GlideModule
import com.bumptech.glide.module.AppGlideModule

@GlideModule
class KotlinAppGlideModule: AppGlideModule() { }

6. sync & build.

**Comment by sjudd** [comment] 2018-05-29 16:02
Yeah this is a dupe of #3080

**Closed by sjudd** 2018-05-29 16:02 UTC
Labels: question

**Comment by Auto-Droid** [comment] 2018-09-17 10:49
Hi, I M THE BEST DEVELOPER
