### ISSUE TITLE
[4.6.0] error: incompatible types: GlideModule cannot be converted to Annotation @GlideModule()  ^

### ISSUE THREAD

**Issue by JienLee** [bumptech/glide#2865] opened 2018-02-02 04:57 UTC
**Glide Version**: 4.6.0
**Integration libraries**: okhttp3-3.9.1

Update to 4.6.0, I got this issue.

```
Error:(10, 2) error: incompatible types: GlideModule cannot be converted to Annotation @GlideModule()  ^
```

My Project used exteneded 'AppGlideModule' class.

**What can I do this situation?**

```
import android.content.Context
import com.bumptech.glide.GlideBuilder
import com.bumptech.glide.annotation.GlideModule
import com.bumptech.glide.load.engine.cache.ExternalCacheDiskCacheFactory
import com.bumptech.glide.load.engine.cache.LruResourceCache
import com.bumptech.glide.module.AppGlideModule

@GlideModule
class GlideModule : AppGlideModule(){
    override fun applyOptions(context: Context, builder: GlideBuilder) {
        builder.setDiskCache(ExternalCacheDiskCacheFactory(context, "cache", DISK_CACHE_SIZE))
                .setMemoryCache(LruResourceCache(cacheSize.toLong()))
    }

    override fun isManifestParsingEnabled(): Boolean {
        return false
    }

    companion object {
        private val maxMemory = (Runtime.getRuntime().maxMemory() / 1024).toInt()
        private val cacheSize = maxMemory / 8
        private val DISK_CACHE_SIZE = 1024 * 1024 * 10
    }
}
```

**Comment by sjudd** [comment] 2018-02-02 05:32
Duplicate of #2863

**Closed by sjudd** 2018-02-02 05:32 UTC
