### ISSUE TITLE
ConcurrentModificationException | java.util.ArrayList$Itr in next

### ISSUE THREAD

**Issue by foxyoverdrive** [bumptech/glide#4268] opened 2020-06-22 14:29 UTC
**Glide Version**: 4.11.0

**Integration libraries**: OkHttp3

**Device/Android Version**: Redmi Note 4 Android 7.0

**Issue details / Repro steps / Use case background**: don't know how to reproduce this exception, sadly.

**Stack trace / LogCat**:
```
java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.next(ArrayList.java:831)
    at com.bumptech.glide.Glide.trimMemory(Glide.java:688)
    at com.bumptech.glide.Glide.onTrimMemory(Glide.java:900)
    at android.app.Application.onTrimMemory(Application.java:138)
    at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5120)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1741)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:165)
    at android.app.ActivityThread.main(ActivityThread.java:6375)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

**Comment by sjudd** [comment] 2020-06-24 17:04
Duplicate of #4162

**Closed by sjudd** 2020-06-24 17:04 UTC
