### ISSUE TITLE
NullPointerException com.bumptech.glide.load.engine.DecodeJob.compareTo

### ISSUE THREAD

**Issue by OsBelief** [bumptech/glide#2864] opened 2018-02-02 03:31 UTC
I have a problem.

Glide Version: 4.3.1
Android Version:7.0
Device:Moto(E4) Plus

java.lang.NullPointerException: Attempt to read from field 'com.bumptech.glide.Priority com.bumptech.glide.load.engine.DecodeJob' on a null object reference
	at com.bumptech.glide.load.engine.DecodeJob.compareTo(SourceFile:10204)
	at java.util.concurrent.PriorityBlockingQueue.siftUpComparable(PriorityBlockingQueue.java:331)
	at java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:459)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1352)
	at com.bumptech.glide.load.engine.executor.GlideExecutor.execute(SourceFile:255)
	at com.bumptech.glide.request.SingleRequest.a(SourceFile:19115)
	at com.bumptech.glide.request.target.ViewTarget.getSize(SourceFile:1250)
	at com.bumptech.glide.request.SingleRequest.begin(SourceFile:257)
	at com.bumptech.glide.RequestManager.onStart(SourceFile:4095)
	at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(SourceFile:50)
	at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SourceFile:175)

The code is confused, I try to restore, but still some code lines are not up, please forgive.

**Comment by sjudd** [comment] 2018-02-02 05:33
Duplicate of #2658

**Closed by sjudd** 2018-02-02 05:33 UTC
