### ISSUE TITLE
NoSuchElementException from SupportRequestManagerFragment.onLowMemory

### ISSUE THREAD

**Issue by justinfriberg** [bumptech/glide#722] opened 2015-11-02 21:35 UTC
Our crash monitoring facility had identified the above exception.  It has been reported using Glide 3.5.2 and 3.5.0.  It usually occurs in Android 4 devices, though we have reports up to 5.1.  We're not able to reproduce it in our testing.  While it's not a frequent report, we have seen 300+ reports in the last 30 days.  

It looks like it may be the same or related to #266. Here's the stack trace in our case:  
```java
java.util.LinkedHashMap$LinkedHashIterator.nextEntry (LinkedHashMap.java:350)
java.util.LinkedHashMap$EntryIterator.next (LinkedHashMap.java:374)
com.bumptech.glide.util.LruCache.trimToSize (LruCache.java:157)
com.bumptech.glide.util.LruCache.clearMemory (LruCache.java:146)
com.bumptech.glide.Glide.clearMemory (Glide.java:372)
com.bumptech.glide.RequestManager.onLowMemory (RequestManager.java:92)
com.bumptech.glide.manager.SupportRequestManagerFragment.onLowMemory (SupportRequestManagerFragment.java:75)
android.support.v4.app.Fragment.performLowMemory (Fragment.java:1851)
dalvik.system.NativeStart.main (NativeStart.java)
```

**Comment by TWiStErRob** [comment] 2015-11-02 22:05
* Is it an internal crash reporting thing?  
I'm hoping it's not, because then one of the 300 may have written something in the description field that gives a clue to repro.
* Are all the stack traces exactly the same?
* Any pattern in device manufacturers?
* Do you mean Android 4 as anything randomly between 4.0 and 4.4.2?
* **Please try to upgrade to 3.6.1, it's not that far from 3.5.2.**

I took a quick look at `LruCache` (:372 is `memoryCache.clearMemory()`) and I think this is only possible if `getSize` returns different values at different times which results in `currentSize` and `cache.size()` being out of sync. @sjudd do you think it's possible?

Do you have any code that may mess with Bitmaps confusing Glide's internals?
(For example try navigating to the Bitmap class and then execute *Find Usages Settings...*:
![image](https://cloud.githubusercontent.com/assets/2906988/10895695/d43d6c68-81b5-11e5-9896-2194d42292db.png)
to see if you call any methods on Bitmaps.

**Comment by justinfriberg** [comment] 2015-11-03 19:24
We're using Crashlytics/Fabric for crash reports, so no descriptions.  I'll see if I can find out if there's anything in the play store reporting.  The stack trace is the same for each of the reports.  

I don't see any pattern in device manufacturers.  Our latest release show 32% Motorola, 31% LG, 28% Samsung, 9% other.

I thought I'd seen earlier Android versions when I wrote the initial report, but after a careful review, it's all KitKat (starting with 4.4.0) or later.  It's dominated by 4.4 reports, but we have about 15-20 on 5.01/5.1.  

We'll update to 3.6.1 for our next release presuming we don't encounter any QA issues.

I don't see anything unusual that we're doing with Bitmaps.  No subclasses, etc.  Two unlikely possibilities: We use the palette generation code as seen on the bottom of https://github.com/bumptech/glide/wiki/Custom-targets.  Also, we do use Google's CastCompanionLibrary for casting, which has a separate mechanism for grabbing bitmaps, though I don't see any way they'd interact.

**Comment by TWiStErRob** [comment] 2015-11-03 20:34
I don't think cast can interfere, unless you use Glide with a custom target to pass a loaded Bitmap over to cast somehow.

Palette generation may be the cause, especially if used in lists. The code example you gave starts the generation async, so it can - in theory - finish after Glide has already cleared the target. Clearing can happen for example when scrolling and staring a new load into a recycled ImageView. This may result in the Bitmap going back to the pool too soon; though Palette should only read those Bitmaps. Still just guessing, sorry.

Check out [integration-palette](https://github.com/bumptech/glide/tree/palette/integration/palette/src/main/java/com/bumptech/glide/integration/palette) for a better version of Palette handling (this is what Sam meant in the wiki). Using those classes is as easy as:
```java
.asBitmap()
.transcode(new PaletteBitmapTranscoder(context), PaletteBitmap.class)
.into(new PaletteBitmapViewTarget(imageView) {
    @Override protected void setResource(PaletteBitmap resource) {
        super.setResource(resource);
        // use resource.palette here to update backgrounds and text colors
    }
})
```
There's also #272 which probably won't be merged into 3.0, but a [better version](https://github.com/TWiStErRob/glide/tree/palette-lib) into 4.0.

**Comment by justinfriberg** [comment] 2015-11-04 01:10
I'll see if I can integrate the revised palette handling and see if it resolves the issue.  I'll report back once we've released the update to see if the issue is addressed.  Thanks for the suggestion!

**Comment by TWiStErRob** [comment] 2015-11-12 08:57
Please reopen once you had a chance to publish and gather more information.

**Closed by TWiStErRob** 2015-11-12 08:57 UTC
Labels: bug, invalid
