### ISSUE TITLE
Image flicker using Glide 4.0.0

### ISSUE THREAD

**Issue by kancic** [bumptech/glide#2194] opened 2017-08-02 10:44 UTC
Hi, 

first of all thank you for a great library. The issue started today when I updated to the newest Glide 4.0.0 from 4.0.0 RC1. Images everywhere started flickering when refreshing data (for example in the RecyclerView's notifyDatasetChanged method). Here is my helper class that I'm using for displaying images. 

```java
public class ImageManager {
    public static ImageManager.Builder with(Context context) {
        return new Builder(context);
    }

    public static class Builder {
        private final RequestManager requestManager;
        private RequestBuilder<Drawable> requestBuilder;

        public Builder(Context context) {
            requestManager = Glide.with(context);
        }

        public Builder load(String url) {
            requestBuilder = requestManager.load(url);
            return this;
        }

        public Builder load(Uri uri) {
            requestBuilder = requestManager.load(uri);
            return this;
        }

        public void clear(ImageView imageView) {
            requestManager.clear(imageView);
        }

        public void into(ImageView imageView) {
            RequestOptions requestOptions = new RequestOptions();
            requestOptions = requestOptions.downsample(DownsampleStrategy.AT_LEAST);
            if (ViewCompat.getTransitionName(imageView) != null) {
                requestOptions = requestOptions.dontTransform();
            }
            requestBuilder.apply(requestOptions).thumbnail(0.1f).into(imageView);
        }
    }
}
```

Maybe this issue is related with this other [issue](https://github.com/bumptech/glide/issues/2035), but I didn't have a problem with this on that version so I created a new topic.

**Comment by sjudd** [comment] 2017-08-02 16:43
I'd guess you have view widths and heights that are not fixed? Ie they're match_parent, or wrap_content or something similar? Can you share your xml or the properties of the ImageView you're loading into?

If so it's probably b476c2aa03a6028485e6d3e8f90f38b86f86ed13, though I actually wouldn't have expected you to see any effect since isLaidOut seems like it was always false for views in a RecyclerView.

It's hard for us to tell when we're given a View without fixed layout parameters whether or not we can trust the existing View dimensions. For example, in a RecyclerView where views are sized using wrap_content/match_parent, the View passed to onBindView will have a non zero width and height, but that width and height will be based on the previous image and may be incorrect for the new image. 

If we don't wait for layout before starting the image load, we might load an image with incorrect dimensions. If we do we wait for layout when starting the image load, you might see a flicker because we can't load the image from the memory cache until we know what size to use. 

If you use stable ids and Glide implemented a way to ignore redundant request (ie detect that the new request exactly matches the  existing request for a given Target) that would fix the issue. Without stable ids, there's no guarantee RecyclerView will use the same View for the same position in the RecyclerView. Without an equality check in Glide, we always start a new request and rely on the memory cache to avoid flickering, which doesn't work here.

Totally possible that there's something simpler you're doing that could fix the issue, but if I'm correct about the cause, this will require some thought.

**Comment by kancic** [comment] 2017-08-02 19:49
I believe you are right, the ImageView size is not fixed. And I'm using stable ids. Here is the layout:

```xml
   <android.support.percent.PercentFrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:foreground="?selectableItemBackground"
        android:padding="4dp">

        <ImageView
            android:id="@+id/image"
            android:scaleType="centerCrop"
            android:transitionName="@{item.imageUrl}"
            app:layout_aspectRatio="100%"
            app:layout_widthPercent="100%"
            bind:imageUrl="@{item.imageUrl}"
            tools:src="@drawable/welcome_background" />
    </android.support.percent.PercentFrameLayout>
```

Thank you for the detailed answer. Sorry if I've missed something, It's late here, I will read again your answer tomorrow.

**Comment by Tolriq** [comment] 2017-08-04 17:13
@sjudd facing the same issue here outside of recyclerview.

The problem is about Android transitions, to avoid problems and slowdown, I rely on memory cache to reload images inside a detail fragment. (With no fixed size for the images).

The call is basic with noTransform but my datafetcher is forced to not download the image if it's not in it's internal cache so that the transition can start without waiting for the whole image being downloaded from Internet.

When the transition is finished I repeat the same call to either load the image if needed or just refresh from memory without transitions.

With last Glide 4.0, it seems the second call does not use memory cache and the transition is started, leading to the flickering.

**Comment by sjudd** [comment] 2017-08-04 18:36
@Tolriq What transition are you referring to? What is the second call? 

A second call can lead to flickering if the second request isn't identical to the first or (as described above) if the View doesn't have a fixed size and has a layout request pending.

**Comment by Tolriq** [comment] 2017-08-04 19:19
I talk about Android transitions sorry (Not cool to have that name too for imports ;) )

But I found my issue it seems Glide 4 not only rely on the cache key updated with updateDiskCacheKey but also take in account the hash code of the Model :(

I guess I miss read the docs about that change or if not documented it should be :)

**Comment by Tolriq** [comment] 2017-08-05 18:31
@sjudd Not sure this is 100% related but posting here to simplify as there's 90% chance it's tied :)

It seems that on Glide 4.0 you can't load an image in a ImageView with a GONE visibility even if the view was properly laid out before set to GONE. Was working in Glide 3.X.

Is this wanted new behavior or side effect from the commit you referenced ?

**Comment by kancic** [comment] 2017-08-07 08:16
I've done a little bit of testing and the issue is gone when I remove this line:

```java
            if (ViewCompat.getTransitionName(imageView) != null) {
                requestOptions = requestOptions.dontTransform();
            }

```

I'm using shared element transitions to animate transition between activities so I need this line to make the transitions smoother.

**Comment by Tolriq** [comment] 2017-08-07 08:30
@kancic Are you sure you also use dontTransform on the transition target too (in other activity)? Both were needed in Glide 3 to have 100% sucess I doubt this have changed.

Except the issue with not fully displayed image I use the same things as you (except the thumbnails) and have not this issue (Once fixed the hash code of the model, but you don't seems to use a special model).

Does all your images flicker or only those who may not be fully displayed?

On this same subject, fixing the hash code have solved 95% of the flickering, but I still have some in recyclerview on images that are not fully displayed.

Like if the first images is half displayed when recyclerview is updated this image will be reloaded with animation so not from memory cache. 

This does not seems related to @sjudd linked commit, so maybe there's something else somewhere else but can't find it.

**Comment by kancic** [comment] 2017-08-07 10:17
I use dontTransform on both of them (list + details screens), but not all of them in recyclerView flicker. I don't use a model, just a String for the url.

**Comment by sjudd** [comment] 2017-08-18 15:25
@kancic I have no idea why setting dontTransform would change anything if you're using Glide v4. There is no longer a default transition, so dontTransform() is only required if you manually set a transition on your request earlier. 

That said, since you're using stable ids, the issue might be fixed in the 4.1.0 snapshot. Might be worth a try.

**Comment by sjudd** [comment] 2017-08-18 15:29
I think with 73a8e0116a7826b631775f42f9a04aad374f3bb8 and 9d10097 this is fixed for users using stable ids in the 4.1 snapshot, which is what we set out to do here.

Closing for now. If you can still reproduce flashing in notifyDataSetChanged() with the 4.1 snapshot and stable ids, please re-open.

**Closed by sjudd** 2017-08-18 15:29 UTC
Labels: enhancement

**Comment by Tolriq** [comment] 2017-08-18 15:33
@sjudd can you clarify "so dontTransform() is only required if you manually set a transition on your request earlier."

In glide 3 dontTransform was mandatory for transitions.

Now in 4 I have left them but also use transition as animate no more exist by itself.
transitionOptions.transition(new FadeSaturateAnimation()); (ViewPropertyTranstion)

Does this setup change anything in item bounds / cache ? (The transition only play with fade / saturation matrix) ?

**Comment by sjudd** [comment] 2017-08-18 18:54
Ugh sorry dontTransform() is still required. dontTransition is no longer required because there is no default transition.

**Comment by kancic** [comment] 2017-08-21 12:20
@sjudd 4.1 snapshot fixed it, thank you very much 😄  👍

**Comment by sjudd** [comment] 2018-12-19 21:55
@thundertrick unfortunately your solution is unsafe. When you start a new request, the old request is cleared and it's resources may be recycled or re-used to display another image. With your solution you may experience random crashes, graphical corruption, or the user may see incorrect images.

If you want to retain the previous image until the new image loads, you can use the `.thumbnail()` API: http://bumptech.github.io/glide/doc/options.html#thumbnail-requests

If you want to cross fade between two different images, see: http://bumptech.github.io/glide/doc/transitions.html#cross-fading-across-requests
