### ISSUE TITLE
Error loading resources

### ISSUE THREAD

**Issue by matthieuchemin** [bumptech/glide#2265] opened 2017-08-18 11:54 UTC
**Glide Version**:
4.0.0

**Integration libraries**:

**Device/Android Version**:
Emulator Pixel / API 25

**Issue details / Repro steps / Use case background**: 
I have trouble loading resources to an image view using the `load` method.
I have test with several different resources.
I observed that this error only occurred when `firstResId` (the id of the drawable i use to call `load`) is the id of an xml drawable.
However this kind of drawable are handle fine by the placeholder method.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java

mGlideRequestManager  = Glide.with(DealThreadsFragmentBase.this)
...
mGlideRequestManager
                        .load(firstResId) //id of a drawable
                        .apply(mRequestOptions
                                .placeholder(secondeResId) //id of a drawable
                        )
                        .into(viewHolder.threadImageView);
```

**Layout XML**:
```xml
        <ImageView
            android:id="@+id/post_deal_thread_image"
            android:layout_width="96dp"
            android:layout_height="96dp"
            android:layout_marginLeft="@dimen/deal_thread_image_margin_left"
            android:layout_marginStart="@dimen/deal_thread_image_margin_left"
            android:scaleType="centerCrop"
            tools:src="@drawable/placeholder_deal_96dp" />
```

**Stack trace / LogCat**:
```ruby
I/Glide: Root cause (1 of 1)
 java.io.FileNotFoundException: Resource does not exist: 
  android.resource://com.pepper.apps.android.beta4.debug/drawable/smiley_devil_height_24dp

at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:976)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:907)
at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:21)
at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:13)
at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:40)
at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:95)
at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:398)
at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:359)
at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:129)
at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:48)
at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:95)
at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:252)
at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
```

**Comment by sjudd** [comment] 2017-08-18 14:09
Duplicate of #2137

**Closed by sjudd** 2017-08-18 14:09 UTC

**Comment by avnitambaliya31** [comment] 2021-10-11 04:05
I fetched the same issue with this. so, how to fix this crash error. any one please suggest me .
