### ISSUE TITLE
Placeholder issue with CircleImageView target

### ISSUE THREAD

**Issue by slodky** [bumptech/glide#528] opened 2015-07-08 09:03 UTC
I encountered problem when using CircleImageView (https://github.com/hdodenhof/CircleImageView). It also happens using CircularImageView (https://github.com/Pkmmte/CircularImageView).

When image is loaded from memory everything works fine but when loading from disk cache CircleImageView shows placeholder image. When using RequestListener method onResourceReady is properly called but placeholder image stays.
If no placeholder is set image is loaded properly.

Glide version: 3.6.1
Tested on Android 4.4 and 5.0

**Comment by TWiStErRob** [comment] 2015-07-08 10:47
Thanks for the report, we're aware of it and sadly not much we can do. In short the problem is that those `ImageView`s don't support `TransitionDrawable`. Suggestions are always welcome if you figure something out! 

This is a duplicate of #302, #504 and #482. Start reading at [my answer on #504](https://github.com/bumptech/glide/issues/504#issuecomment-113459960).

**Closed** 2015-07-15 14:29 UTC
