### ISSUE TITLE
Warning:com.bumptech.glide.load.resource.bitmap.VideoDecoder: can't find referenced method 'android.graphics.Bitmap getScaledFrameAtTime(long,int,int,int)' in library class android.media.MediaMetadataRetriever

### ISSUE THREAD

**Issue by noState** [bumptech/glide#2823] opened 2018-01-19 08:08 UTC
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment] 2018-01-19 15:05
Duplicate of #2780

**Closed by sjudd** 2018-01-19 15:05 UTC

**Comment by marmor7** [comment] 2018-12-27 10:21
I think this was merged into the wrong issue, this issue is related to a missing proguard snippet - a duplicate of https://github.com/bumptech/glide/issues/3331#issuecomment-430448716
