### ISSUE TITLE
Register too many Broadcast Receivers

### ISSUE THREAD

**Issue by qingyizeng** [bumptech/glide#3038] opened 2018-04-20 02:16 UTC
java.lang.AssertionError
Register too many Broadcast Receivers
android.app.LoadedApk.checkRecevierRegisteredLeakLocked(LoadedApk.java:1195)
android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1224)
android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1601)
android.app.ContextImpl.registerReceiver(ContextImpl.java:1574)
android.app.ContextImpl.registerReceiver(ContextImpl.java:1562)
android.content.ContextWrapper.registerReceiver(ContextWrapper.java:603)
com.bumptech.glide.manager.e.c(DefaultConnectivityMonitor.java:1054)
com.bumptech.glide.manager.a.a(ActivityFragmentLifecycle.java:50)
com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:175)
android.support.v4.app.Fragment.performStart(Fragment.java:2287)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1458)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3186)
android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:203)
android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:582)

**Comment by sjudd** [comment] 2018-04-25 16:39
Duplicate of #1161

**Closed by sjudd** 2018-04-25 16:39 UTC
