### ISSUE TITLE
onResourceReady "from"

### ISSUE THREAD

**Issue by farfromrefug** [bumptech/glide#339] opened 2015-02-11 17:18 UTC
Hi,

Is there a way to know in onResourceReady if the drawable was loaded from disk/cache/network ? just like picasso does.
This is very practical to only animate new drawable when coming from network (in listview).

Thanks

**Comment by sjudd** [comment] 2015-02-11 18:55
Looks like this is a duplicate of #108 

We may not get to everything @TWiStErRob listed in that bug, but we should be able to show local/remote/disk cache/memory cache at least.

**Closed by sjudd** 2015-02-11 18:55 UTC
Labels: enhancement

**Comment by farfromrefug** [comment] 2015-02-12 07:44
Sorry missed the other ticket!
