### ISSUE TITLE
NullPoint in recycleView

### ISSUE THREAD

**Issue by s949492225** [bumptech/glide#2044] opened 2017-06-16 05:57 UTC
GlideExecutor: Request threw uncaught throwable
                                                                  java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.clear()' on a null object reference
                                                                      at com.bumptech.glide.util.pool.FactoryPools$3.reset(FactoryPools.java:86)
                                                                      at com.bumptech.glide.util.pool.FactoryPools$3.reset(FactoryPools.java:83)
                                                                      at com.bumptech.glide.util.pool.FactoryPools$FactoryPool.release(FactoryPools.java:162)
                                                                      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.cleanup(MultiModelLoader.java:98)
                                                                      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.cleanup(MultiModelLoader.java:101)
                                                                      at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:87)
                                                                      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:45)
                                                                      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275)
                                                                      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:245)
                                                                      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:220)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                      at java.lang.Thread.run(Thread.java:761)
                                                                      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)

**Comment by sjudd** [comment] 2017-06-16 19:00
Dupe of #2028

**Closed by sjudd** 2017-06-16 19:00 UTC
