### ISSUE TITLE
Glide thumbnail and final image size wrong with crossFade

### ISSUE THREAD

**Issue by jaumard** [bumptech/glide#2931] opened 2018-03-03 15:25 UTC
**Glide Version**:4.6.1
**Integration libraries**: okhttp3
**Device/Android Version**:all
**Issue details / Repro steps / Use case background**: 
```
GlideApp.with(imageView.context)
                .load(url)
                .thumbnail(GlideApp.with(imageView.context)
                        .load(thumbnail))
                .transition(withCrossFade())
                .error(R.drawable.ic_error_outline_24dp)
                .into(imageView)
```
So maybe my usage is not correct but I want to load the thumbnail with has a square size (let's say 150 * 150) and then show the full resolution image (let's say 640 * 800). 
The final image has a square size once load instead to the right one. If I remove the transition `.transition(withCrossFade())` then the final image is ok.

Any idea ?

**Comment by thanhthein** [comment] 2018-03-03 17:36
this is my case #2922

**Comment by sjudd** [comment] 2018-03-08 16:29
Hi @jaumard,

It looks like you might not have included some important information when you filed this issue. To make sure we have all the information we need to help with your issue. Please take a look at the [Issue Template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md) and make sure you've filled out as many sections as possible.

In particular you **must** include:

* Glide Version
* Glide load line
* Issue details.

I'm marking this issue as requiring more information. Please understand that if you do not provide that information or update the issue within the next 7 days this issue will be automatically closed so that it doesn''t clutter the bug tracker.

Best regards,

~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by sjudd** [comment] 2018-03-08 16:30
Duplicate of #363

**Closed by sjudd** 2018-03-08 16:30 UTC
