### ISSUE TITLE
glide 4.7.1  Error

### ISSUE THREAD

**Issue by huahua495** [bumptech/glide#3157] opened 2018-06-21 02:12 UTC
@NonNull
  public final Registry setResourceDecoderBucketPriorityList(@NonNull List<String> buckets) {
    List<String> modifiedBuckets = new ArrayList<>(buckets);
    modifiedBuckets.add(0, BUCKET_PREPEND_ALL);
    modifiedBuckets.add(BUCKET_APPEND_ALL);
    decoderRegistry.setBucketPriorityList(modifiedBuckets);
    return this;
  }
It may appear here
java.lang.ClassCastException: int[] cannot be cast to java.lang.Object[]
        at java.util.Arrays$ArrayList.toArray(Arrays.java:120)
        at java.util.ArrayList.<init>(ArrayList.java:97)
        at com.bumptech.glide.Registry.setResourceDecoderBucketPriorityList(Registry.java:268)
Can you tell me what caused this?

Discovered by tracking， The last sentence here

  public Registry() {
    this.modelLoaderRegistry = new ModelLoaderRegistry(throwableListPool);
    this.encoderRegistry = new EncoderRegistry();
    this.decoderRegistry = new ResourceDecoderRegistry();
    this.resourceEncoderRegistry = new ResourceEncoderRegistry();
    this.dataRewinderRegistry = new DataRewinderRegistry();
    this.transcoderRegistry = new TranscoderRegistry();
    this.imageHeaderParserRegistry = new ImageHeaderParserRegistry();
    setResourceDecoderBucketPriorityList(
        Arrays.asList(BUCKET_GIF, BUCKET_BITMAP, BUCKET_BITMAP_DRAWABLE));
  }
 public static final String BUCKET_GIF = "Gif";
  public static final String BUCKET_BITMAP = "Bitmap";
  public static final String BUCKET_BITMAP_DRAWABLE = "BitmapDrawable";

Here is that this error should not occur

**Comment by fuyifang** [comment] 2018-06-27 07:04
I have the same problem,do you solve it ?

**Comment by huahua495** [comment] 2018-06-27 07:15
No, no solution was found for the time being

**Comment by fuyifang** [comment] 2018-06-27 07:18
do you use yunos?

**Comment by huahua495** [comment] 2018-06-27 07:21
没有用那个..

**Comment by sjudd** [comment] 2018-07-03 22:12
Can you attach a sample app where this reproduces?

**Comment by sjudd** [comment] 2018-07-03 22:13
And can you attach a complete stack trace?

**Comment by huahua495** [comment] 2018-07-04 06:06
Is the phone that we use the yunos system, this problem will occur during initialization.

**Comment by tobioyelekan** [comment] 2018-08-07 13:59
@sjudd please me with this issue https://stackoverflow.com/questions/51709880/glide-not-loading-image-from-redirect-link

**Comment by hellobalabala110** [comment] 2018-08-08 04:54
i have the same questions, when i was load a gif in adapter.

Fatal Exception: java.lang.ClassCastException: int[] cannot be cast to java.lang.Object[]
       at java.util.Arrays$ArrayList.toArray(Arrays.java:120)
       at java.util.ArrayList.<init>(ArrayList.java:97)
       at com.bumptech.glide.Registry.setResourceDecoderBucketPriorityList(Registry.java:268)
       at com.bumptech.glide.Registry.<init>(Registry.java:67)
       at com.bumptech.glide.Glide.<init>(Glide.java:333)
       at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:452)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java:264)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java:219)
       at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:180)
       at com.bumptech.glide.Glide.get(Glide.java:164)
       at com.bumptech.glide.Glide.getRetriever(Glide.java:671)
       at com.bumptech.glide.Glide.with(Glide.java:698)
       at com.example.boyibo.yesebo.view.glide.GlideApp.with(GlideApp.java:88)
       at com.example.boyibo.yesebo.view.glide.GlideUtils.load(GlideUtils.java:32)
       at com.example.boyibo.yesebo.adapter.HomeContentAdapter.convert(HomeContentAdapter.java:50)
       at com.example.boyibo.yesebo.adapter.HomeContentAdapter.convert(HomeContentAdapter.java:19)
       at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:919)
       at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
       at com.example.boyibo.yesebo.view.MLinearLayoutManager.onLayoutChildren(MLinearLayoutManager.java:25)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1160)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.layout(RefreshContentWrapper.java:182)
       at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:722)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1160)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
       at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1160)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java:386)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15127)
       at android.view.ViewGroup.layout(ViewGroup.java:4867)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2331)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2030)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1195)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6237)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5312)
       at java.lang.reflect.Method.invokeNative(NativeMethod)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)


my GlideUtils code :
  GlideApp.with(context).asGif().load(url)
                        .transition(withCrossFade(200))
                        .placeholder(PLACEHOLDER_IMG).error(PLACEHOLDER_IMG).into(iv);

the device is UOOGOU and the sdkversion is 4.4.2.

**Comment by sjudd** [comment] 2018-09-04 15:54
Duplicate of #3296

**Closed by sjudd** 2018-09-04 15:54 UTC
Labels: bug
