### ISSUE TITLE
Images on the first screen not showing

### ISSUE THREAD

**Issue by Crabime** [bumptech/glide#1508] opened 2016-10-09 11:06 UTC
Question i have put in SO, here is the [link](http://stackoverflow.com/questions/39939740/android-glide-image-is-not-showing-on-the-first-screen).

**Glide Version**: 3.7.0

**Integration libraries**: support-v4:24.1.1/appcompat-v7:24.1.1/design:24.1.1

**Device/Android Version**: Device android version 6.0

**Issue details / Repro steps / Use case background**:
I am using Android glide to load remote images, but here i met a strange problem which image on the first screen not showing but while i scroll down and scroll up again, those images become showing.

maybe you are not familiar with such process, I demonstrate it shortly, first I need to send request to my remote server and return image url, then i get such url and use glide to download it from remote(whatever server not mine) and show on the screen.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
public class SiteAdapter extends ArrayAdapter<Site> {
    private int resourceId;
    private List<Site> sites = null;
    private Context context;
    private SiteHolder siteHolder;
    /**
     * @param context the current activity context, we can get it using the super ArrayAdapter constructor
     * @param resource the site_layout.xml file
     * @param objects the collection to store all the sites
     */
    public SiteAdapter(Context context, int resource, List<Site> objects) {
        super(context, resource, objects);
        this.context = context;
        this.resourceId = resource;
        this.sites = objects;
    }

    @Override
    public Site getItem(int position) {
        return sites.get(position);
    }

    @Override
    public int getCount() {
        return sites.size();
    }

    //get the viewpage which inflate by site_layout.xml file
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        Site site = getItem(position);
        View view = convertView;
        siteHolder = new SiteHolder();
        if (view == null) {
            LayoutInflater vi = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
            view = vi.inflate(resourceId, null);
        }
        //this place we need to get the whole widget in site_layout.xml file
        siteHolder.image = (ImageView) view.findViewById(R.id.thumbnail);
        siteHolder.address = (TextView)view.findViewById(R.id.address);
        siteHolder.mallName = (TextView) view.findViewById(R.id.name);
        siteHolder.distance = (TextView) view.findViewById(R.id.distance);
        siteHolder.address.setText(site.getAddress());
        //set name of the view
        siteHolder.mallName.setText(site.getName());
        //set price of the view
        //set distance of the view
        siteHolder.distance.setText("<" + site.getDistance() + "m");
        //set image
        ImageTask task = new ImageTask();
        task.execute("http://xxxx/springmvc/getFirst/" + site.getName());
        return view;
    }

    //检测adapater中加载网络资源是否可行?结论:不可行
    public String getImgUrl(String str){
        String data = "";
        try {
            URL u = new URL(str);
            HttpURLConnection conn = (HttpURLConnection) u.openConnection();
            InputStream is = conn.getInputStream();
            BufferedReader br = new BufferedReader(new InputStreamReader(is));
            String content = "";
            StringBuffer sb = new StringBuffer();
            while((content = br.readLine()) != null){
                sb.append(content);
            }
            data = sb.toString();
            br.close();
            is.close();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return data;
    }
    class ImageTask extends AsyncTask<String, Void, String>{

        @Override
        protected String doInBackground(String... str) {
            String data = "";
            data = getImgUrl(str[0]);
            return data;
        }

        @Override
        protected void onPostExecute(String s) {
            Glide.with(context)
                .load(s)
                .fitCenter()
                .into(siteHolder.image);
        }
    }

    class SiteHolder{
        ImageView image;
        TextView mallName;
        TextView address;
        TextView distance;
    }
}
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="horizontal">
    <ImageView
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:id="@+id/thumbnail"
        android:layout_gravity="clip_horizontal"
        android:adjustViewBounds="true"
        android:maxWidth="60dp"
        android:maxHeight="60dp"
        android:src="@mipmap/ubuntu"
        android:contentDescription="left thumbnail"
        android:layout_marginLeft="15dp"
        android:layout_marginTop="5dp"
        android:layout_marginBottom="2dp"
        />
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_marginLeft="80dp"
        android:layout_marginTop="5dp"
        android:layout_marginRight="15dp"
        android:orientation="vertical"
        android:gravity="left">
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="5dp"
            android:layout_marginLeft="10dp"
            android:maxWidth="200dp"
            android:textSize="16sp"
            android:textStyle="bold"
            android:text="金堂羊蝎子"
            android:singleLine="true"
            android:maxLines="1"
            android:ellipsize="end"
            android:id="@+id/name"
            android:textColor="@color/black"/>
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:maxWidth="200dp"
            android:id="@+id/address"
            android:layout_marginTop="4dp"
            android:layout_marginLeft="10dp"
            android:textSize="12sp"
            android:singleLine="true"
            android:maxLines="1"
            android:ellipsize="end"
            tools:text="北京市海淀区紫竹院路北方地产大厦"/>
    </LinearLayout>
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/distance"
        android:text="&lt;500m"
        android:layout_marginStart="300dp"
        android:layout_marginLeft="300dp"
        android:layout_marginTop="18dp"
        />
</RelativeLayout>
```

**Stack trace / LogCat**:
last but not least, using `adb shell setprop log.tag.xxx DEBUG` does not show any error.

![](http://i.stack.imgur.com/jPDSs.png)

**Comment by TWiStErRob** [comment] 2016-10-09 11:42
Updated your above comment with info from SO, can you please fill in the remaining info? (e.g. XML)

**Comment by TWiStErRob** [comment] 2016-10-09 16:37
Thanks for moving to this forum, it's easier to have a conversation here; SO is not designed for that.

Here's some stuff that's worth trying. Not all of them necessarily connected to this issue, but we never know. I'll just write down what I would change, the rest is up to you:
 * Change `android:src="@mipmap/ubuntu"` to `tools:src="@mipmap/ubuntu"` for two reasons: 1) it's a waste load the image and it may flash to the user on a bad connection. 2) If you really want to show this icon while the image is loading, use `.placeholder()`; without that you wouldn't get the same behavior after first inflate and later when you recycle items (scrolling). You can do the same with `android:text="&lt;500m"`.
 * `android:layout_gravity="clip_horizontal"` not sure what `clip_` means, but it may affect how Glide sees the `ImageView`'s size and hence fail, try without that, and when we find the root cause put it back
 * You're using the `ViewHolder` pattern in a little weird way. The point of it is to prevent calling `findViewById` on recycling items, yet you allocate a new `SiteHolder` every time and popuplate it. Move all the `findViewById` calls right after `inflate` inside the if and call `convertView.setTag(holder)`. When `convertView` is not null, just use `SiteHolder holder = (SiteHolder)convertView.getTag();`.
 * **I think I just discovered what's wrong with your code: you're storing `siteHolder` in a field of the adapter, which means that at ever bind of a row you're overwriting it. This explains why you have only the last image visible and not the rest.**
 * `StringBuffer` is synchronized and slow, which is unnecessary for single-threaded access like your use case, use `StringBuilder`.
 * You can do much better than that AsyncTask. It is wasteful, think about this case: user flings the list. What happens? Let's say the fling scrolls down 50 items. For each item you fire an AsyncTask which you never cancel, so even after quickly recycling and re-binding the first 40 items there are 40 in-flight requests going on. We can do better, here's how:

	```java
	// replace `new ImageTask().execute()` with this statement:
	Glide.with(context)
		     .load(new IndirectImage("http://xxxx/springmvc/getFirst/" + site.getName()))
		     .fitCenter()
		     .into(siteHolder.image);

	// in GlideModule, see https://github.com/bumptech/glide/wiki/Configuration
	glide.register(IndirectImage.class, InputStream.class, new ModelLoaderFactory<IndirectImage, InputStream>() {
		@Override public ModelLoader<IndirectImage, InputStream> build(
				Context context, GenericLoaderFactory factories) {
			final ModelLoader<String, InputStream> realLoader =
					factories.buildModelLoader(String.class, InputStream.class);
			return new StreamModelLoader<IndirectImage>() {
				@Override public DataFetcher<InputStream> getResourceFetcher(
						IndirectImage model, int width, int height) {
					return new IndirectImageFetcher(realLoader, model, width, height);
				}
			};
		}
		@Override public void teardown() {}
	});

	// This class is only needed for Glide to be able to distinguish between a String
	// and a String that needs your special double-dispatch handling.
	public class IndirectImage {
		private final String url;
		public IndirectImage(String url) {
			this.url = url;
		}
		public String getIndirectUrl() {
			return url;
		}
	}
	```

	```java
	public class IndirectImageFetcher implements DataFetcher<InputStream> {
		private final ModelLoader<String, InputStream> realLoader;
		private final IndirectImage model;
		private final int width;
		private final int height;

		private volatile boolean cancelled;
		private HttpURLConnection conn;
		private BufferedReader reader;
		private DataFetcher<InputStream> realFetcher;

		public IndirectImageFetcher(
				ModelLoader<String, InputStream> realLoader, IndirectImage model, int width, int height) {
			this.realLoader = realLoader;
			this.model = model;
			this.width = width;
			this.height = height;
		}

		@WorkerThread
		@Override public InputStream loadData(Priority priority) throws Exception {
			conn = (HttpURLConnection)new URL(model.getIndirectUrl()).openConnection();
			if (cancelled) {
				// break in case we got cancelled while retrieving the url
				return null;
			}
			reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			// Note: URLs cannot be multiline, so reading a single line is enough
			String url = reader.readLine();
			if (cancelled) {
				// break in case we got cancelled while retrieving the url
				return null;
			}
			realFetcher = realLoader.getResourceFetcher(url, width, height);
			return realFetcher.loadData(priority);
		}
		@Override public void cleanup() {
			if (realFetcher != null) {
				realFetcher.cleanup();
			}
			freeResources();
		}
		@Override public String getId() {
			// cache by the original Url, not the retrieved one
			// this prevents future unnecessary lookups and allows for quick cache access
			return model.getIndirectUrl();
		}
		@Override public void cancel() {
			cancelled = true;
			if (realFetcher != null) {
				realFetcher.cancel();
				realFetcher = null;
			}
			freeResources();
		}
		private void freeResources() {
			if (reader != null) {
				try {
					reader.close();
					reader = null;
				} catch (IOException ignore) {
					// can't do much about it, our result is already ignored
				}
			}
			if (conn != null) {
				conn.disconnect();
				conn = null;
			}
		}
	}
	```

 * You can take the above one step further: cache the resolved url so you don't need to send 2 requests every time. Add a `String resolvedUrl` field into `IndirectImage` and change the fetcher to check for null on that field + `model.resolvedUrl  = reader.readLine();` + `getResourceFetcher(model.resolvedUrl)`. This will update the model and read as necessary, but for this to work you have to populate your adapter with `IndirectImage` objects, instead of having just a simple String as url.
 * Note: `IndirectImage` can be merged with `Site` so you can `.load(site)`.

**Closed** 2016-10-09 16:47 UTC
Labels: question
