### ISSUE TITLE
NoSuchMethodError: com.google.common.collect.FluentIterable.join

### ISSUE THREAD

**Issue by MartinT86** [bumptech/glide#2375] opened 2017-09-11 20:32 UTC
Hi,
I'm trying to use glide alongside google vision api. However I am getting the following error when I try and the glide and google vision api dependencies at the same time.

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.join(Lcom/google/common/base/Joiner;)Ljava/lang/String;

**Glide Version**:
compile 'com.github.bumptech.glide:glide:4.1.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'

**Integration libraries**:
compile 'com.google.apis:google-api-services-vision:v1-rev360-1.22.0'

**Issue details / Repro steps / Use case background**: 

This error occurs on a clean new android studio project if you add the glide and the google vision api dependencies.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

I am trying to get the generated api working.
Using standard Glide.with... works fine but if I add the MyAppGlideModule class thats when the error occurs.

I am trying to use GlideApp.... as i want to edit my caching strategies.

**Comment by sjudd** [comment] 2017-09-11 20:42
Probably a duplicate of #2059. You might be able to update versions so that they both use the same version of guava.

**Comment by MartinT86** [comment] 2017-09-11 20:48
Thanks for coming back to me so quickly.
And forgive me if I'm wrong on this, I'm relatively new to android still, but I believe the dependencies I've listed are the latest available for both glide and the Google vision API?

**Comment by TWiStErRob** [comment] 2017-09-11 21:24
@MartinT86 vision is a `compile` time dependency, Glide is too. The problem likely stems from the `annotationProcessor`, do you have any other? Try running `gradlew :app:dependencies --configuration annotationProcessor` and look for arrows on lines where Guava is mentioned.

**Comment by MartinT86** [comment] 2017-09-12 21:07
hi @TWiStErRob no there are no other annotation processors.

i've tried to follow the advice from this issue #2064 but i've still had no luck.

i've tried adding guave directly 
`annotationProcessor 'com.google.guava:guava:23.0'`

i've tried excluding guava from glide (i'm not even sure if i'm trying to do that correctly)
`annotationProcessor ('com.github.bumptech.glide:compiler:4.1.1') {
        exclude group: 'com.google.guava', module: 'guava-jdk5'
}`

running gradlew :app:dependencies --configuration annotationProcessor returned;

`annotationProcessor - Classpath for the annotation processor for 'main'.
+--- com.github.bumptech.glide:compiler:4.1.1
|    +--- com.squareup:javapoet:1.9.0
|    +--- com.google.auto.service:auto-service:1.0-rc3
|    |    +--- com.google.auto:auto-common:0.3
|    |    |    \--- com.google.guava:guava:18.0 -> 23.0
|    |    |         +--- com.google.code.findbugs:jsr305:1.3.9 -> 3.0.1
|    |    |         +--- com.google.errorprone:error_prone_annotations:2.0.18
|    |    |         +--- com.google.j2objc:j2objc-annotations:1.1
|    |    |         \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
|    |    \--- com.google.guava:guava:19.0 -> 23.0 (*)
|    +--- com.google.code.findbugs:jsr305:3.0.1
|    \--- com.github.bumptech.glide:annotations:4.1.1
\--- com.google.guava:guava:23.0 (*)

(*) - dependencies omitted (listed previously)

BUILD SUCCESSFUL

Total time: 2.08 secs`

so no error there? any advice would be massively helpful as this is basically meaning i cant use glide with my app which would be a great shame.

thanks

**Comment by sjudd** [comment] 2017-09-15 14:17
Hopefully this is fixed in #2059. You can use the [snapshot][1] to test it out.

[1]: http://bumptech.github.io/glide/dev/snapshots.html

**Closed by sjudd** 2017-09-15 14:17 UTC

**Comment by GrzegorzFeather** [comment] 2017-09-21 22:14
@sjudd `4.2.0-SNAPSHOT` fixed it for me

**Comment by sjudd** [comment] 2017-09-22 14:30
Thanks for confirming!
