### ISSUE TITLE
Called reconfigure on a bitmap that is in use! This may cause graphical corruption!

### ISSUE THREAD

**Issue by nirmal912** [bumptech/glide#1961] opened 2017-05-23 20:29 UTC
I have to load multiple GIF in Activity, it works fine but getting continuously this message **Called reconfigure on a bitmap that is in use! This may cause graphical corruption!**
 i am using GIF from Drawable folder

this new gradle version i am using right now **compile 'com.github.bumptech.glide:glide:4.0.0-RC0'**

this is how m calling image to set using my holder.

        Glide.with(mContext).load(arrayList.get(position))
                .apply(new RequestOptions()
                        .placeholder(R.mipmap.ic_launcher)
                        .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC))

                .into(holder.ivSponser);

**Comment by sjudd** [comment] 2017-05-24 14:44
Duplicate of #743

**Closed by sjudd** 2017-05-24 14:44 UTC
