### ISSUE TITLE
Can not find GlideApp Class in glide 4.0?

### ISSUE THREAD

**Issue by developerHaoz** [bumptech/glide#1966] opened 2017-05-24 14:40 UTC
Can not find GlideApp Class in glide 4.0?

**Comment by sjudd** [comment] 2017-05-24 14:42
See http://bumptech.github.io/glide/doc/getting-started.html.

You need an ``AppGlideModule`` annotated with ``@GlideModule`` and a dependency on Glide's annotation processor in your build.gradle file. 

Alternatively you can continue to use Glide as a substitute if you don't want to use the generated API.

This is a duplicate of #1939

**Closed by sjudd** 2017-05-24 14:42 UTC
Labels: duplicate

**Comment by sjudd** [comment] 2017-08-15 23:57
Duplicate of #1939

**Comment by developerHaoz** [comment] 2017-08-16 01:36
thanks.

**Comment by checkming** [comment] 2019-06-25 03:09
You could make project in "android studio -> build -> rclean project - > ebuild project - > make project", Repeat the above operation！
it will generate the GlideApp class.
