### ISSUE TITLE
AndroidX android 4.9.0

### ISSUE THREAD

**Issue by Yinzeyu** [bumptech/glide#3680] opened 2019-05-30 06:31 UTC
Glide  Version 4.9.0 does not support AndrdoidX?，Only version 4.8 supports Androidx? Why does version 4.8 support version 4.9 not support Android X?

**Comment by CristianGM** [comment] 2019-05-30 09:22
Could you please add some information to the issue?
What's the error? In which case?

**Comment by sjudd** [comment] 2019-05-31 19:36
Duplicate of #3184

**Closed by sjudd** 2019-05-31 19:36 UTC

**Comment by HDHunter** [comment] 2019-08-06 13:29
Do we have AndroidX Version ?

**Comment by Yinzeyu** [comment] 2019-08-06 13:34
yes,androidx version   Glide  Version 4.9.0

**Comment by Yinzeyu** [comment] 2019-08-06 13:35
> Do we have AndroidX Version ?

yes,androidx Glide Version 4.9.0

**Comment by ZakTaccardi** [comment] 2019-08-08 21:56
`4.9.0` does not support AndroidX. AndroidX will be supported in `4.10.0` - but that has not been released yet.

`4.10.0-SNAPSHOT` has AndroidX support
