### ISSUE TITLE
Failed to resolve okhttp3-integration:1.4.0@jar and okhttp3-integration:1.4.0

### ISSUE THREAD

**Issue by start141** [bumptech/glide#1168] opened 2016-04-29 09:52 UTC
Failed to resolve: glide-parent:library:unspecified

using
compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@jar' and
compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0'

**Comment by TWiStErRob** [comment] 2016-04-29 09:55
Duplicate of #941.

Tip: if you copy your title or even whole description into Google Search you'll be directed to #957 / #941.

**Closed by TWiStErRob** 2016-04-29 09:55 UTC
Labels: bug, duplicate

**Comment by start141** [comment] 2016-04-29 10:00
thanks!
