### ISSUE TITLE
com.bumptech.glide.request.target.ViewTarget MemoryLeak

### ISSUE THREAD

**Issue by DenBond7** [bumptech/glide#1021] opened 2016-03-02 09:12 UTC
Hello. I found a memory leak in **com.bumptech.glide.request.target.ViewTarget**.

**GlideDrawableImageViewTarget** provide a memory leak. It keeps a reference to my activity. And GC can not release the activity.

![2016-02-24_17-33-43](https://cloud.githubusercontent.com/assets/2863246/13455487/59200878-e066-11e5-9ea9-f145a9f6506a.png)

I found this problem when run "SELECT * FROM instanceof android.support.v7.app.AppCompatActivity" in MAT.

When I use 
`protected final WeakReference<T> view;`
 in  **com.bumptech.glide.request.target.ViewTarget** I resolved this problem for me. 

P.S. Sorry for my English :)

**Comment by TWiStErRob** [comment] 2016-03-02 10:39
That's normal, is that activity closed? and did you use `Glide.with((Activity)this)` (cast is  not necessary just to show which overload is used)?

For more info on why I ask this:
http://stackoverflow.com/a/32887693/253468

**Comment by TWiStErRob** [comment] 2016-03-02 10:41
Also it looks like that request is in-flight because it's referenced by a worker thread.

**Comment by DenBond7** [comment] 2016-03-02 10:48
I use Glide.with(this) everywhere. 
This problem I received after next steps:

1. Open my app

1. Open an activity where showing RecycelerView with images (load by Glide.with(this))

1. Then press Back -> Back -> .... Home Screen.

1. After I wait about 1 minute and press to run GC. 

1. Then I collect glide.hprof

**Comment by TWiStErRob** [comment] 2016-03-02 11:13
Hmm, that's strange, I would expect step 3 to destroy your app, so much that you shouldn't be able to take a dump of it. I'll try to repro.

@sjudd any thoughts?

**Comment by DenBond7** [comment] 2016-03-02 11:18
Ok. If you need more information, write what I can still be useful.

**Comment by DenBond7** [comment] 2016-03-02 11:18
Sorry, I closed by mistake

**Comment by TWiStErRob** [comment] 2016-03-02 11:57
Just an update: so far I wasn't able to pinpoint Glide as the source of Activity retainment. It always shows `InputMethodManager` or `ViewConfiguration` as the GC root.

**Comment by TWiStErRob** [comment] 2016-03-02 12:23
Nope, they always come back as being held by those two classes. I cannot make the system hold more than two activities even if I keep starting the app again and again from the app drawer. 1 activity is held by IMM and another one is by VC. I'm using a Galaxy S4, maybe that's why it's different: square/leakcanary#1
Can you consistently reproduce this issue? Are you able to leak more than one activity?

**Comment by DenBond7** [comment] 2016-03-02 12:53
Ok, I will do it.

**Comment by DenBond7** [comment] 2016-03-09 10:03
Hello. Sorry, I was unobservant. I created a new [issue](https://github.com/bumptech/glide/issues/1044).

**Comment by TWiStErRob** [comment] 2016-03-09 10:52
I'll close this as a duplicate of #1044 as that has more info.

**Closed** 2016-03-09 10:52 UTC
Labels: duplicate, question
