### ISSUE TITLE
Canvas: trying to use a recycled bitmap randomly when cycling through images

### ISSUE THREAD

**Issue by jt-gilkeson** [bumptech/glide#625] opened 2015-09-14 22:33 UTC
I've got 3 views that I'm loading random images into on a timer.  I'm trying to crossfade the new image with the currently displayed image.  I basically get a random image from a list of about 10 and call the method below 3 times (with different views) every 6 seconds.  

This works most of the time, but sometimes it crashes due to the exception included below. When I was using a button click to do the update I was able to have this exception happen pretty easily.   I'm wondering if there is some sort of race condition internally on the fetch and render between the previous call and the new call?  

Is there a better way to do this or should this work as I'm currently using it?

Using 3.6.1

Here's the code:
```
mDownloadedSize is the max of the screen width or height - I'm using this so rotations have immediate cache hit image loading.  

private void loadImage(ImageView view, String photoUrl)
{
			Drawable oldImage = view.getDrawable();
			Glide.with(MyFragment.this)
				 .load(photoUrl)
				 .crossFade()
				 .placeholder(oldImage)
				 .override(mDownloadSize, mDownloadSize)
				 .centerCrop()
				 .into(view);
}
```

```
    java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@20260fad
            at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
            at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:599)
            at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(GlideBitmapDrawable.java:101)
            at com.bumptech.glide.request.target.SquaringDrawable.draw(SquaringDrawable.java:151)
            at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:198)
            at android.widget.ImageView.onDraw(ImageView.java:1158)
            at android.view.View.draw(View.java:15231)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewG
```

**Comment by TWiStErRob** [comment] 2015-09-14 23:26
The problem is `getDrawable()`, as soon as you have a reference to that and want to use it later, you're working against Glide. `into()` calls `clear` which returns the `Bitmap` inside `oldImage` into the `BitmapPool` which means that it's recycled and ready to be re-used for any further loads (maybe even the one you're just starting). After `clear`-ing the target Glide loads your new image into the - now empty - target. The problem here is that `Target`'s the ownership of a `Bitmap` starts with `Target.onResourceReady` and ends with `Target.onLoadCleared` (actually on in `onLoadCleared` the resources are already freed = the Bitmap is returned to the pool, so it's already invalid), however you're still using it after `onLoadCleared` because you saved it in a local and it'll be handed to `Target.onLoadStarted` during `into`'s execution and then the `ImageView` will try to draw it, as the exception shows.

The solution I can think of is to make a copy of that drawable's `Bitmap` and then use that new bitmap as a placeholder. Using `.asBitmap()` would help you to make sure it's a `BitmapDrawable` you can hack the bitmap out of easily and make a `copy()` of it. @sjudd do you know a better one?

**Comment by jt-gilkeson** [comment] 2015-09-14 23:45
Any chance of adding an enhancement to glide for crossfade() to use the imageview's current image (if there is one) if placeholder() is not set?  (i.e. if I'm telling it to crossfade and not providing a placeholder is there a use case for not crossfading with the current image?)

**Comment by sjudd** [comment] 2015-09-15 00:29
I think this is a duplicate of #132, let me know if that doesn't provide enough context.

**Comment by jt-gilkeson** [comment] 2015-09-15 00:46
So it sounds like the "safe" workaround is in https://github.com/bumptech/glide/issues/527  i.e. make a bitmap copy of the current view and use that as the placeholder is the best way to crossfade from the current view to the new image?

**Comment by jt-gilkeson** [comment] 2015-09-15 01:33
OK I think I've got something working, not sure how safe it is, but it seems to do what I want.

```
		private void loadImage(ImageView view, String photo)
		{
			Drawable safeImage = copy(view.getDrawable());
			Glide.with(SplashboardFragment.this)
				 .load(photo)
				 .crossFade()
				 .placeholder(safeImage)
				 .override(mDownloadSize, mDownloadSize)
				 .centerCrop()
				 .into(view);
		}

		private Drawable copy(Drawable drawable)
		{
			Bitmap bitmap = null;
			Drawable tempDrawable = drawable;

			if (drawable instanceof TransitionDrawable)
			{
				tempDrawable = ((TransitionDrawable)drawable).getDrawable(1);
			}

			if (tempDrawable instanceof BitmapDrawable)
			{
				bitmap = ((BitmapDrawable)tempDrawable).getBitmap();
			}
			else if (tempDrawable instanceof GlideBitmapDrawable)
			{
				bitmap = ((GlideBitmapDrawable)tempDrawable).getBitmap();
			}
			else if (tempDrawable instanceof SquaringDrawable)
			{
				SquaringDrawable sq = (SquaringDrawable)tempDrawable;
				bitmap = ((GlideBitmapDrawable)sq.getCurrent()).getBitmap();
			}

			if (bitmap != null)
			{
				bitmap = bitmap.copy(bitmap.getConfig(), bitmap.isMutable());
				return new BitmapDrawable(getResources(), bitmap);
			}

			return null;
		}
```

**Comment by sjudd** [comment] 2015-09-15 01:50
Yes we don't perform animations from cache. A common case is someone calls notifyDataSetChanged on a list or a grid, you wouldn't want all of the already on screen images to run a cross fade and blink in and out.

One alternative to your solution might be to use a ViewSwitcher. It's perfectly safe to load two different images into two different Views, so you could load the next image into the ViewSwitcher's next view, and then swap the views when the load finishes to cross fade.

**Comment by TWiStErRob** [comment] 2015-09-15 10:20
See #545 for skipping `SquaringDrawable`.

**Comment by sjudd** [comment] 2015-09-15 14:38
I'm going to close this as a duplicate of #132 for now. Hopefully you've got something working, either from @TWiStErRob's suggestion or mine above.

**Closed by sjudd** 2015-09-15 14:38 UTC
