### ISSUE TITLE
Feature Request: Image Loading Backoff with Down-Sampling

### ISSUE THREAD

**Issue by ygnessin** [bumptech/glide#1762] opened 2017-03-02 02:45 UTC
In today's post in the [Android Developers Blog](https://android-developers.googleblog.com/2017/03/getting-santa-tracker-into-shape.html), Google described an image loading backoff strategy that enables them to display downsampled images while eliminating OOMs.

Would it be possible for Glide to implement something similar in its Bitmap decoding? In our app I have definitely seen older devices fail to load images due to being out of memory, and downsampling like this could help!

I've reproduced the relevant part of the blog post below:

> **Image Loading Backoff**
>
> When initializing a game in Santa Tracker we often load all of the Bitmaps needed for the first scene into memory so that the game can run smoothly.  The naive approach looks like this:
> 
> ```java
> private LruCache<Integer, Drawable> mMemoryCache;
> private BitmapFactory.Options mOptions;
> public void init() {
>   // Initialize the cache
>   mMemoryCache = new LruCache<Integer, Drawable>(240);
>   // Start with no Bitmap sampling
>   mOptions = new BitmapFactory.Options();
>   mOptions.inSampleSize = 1;
> }
> public void loadBitmap(@DrawableRes int id) {
>     // Load bitmap
>     Bitmap bmp = BitmapFactory.decodeResource(getResources(), id, mOptions);
>     BitmapDrawable bitmapDrawable = new BitmapDrawable(getResources(), bmp);
>     
>     // Add to cache
>     mMemoryCache.put(id, bitmapDrawable);
> }
> ```
> 
> However the decodeResource function will throw an OutOfMemoryError if we don't have enough RAM to load the Bitmap into memory.  To combat this, we catch these errors and then try to reload all of the images with a higher sampling ratio (scaling by a factor of 2 each time):
> 
> ```java
> private static final int MAX_DOWNSAMPLING_ATTEMPTS = 3;
> private int mDownsamplingAttempts = 0;
> private Bitmap tryLoadBitmap(@DrawableRes int id) throws Exception {
>     try {
>         return BitmapFactory.decodeResource(getResources(), id, mOptions);
>     } catch (OutOfMemoryError oom) {
>         if (mDownSamplingAttempts < MAX_DOWNSAMPLING_ATTEMPTS) {
>             // Increase our sampling by a factor of 2
>             mOptions.inSampleSize *= 2;
>             mDownSamplingAttempts++;
>         }
>     }
>     throw new Exception("Failed to load resource ID: " + resourceId);
> }
> ```
> 
> With this technique low-memory devices will now see more pixelated graphics, but by making this tradeoff we almost completely eliminated memory errors from Bitmap loading.

**Comment by sjudd** [comment] 2017-03-02 16:00
I always appreciate seeing what other people are trying. I don't think this particular usage is a good idea though.

Most OOMs in Android apps are either wildly inappropriate Bitmap sizes or memory leaks. 

If the issue is a memory leak, then catching OOMs like this won't fix the underlying problem. Instead it will just mean you will see OOMs in different parts of your codebase, not where you allocate Bitmaps.

If the issue is inappropriate Bitmap sizes, you're much better off picking a reasonable image size than trying to load the largest Bitmap you can stuff in memory. By default, Glide aims to use the size of the view you're going to display a Bitmap in. Using the size of the view allows the images to look good and automatically scales them for the screen density and RAM of each individual device. No reasonable Android device would have a screen size that requires more pixels than can be held in memory.

There's also a danger to to scaling down downsampling attempts. In some cases you will get the perfect combination of memory cap and image size where you fill almost all of your remaining memory cap with a single image and then crash when you try to allocate the next object.

With all that said, I don't really understand the use case of Santa Tracker. They may have some special reason for needing this logic that I don't understand. I definitely don't think it's a good generalized approach to image loading in Android.

**Closed by sjudd** 2017-03-02 16:00 UTC

**Comment by ygnessin** [comment] 2017-03-03 19:00
@sjudd Thanks for taking the time to look into it, and thanks for the great library!
