### ISSUE TITLE
GifDecode byte[] buffer memory allocations keeps growing?

### ISSUE THREAD

**Issue by sumbulAlvi** [bumptech/glide#785] opened 2015-12-03 21:11 UTC
Hi. For the Tumblr app, we're seeing a nonstop-growth in memory allocations through Android Monitor. This occurs the more and more a user browses the app, through multiple posts (majority of posts are GIF and image heavy).The allocated memory stays at a constant size even when the user is idle on just one post. Through getting the heap dump at around 200-250MB mem allocation, the following classes are found:
<img width="733" alt="screen shot 2015-12-03 at 3 44 59 pm" src="https://cloud.githubusercontent.com/assets/14984167/11574153/e8b71a42-99d7-11e5-9018-8fe6cc443baa.png">
Specifically:
`byte[]: 182MB`, 
`Bitmap: 109MB`

The `Bitmap` resources can be passed off as the bitmaps being held in the Bitmap pool which is okay. However, the `byte[]` arrays growing is suspect. 

After running and analyzing the allocation tracking logs, it looks like the top Allocator classes involved are `ByteArrayOutputStream` (55%) and Glide's `GifDecoder` class (24%) which most likely uses `ByteArrayOutputStream`. This makes sense as the `byte[]` arrays are the ones that have had the majority of allocations, presumably from gif decoding. Looking at the methods that are doing majority of the memory allocations, we see `cacheAndDecodeSourceData() -> decode():22 GifBitmapWrapperStreamResourceDecoder`, `decodeFromSourceData()` and `loadFromCache()`. 

So: All of the `byte[]` objects are being allocated here used for gif image decoding/encoding. 

The question is, why are the `byte[]` buffers not freed? Why do they remain in memory and continue grow with the number of GIFs appearing on screen? When forcing garbage collector through Android Monitor, the `byte[]` arrays are still not freed so there is some reference to the `byte[]` objects even after the decode has completed and we are sitting stationary at some screen of the app. Could you provide some insight into this? Much appreciated, thanks!

**Comment by TWiStErRob** [comment] 2015-12-03 21:15
Without looking at the code my first suggestion would be that if you have all this data and reproduced you should take a heap dump and analyze it more deeply by looking at those `byte[]` objects and checking what's keeping them in memory by walking the incoming references.

**Comment by TWiStErRob** [comment] 2015-12-03 21:20
There's also a known issue for GIFs, likely you found that too #690

**Comment by sjudd** [comment] 2015-12-03 21:30
A heap dump would definitely be helpful, if you can take after you've noticed memory usage has gotten unreasonably large.

Also what version of Glide are you using?

**Comment by sumbulAlvi** [comment] 2015-12-05 00:13
Thanks for the response @TWiStErRob  & @sjudd. I've been going through the heap dumps and consistently see very high level of allocations for `byte[]`, around 300MB after lots of scrolling, and potential to grow if I continue. Using MAT, the top references are from `android.graphics.Bitmap` (accounting for 191MB) as expected. Using merge-shortest-paths-to-GC, we see the following 
![screen shot 2015-12-04 at 6 33 30 pm](https://cloud.githubusercontent.com/assets/14984167/11604461/b6741ace-9aba-11e5-9acd-1091ffe834e2.png)

Still not much information about what the suspect objects are that are holding on to ~300MB bytes in this dump.

I will try to use a snapshot of Glide 4.0 and see if that makes any difference. Currently, I'm using 3.6.1.

**Comment by TWiStErRob** [comment] 2015-12-05 08:57
Can we repro this in the released Thumblr app, or can you share a heap dump (.hprof) on Drive or something?

If this is #690, 4.0 won't help.

I'd say try to disable the Bitmap pool because it's misleading (use `BitmapPoolAdapter` in `GlideModule`), hopefully it still repros after that too.

Does this lead to an OutOfMemoryError if you scroll a lot lot?

**Comment by sumbulAlvi** [comment] 2015-12-08 18:36
Is there any email I can send the (.hprof) file to from `sumbul@tumblr.com`? After disabling the Bitmap pool, the problem is persisting and the OOM occurs shortly after scrolling through many posts again.

**Comment by TWiStErRob** [comment] 2015-12-08 18:55
I think GMail can't handle 300MiB attachments (or maybe that limit is only for sending?!). I guess the best is to upload it somewhere and put the link here (or send us both a link, emails on GitHub profiles, if you want to keep it private).

**Comment by sjudd** [comment] 2016-01-28 15:15
This may have been fixed in #892? Can you try again on 3.7 and see if you still see the same issues?

**Comment by rrahul** [comment] 2016-02-03 17:20
I'm facing similar issue with 3.7.0, ( not sure exactly same issue, but i can see lot of byte arrays as mentioned above, accumulated over time)
I am using glide like
      Glide.with(APPLICATION_CONTEXT)
                .load(imageUri)
                .crossFade()
                .fitCenter()
                .placeholder(myplaceholderimage)
                .into(imageView);
from my CursorAdapter's bindView().I make this glide call right from my bindView


And my ImageView looks like
 <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:adjustViewBounds="true"
            android:maxHeight="@dimen/max_width"
            android:maxWidth="@dimen/max_width"/>

The scrolling is laggy and out of memory error is thrown, after sometime, while scrolling in a list with about 30-40 gifs

![1](https://cloud.githubusercontent.com/assets/1327172/12790131/24ada698-caa1-11e5-898e-679ab331665d.png)
![2](https://cloud.githubusercontent.com/assets/1327172/12790130/24ac8376-caa1-11e5-8e97-36f13c7f6fac.png)
![3](https://cloud.githubusercontent.com/assets/1327172/12790129/24ac3574-caa1-11e5-99f8-fc4f2d5a9a2c.png)

**Comment by TWiStErRob** [comment] 2016-02-21 22:47
We had some offline discussions with Sumbul about this and couldn't find any definitive proof of Glide mishaps. Most of the memory we found was accounted for, one way or another. The flow that she analyzed contained a lot of scrolling and multiple activities/fragments/viewpagers on top of each other, each holding on to their respective resources. Also `.override(SIZE_ORIGINAL)` was used a lot in the code which results in unnecessarily huge allocations.

Here are some tips I wrote:
 * use SOURCE cache only for GIFs
 * Clear the image views as soon as their items are recycled in RecyclerView.Adapter#onViewRecycled. If there are many different types of items layouts and they can hold a lot of images in memory unnecessarily even when not visible (in scrap).
 * Somehow unbind the current visible items in onStop and re-bind in onStart when you come back, this will help with stuff kept in the background
 * Be careful with ViewPagers, they cache the offscreen views, and if that's a list with animated GIFs you may have double memory usage; again hook into their lifecycle and clear/re-bind when necessary

In our last correspondence she said:

> I resolved a lot of the memory issues by manually releasing resources by calling `Glide.clear(target)` whenever an item was recycled.

Considering the above and the related fixes to `rawData` I'm closing this. If there's any proof of Glide misbehaving with memory allocations, feel free to reopen or comment; or just open a new issue.

**Closed by TWiStErRob** 2016-02-21 22:47 UTC
Labels: question
