### ISSUE TITLE
Remove cached image or re-cache the image

### ISSUE THREAD

**Issue by niteshkhatri** [bumptech/glide#657] opened 2015-09-28 18:41 UTC
Hi. First of all thanks for such a great library.

I am having a little issue. I have a screen with user's profile image. User can also change his profile picture. The profile picture is saved in the sdcard with name "abc.png". When the user changes his profile picture, the newly selected image will replace the old image in sdcard.

Now if I show the profile picture using Glide, it takes the image from cache and shows old picture. How can I remove the old cached image? How to re-cache the image?

How to implement this?

**Comment by TWiStErRob** [comment] 2015-09-28 18:47
I think this is a duplicate of #624, the take away from that is [the wiki link](https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation#custom-cache-invalidation) and the use of `.signature()` API.

**Comment by niteshkhatri** [comment] 2015-09-28 19:30
@TWiStErRob Using .signature() will change the image. However, the old image will still there be in the memory (ram/disk). How to remove that old image completely?

**Comment by TWiStErRob** [comment] 2015-09-28 21:59
Yeah, I know, it's unfortunately currently not possible to figure out which file is that, but you can [lower the cache size](https://github.com/bumptech/glide/wiki/Configuration#size) so the LRU will take care of it faster. The default is 200MB IIRC.

**Comment by sjudd** [comment] 2015-09-30 16:01
Let us know if we can help with anything else.

**Closed by sjudd** 2015-09-30 16:01 UTC
Labels: question
