### ISSUE TITLE
Pictures from https url do NOT load

### ISSUE THREAD

**Issue by jahirfiquitiva** [bumptech/glide#3101] opened 2018-05-21 02:11 UTC
**Glide Version**: 4.7.1

**Integration libraries**: okhttp3

**Device/Android Version**: Genymotion Emulator 7.1.1

**Issue details / Repro steps / Use case background**: 

I am trying to load an image from an `https` url but nothing loads nor listener is fired or anything.

I have tried with Picasso, and it loads the picture properly, but I'd like to use Glide 😕 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
val imageView:ImageView? = findViewById(R.id.comic_image)
Picasso.get().load("https://imgs.xkcd.com/comics/mc_hammer_age.png").into(imageView) // Works!
GlideApp.with(this).load("https://imgs.xkcd.com/comics/mc_hammer_age.png").into(imageView) // Doesn't work D:
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageView
        android:id="@+id/comic_image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerInside"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="?actionBarSize"
        android:minHeight="?actionBarSize">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?actionBarSize"
            android:minHeight="?actionBarSize"
            android:background="?colorPrimary"
            app:layout_scrollFlags="scroll|enterAlways" />

    </android.support.design.widget.AppBarLayout>

</android.support.design.widget.CoordinatorLayout>
```

**Stack trace / LogCat**: **nothing**

**Comment by sjudd** [comment] 2018-05-24 22:32
Start with http://bumptech.github.io/glide/doc/debugging.html. If you can attach a reproducible test case or a sample app that would help too.

**Comment by jahirfiquitiva** [comment] 2018-05-27 15:14
@sjudd I think the code I attached could be easily reproducible.

Anyways, here's the link to my project: https://github.com/jahirfiquitiva/xkcd
In `MainActivity.kt` is where I'm trying to load the picture.

I tried adding a listener to the load, and it sometimes worked and sometimes didn't. When it did, the `onResourceReady` method was called but the image wasn't added to the view.

Thank you.

**Comment by jahirfiquitiva** [comment] 2018-05-29 20:48
@sjudd  Yes, it's weird the image does not appear. The image does have a reasonable size because it is loaded fine with Picasso

**Comment by jahirfiquitiva** [comment] 2018-06-02 22:46
@sjudd Any news/help regarding this? 🙏

**Comment by jahirfiquitiva** [comment] 2018-06-09 23:52
@sjudd @TWiStErRob 
I would appreciate some help about this. Thanks in advance 🙌🏼

**Comment by TWiStErRob** [comment] 2018-06-10 12:14
I checked out your repo and ran it, even with default state (Picasso only loading ) it didn't show anything, enabled logging as well and there's 0 output. Debugged a bit and the problem is that the `ZoomableImageView` doesn't lay out correctly. If you open the preview it shows as a 0x0 view even though it's `match_parent` on both sides. Changing to `ImageView` made Picasso work. Removing Picasso and using your Glide code also worked with `ImageView`.

Both libs read the size of the view that you load `into` if they don't lay out with a size the load will never actually start because the libs don't know how big an image you want (you can't fit into nothing, right?). You can force the size with `override()` (Glide) or `resize()` (Picasso) overloads. Note: for Glide there's a special constant called `Target.SIZE_ORIGINAL`, but be careful with memory consumption.

**Comment by TWiStErRob** [comment] 2018-06-10 18:01
Going to close this as we know the root cause (being something with custom view / layout), feel free to keep commenting if you discover some new info.

**Closed by TWiStErRob** 2018-06-10 18:01 UTC
Labels: question, view size

**Comment by jahirfiquitiva** [comment] 2018-06-10 20:39
Ok. Thanks for the help nonetheless @TWiStErRob 😄
