### ISSUE TITLE
Gif memory usage

### ISSUE THREAD

**Issue by thest1** [bumptech/glide#690] opened 2015-10-17 13:27 UTC
I have an Activity and I want to display gif in it. I do it using glide 3.6.1. Works just great. 

I can see glide uses a reasonable amount of memory to display gif. Mostly it's GifDecoder.rawData. That's OK, I realize we need it.

But when I close the Activity I wan't all this stuff to be garbage collected. Looks like it doesn't happen. rawData still consumes a lot of memory. Do I do something wrong? Or I should do something to free internal resources when I close the Activity and don't want GifDecoder to retain in memory?

I use Memory Monitor in Android Studio. I can see that allocated memory is never released. Gif can be a few megabytes size. Allocating them forever can cause pretty bad OutOfMemory issues.

I use Samsung Galaxy S3 Android 4.3 but I'm pretty sure it works the same for any other device.

**Comment by TWiStErRob** [comment] 2015-10-17 14:29
You can force Glide to clear the target via:
```java
Glide.clear(imageView);
```
but that should happen automatically where Fragments are available. What did you pass to `Glide.with` when loading the GIF into the ImageView? Feel free to share your full Glide load line.

**Comment by thest1** [comment] 2015-10-17 15:52
I pass Activity to Glide.with(), no fragments involved.

    Glide.with(this)
    .load(file_path)
    .diskCacheStrategy(DiskCacheStrategy.NONE)
    .skipMemoryCache(true)
    .into(imageView);

I tried Glide.clear(imageView) on Activity close, no effect. Still rawData remains allocated. 

I thought you're aware about the problem. If you're not I need to ensure I don't miss anything, could just be my fault.

Looks like some GifResourceDecoder.DECODER_POOL references GifDecoder. That's why GifDecoder is retained forever and huge rawData inside it. 

Can't see GifResourceDecoder.DECODER_POOL in the latest sources, probably the issue is already fixed? I build against 3.6.1.

**Comment by TWiStErRob** [comment] 2015-10-17 17:07
> I pass Activity to Glide.with(), no fragments involved.

I wanted to know this because it means that Glide can add its own viewless `[Support]RequestManagerFragment` to the activity which in turn means that the imageView should be cleared upon destroy.

Sadly I'm not familiar with the 4.0 codebase yet, it's possible that the pool was just moved to another class or renamed. Did you customize 3.6.1 or it's just a jar or compile dependency? Also can you please fill out the [issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues) so it's possible to reproduce it with better precision. Feel free to edit your original comment with details.

**Comment by TWiStErRob** [comment] 2015-10-17 17:15
Actually, by a quick glance at [`GifDecoder`](https://github.com/bumptech/glide/blob/e85cf305eb8e030cbfc3a7c73f438085ee0fb025/third_party/gif_decoder/src/main/java/com/bumptech/glide/gifdecoder/GifDecoder.java#L348) it simply doesn't clear `rawData`, it will wait for that buffer to be GC'd only when the decoder is next used. If you check master `GifDecoder` changed a lot and that one nulls `rawData` in `clear()`.

**Comment by thest1** [comment] 2015-10-18 03:09
> Glide can add its own viewless [Support]RequestManagerFragment to the activity which in turn means that the imageView should be cleared upon destroy.

I see. Probably GifDecoder is not cleared even when ImageView is cleared.

I don't customize anything, I just add "compile 'com.github.bumptech.glide:glide:3.6.1'"

I'll provide issue template, just give me some time.

>  it will wait for that buffer to be GC'd only when the decoder is next used

Can confirm that. I can see that Gif1 memory is released only when I display another Gif2. If I never display another gif then memory seems to be never released.

**Comment by TWiStErRob** [comment] 2015-12-03 21:52
I found a **really hacky** way that may allow for further confirmation and maybe as a temporary workaround. It is untested and may interfere with Glide internals (e.g. when using a normal `Glide.with.load.into` without any `as*()` calls).

```java
.asGif()
.decoder(new FixedGifResourceDecoder(context))
```

```java
package com.bumptech.glide.load.resource.gif; // need to be in same package to access package private stuff

import android.content.Context;

import com.bumptech.glide.Glide;
import com.bumptech.glide.gifdecoder.*;

public class FixedGifResourceDecoder extends GifResourceDecoder {
	private static final GifHeaderParserPool PARSER_POOL = new GifHeaderParserPool(); // package private class
	private static final GifDecoderPool DECODER_POOL = new FixedGifDecoderPool();
	public FixedGifResourceDecoder(Context context) {
		super(context, Glide.get(context).getBitmapPool(), PARSER_POOL, DECODER_POOL); // package private ctor
	}

	static class FixedGifDecoderPool extends GifDecoderPool { // package private class
		private static final byte[] NO_DATA = new byte[0];
		private static final GifHeader EMPTY_HEADER = new GifHeader();
		@Override public synchronized void release(GifDecoder decoder) {
			decoder.clear(); // clear
			decoder.setData(EMPTY_HEADER, NO_DATA); // set dummy data
			super.release(decoder); // clear again so only dummy data is leaked
		}
	}
}
```

**Comment by TWiStErRob** [comment] 2016-01-14 15:00
@thest1 it could be fixed in [3.7.0-SNAPSHOT from build 5](https://github.com/bumptech/glide/wiki/Snapshots) via #892, you can give it a try.

**Comment by sjudd** [comment] 2016-01-14 15:05
A similar fix to the one in that PR made it into master at some point as well: https://github.com/bumptech/glide/blob/master/third_party/gif_decoder/src/main/java/com/bumptech/glide/gifdecoder/GifDecoder.java#L417

**Comment by TWiStErRob** [comment] 2016-01-14 15:08
Oh, true that, I said the same above: "If you check 4.0 GifDecoder changed a lot and that one nulls rawData in clear().". I must've confused this issue with something else.

**Closed** 2016-01-21 23:51 UTC
Labels: bug
