### ISSUE TITLE
Glide v4.15.1  java.lang.IllegalStateException: Cannot recycle a resource while it is still acquired

### ISSUE THREAD

**Issue by hpdx** [bumptech/glide#5211] opened 2023-07-13 02:13 UTC
com.bumptech.glide.load.engine.EngineResource.recycle

Fatal Exception: java.lang.IllegalStateException: Cannot recycle a resource while it is still acquired
       at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:68)
       at com.bumptech.glide.load.engine.ResourceRecycler$ResourceRecyclerCallback.handleMessage(ResourceRecycler.java:37)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loopOnce(Looper.java:223)
       at android.os.Looper.loop(Looper.java:324)
       at android.app.ActivityThread.main(ActivityThread.java:8464)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)

**Comment by lyjSmile** [comment] 2023-07-24 06:18
I hava same probleam, did you solve it?

java.lang.IllegalStateException: Cannot recycle a resource while it is still acquired
       at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:68)
       at com.bumptech.glide.load.engine.ResourceRecycler$ResourceRecyclerCallback.handleMessage(ResourceRecycler.java:37)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7851)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by TWiStErRob** [comment] 2023-10-12 15:37
Duplicate of https://github.com/bumptech/glide/issues/4507, please "Subscribe" to that issue.

**Closed by TWiStErRob** 2023-10-12 15:37 UTC
