### ISSUE TITLE
cache is not uesd when load from byte[]

### ISSUE THREAD

**Issue by adsl99801** [bumptech/glide#2395] opened 2017-09-14 16:43 UTC
Version  
  compile 'com.github.bumptech.glide:glide:4.1.1' 
  compile  'io.reactivex:rxjava:1.1.0'
Device asus zenpone2

code1.  load local file 
```
 Glide.with(context).asBitmap().load(file).into(new SimpleTarget<Bitmap>() {
                @Override
                public void onResourceReady(Bitmap resource, Transition<? super Bitmap> transition) {
                    sub.onNext(resource);
                }
            });
```
cache **file is ok. But  if I  load from byte aray cache is not uesd. It happend in  >v4 ,v3.7.0 is work fine.**
code2:  from byte[]
```
   Glide.with(context).asBitmap().load(igBytes).into(new SimpleTarget<Bitmap>() {
                @Override
                public void onResourceReady(Bitmap resource, Transition<? super Bitmap> transition) {
                    sub.onNext(resource);
                }
            });

```

**Comment by sjudd** [comment] 2017-09-14 17:38
Duplicate of #2290

**Closed by sjudd** 2017-09-14 17:38 UTC
