### ISSUE TITLE
Load images with okhttp very slow if the exifRotation = 90!

### ISSUE THREAD

**Issue by start141** [bumptech/glide#604] opened 2015-08-31 09:01 UTC
Hi!
I test some `big` images which `exifRotation` is 90.
When using okhttp, it showed very very slow, about `5 - 10` seconds.
But, showed fast if not using okhttp!

When using okhttp:
If set `diskCacheStrategy(DiskCacheStrategy.SOURCE)`, it will show faster!
If set `override()` with a smaller size, it is also showed faster!
If `exifRotation` is 0, it is also showed faster!

My test images is: (put into sdcard, load from sdcard)
https://cloud.githubusercontent.com/assets/6055764/3547973/bc1e4710-08a3-11e4-99e9-4d26f2f1f67e.jpg
https://cloud.githubusercontent.com/assets/6055764/3547974/be3b85b2-08a3-11e4-8e0b-eb4a484c8654.jpg
https://cloud.githubusercontent.com/assets/6055764/3547975/c0b52726-08a3-11e4-9437-bdb5c777d0b5.jpg

Is it the same problem? #150

**Comment by TWiStErRob** [comment] 2015-08-31 09:23
Possibly the same, can you please fill out the [issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues)?

If it's on the sd card you can use NONE to prevent duplicating the image and it will be even faster. However this doesn't change the fact that RESULT cache is extremely slow for you.
My best guess would be that because of the rotation the full image must be loaded before being able to downsample and rotate it, but then it's hard to explain why override makes it faster. @sjudd could possibly answer this one better.

**Comment by start141** [comment] 2015-08-31 11:17
I sure if use centerCrop()(or maybe override()) into a small ImageView, it will loaded faster a lot!

**Comment by TWiStErRob** [comment] 2015-08-31 11:26
I'm asking for the issue template because it may be a device specific issue, or your layout forces Glide to load a too big image, that is, bigger than necessary for the ImageView target.


... wait, you said using OkHttp, but then you said it's on the sd card, so which one? Because downloading each of those images takes quite a few seconds, even with fast connection. Also did you clear the cache between these tests?

**Comment by start141** [comment] 2015-08-31 12:32
Yes, I clear the cache between tests.

I am using okhttp and load image from sdcard, not from network. I have test some devices(include nexus 5), all have the same problem. it is not a device specific issue.

**Comment by start141** [comment] 2015-08-31 12:32
Thanks for your reply!

**Comment by start141** [comment] 2015-08-31 12:36
If test with the imags above which I give, it's easy to show this issue. Thanks!

**Comment by TWiStErRob** [comment] 2016-03-26 19:11
I checked this finally, but there's bug here.

 * The original image is 3264x2448 (rotated 90)
 * my test view is 1080x1677
 * Glide loads a downsampled version which is the full image (3264x2448) because 1632 < 1677. If the relation was reversed that would allow sample size of two.
 * This downsampled Bitmap is rotated by drawing it onto another Bitmap through Canvas and Matrix: 2448x3264
 * This rotated Bitmap is then sent through FitCenter which downscales it to 1080x1677

So to read these images you need: 2 huge and 1 large Bitmap in memory. I was expecting slow load times, but **the image was loaded in less 2 seconds for me** (even with debugger attached).

*OkHttp is not involved with local sdcard loads.*

 If you create a sample app that reproduces the issue (5-10 seconds loading time) we can investigate more, until then I'll close this.

**Closed by TWiStErRob** 2016-03-26 19:11 UTC
Labels: question, repro-needed
