### ISSUE TITLE
Attempting to merge String loader with Custom data loader

### ISSUE THREAD

**Issue by donpwilson** [bumptech/glide#1504] opened 2016-10-07 17:34 UTC
I'm trying to merge two loaders to avoid proliferation of code in my app. Currently, wherever I load an image I have implemented two builders and switch between them as required. I'd very much like to use just one builder by extending the one I use to load images from various cloud storage providers to include the ability to load images on the device. I've explored Glide code and questions on StackOverflow but cannot find a solution. I have the feeling that it must be very simple. Can you help?

First builder - which I'd like to remove:

```java
DrawableRequestBuilder<String> builder = Glide.with(this)
                            .fromString()
                            .load(My_Constants.FILE_PREFIX + photo)
```

Second builder:

```java
Drive_Loader loader = new Drive_Loader();
loader.setLoadInfo(photo_record.getDrive(), photo_record.getId(), false,false);
DrawableRequestBuilder builder1 = Glide.with(this)
        .from(Drive_Loader.class)
        .load(loader)
```

Attempt to extend my custom dataLoader and dataFetcher with TODOs where I cannot work out what to include:

```java
public class DriveModelLoader implements StreamModelLoader<Drive_Loader> {
    private final DataFetcher<InputStream> defaultFetcher;
    private final com.google.api.services.drive.Drive pGoogleDrive;
    private final com.google.api.services.drive.Drive pGooglePhotos;
    private final CloudStorage pOneDrive;
    private final CloudStorage pDropbox;
    private final CloudStorage pBox;`

    public DriveModelLoader(DataFetcher<InputStream> defaultFetcher, com.google.api.services.drive.Drive google_drive,
                            com.google.api.services.drive.Drive google_photos, CloudStorage one_drive, CloudStorage dropbox,
                            CloudStorage box) {
        this.defaultFetcher=defaultFetcher;
        pGoogleDrive = google_drive;
        pGooglePhotos = google_photos;
        pOneDrive = one_drive;
        pDropbox = dropbox;
        pBox = box;
    }

    @Override
    public DataFetcher<InputStream> getResourceFetcher(Drive_Loader loader, int width, int height) {
        return new DriveDataFetcher(defaultFetcher,pGoogleDrive, pGooglePhotos, pOneDrive, pDropbox, pBox,
                loader);
    }

    public static class Factory implements ModelLoaderFactory<Drive_Loader, InputStream> {
        private final DataFetcher<InputStream> defaultFetcher;
        private final com.google.api.services.drive.Drive google_drive;
        private final com.google.api.services.drive.Drive google_photos;
        private final CloudStorage one_drive;
        private final CloudStorage dropbox;
        private final CloudStorage box;

        public Factory(com.google.api.services.drive.Drive google_drive,
                       com.google.api.services.drive.Drive google_photos, CloudStorage one_drive, CloudStorage dropbox,
                       CloudStorage box) {
            //TODO what goes here?
            this.defaultFetcher = null;
            this.google_drive = google_drive;
            this.google_photos = google_photos;
            this.one_drive = one_drive;
            this.dropbox = dropbox;
            this.box = box;
        }

        public ModelLoader<Drive_Loader, InputStream> build(Context context, GenericLoaderFactory
                factories) {
            return new DriveModelLoader(defaultFetcher,google_drive, google_photos, one_drive, dropbox, box);
        }

        public void teardown() {
        }
    }
}
```

```java
public class DriveDataFetcher implements DataFetcher<InputStream> {

    private final Drive_Loader pLoader;
    private final DataFetcher<InputStream> defaultFetcher;
    private boolean pCancelled = false;
    private com.google.api.services.drive.Drive pGoogleDrive = null;
    private com.google.api.services.drive.Drive pGooglePhotos = null;
    private CloudStorage pOneDrive = null;
    private CloudStorage pDropbox = null;
    private CloudStorage pBox = null;
    private boolean pLoadOnlyFromCache = false;
    private boolean pGetThumbnail = false;

    public DriveDataFetcher(DataFetcher<InputStream> defaultFetcher, com.google.api.services.drive.Drive google_drive,
                            com.google.api.services.drive.Drive google_photos, CloudStorage one_drive, CloudStorage dropbox,
                            CloudStorage box, Drive_Loader loader) {
        this.defaultFetcher=defaultFetcher;
        pGoogleDrive = google_drive;
        pGooglePhotos = google_photos;
        pOneDrive = one_drive;
        pDropbox = dropbox;
        pBox = box;
        pLoader = loader;
        pLoadOnlyFromCache = loader.getLoadOnlyFromCache();
        pGetThumbnail = loader.getLoadThumbnail();
    }

    public String getId() {
        return pLoader.getFileId();
    }

    public InputStream loadData(Priority priority) {
        if (pCancelled || pLoadOnlyFromCache) return null;
        InputStream content = null;
        try {
            switch (pLoader.getDrive()) {
                case My_Constants.DRIVE_FILE_INTERNAL:
                case My_Constants.DRIVE_FILE_MEMORY_CARD:
                case My_Constants.DRIVE_USB_DRIVE:
                    //TODO what goes here?
                    content = defaultFetcher.loadData(priority);
                break;
                case My_Constants.DRIVE_GOOGLE_DRIVE:
                    content = pGoogleDrive.files().get(getId()).executeMedia().getContent();
                    break;
                case My_Constants.DRIVE_GOOGLE_PHOTOS:
                    content = pGooglePhotos.files().get(getId()).executeMedia().getContent();
                    break;
                case My_Constants.DRIVE_ONE_DRIVE:
                    if (pGetThumbnail) {
                        content = pOneDrive.getThumbnail(pLoader.getFileId());
                    } else {
                        content = pOneDrive.download(pLoader.getFileId());
                    }
                    break;
                case My_Constants.DRIVE_DROPBOX:
                    if (pGetThumbnail) {
                        content = pDropbox.getThumbnail(pLoader.getFileId());
                    } else {
                        content = pDropbox.download(pLoader.getFileId());
                    }
                    break;
                case My_Constants.DRIVE_BOX:
                    if (pGetThumbnail) {
                        content = pBox.getThumbnail(pLoader.getFileId());
                    } else {
                        content = pBox.download(pLoader.getFileId());
                    }
                    break;
            }
            if (pCancelled) {
                content = null;
            }
        } catch (Exception e) {
            //   My_Utils.log(this.getClass(), e.fillInStackTrace() ,"loadData() exception");
            content = null;
        }
        return content;
    }

    @Override
    public void cleanup() {
    }

    public void cancel() {
        pCancelled = true;
    }
}
```

**Comment by TWiStErRob** [comment] 2016-10-07 21:18
> //TODO what goes here? `this.defaultFetcher = null;`

That's a little early to be talking fetchers. First you need to create a model loader and that will create a fetcher. If you want to fall back you need to query Glide in the factory method (`build`):
```java
ModelLoader<String, InputStream> delegate = factories.buildModelLoader(String.class, InputStream.class);
```

> `switch` in `DriveDataFetcher`

It looks a little to do that switch. The way Glide was designed is that the model loader decides how to load the model and it is actually a factory for a fetcher. There could be a fetcher for each type, e.g. a constructor like: `OneDriveFetcher(pOneDrive, loader)` for each of the different cloud providers.

> `if (pCancelled) { content = null; }`

You're leaking here, who calls `.close()` on the stream? I also suggest you store the stream as a field in fetcher and close it in `cancel()` and `cleanup()`. In cancel if you close the stream the decoding process should stop immediately, not wasting time to read to the end.

> //TODO what goes here? `content = defaultFetcher.loadData(priority);`

That looks correct, however I'm not sure why you want to do the dispatch yourself, Glide already handles String/Uri/File/Integer models. I think your confusion comes from the `switch`. The fetcher already knows what model to load and how to load it, so you can simply call `loadData` on it. The tricky part here is that you're actually wrapping it and therefore you would need to delegate all lifecycle events (`cancel`, `cleanup`) to it as well to prevent leaks. It's much easier if you move the switch (at least part of it) to the loader and return the fetcher created by the `delegate`, so Glide can manipulate it correctly. Check out #606 and the related code in [glide-support](https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/github/_606_fallback_in_fetcher) (this repo contains a lot of examples I wrote in a runnable form)

> `DriveModelLoader`, `DriveDataFetcher`, `Drive_Loader`

I suggest you rename your classes to represent what they really mean: use `Cloud` instead of `Drive`, don't let "historical reasons" creep in.

> `Drive_Loader` class

I think what might makes things hard is this class. Not sure how you create them, but I would imagine that the logic in `download` method is actually what should be in each corresponding fetcher class. You're collapsing all the different types maybe too early.

> builder - which I'd like to remove

```java
Glide.with(context).load(anything)...
```
you don't actually need to use that part of the generics, just use the `.load(T extends Object)` overload and you'll get a `DrawableRequestBuilder<Object>`. You don't need to use the `.from*` methods if you don't know what you're going to load: in the end the loaderfactory discovery is done via `model.getClass()` (if no `from*` was called prior), so you can allow for loss of type information at that point.

-----

Hopefully I've addressed everything. If you need more info, feel free to ask; or if prose is too confusing I could try to change your implementation and post it here.

**Closed by TWiStErRob** 2016-10-07 21:18 UTC
Labels: question

**Comment by donpwilson** [comment] 2016-10-11 13:26
Thank you for your prompt and comprehensive response. It gave me plenty to think about and shocked me at how many issues and weaknesses there were in my code. I show below my revised code to provide a record of what is hopefully a better way to proceed. I would be grateful if you could give this a look over. I am left with one small issue that I cannot resolve. This is that the line:

`builder.thumbnail(thumbnail_builder)`

gives a lint warning message in Android Studio 2.2:

`Unchecked call to .thumbnail(DrawableRequestBuilder<?>)' as a member of com.bumptech.glide.DrawableRequestBuilder'`

Also, one question: This code is in a RecyclerView and I pass pRequestManager in through the constructor from the calling Fragment where it is defined as Glide.with(this). Is this the best way of calling Glide within an adapter?

Apologies that some of the code cut and paste hasn't quite formatted as it should!

Call in onBindViewHolder(), with some irrelevant code removed:

`DrawableRequestBuilder builder = pRequestManager
                    .load(new Photo_Loader_Model(photo_record, false))
                    .signature(new MediaStoreSignature("", photo_record.getLastModifiedTime(), 0))
                    .priority(Priority.NORMAL)
                    .centerCrop()
                    .crossFade()
                    .placeholder(R.drawable.transparent_1)
                    .listener(new RequestListener<Photo_Loader_Model, GlideDrawable>() {
                        @Override
                        public boolean onException(Exception e, Photo_Loader_Model model, Target<GlideDrawable> target, boolean isFirstResource) {
                            My_Utils.log(this.getClass().getEnclosingClass(), "onException() photo %s exception %s",
                                    photo, (e != null) ? e.fillInStackTrace() : null);
                            viewHolder.getProgressCloudView().setVisibility(View.GONE);
                            viewHolder.getProgressBarView().setVisibility(View.GONE);
                            }
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(GlideDrawable resource, Photo_Loader_Model model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                            viewHolder.getProgressCloudView().setVisibility(View.GONE);
                            viewHolder.getProgressBarView().setVisibility(View.GONE);
                            return false;
                        }
                    });
            switch (photo_record.getSourceType()) {
                case Photo_Record.SOURCE_TYPE_FILE:
                    viewHolder.getProgressBarView().setVisibility(View.VISIBLE);
                    viewHolder.getProgressCloudView().setVisibility(View.GONE);
                    builder.error(R.drawable.no_photo)
                            .diskCacheStrategy(DiskCacheStrategy.RESULT)
                            .into(viewHolder.getImageView());
                    break;
                case Photo_Record.SOURCE_TYPE_CLOUD_STORAGE:
                    viewHolder.getProgressBarView().setVisibility(View.GONE);
                    viewHolder.getProgressCloudView().setVisibility(View.VISIBLE);
                    final DrawableRequestBuilder<Photo_Loader_Model> thumbnail_builder = pRequestManager
                            .load(new Photo_Loader_Model(photo_record, true))
                            .centerCrop()
                            .priority(Priority.HIGH)
                            .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                            .signature(new MediaStoreSignature("", photo_record.getLastModifiedTime(), 0));
                    builder.thumbnail(thumbnail_builder)
                            .error(R.drawable.padded_cloud)
                            .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                            .into(viewHolder.getImageView());
                    break;
            }    `

Photo_Loader_Model:

`public class Photo_Loader_Model {

    private Photo_Record record;
    private boolean thumbnail;

    public Photo_Loader_Model(Photo_Record record, boolean thumbnail) {
        this.record = record;
        this.thumbnail = thumbnail;
    }

    public Photo_Record getPhotoRecord(){
        return record;
    }

    public int getSource() {
        return record.getSource();
    }

    public String getPhoto() {
        return record.getPhoto();
    }

    public String getFileId() {
        return record.getId();
    }

    public boolean getLoadThumbnail() {
        return thumbnail;
    }
}`

My_Model_Loader:

`public class My_Model_Loader implements StreamModelLoader<Photo_Loader_Model> {
    private final ModelLoader<String, InputStream> string_loader;
    private final com.google.api.services.drive.Drive google_drive;
    private final com.google.api.services.drive.Drive google_photos;
    private final CloudStorage one_drive;
    private final CloudStorage dropbox;
    private final CloudStorage box;

    private My_Model_Loader(ModelLoader<String, InputStream> string_loader, com.google.api.services.drive.Drive google_drive,
                            com.google.api.services.drive.Drive google_photos, CloudStorage one_drive, CloudStorage dropbox,
                            CloudStorage box) {
        this.string_loader = string_loader;
        this.google_drive = google_drive;
        this.google_photos = google_photos;
        this.one_drive = one_drive;
        this.dropbox = dropbox;
        this.box = box;
    }

    @Override
    public DataFetcher<InputStream> getResourceFetcher(Photo_Loader_Model model, int width, int height) {
        switch (model.getSource()) {
            case My_Constants.SOURCE_FILE_INTERNAL:
            case My_Constants.SOURCE_FILE_MEMORY_CARD:
            case My_Constants.SOURCE_USB_DRIVE:
                return string_loader.getResourceFetcher(model.getPhoto(), width, height);
            case My_Constants.SOURCE_GOOGLE_DRIVE:
                return new GoogleDriveFetcher(google_drive, model,loadOnlyFromCache(model.getSource()));
            case My_Constants.SOURCE_GOOGLE_PHOTOS:
                return new GoogleDriveFetcher(google_photos, model,loadOnlyFromCache(model.getSource()));
            case My_Constants.SOURCE_ONE_DRIVE:
                return new CloudRailFetcher(one_drive, model,loadOnlyFromCache(model.getSource()));
            case My_Constants.SOURCE_DROPBOX:
                return new CloudRailFetcher(dropbox, model,loadOnlyFromCache(model.getSource()));
            case My_Constants.SOURCE_BOX:
                return new CloudRailFetcher(box, model,loadOnlyFromCache(model.getSource()));
        }
        return null;
    }

    private boolean loadOnlyFromCache(int source) {
        return (!My_CloudCredentials.getInstance().getIsLoggedIn(source)) || (!My_Utils.isDeviceOnline());
    }

    public static class Factory implements ModelLoaderFactory<Photo_Loader_Model, InputStream> {
        private final com.google.api.services.drive.Drive google_drive;
        private final com.google.api.services.drive.Drive google_photos;
        private final CloudStorage one_drive;
        private final CloudStorage dropbox;
        private final CloudStorage box;

        public Factory(com.google.api.services.drive.Drive google_drive,
                       com.google.api.services.drive.Drive google_photos, CloudStorage one_drive, CloudStorage dropbox,
                       CloudStorage box) {
            this.google_drive = google_drive;
            this.google_photos = google_photos;
            this.one_drive = one_drive;
            this.dropbox = dropbox;
            this.box = box;
        }

        public ModelLoader<Photo_Loader_Model, InputStream> build(Context context, GenericLoaderFactory
                factories) {
            return new My_Model_Loader(factories.buildModelLoader(String.class, InputStream.class),
                    google_drive, google_photos, one_drive, dropbox, box);
        }

        public void teardown() {
        }
    }
}`

CloudRailFetcher:

`class CloudRailFetcher implements DataFetcher<InputStream> {

    private InputStream input_stream;
    private Photo_Loader_Model model;
    private CloudStorage service;
    private boolean load_only_from_cache;

    CloudRailFetcher(CloudStorage service, Photo_Loader_Model model, boolean load_only_from_cache) {
        this.service = service;
        this.model = model;
        this.load_only_from_cache = load_only_from_cache;
    }

    @Override
    public String getId() {
        return model.getFileId() + String.valueOf(model.getLoadThumbnail());
    }

    @Override
    public InputStream loadData(Priority priority) throws Exception {
        if ((service == null) || load_only_from_cache) {
            return null;
        }
        try {
            if (model.getLoadThumbnail()) {
                input_stream = service.getThumbnail(model.getFileId());
            } else {
                input_stream = service.download(model.getFileId());
            }
        } catch (Exception ex) {
            My_Utils.log(this.getClass(), "loadData() exception %s", ex.toString());
            cleanup();
        }
        return input_stream;
    }

    @Override
    public void cleanup() {
        if (input_stream != null) {
            try {
                input_stream.close();
            } catch (java.io.IOException e) {
                My_Utils.log(this.getClass(), "cleanup() exception %s", e.toString());
            }
        }
    }

    @Override
    public void cancel() {
        if (input_stream != null) {
            try {
                input_stream.close();
            } catch (java.io.IOException e) {
                My_Utils.log(this.getClass(), "cancel() exception %s", e.toString());
            }
        }
    }
}`

**Comment by TWiStErRob** [comment] 2016-10-11 14:36
Fixed your formatting. Edit the comment (pencil in upper right) to see what changed. I'll read it later.

**Comment by TWiStErRob** [comment] 2016-10-11 16:36
> Unchecked call

That's not a lint, that's a Java compiler warning. It's very likely because you're using a raw type. Genericize builder with `<Photo_Loader_Model>` or `<?>`. (If you're calling a method on a raw type, all generics are erased, so javac can't prove that your call is valid, which it is.)

> `pRequestManager = Glide.with(this)`

Yes, http://stackoverflow.com/a/32887693/253468

> `MediaStoreSignature`

You could write your own `TimeSignature`, see `StringSignature` for a simple example.

> `builder....`

You should use `builder.clone()....` because otherwise there may be a conflict if the binds are called in a certain order. For example the thumbnail designed for another cloud storage entry may show up for a local file. Oh, just noticed, the above is only valid if you cache the builder in a field. You can do that by replacing `load()` with a `from(Class)` call and move that long init to the constructor.

> `e.fillInStackTrace()`

I think you're losing information here. The exception was thrown on another thread in another context, yet you're re-filling the stack trace. You'll only see an irrelevant trace if that log is triggered, either use just `e` itself or `new RuntimeException("in onException", e)` if you want to include both stacks.

> `catch() { cleanup(); }`

You shouldn't do that, there's a reason why that method allows you to throw anything. The error handling is done for you. If you want to log, catch it, log and then `throw e`. Currently you're returning a closed stream which will choke Glide anyway, but potentially without having root cause in the exception. Anything you throw from `loadData` will be delivered to `onException` in the listener.

> `String.valueOf(model.getLoadThumbnail());`

For future ease of debugging I suggest to replace this with `model.getLoadThumbnail() ? "@thumb" : "@image"`
