### ISSUE TITLE
Support Incremental Annotation Processing in Gradle 4.7+

### ISSUE THREAD

**Issue by technoir3** [bumptech/glide#3072] opened 2018-05-07 07:29 UTC
Docs: https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing
Gradle feature discussion: https://github.com/gradle/gradle/issues/1320

**Comment by sjudd** [comment] 2018-05-07 17:19
Duplicate of #2983.

Pull requests are always welcome!

**Closed by sjudd** 2018-05-07 17:19 UTC
