### ISSUE TITLE
"Glide" How does the network image loading library work with GifDrawable?

### ISSUE THREAD

**Issue by TheMelody** [bumptech/glide#2468] opened 2017-10-11 13:33 UTC
"Glide" network load library how to configure the combination of "android-gif-drawable" library.
"android-gif-drawable":https://github.com/koral--/android-gif-drawable.

Now I use the "Glide" network to load the library, and then pass Gifdrawable the gifImageView, but the two fragment switch, at the same time, each fragment which has a list of loading gif picture, switch, the list of gif graphics display animation card pause.

**Comment by sjudd** [comment] 2017-10-11 14:07
Sounds like a duplicate of #899

**Closed by sjudd** 2017-10-11 14:07 UTC

**Comment by TheMelody** [comment] 2017-10-12 01:33
Glide Version 4.2.0;   two fragment switch, at the same time, each fragment which has a list of loading gif picture, switch, the list of gif graphics display animation card pause.

**Comment by TheMelody** [comment] 2017-10-14 09:10
# **小伙伴们技术交流请加群: 490113234**
>**## I have solved my problem！！！！**
I found a solution:[https://futurestud.io/tutorials/glide-callbacks-simpletarget-and-viewtarget-for-custom-view-classes](url)

> **public void onBindViewHolder(BaseHolder holder, int position)**
_for example_:

 xxxIvCoverView.setImageDrawable(null);
 xxxIvCoverView.setTag(R.id.imageid,gifUrl);

**Set up ViewTarget.....**

>ViewTarget viewTarget=new ViewTarget<pl.droidsonroids.gif.GifImageView,com.bumptech.glide.load.resource.gif.GifDrawable>(xxxIvCoverView){
           @Override
            public void onResourceReady(GifDrawable resource, Transition<? super GifDrawable> 
                transition) {
           if(xxxIvCoverView.getTag(R.id.imageid)!=null&&gifUrl==xxxIvCoverView.getTag(R.id.imageid)) {
                    pl.droidsonroids.gif.GifDrawable gifFromBytes=null;
                    try {
                        gifFromBytes = new pl.droidsonroids.gif.GifDrawable(resource.getBuffer());
                        this.view.setImageDrawable(gifFromBytes);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }finally {
                        if(null==gifFromBytes){
                            this.view.setImageDrawable(resource);
                        }
                    }
                }
    }
}
>**At last**
GlideApp.with(mBaseFragment).asGif()
                    .load(gifUrl)
                    .into(viewTarget);
