### ISSUE TITLE
Delays on last GIF frames are ignored

### ISSUE THREAD

**Issue by seanyriver** [bumptech/glide#1677] opened 2017-01-06 23:53 UTC
*Glide*: 3.7.0
*Integration libraries*: no
*Devices*: currently running on emulator only, hardware GPU rendering
*Issue*: animated GIFs generally work well, except that the final frame's delay is being ignored.  The product design involves having a long delay on the last frame so that the final rendering can be reviewed again.  Instead the last frame flashes quickly and then it returns to the beginning.
A secondary issue: not only should it be waiting to cycle back to the beginning for the amount stated in the duration, but the particular GIFs being tested are set to only 1 iteration (meaning in theory they should not ever recycle).
To reproduce, generate a GIF with a long delay on the last frame.  Then display the GIF.  It appears to flicker right back to the beginning.  Viewing the same GIF in a web browser or posting to e.g. FB messenger, the delay is properly observed.

*Layout Design*: FrameLayout with a single ImageView inside.  (added) These are inside a RecyclerView.  I am testing with ~ 20 items at one time.
*Code Design*: using a RecyclerViewAdapter; Glide code is in onBindViewHolder

*Error Messages*: I am getting the following, from reading up it doesn't sound like this is related but curious of others' opinions:
W/Bitmap: Called reconfigure on a bitmap that is in use! ...

**Comment by TWiStErRob** [comment] 2017-01-07 13:48
Check #743 re log, but I agree it's very likely unrelated.

First, please update to 3.8.0-SNAPSHOT. I made a lot of changes to GIFs, I think this may be a duplicate of #1060. If this doesn't work then please post an example GIF and reopen!

**Closed by TWiStErRob** 2017-01-07 13:48 UTC
Labels: bug, duplicate

**Comment by TWiStErRob** [comment] 2017-01-07 13:55
Regarding looping: `GifDrawable.onFrameReady` seems to handle it correctly, but `GlideDrawableImageViewTarget` defaults to repeat forever. To fix this you can force:
```java
Glide....into(new GlideDrawableImageViewTarget(holder.imageView, GlideDrawable.LOOP_INTRINSIC));
```
Don't forget that specifying a custom targets removes the automatic transformation detection (see `GenericRequestBuilder.into(ImageView)`) so you need to explicitly add `.fitCenter()` or `.centerCrop()` to preserve behavior.
