### ISSUE TITLE
Error:Failed to resolve: com.android.support:support-annotations:26.0.2

### ISSUE THREAD

**Issue by deejaygeekout** [bumptech/glide#2347] opened 2017-09-07 03:04 UTC
After adding the latest gradle 4.1.1:  

compile 'com.github.bumptech.glide:glide:4.1.1'
compile 'com.android.support:support-v4:25.3.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'

It says failed to resolve annotationProcessor. I need to revert to 4.0.0 release to make this work

**Comment by S-Co** [comment] 2017-09-07 03:28
@deejaygeekout me too.

**Comment by sjudd** [comment] 2017-09-07 04:54
If you change ``compile 'com.android.support:support-v4:25.3.1'`` to ``compile 'com.android.support:support-v4:26.0.2'`` does that work? Can you provide a full stack trace or error message? Are you building with gradle or Android Studio?

Do you have a sample app you could attach that reproduces this? I've tried this in a couple of sample apps where I just create a new one using the Android Studio template and add v4.1.1 as a dependency and it works for me.

I did also try adding ``compile 'com.android.support:support-v4:25.3.1'`` to one of the sample apps and I'm still able to build without an error.

**Comment by sjudd** [comment] 2017-09-07 04:58
One other thought, have you followed https://developer.android.com/topic/libraries/support-library/setup.html?

In particular you may need to add:

```
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}
```

**Comment by ytp135** [comment] 2017-09-07 06:03
Glide4.1.1 still not available ! But Glide4.0.0 is ok

**Comment by jishuo1213** [comment] 2017-09-07 06:48
@sjudd Add  maven {url "https://maven.google.com"},and changed the support library to 26.0.2 worked.But the support library-26.0.2 can not download through sdk manager.Add maven url and sync project,the library will auto download.

**Comment by sjudd** [comment] 2017-09-07 14:33
I think we've found a solution here and the documentation (README and docs page) are updated, closing this for now.

**Closed by sjudd** 2017-09-07 14:33 UTC
Labels: documentation

**Comment by lbx2015** [comment] 2017-10-25 10:12
I got and solved the issue : Failed to resolve: com.android.support:support-annotations:26.0.2
first step:adding google() below jcenter()
second step: change the compile and build sdk to lastest 26 and 26.0.2
third step: change to gradle-4.2.1-all.zip in the gradle_wrapper.properties file  
fourth step: adding   classpath 'com.android.tools.build:gradle:2.3.3'

call my phone if you got concern:18221650910
