### ISSUE TITLE
class com.bumptech.glide.load.engine.GlideException: Failed to load resource

### ISSUE THREAD

**Issue by Le0nHsu** [bumptech/glide#3097] opened 2018-05-18 02:59 UTC
There were 5 causes:
                                                             java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
                                                             java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
                                                             java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
                                                             java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
                                                             java.io.FileNotFoundException(No content provider: url)

but the url'pic can be load by my pc

**Comment by sjudd** [comment] 2018-05-18 18:16
Duplicate of #2894

**Closed by sjudd** 2018-05-18 18:16 UTC

**Comment by spuermax** [comment] 2019-03-05 02:39
Exception:  W/Glide: Load failed for -1 with size [300x300]
class com.bumptech.glide.load.engine.GlideException: Failed to load resource
Log:In RequestListener method onResourceReady "android.graphics.drawable.BitmapDrawable@e42a9b6"

The first time the page fails to load; the end page, the second time the page is loaded successfully.

**Comment by Thien658jjh** [comment] 2019-06-04 09:55
> Duplicate of #2894

It was not duplicate please. I have the same issues, and totally don't have any concerns about space or anything like that

**Comment by mochadwi** [comment] 2020-01-05 20:17
is this related to #4031 ?

**Comment by AtulSalgaonkar** [comment] 2021-06-15 15:25
got same issue in version: 4.10.0

java.io.IOException(Exception decoding bitmap, outWidth: 720, outHeight: 720, outMimeType: image/jpeg, inBitmap: [192x192] ARGB_8888 (147456))
    com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 40599 markLimit: 65536)
     call GlideException#logRootCauses(String) for more detail

**Comment by damian-cell** [comment] 2021-06-16 05:21
> There were 5 causes:
> java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
> java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
> java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
> java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
> java.io.FileNotFoundException(No content provider: url)
> 
> but the url'pic can be load by my pc
