### ISSUE TITLE
How can i listen to the progress of image's loading

### ISSUE THREAD

**Issue by jonyChina162** [bumptech/glide#685] opened 2015-10-14 08:20 UTC
I am now developing for a new app, and I need to update the progress bar manually when loading an image. However, glide's api  seems unfriendly when I try to get the current progress.
In UIL lib, I can easily set an ImageLoadingListener to do this . I try to do the same thing but not modify the glide core lib, but I found it's hard for me.
So in glide lib , how can i listen to the progress of image's loading.
If there's no good answer, i think i had to use rxjava or modify the glide core lib(it's terrible).
Thank goodness for reading my aweful English

**Comment by TWiStErRob** [comment] 2015-10-14 21:24
There isn't an easy way, see #232 (duplicate) for details.

https://github.com/bumptech/glide/issues/232#issuecomment-95649082 gave an idea how it may be possible, but the gist he provided seems to only work for one image only. You'll need [OkHttp](https://github.com/bumptech/glide/wiki/Integration-Libraries#okhttp) to try that out.

**Comment by sjudd** [comment] 2015-10-15 14:30
Closing as a duplicate of #232

**Closed by sjudd** 2015-10-15 14:30 UTC
Labels: question

**Comment by jonyChina162** [comment] 2015-10-18 05:48
@TWiStErRob  Thanks a lot! what I need is just to track the download progresses of one image, and I have implemented it, many thanks
