### ISSUE TITLE
CrossFade images from cache.

### ISSUE THREAD

**Issue by hunter-isaiah96** [bumptech/glide#241] opened 2014-11-08 14:22 UTC
I'm trying to CrossFade each image loaded,but once it has loaded the images once,it jumps straight to the image without crossfading.

I'm using this in a while(true) loop in a thread.

```java
Glide.with(this).load(images[i]).placeholder(imageView.getDrawable()).crossFade(1000).into(imageView);
```

I tried checking out the glidesong project,but can't figure out exactly what is different about the code there.

**Comment by kevinvanmierlo** [comment] 2015-06-09 09:08
I also would like to see this behavior. As for syntax I had an idea to do it like this: `.crossfade(boolean forceCacheAnimation)`.

**Comment by TWiStErRob** [comment] 2015-10-15 21:28
@hunter-isaiah96 assuming a duplicate of #132

feel free to reopen if you think otherwise and please answer:
> If not, can you clarify what is the effect you're trying to get?

@kevinvanmierlo you should subscribe to #132 too for further updates

**Closed by TWiStErRob** 2015-10-15 21:28 UTC
Labels: duplicate, enhancement
