### ISSUE TITLE
Images are misplaced when the gridview is scrolling

### ISSUE THREAD

**Issue by ruanml** [bumptech/glide#279] opened 2014-11-25 12:00 UTC
hello, everyone.
i have a problem that the images are misplaced when the gridview is scrolling fast.
i just use glide in getView() like this:
Glide.with().load().asBitmap().thumbnail().into();

**Comment by ruanml** [comment] 2015-01-09 07:36
Dear Sam:
Sorry, I did something else in last month. 

I tested the sample with different devices. 
I used 600 pics.
The result is as following:
Nexus 10(Android 5.0): Glide works fine
Nexus 4(Android 4.3): Glide works fine
SAMSUNG S4(Android 4.4.2): misplaced if scroll gridview fast
MOTO G(Android 4.4.4): misplaced if scroll gridview fase

I think that If scroll fast, when finish loading picture, the image view which the picture should be loaded into is disappeared, so the picture is loaded into a wrong place.
It's just my guess.

I tried to do something specific to reproduce it , but failed. 
I recorded the screen to display misplaced and upload to youtube.
http://youtu.be/ttf0VSey0zU

Thanks.

**Comment by sjudd** [comment] 2015-01-09 15:01
Thanks for the follow up, I'll try with one of those devices.

Out of curiosity if you call [``setDecodeFormat``][1] with [``ALWAYS_ARGB_8888``][2], does that fix the problem on those devices? You can see [the wiki][3] for more info on using ``GlideBuilder``. If setting the code format to argb8888 fixes the problem, this may be related to #301.

[1]: http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/GlideBuilder.html#setDecodeFormat(com.bumptech.glide.load.DecodeFormat)
[2]: http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/load/DecodeFormat.html#ALWAYS_ARGB_8888
[3]: https://github.com/bumptech/glide/wiki/Configuration

**Comment by ruanml** [comment] 2015-01-13 01:41
Dear Sam:
Thank you for your advice.

I tested it by using MOTO G and SAMSUNG S4 and it worked fine.
When using Nexus 10 and 4, it also works fine without setting ALWAYS_ARGB_8888. 
this bug only happens on some devices.

**Comment by kainecy** [comment] 2015-01-15 08:16
htc-htc_d816t-HC45RWW09037
I use Glide in PullToRefreshListView BaseAdapter.getView
the convertView is reused.
Should call Glide.clear before load?

**Comment by sjudd** [comment] 2015-01-15 17:58
Ok definitely a duplicate of #301, let's track things there since we seem to be closer to the root cause in that bug.

**Closed by sjudd** 2015-01-15 17:58 UTC
Labels: bug

**Comment by mtst99** [comment] 2016-01-26 11:17
This problem happened for me on Galaxy S5 on fast scrolling.
RecyclerView with GridLayoutManager that shows 6 images on each row and it has many type of views.
I had no choice other than doing this
recyclerView.getRecycledViewPool().setMaxRecycledViews(Adapter.INT_VIEW_TYPE_PHOTO, 0);
So I keep number of cached images to zero unless you could provide different approach.

**Comment by TWiStErRob** [comment] 2016-01-26 12:16
Can you please open a [new issue](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues), this seems to be fixed by #301 last year.

Please include the interactions with the imageView inside the holder (including any conditions that surround them) in `onBind`, `onRecycled` and your `GlideModule` customizations; also include inflating code if you dynamically generate ImageViews. The best would be if you can create a small repro app.

**Comment by mtst99** [comment] 2016-02-02 09:06
Sorry, my bad. I didn't read previous comments thoroughly as I wasn't aware of how ListView and GridView behave with Glide and my case was about RecyclerView so it made me not pay too much attention while answer was here( "setDecodeFormat with ALWAYS_ARGB_8888"). Because of curiosity about speed and performance of ListView compare to RecyclerView I decided to give it a try and result was weird. I got faster scrolling experience with ListView that I think is because of simplicity of items hierarchy which is another topic of discussion but it made me understand getView part of this question so continue all the responses and get my answer. Thank you.

**Comment by PrashantSPol** [comment] 2016-06-03 09:24
Hello,
is there any update on this issue ??

I am still facing same issue. Images in gridView are misplaced after fast scrolling.

in listview, child views are reused on scroll, 
but glide is making calls for all views which are getting scrolled.
If earlier image loading was delayed then it will be shown in re-used component.
In short:

image_1(url1)
image_2(url2)
.
.
.
.
.
reused_image_1(url-new1)
reused_image_2(url-new2)

if url1 image download delayed, then url1 will be shown in reused image_1.

**Comment by TWiStErRob** [comment] 2016-06-03 09:37
Please open a new issue with all the details filled in. Based on this partial info I'm guessing you may be starting an load async that is not cancelled when the item is re/unbound.
