### ISSUE TITLE
NoClassDefFoundErrors in 4.6

### ISSUE THREAD

**Issue by SUPERCILEX** [bumptech/glide#2866] opened 2018-02-02 06:46 UTC
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider
```

Guessing it's related to #2863.

**Comment by krishnameena** [comment] 2018-02-02 09:52
I am also facing the same issue 

```
java.lang.NoClassDefFoundError: com.bumptech.glide.load.resource.gif.GifBitmapProvider
                                                                              at com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder.<init>(ByteBufferGifDecoder.java:70)
                                                                              at com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder.<init>(ByteBufferGifDecoder.java:56)
                                                                              at com.bumptech.glide.Glide.<init>(Glide.java:339)
                                                                              at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:472)
                                                                              at com.bumptech.glide.Glide.initializeGlide(Glide.java:264)
                                                                              at com.bumptech.glide.Glide.initializeGlide(Glide.java:219)
                                                                              at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:180)
                                                                              at com.bumptech.glide.Glide.get(Glide.java:164)
                                                                              at com.bumptech.glide.Glide.getRetriever(Glide.java:670)
                                                                              at com.bumptech.glide.Glide.with(Glide.java:722)
                                                                              at .activities.DeviceKeyActivity.onCreate(DeviceKeyActivity.java:73)
                                                                              at android.app.Activity.performCreate(Activity.java:6259)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by sjudd** [comment] 2018-02-02 14:35
Duplicate of #2863

**Closed by sjudd** 2018-02-02 14:35 UTC
