### ISSUE TITLE
Setting a placeholder causes image not to render on Kitkat and below

### ISSUE THREAD

**Issue by silentlion** [bumptech/glide#914] opened 2016-01-21 01:31 UTC
I'm doing a simple image load for an item inside the adapter's onBindViewHolder:
```
    Glide.with(mContext)
    .load(companyLogoUrl)
	.placeholder(mCompanyLogoStockDrawable)
	.crossFade()
	.into(((JobViewHolder) holder).companyLogoView);
```
This works fine on Lollipop and above.
On KitKat and below, the image never loads. It always stays on the placeholder.

If I remove the .placeholder(...) then the image loads successfully.

I found one workaround. If I add a .listener, which does notifyDataSetChanged() upon completion, then the image loads successfully. This workaround presents issues sometimes however, you can't safely call notifyDataSetChanged from within onBind..
```
    Glide.with(mContext)
    .load(companyLogoUrl)
	.placeholder(mCompanyLogoStockDrawable)
	.crossFade()
	.listener(new RequestListener<String, GlideDrawable>() {
		@Override
		public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
			notifyDataSetChanged();
			return false;
		}

        @Override
		public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
			notifyDataSetChanged();
			return false;
		}
	})
	.into(((JobViewHolder) holder).companyLogoView);
```

**Comment by TWiStErRob** [comment] 2016-01-21 09:38
Please check why it is not loading:
https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

Also since you're using a recycler view adapter you could just notify for that single position iirc to prevent rebinding everything. You can always post to the UI thread if direct call is not safe. However this is basic functionality and it should work, please check the exception and logs for what's happening.

**Comment by TWiStErRob** [comment] 2016-01-21 09:40
Oh, wait I just noticed you're using a custom target (`JobViewHolder implements Target`?). Please include the relevant sources from that.

**Comment by silentlion** [comment] 2016-01-21 20:53
@TWiStErRob I tried debugging log.tag.GenericRequest, but didn't see any exceptions.
Yes, the single position update is the same kind of workaround as notifyDataSetChanged(). I tried both, and sometimes they work, sometimes they don't. Regardless, that's just a workaround - not a fix.

This seems to me like a serious glide bug, because a) this works fine on Lollipop and above and b) It works fine if I remove the .placeholder.

**Comment by silentlion** [comment] 2016-01-21 21:11
Additionally, I put the following debug logger in:

```
    public class LoggingListener<T, R> implements RequestListener<T, R> {
        @Override public boolean onException(Exception e, Object model, Target target, boolean isFirstResource) {
            android.util.Log.d("GLIDE", String.format(Locale.ROOT,
                    "onException(%s, %s, %s, %s)", e, model, target, isFirstResource), e);
            return false;
        }
        @Override public boolean onResourceReady(Object resource, Object model, Target target, boolean isFromMemoryCache, boolean isFirstResource) {
            android.util.Log.d("GLIDE", String.format(Locale.ROOT,
                    "onResourceReady(%s, %s, %s, %s, %s)", resource, model, target, isFromMemoryCache, isFirstResource));
            return false;
        }
    }
```

And all report successful onResourceReady, even though they are not loading:
```
01-21 13:06:15.269 30908-30908/com.x D/GLIDE: onResourceReady(com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable@421ab300, https://media.x.com/sql/2763/logo-1451953390963.png, Target for: com.x.ui.custom.RoundedImageView{41b51568 V.ED.... ........ 45,60-180,195 #7f0e03a1 app:id/companyLogo}, false, true)
01-21 13:06:15.279 30908-30908/com.x D/GLIDE: onResourceReady(com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable@420e2380, https://media.x.com/sql/4138/ogo-1446040583582.png, Target for: com.x.ui.custom.RoundedImageView{41da0380 V.ED.... ........ 45,60-180,195 #7f0e03a1 app:id/companyLogo}, false, true)
01-21 13:06:15.299 30908-30908/com.x D/GLIDE: onResourceReady(com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable@41ecad40, https://media.x.com/sql/613/logo.png, Target for: com.x.ui.custom.RoundedImageView{422bfe68 V.ED.... ........ 45,60-180,195 #7f0e03a1 app:id/companyLogo}, false, true)
01-21 13:06:15.299 30908-30908/com.x D/GLIDE: onResourceReady(com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable@41ddfd88, https://media.x.com/sql/97/logo.png, Target for: com.x.ui.custom.RoundedImageView{4207e578 V.ED.... ........ 45,60-180,195 #7f0e03a1 app:id/companyLogo}, false, true)
01-21 13:06:15.379 30908-30908/com.x D/GLIDE: onResourceReady(com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable@420ead30, https://media.x.com/sql/8014/logo.png, Target for: com.x.ui.custom.RoundedImageView{41b54740 V.ED.... ........ 45,60-180,195 #7f0e03a1 app:id/companyLogo}, false, true)
01-21 13:06:15.379 30908-30908/com.x D/GLIDE: onResourceReady(com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable@420b0418, https://media.x.com/sql/8874/logo-1453269130589.png, Target for: com.x.ui.custom.RoundedImageView{41d08388 V.ED.... ........ 45,60-180,195 #7f0e03a1 app:id/companyLogo}, false, true)
```

**Comment by TWiStErRob** [comment] 2016-01-21 21:11
Try the listener debugging as well.

I know they're the same workaround, I just suggested because it is likely faster if you need to apply it.

What happens if you replace crossFade with dontAnimate?

It cannot be a serious Glide bug because no one noticed it in the past 1+ year... there must be something exotic you're doing. Can you please try to isolate this issue into a separate application that you can share? Or share the original code (email me)? We need to reproduce this to fix it, and so far there were no placeholder issues.

In any case what is `mCompanyLogoStockDrawable`?

**Comment by TWiStErRob** [comment] 2016-01-21 21:14
Scratch that... here's a [nice list](https://github.com/bumptech/glide/issues?utf8=%E2%9C%93&q=is%3Aissue+CircleImageView+OR+CircularImageView+OR+RoundedImageView). We dug deep and found the core of the problem: https://github.com/bumptech/glide/issues/482#issuecomment-107977982 (_scroll down a little, the images may make the URL anchor displaced, it's the last long comment by me_)

You have two options:
 * use [CircleTransform](http://stackoverflow.com/a/25806229/253468) instead of custom ImageView
 * add `.dontAnimate()`

While disabling the animation seems easier, you may have more luck with the transformation in the long run.

**Comment by TWiStErRob** [comment] 2016-01-21 21:19
It's interesting that it works on Lollipop, can you please share the core of your RoundedImageView? There must be an SDK condition in it rlor something.

**Comment by silentlion** [comment] 2016-01-21 21:43
@TWiStErRob - thanks, that did it. 

So it seems Glide has an issue with the CircleDrawable/RoundedImageView code. It's a pretty commonly used library and there are several implementations of it online:
https://github.com/vinc3m1/RoundedImageView/
https://github.com/hdodenhof/CircleImageView
https://gist.github.com/melanke/7158342

We use a customized clone of the first lib.
You should probably document this as a warning on Glide's github, and call onException() when this happens, or better yet raise a suggestion at runtime in the logs to use .dontAnimate() or Glide's own CircleTransform. It's a deep bug and if you didn't help me or didn't happen to see this case already, I would've been in trouble...

**Comment by TWiStErRob** [comment] 2016-01-21 21:54
Where and how would you document it? There are so many names and forks of it. You can't do an instanceof on it from Glide. I guess we could do a `getClass().contains` on the target view, but it seems really hacky.

I think there are so many occurrences of this in this issue tracker that most people should find it, and those who don't, report it and we close it as dupe :)

Those extensions of the `ImageView` are hacks in my eyes, they render the drawable onto a Bitmap, regardless of how wasteful that is. A proper implementation would draw super as usual with a circular mask. This is just how I see it.

**Comment by TWiStErRob** [comment] 2016-01-21 22:07
Hmm, I just checked the code of the first, that is a better implementation. I wonder why it doesn't work. It must be a different reason than usual because [this](https://github.com/vinc3m1/RoundedImageView/blob/master/roundedimageview/src/main/java/com/makeramen/roundedimageview/RoundedDrawable.java#L104) branch should execute for TransitionDrawable. Possibly vinc3m1/RoundedImageView#94

**Closed** 2016-01-21 22:15 UTC
Labels: duplicate, question

**Comment by silentlion** [comment] 2016-01-21 22:21
By documenting, I meant putting a warning in the README.md on Glide's homepage. That should help people be aware of it.
As for detecting this issue within code, detecting the class instanceof the ImageView might not be a bad idea. There are only 2 or 3 of these class names, namely RoundedImageView is the most popular.

**Comment by TWiStErRob** [comment] 2016-02-07 12:06
https://github.com/bumptech/glide/pull/966/files#diff-04c6e90faac2675aa89e2176d2eec7d8R118
