### ISSUE TITLE
Error:Glide library java.lang.AbstractMethodError by adding another library

### ISSUE THREAD

**Issue by snajdovski** [bumptech/glide#3541] opened 2019-02-25 09:59 UTC
I am getting an Error by adding this **library** into my project
The library:` 'com.github.RahulJanagouda:StatusStories:1.0.1'`
**The error log:**
`2019-02-24 10:43:32.993 12294-12294/com.ozurak.mk E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.ozurak.mk, PID: 12294
java.lang.AbstractMethodError: abstract method "void com.bumptech.glide.module.RegistersComponents.registerComponents(android.content.Context, com.bumptech.glide.Glide, com.bumptech.glide.Registry)"
    at com.bumptech.glide.Glide.initializeGlide(Glide.java:231)
    at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:172)
    at com.bumptech.glide.Glide.get(Glide.java:156)
    at com.bumptech.glide.Glide.getRetriever(Glide.java:535)
    at com.bumptech.glide.Glide.with(Glide.java:561)
    at com.ozurak.mk.adapters.NewsFeedRecyclerViewAdapter.getPostImage(NewsFeedRecyclerViewAdapter.java:166)
    at com.ozurak.mk.adapters.NewsFeedRecyclerViewAdapter.onBindViewHolder(NewsFeedRecyclerViewAdapter.java:69)
    at com.ozurak.mk.adapters.NewsFeedRecyclerViewAdapter.onBindViewHolder(NewsFeedRecyclerViewAdapter.java:35)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
    at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)......`
**The Gradle file of the StatusStrories Library:**
```
dependencies {
implementation 'com.android.support:appcompat-v7:26.1.0'
// Glide v3 (stable)
implementation 'com.github.bumptech.glide:glide:3.9.0'
// OkHttp3
implementation 'com.github.bumptech.glide:okhttp3-integration:1.6.0-SNAPSHOT'
implementation 'com.squareup.okhttp3:okhttp:3.10.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.7.0'
testImplementation 'junit:junit:4.12'
androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.1', {
    exclude group: 'com.android.support', module: 'support-annotations'
})}
```
**My Gradle File:**
```
//emoji disabler
implementation 'com.xw.repo:xedittext:2.1.0@aar'
//firebase
implementation 'com.google.firebase:firebase-storage:10.0.1'
implementation 'com.google.firebase:firebase-auth:10.0.1'
implementation 'com.google.firebase:firebase-database:10.0.1'

//android
implementation 'com.android.support:recyclerview-v7:26.+'
implementation 'com.android.support:cardview-v7:26.1.0'
implementation 'com.android.support:appcompat-v7:26.+'
implementation 'com.android.support.constraint:constraint-layout:1.0.2'
implementation 'com.android.support:design:27.1.1'

//circle image view
implementation 'de.hdodenhof:circleimageview:2.2.0'

//like button
implementation 'com.github.jd-alexander:LikeButton:0.2.3'

//image loader
implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'

//ExifInterface support
implementation "com.android.support:exifinterface:26.+"

//image picker
implementation 'com.github.nguyenhoanglam:ImagePicker:1.2.1'

//button
implementation 'com.beardedhen:androidbootstrap:2.3.2'

//image loader
//image scroll 7/8/2018
implementation 'com.github.Q42:AndroidScrollingImageView:1.3.3'
//dropdown list
implementation 'com.github.JayFang1993:DropDownMenu:v0.9'
//zoom
implementation 'com.ablanco.zoomy:zoomy:1.1.0'
//stories
implementation 'com.github.RahulJanagouda:StatusStories:1.0.1'

//glide
implementation 'com.github.bumptech.glide:glide:4.9.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'

// OkHttp3
implementation 'com.github.bumptech.glide:okhttp3-integration:1.6.0-SNAPSHOT'
implementation 'com.squareup.okhttp3:okhttp:3.10.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.7.0'

```

**Comment by sjudd** [comment] 2019-03-05 02:05
There's a lot to unpack here. Are you able to narrow this down to a smaller set of dependencies? or reproduce the issue in a minimal sample app?

**Comment by sjudd** [comment] 2019-03-05 02:35
Duplicate of #2994. One of your dependencies has included a v3 module.

**Closed** 2019-03-05 16:23 UTC
