### ISSUE TITLE
gif loading taking too much time with glide 

### ISSUE THREAD

**Issue by AkashRai1992** [bumptech/glide#1055] opened 2016-03-13 11:01 UTC
i need to show gif in recyle view android, i am currently using glide and sending gif request to download gif in the onbindviewholder callback
the scroll is smooth but the gif download is very slow with glide,can anybody suggest better mechanism.
current code is
```java
package com.example.akash.videogramassignment.adapters;

import android.app.Activity;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.bumptech.glide.Glide;
import com.bumptech.glide.load.engine.DiskCacheStrategy;
import com.example.akash.videogramassignment.R;
import com.example.akash.videogramassignment.apputils.AppUtils;
import com.example.akash.videogramassignment.models.videoassignment.GridBaseData;
import com.example.akash.videogramassignment.viewholders.GIFItemViewHolder;

import java.util.ArrayList;
import java.util.List;


/**
 * Created by akash on 12/3/16.
 */
public class VideoGramDataAdapter extends RecyclerView.Adapter<GIFItemViewHolder> /*implements OnItemClickListener*/ {
    private List<GridBaseData> mHomePageItemList = new ArrayList<>();
    private final int deviceWidth = AppUtils.getDeviceWidth();
    /*Map<Integer, GifDrawable> params = new HashMap(mHomePageItemList.size()) {
        @Override
        public GifDrawable get(Object key) {
            if (!containsKey(key))
                return null;
            return (GifDrawable) super.get(key);
        }
    };
    Map<Integer, Boolean> isGifRequest = new HashMap(mHomePageItemList.size()) {
        @Override
        public Boolean get(Object key) {
            if (!containsKey(key))
                return false;
            return (Boolean) super.get(key);
        }
    };*/

    private Activity mContext;
    private GIFItemViewHolder GIFItemViewHolder;

    public VideoGramDataAdapter(List<GridBaseData> homePageListItemList, Activity context) {
        mHomePageItemList = homePageListItemList;
        mContext = context;

    }

    @Override
    public GIFItemViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.layout_gif_item_tuple, parent, false);
        return new GIFItemViewHolder(view);
    }

    @Override
    public void onBindViewHolder(GIFItemViewHolder holder, int position) {
     /* float factor = deviceWidth/(mHomePageItemList.get(position).grid.width);
        int height = (int)factor*(mHomePageItemList.get(position).grid.height);
        holder.tupleContainer.setLayoutParams(new ViewGroup.LayoutParams(
                deviceWidth, height)); */
        //Glide.with(mContext).load(R.layout.layout_spinner).override(Integer.valueOf(mHomePageItemList.get(position).grid.height), deviceWidth); // resizes the image to these dimensions (in pixel). does not respect aspect ratio.into(holder.mItemIcon);
        /*if (isGifRequest != null *//*&& isGifRequest.get(position) *//* && params != null && params.get(position) != null) {*/
        Glide.with(mContext).load(mHomePageItemList.get(position).grid.gif_url)
                .asGif()
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                //.override(/*Integer.valueOf(mHomePageItemList.get(position).grid.height)*/(deviceWidth*3)/4, deviceWidth)
                .into(holder.mItemIcon);
        /*} else
            Glide.with(mContext).load(mHomePageItemList.get(position).ppurl).into(GIFItemViewHolder.mItemIcon);*/


    }


    @Override
    public int getItemCount() {
        return mHomePageItemList != null ? (mHomePageItemList.size()) : 0;
    }

    public void addAll(List<? extends GridBaseData> items) {
        mHomePageItemList.addAll(items);
    }


   /* @Override
    public void onItemClick(int position, View v) {
        if (GIFItemViewHolder != null && mContext != null) {
            if (params.get(position) == null) {
                downloadImage(position, v);
                isGifRequest.put(position, true);
            } else {
                ImageView imageView = (ImageView) v;
                //imageView.setImageDrawable(params.get(position));
                Glide.with(mContext).load(params.get(position)).into(imageView);
            }
        }
        if (mContext != null) {
            LogUtils.makeToast("called" + position, mContext.getApplicationContext());
        }
    }*/

    /*private void downloadImage(final int position, View v) {
        ImageView imageView = (ImageView) v;
     *//*   Glide.with(mContext).load(mHomePageItemList.get(position).grid.gif_url).asGif()
                .into(new SimpleTarget<GifTypeRequest>() {
                    @Override
                    public void onResourceReady(GifTypeRequest resource, GlideAnimation glideAnimation) {
                        params.put(position, resource);
                        //Glide.with(this).load(R.raw.sample_gif).into(imageViewTarget);
                    }
                });*//*
        Glide.with(mContext).load(mHomePageItemList.get(position).grid.gif_url).asGif().listener(new RequestListener<String, GifDrawable>() {
            @Override
            public boolean onException(Exception e, String model, Target<GifDrawable> target, boolean isFirstResource) {
                return false;
            }

            @Override
            public boolean onResourceReady(GifDrawable resource, String model, Target<GifDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                params.put(position, resource);
                return false;
            }


        }).into(imageView);
    }*/

    @Override
    public void onViewRecycled(GIFItemViewHolder holder) {
        super.onViewRecycled(holder);
        Glide.clear(holder.mItemIcon);
    }
}
```

**Comment by TWiStErRob** [comment] 2016-03-13 11:42
Duplicate of #281 and many others... change RESULT (=default) to SOURCE.

This should help to find out more:
https://www.google.com/search?q=glide+gif+slow

Also worth noting that you shouldn't hold onto `GifDrawable`s, it's unsafe as they can be recycled and become invalid. Memory cache should take care of fast reuse and to decide "GIF or not" I suggest `url.endsWith(".gif")` if the url has a filename.

Out of curiosity: what's the reason for doing `containsKey` in the `params` custom Map? As far as I know a `get` for a nonexistent key will return null by design.

**Closed** 2016-03-13 11:42 UTC
Labels: duplicate, question

**Comment by AkashRai1992** [comment] 2016-03-13 12:18
that was a naive approach to show gif, thanks for showing your concern on commented code too,
but the problem i am facing that eventhough i changed the DiskCachecategory to source , the change is not worth noticing, my problem is to load gifs fast, is there any other approach to do the task, other then changing disKCacheCategory to source ?
Btw thanks a ton for a quick reply.

**Comment by TWiStErRob** [comment] 2016-03-13 12:41
Well, if it wasn't that the RESULT caching made it re-encode the GIF, then Glide cannot do much about a slow/bad internet connection, bytes are bytes, there's no way around transferring them. I checked videogram.com and those thumbnails are 1-2MB large, opening the main page needed 34MB of traffic on my laptop. If you're doing something similar that's gonna be tricky. Also if there are many images displayed at once (3 column grid for example) then all those HTTP requests are fired at once (with rate-limited queuing of course), making it even slower. Currently there's no progressive display of GIFs, the files must be fully available before displaying them.

You can try firing `downloadOnly` requests before the items are displayed so by the time you get there via scrolling they're already in SOURCE cache. There's a `ListPreloader` in 3.7.0, but preloading is a little different than downloadOnly: it actually decodes the image which may not be useful with GIFs, but you can give it a try. Or you can try a quick and dirty solution of firing `downloadOnly` requests for `position + 1..3` on every bind so the next ones will download beforehand.
