### ISSUE TITLE
picture looks very bad on android 6.0

### ISSUE THREAD

**Issue by water54** [bumptech/glide#696] opened 2015-10-19 08:38 UTC
when i use like this: 
```java
Glide.with(mContext).load(mUrl).placeholder(R.drawable.placeholder).crossFade().into(mViewHolder.getImageView()); 
```
on android may cause picture looks smaller than imageview .note that i have set imageview scale fitXY.

**Comment by TWiStErRob** [comment] 2015-10-19 11:07
This sounds like #363 with the possibility of fitXY making it more prominent.

I'm afraid you have to skip `.crossFade()` in favor of `.dontAnimate()` if your placeholder doesn't match the size (or at least aspect ratio) of what you're loading.

If you don't think this is a duplicate of #363 please fill in the [issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues) (feel free to edit your original comment).

**Comment by water54** [comment] 2015-10-20 11:30
i replace .crossFade() with .dontAnimate() as your advice.and it works. but why this only happens on android 6.0 after my nexus5 upgrade to android 6.0 from 5.1.1?

**Comment by TWiStErRob** [comment] 2015-10-20 12:05
Good question. I'm gonna close this as a duplicate, because the other one has more info. Feel free to subscribe to #698.

**Closed by TWiStErRob** 2015-10-20 12:05 UTC
Labels: duplicate, question
