### ISSUE TITLE
OkHttpClient Leak after FileNotFoundException (No Image)

### ISSUE THREAD

**Issue by rcgonzalezf** [bumptech/glide#2812] opened 2018-01-15 03:00 UTC
**Glide Version**: 4.3.1

**Integration libraries**:

**Device/Android Version**: Pixel Android 8.1

**Issue details / Repro steps / Use case background**: 

I'm using gravatar to get the icon for an app, sometimes the user won't have a gravatar profile and that's ok, I just don't show it; however when that happens it seems that Glide doesn't closes the response body.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 Glide.with(context)
                .asBitmap()
                .load(gravatarURL)
                .into(object : SimpleTarget<Bitmap>() {
                    override fun onResourceReady(resource: Bitmap, glideAnimation: Transition<in Bitmap>) {
                        callback.onImageAvailable(resource)
                    }

                    override fun onLoadFailed(errorDrawable: Drawable?) {
                        // nothing expected
                    }
                })
```

**Layout XML**:
```xml
Irrelevant for this case
```

**Stack trace / LogCat**:
```ruby
Root cause (1 of 1)
                                                           java.io.FileNotFoundException: https://www.gravatar.com/avatar/abc.jpg?s=96&d=404&r=g
                                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
                                                               at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                               at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
                                                               at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getInputStream(TrackedHttpURLConnection.java:356)
                                                               at com.android.tools.profiler.support.network.httpurl.HttpsURLConnection$.getInputStream(HttpsURLConnection$.java:261)
                                                               at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:104)
                                                               at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:54)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:147)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141)
                                                               at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:60)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                               at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                               at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                               at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
                                                               at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                               at java.lang.Thread.run(Thread.java:764)
                                                               at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
```

01-14 18:58:38.279 16938-17139/ W/OkHttpClient: A connection to https://www.gravatar.com/ was leaked. Did you forget to close a response body?

**Comment by sjudd** [comment] 2018-01-16 15:14
If you try the OkHttp integration library do you see the same issue? http://bumptech.github.io/glide/int/okhttp3.html. I'd guess this either an issue with how we clean up HttpUrlConnections or a platform issue since we're not actually using OkHttp directly.

**Comment by skauss** [comment] 2018-01-17 10:11
I have the same warning 
```
01-17 11:02:35.532 19466-19466/com.package.xx W/Glide: Load failed for http://host.domain.de/path/to/image/image.jpg with size [320x320]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
         Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
            Cause (1 of 1): class java.io.FileNotFoundException: http://host.domain.de/path/to/image/image.jpg

01-17 11:02:38.213 19466-19577/com.package.xx W/OkHttpClient: A connection to  http://host.domain.de/ was leaked. Did you forget to close a response body?
01-17 11:02:38.214 19466-19577/com.package.xx W/OkHttpClient: A connection to  http://host.domain.de/ was leaked. Did you forget to close a response body?
```

**Comment by rcgonzalezf** [comment] 2018-01-22 07:34
I bumped up my glide version from `4.3.1` to `4.5.0` and the issue is now gone. If I go back I'm still getting the warning. It seems the OkHttp integration library doesn't actually make a difference for this issue. In my case updating wasn't a problem so I'll use the latest. 

Thanks.

**Comment by sjudd** [comment] 2018-01-22 15:21
Thanks @rcgonzalezf.

@skauss what version of Glide are you using?

**Comment by skauss** [comment] 2018-01-22 15:25
I use the Glide Version 4.3.1

**Comment by sjudd** [comment] 2018-01-22 15:27
Ok let's assume this is fixed in 4.5.0. If someone can reproduce on 4.5.0 or higher please let me know.

**Closed by sjudd** 2018-01-22 15:27 UTC
Labels: bug, repro-needed

**Comment by skauss** [comment] 2018-02-01 09:45
Hi,
today I found the Warning of the OkHttpClient again. 
The version of Glide is 4.5.0 and the OkHttpClient is 3.9.1

```
W/OkHttpClient: A connection to http://host.domain.xx/ was leaked. Did you forget to close a response body?
```
It occur only some times in the case I have a **FileNotFoundException**
Some times mean 6 times file not found and 2 times OkHttpClient: A connection to xx was leaked

```
java.io.FileNotFoundException: http://host.domain.xx/theImage.jpg
                                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
                                                                                  at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
                                                                                  at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
                                                                                  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:97)
                                                                                  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:148)
                                                                                  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:142)
                                                                                  at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
                                                                                  at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:97)
                                                                                  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                                                  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                                  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                                  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                  at java.lang.Thread.run(Thread.java:764)
                                                                                  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```
Regards

**Comment by leocorder** [comment] 2018-07-25 15:01
Same issue here when I have a **FileNotFoundException**.
Glide version: **4.7.1**

**Comment by TeunVR** [comment] 2018-09-05 06:55
Same here, also on 4.7.1.

**Comment by sjudd** [comment] 2018-09-12 20:12
What versions of Android are you seeing this message on?

**Comment by skauss** [comment] 2018-09-13 06:55
I use now Glide 4.8.0 on Android 7.1 / Android 9.0 and is seems the problem is solved.

**Comment by lbx2015** [comment] 2019-08-27 10:53
I am using glide 4.9.0 and glide:compiler:4.9.0. and got  W/OkHttpClient: A connection to http://test-api.heitouyang.cn/ was leaked. Did you forget to close a response body? after the image not found.
How can I solve this.

    implementation 'com.github.bumptech.glide:glide:4.9.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'

**Comment by nhannt201** [comment] 2021-09-24 07:46
I think the problem of this topic will be solved quickly with this solution. I had the same problem and solved it successfully!
https://stackoverflow.com/questions/28221555/how-does-okhttp-get-json-string

**Comment by slopeio23** [comment] 2022-11-30 06:43
I was astonished at how much information was on your website. I appreciate you acknowledging my attempts to make others better [slope io](https://slope-io.com)
