### ISSUE TITLE
View always appear light green background from cache load

### ISSUE THREAD

**Issue by AndroidFa** [bumptech/glide#863] opened 2016-01-06 06:59 UTC
glide load cache image in SamsungNote2 ，image view always appear light green background.
glide version is 3.6.1
![Uploading photo.jpg…]()

**Comment by TWiStErRob** [comment] 2016-01-06 10:22
Your image didn't upload, but sounds like a duplicate of #515. Sam explained it best here: https://github.com/bumptech/glide/issues/305#issuecomment-112937571

I'm going to close this as a duplicate, but feel free to ask followup questions here.

**Closed by TWiStErRob** 2016-01-06 10:22 UTC
Labels: duplicate, question

**Comment by AndroidFa** [comment] 2016-01-12 05:15
Thank you for your answer
