### ISSUE TITLE
load Url pic fail at first

### ISSUE THREAD

**Issue by mBigFlower** [bumptech/glide#553] opened 2015-07-24 01:34 UTC
Hello , 
    when i use glide to load url picture, just like 
    Glide.with(this).load(url).placeholder(R.drawable.img_photo_fail).into(imageview);
    I find that the imageview shows the placeholder's pic instead of the url's pic at first .
and I click back and come in again , it's rgiht .

   and if I use glide like this
   Glide.with(this).load(url).into(imageview);  
   without placehold . It can work well .

   What can I do ? thank you .

**Comment by TWiStErRob** [comment] 2015-07-24 09:32
The first time it's probably downloading the image, which takes time. placeholders are disgned to be shown first and replaced when the resource is available. The second time the image is already in memory cache which means the placeholder is skipped and image is shown immediately.

Try to wait longer the first time to see if it loads.

For me it seems like it's WAI (working as intended), please describe your problem in more detail if you feel otherwise. (You may include version numbers, xml, adapter if list, stack trace if any via listener).

**Comment by mBigFlower** [comment] 2015-07-25 13:47
Thank you for your reply. 
I think I find the reason. I want to load the url picture into a circle ImageView which is made by others rather than the ImageView. maybe the mistake is caused by the user-defined widget
Thank you !

**Comment by TWiStErRob** [comment] 2015-07-25 13:52
In that case this is a duplicate of https://github.com/bumptech/glide/issues/528#issuecomment-119538633 and many others, try [CircleTransform](http://stackoverflow.com/a/25806229/253468).

**Comment by sjudd** [comment] 2015-07-28 00:02
Let us know if we can help further.

**Closed by sjudd** 2015-07-28 00:02 UTC

**Comment by Wenqin-231** [comment] 2016-11-18 07:11
I meet the same question , thanks for your answer.
