### ISSUE TITLE
When ImageView scaleType is centerInside, the result bitmap size may be wrong!

### ISSUE THREAD

**Issue by start141** [bumptech/glide#592] opened 2015-08-21 04:58 UTC
**Thanks for reading!**

I will show something to intro this issue.

**I have test two images:**
```
image one
original size 157 × 266
```
![img_20150820_145618 01 01](https://cloud.githubusercontent.com/assets/6055764/9401110/d96ac1e2-47fc-11e5-9f87-916d4b4800e4.jpg)

```
image two
original size 3264 × 2448
```
![img_20150820_145618](https://cloud.githubusercontent.com/assets/6055764/9401576/1f087d1e-4804-11e5-93b2-5c8a577cb9bb.jpg)

**Test One:**
layout
```xml
<ImageView
    android:id="@+id/photoView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerInside"
    android:background="#2aa0a6"/>
```
code
```java
Glide.with(getActivity())
     .load(path)
     .asBitmap()
     .into(new BitmapImageViewTarget(mPhotoView) {
            @Override
            public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                super.onResourceReady(resource, glideAnimation);
                Log.e("Glide Test", "imageView scaleType=centerInside"
                                + " width=" + mPhotoView.getWidth()
                                + " height=" + mPhotoView.getHeight() + ", "
                                + " onResourceReady:"
                                + " bitmap width=" + resource.getWidth()
                                + " height=" + resource.getHeight());
            }
    });
```

test result log
```ruby
image one
08-21 12:00:44.192  10260-10260/im.varicom.colorful E/Glide Test﹕ imageView scaleType=centerInside width=1080 height=1920,  onResourceReady: bitmap width=157 height=226
image two
08-21 12:00:44.414  10260-10260/im.varicom.colorful E/Glide Test﹕ imageView scaleType=centerInside width=1080 height=1920,  onResourceReady: bitmap width=3264 height=2448
```

My conclusion:
the `image one`'s width and height both `smaller than` the imageView size, **it is show normally**.

the `image two`'s width and height both `larger than` the imageView size, the result bitmap width and height is the original size. I think it is not the right way!
**it let waste a lot of memory and let load the big image slower,
if the image show in ViewPager, scroll will not smooth.**

(I think the best way is let result bitmap size  `not larger than` the `imageView` size when the `image` size larger than the `imageView` size)
 
　
　
**Test Two:**
layout
```xml
<ImageView
    android:id="@+id/photoView"
    android:layout_width="200dp"
    android:layout_height="200dp"
    android:scaleType="centerInside"
    android:layout_centerInParent="true"
    android:background="#2aa0a6"/>
```
code
```java
Glide.with(getActivity())
    .load(path)
    .asBitmap()
    .into(new BitmapImageViewTarget(mPhotoView) {
            @Override
            public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                super.onResourceReady(resource, glideAnimation);
                Log.e("Glide Test", "imageView scaleType=centerInside"
                                + " width=" + mPhotoView.getWidth()
                                + " height=" + mPhotoView.getHeight() + ", "
                                + " onResourceReady:"
                                + " bitmap width=" + resource.getWidth()
                                + " height=" + resource.getHeight());
            }
    });
```

test result log
```ruby
image one
08-21 12:42:30.365    8109-8109/im.varicom.colorful E/Glide Test﹕ imageView scaleType=centerInside width=600 height=600,  onResourceReady: bitmap width=157 height=226

image two
08-21 12:42:30.364    8109-8109/im.varicom.colorful E/Glide Test﹕ imageView scaleType=centerInside width=600 height=600,  onResourceReady: bitmap width=816 height=612
```

My conclusion:
When the `imageView` size change, the image which width and height both `smaller than` the imageView size, **it will show normally**.

But, if the image width and height both `larger than` the imageView size, the result bitmap size sometimes will change also .

But above all, I think when ImageView scaleType is centerInside, glide load the result bitmap size may be wrong! 
I think the best way is let result bitmap size `not larger than` the `imageView` size when the `image` size larger than the `imageView` size.

**Comment by start141** [comment] 2015-08-21 05:05
ScreenShots:

**Test One**
image one
![device-2015-08-21-125226](https://cloud.githubusercontent.com/assets/6055764/9401618/a6778010-4804-11e5-893c-cc78afe63612.png)
image two
![device-2015-08-21-125238](https://cloud.githubusercontent.com/assets/6055764/9401640/2a99d8ac-4805-11e5-9cb1-747d6cb9bc1a.png)

**Test Two**
image one
![device-2015-08-21-125050](https://cloud.githubusercontent.com/assets/6055764/9401631/06aaf106-4805-11e5-8fc6-69748c06145e.png)
image two
![device-2015-08-21-125114](https://cloud.githubusercontent.com/assets/6055764/9401634/14684cb2-4805-11e5-9087-9a36a7191644.png)

**Comment by sjudd** [comment] 2015-08-21 14:40
Interesting, it looks like I didn't include center inside in the set of recognized scale types: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/RequestBuilder.java#L375. That said, you can still get the effect you want by calling fitCenter() manually.

Thanks for pointing this out.

**Comment by start141** [comment] 2015-08-21 15:10
Thanks for your reply!
Yeah, you are right. But fitCenter will let the image fit the imageView. It is not the right effect of centerInside.

Glide is a very beautiful library, it is nice. I hope it can 
become more and more perfect!

**Comment by TWiStErRob** [comment] 2015-10-16 16:35
Closing this as duplicate of #591.

**Closed by TWiStErRob** 2015-10-16 16:35 UTC
Labels: bug, duplicate
