### ISSUE TITLE
NullPointerException in SizeConfigStrategy.decrementBitmapOfSize

### ISSUE THREAD

**Issue by LiHanGuang** [bumptech/glide#703] opened 2015-10-21 03:14 UTC
Hello @sjudd @TWiStErRob: 
  I find a bug of glide maybe today.  If this bug is belong to glide, please show me the code how to fix it, thanks.

**Version: Glide 3.6.1**

- **build.gradle**
```java
compile 'com.github.bumptech.glide:glide:3.6.+'
```

-  **bug description**
```ruby
java.lang.RuntimeException: Unable to destroy activity {com.jiahe.qixin/com.jiahe.qixin.ui.LargeImageBrowserActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3741)
...
Caused by: java.lang.NullPointerException:
    at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.decrementBitmapOfSize(SizeConfigStrategy.java:108)
    at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.removeLast(SizeConfigStrategy.java:100)
    at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.trimToSize(LruBitmapPool.java:175)
    at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.clearMemory(LruBitmapPool.java:157)
    at com.bumptech.glide.Glide.clearMemory(Glide.java:369) // I am here !!!!!!!!!!!!!!!!
    at com.jiahe.qixin.ui.LargeImageBrowserActivity.onDestroy(LargeImageBrowserActivity.java:299)
    at android.app.Activity.performDestroy(Activity.java:5528)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1119)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3728)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3759)
    at android.app.ActivityThread.access$1400(ActivityThread.java:158)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5390)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:667)
    at dalvik.system.NativeStart.main(Native Method)
```

-  **usage**
```java
@Override
public void onDestroy() {
    super.onDestroy();
    cancelAsyncTasks();

    if (mBinded) {
        unbindService(mServConn);
        mBinded = false;
    }

    if (mLargeView != null) {
        Drawable drawable = mLargeView.getDrawable();
        mLargeView.setImageDrawable(null);
        if(drawable instanceof GlideBitmapDrawable){
            GlideBitmapDrawable bmpDrawable = (GlideBitmapDrawable)drawable;
            Bitmap bmp = bmpDrawable.getBitmap();
            if (!bmp.isRecycled()){
                bmp.recycle();
            }
        }else if (drawable instanceof GifDrawable){
            GifDrawable gifDrawable = (GifDrawable) drawable;
            gifDrawable.stop();
            gifDrawable.recycle();
        }
    }

    Glide.get(this).clearMemory();    // I am here !!!!!!!!!!!!!!!!
    Glide.get(this).getBitmapPool().clearMemory();
    Glide.get(this).setMemoryCategory(MemoryCategory.NORMAL);
}
```

**Comment by TWiStErRob** [comment] 2015-10-21 11:07
> ```java
Glide.get(this).clearMemory();    // I am here !!!!!!!!!!!!!!!!
Glide.get(this).getBitmapPool().clearMemory();
```

This looks like you've found #687 too.

> ```java
if (mLargeView != null) {
    ...
}
```

all of the code inside there should be automatically done by Glide in `super.onDestroy()` if you use the correct context when loading with `Glide.with`. The correct context in this case is a fragment attached to the activity or the activity itself, but not the application context. I highly recommend removing that code.

> SizeConfigStrategy.java:108
```java
107 Integer current = sizes.get(size);
108 if (current == 1) {
```

which means that the sizes Map contains a `null` value or doesn't have the key it's looking for.
I have a feeling that SizeConfigStrategy.java:99 `Util.getBitmapByteSize` returns an invalid value because you recycled the `Bitmap` yourself.

To fix your issue change
```java
if (mLargeView != null) {
```
to
```java
if (false) {
```
and try if you can reproduce.

If you really want to manually free resources used by `mLargeView` I suggest `Glide.clear(mLargeView)`.

**Comment by LiHanGuang** [comment] 2015-10-26 05:50
@TWiStErRob 
> I have a feeling that SizeConfigStrategy.java:99 Util.getBitmapByteSize returns an invalid value because you recycled the Bitmap yourself which results in a miss in the Map.

> quote in #687
If a Bitmap is shown an ImageView it's an active resource, which means it's not in any cache or pool.

The above two quote   contradiction.  Because the **Bitmap** recycled by myself  is not exist in pool or cache at this moment.  
That means is not have any chances  to call "SizeConfigStrategy.java:99 Util.getBitmapByteSize(**Bitmap(the bitmap recycled by myself)**)"

**Comment by TWiStErRob** [comment] 2015-10-26 08:58
> The above two quote contradiction.

Not necessarily, because you're in `onDestroy()` and after `super.onDestroy()` where the ImageView may have been already cleared by Glide's automatic behaviour, iff you you used activity or fragment in `Glide.with`. This means that your manual clear probably has no effect. Try logging `mLargeView.getTag()` to see if that view is still known to Glide. You may be right though, you should log `getDrawable()` too and double check if you still have the problem.

> That means is not have any chances to call ...

Only you can verify it in your case by debugging the mentioned lines.

> I take the advice like that

...and? Did it help or you're still crashing?
(If you catch it like that, some of your wanted clears may not execute, because of the exception in an earlier call)

> `LargeImageBrowserActivity`

I just realised why you're clearing everything. I suggest that instead of clearing all caches (reduces your app performance on other parts of the app), you can probably simply say: `.skipMemoryCache(true)` on the `load()` to prevent caching the large image.

Other than this: if your large age activity is consistent (i.e. it is loading a screen-sized image every time), you can leave it in the cache so that the next large image can reuse the Bitmap.

**Comment by LiHanGuang** [comment] 2015-10-27 06:30
@TWiStErRob 
First, thanks.

-----

**Reply 1:**
>
...and? Did it help or you're still crashing?
(If you catch it like that, some of your wanted clears may not execute, because of the exception in an earlier call)

My app crashed by this bug only once until now.  Not crash necessarily! 

-----

**Reply 2:**
 I find the cause, may be.  See the trace below:
```java
@Override
public void onDestroy() {
    super.onDestroy();
    ... other code...
    
    if (mLargeView != null) {
        Drawable drawable = mLargeView.getDrawable();
        mLargeView.setImageDrawable(null);
        if(drawable instanceof GlideBitmapDrawable){
            GlideBitmapDrawable bmpDrawable = (GlideBitmapDrawable)drawable;
            Bitmap bmp = bmpDrawable.getBitmap();
            LogWrapper.i("glide_test", bmp.toString() + " width = " + bmp.getWidth() + " ,height = " + bmp.getHeight());
            Bitmap obtainFromPool = Glide.get(this).getBitmapPool().get(bmp.getWidth(), bmp.getHeight(), bmp.getConfig());
            LogWrapper.i("glide_test", obtainFromPool != null? "bitmap is still in pool" : "bitmap is not in pool");
            Glide.clear(mLargeView);
            LogWrapper.i("glide_test", "after Glide.clear(target)" + (obtainFromPool != null ? "222 bitmap is still in pool" : "222 bitmap is not in pool"));

            if (!bmp.isRecycled()){
                bmp.recycle();
            }
        }
    }
    
    ... other code...
}


output result:
10-27 14:20:34.459  23713-23713/com.jiahe.qixin I/glide_test﹕ android.graphics.Bitmap@42d8d280 width = 776 ,height = 1048
10-27 14:20:34.464  23713-23713/com.jiahe.qixin I/glide_test﹕ bitmap is still in pool
10-27 14:20:34.464  23713-23713/com.jiahe.qixin I/glide_test﹕ after Glide.clear(target)222 bitmap is still in pool
```

**conclusion:**
- So the reason of this crash is that  **i recycled the Bitmap  which still exist in pool manually**.
- we should never recyle the bitmap manually which loaded by glide  for ever.
- the below conclusion is wrong!
>quote in #687
If a Bitmap is shown an ImageView it's an active resource, which means it's not in any cache or pool.

**Comment by TWiStErRob** [comment] 2015-10-27 18:25
I'm closing this now, it seems everything is figured out here. Feel free to reopen if you see it differently.

**Closed by TWiStErRob** 2015-10-27 18:25 UTC
Labels: question
