### ISSUE TITLE
Any idea when version 4.0.0 is coming out?

### ISSUE THREAD

**Issue by kiaanpillay** [bumptech/glide#1568] opened 2016-11-04 09:59 UTC
Also, what is the latest stable version? I use 3.7.0 but I see there is a 3.8 and a 3.7.1? Which is the latest stable?

**Comment by TWiStErRob** [comment] 2016-11-04 10:10
Basically a duplicate of #1473.

Latest stable on Maven Central: 3.7.0
[Snapshots](https://github.com/bumptech/glide/wiki/Snapshots): 3.8.0 and 4.0.0

Not officially stable, but there are very rare commits are going to the 3.0 branch which is where the 3.8.0 version snapshot is built from (it has [minor enhancements](https://github.com/bumptech/glide/milestone/12?closed=1), mainly GIF fixes and better animation support).

I don't know where you gathered 3.7.1 from, there was a milestone, but it was renamed 3.8.0 after a major enough change.

**Closed by TWiStErRob** 2016-11-04 10:10 UTC
Labels: duplicate, non-library, question

**Comment by kiaanpillay** [comment] 2016-11-04 10:18
Ok thank you! Another question, do we need to add the v4 support lib for better performance? I have support v13 and there are no errors?

**Comment by TWiStErRob** [comment] 2016-11-04 10:38
Hmm, you might be interested in #137 and [JavaOverload repro](https://github.com/TWiStErRob/TWiStErRob/tree/master/JavaOverload) (read tell-tale and reality sections).

I think if it works for you, then you can use however you want. In production ProGuard should hopefully remove the `with(v4.Fragment)` method anyway.

**Comment by TWiStErRob** [comment] 2016-11-04 10:40
Oh and to answer you question: performance is not affected, because if you're not using v4, then you don't have `FragmentActivity` so Glide cannot add a v4 fragment to track, but it'll use the built-in  Activity and Fragment classes.
