### ISSUE TITLE
GlideApp cannot be generated : from v3 to v4.3.1

### ISSUE THREAD

**Issue by erichyx** [bumptech/glide#2791] opened 2018-01-08 03:26 UTC
Hi guys,
    I have a problem when I migrate glide from v3 to v4.3.1 in project, the GlideApp can't be generated.
    I'm sure that all the dependencies have been added.
    Is because the project has many glide v3 syntax error? If yes, how to fix it?
    Thank you very much!

**Comment by sjudd** [comment] 2018-01-08 15:00
Duplicate of #1939

**Closed by sjudd** 2018-01-08 15:00 UTC
