### ISSUE TITLE
image flicker loading with glide v4

### ISSUE THREAD

**Issue by yanxinmiao** [bumptech/glide#2264] opened 2017-08-18 10:50 UTC
**Glide Version : 4.0.0**:

**Integration libraries : okhttp3-integration:4.0.0**:

**Device/Android Version : xiaomi 6.0**:

**Issue details / Repro steps / Use case background**: 
 options add transform , when refresh recyclerview , the item image will flicker .

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 RequestOptions options = new RequestOptions();
        options.placeholder(R.drawable.default_news_cat_pic)
                .error(R.drawable.default_news_cat_pic)
                .dontAnimate()
                .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC)
                .options.transform(new TopCrop(imageView.getContext()));

GlideApp.with(image.getContext())
      .load(url)
      .apply(options)
      .into(image);
```

**Layout XML**:
```

        <RelativeLayout
            android:id="@+id/rl_content"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingLeft="@dimen/normal_margin"
            android:paddingRight="@dimen/normal_margin"
            android:paddingTop="@dimen/normal_margin">

            <TextView
                android:id="@+id/tv_title"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignLeft="@+id/ll_head"
                android:layout_alignStart="@+id/ll_head"
                android:layout_below="@id/ll_head"
                android:ellipsize="end"
                android:lineSpacingExtra="3dp"
                android:maxLines="2"
                android:paddingBottom="2dp"
                android:text="标题"
                android:textColor="@color/text_black"
                android:textSize="@dimen/font_size_big" />

            <ImageView
                android:id="@+id/iv_image"
                android:layout_width="match_parent"
                android:layout_height="187dp"
                android:layout_below="@id/tv_title"
                android:layout_marginTop="5dp"
                android:src="@drawable/default_news_cat_pic" />

            <TextView
                android:id="@+id/tv_desc"
                style="@style/noraml_text_style"
                android:layout_below="@id/iv_image"
                android:layout_marginTop="7dp"
                android:ellipsize="end"
                android:lineSpacingExtra="2dp"
                android:maxLines="2"
                android:text="简介"
                android:visibility="gone" />

        </RelativeLayout>


```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment] 2017-08-18 15:25
Might be a duplicate of #2194, look through that and let me know if nothing there works for you.

**Closed by sjudd** 2017-08-18 15:25 UTC

**Comment by yanxinmiao** [comment] 2017-08-21 02:36
when i add transform using CenterCrop , the image don't flicker ,but use TopCrop the image flicker .

the topCrop is custom , the CenterCrop  is owned by Glide library 。

the topCrop code 
```
package com.hudong.baikejiemi.utils;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Matrix;
import android.graphics.Paint;

import com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool;
import com.bumptech.glide.load.resource.bitmap.BitmapTransformation;
import com.bumptech.glide.load.resource.bitmap.CenterCrop;

import java.security.MessageDigest;

import static com.bumptech.glide.load.resource.bitmap.TransformationUtils.setAlpha;

/**
 * Created by dell on 2017/6/14.
 */

public class TopCrop extends BitmapTransformation {

    private static final String ID = "com.bumptech.glide.load.resource.bitmap.TopCrop";
    private static final byte[] ID_BYTES = ID.getBytes(CHARSET);
    public TopCrop(Context context) {
        super(context);
    }

    @Override
    protected Bitmap transform(BitmapPool bitmapPool, Bitmap bitmap, int outWidth, int outHeight) {
        Bitmap toReuse = bitmapPool.get(outWidth, outHeight, bitmap.getConfig() != null?bitmap.getConfig(): Bitmap.Config.ARGB_8888);
        Bitmap transformed = topCrop(toReuse, bitmap, outWidth, outHeight);
        if(toReuse != null && toReuse != transformed) {
            toReuse.recycle();
        }
        return transformed;
    }

//    @Override
//    public String getId() {
//        return "TopCrop.com.bumptech.glide.load.resource.bitmap";
//    }
    /**
     *
     * @param recycled
     * @param toCrop
     * @param width
     * @param height
     * @return
     */
    public static Bitmap topCrop(Bitmap recycled, Bitmap toCrop, int width, int height){
        if(toCrop == null) {
            return null;
        } else if(toCrop.getWidth() == width && toCrop.getHeight() == height) {
            return toCrop;
        } else {
            float dx = 0.0F;
            float dy = 0.0F;
            Matrix m = new Matrix();
            float scale;
            //等价于if(dwidth / vwidth > dheight / vheight) 主要是用来判断宽高比的，就是说用来判断是图片的宽比较接近ImageView控件的宽还是图片的高比较接近ImageView控件的高
            if(toCrop.getWidth() * height > width * toCrop.getHeight()) {
                scale = (float)height / (float)toCrop.getHeight();
                dx = ((float)width - (float)toCrop.getWidth() * scale) * 0.5F;
            } else {
                scale = (float)width / (float)toCrop.getWidth();
                dy = ((float)height - (float)toCrop.getHeight() * scale) * 0.5F;
            }

            m.postScale(scale, scale,0,0);
//            m.postTranslate((float)((int)(dx + 0.5F)), (float)((int)(dy + 0.5F)));//实现平移
            Bitmap result;
            if(recycled != null) {
                result = recycled;
            } else {
                result = Bitmap.createBitmap(width, height, toCrop.getConfig() != null ? toCrop.getConfig(): Bitmap.Config.ARGB_8888);
            }

            setAlpha(toCrop, result);
            Canvas canvas = new Canvas(result);
            Paint paint = new Paint(6);
            canvas.drawBitmap(toCrop, m, paint);
            return result;
        }
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof CenterCrop;
    }

    @Override
    public int hashCode() {
        return ID.hashCode();
    }

    @Override
    public void updateDiskCacheKey(MessageDigest messageDigest) {
        messageDigest.update(ID_BYTES);
    }
}


```

this is centerCrop code
```
package com.bumptech.glide.load.resource.bitmap;

import android.content.Context;
import android.graphics.Bitmap;
import android.support.annotation.NonNull;
import com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool;
import java.security.MessageDigest;

/**
 * Scale the image so that either the width of the image matches the given width and the height of
 * the image is greater than the given height or vice versa, and then crop the larger dimension to
 * match the given dimension.
 *
 * Does not maintain the image's aspect ratio
 */
public class CenterCrop extends BitmapTransformation {
  private static final String ID = "com.bumptech.glide.load.resource.bitmap.CenterCrop";
  private static final byte[] ID_BYTES = ID.getBytes(CHARSET);

  public CenterCrop() {
    // Intentionally empty.
  }

  @Deprecated
  public CenterCrop(@SuppressWarnings("unused") Context context) {
    this();
  }

  @Deprecated
  public CenterCrop(@SuppressWarnings("unused") BitmapPool bitmapPool) {
    this();
  }

  // Bitmap doesn't implement equals, so == and .equals are equivalent here.
  @SuppressWarnings("PMD.CompareObjectsWithEquals")
  @Override
  protected Bitmap transform(
      @NonNull BitmapPool pool, @NonNull Bitmap toTransform, int outWidth, int outHeight) {
    return TransformationUtils.centerCrop(pool, toTransform, outWidth, outHeight);
  }

  @Override
  public boolean equals(Object o) {
    return o instanceof CenterCrop;
  }

  @Override
  public int hashCode() {
    return ID.hashCode();
  }

  @Override
  public void updateDiskCacheKey(MessageDigest messageDigest) {
    messageDigest.update(ID_BYTES);
  }
}

```

**Comment by yanxinmiao** [comment] 2017-08-21 02:48
thank you ,my problem is sloved .
the solution is override hashcode and equals method of Transformation .

**Comment by krrishnaaaa** [comment] 2018-11-16 09:34
@yanxinmiao could you please help me out with some code snippet. I am stuck  @there..

Thank You.
