### ISSUE TITLE
Images won't load for some URLs

### ISSUE THREAD

**Issue by KarajkoGabor** [bumptech/glide#1041] opened 2016-03-08 21:11 UTC
Hi guys,

First of all, thanks for the lib. It's very very handy and useful.

I found an issue about loading images from web. There are some URLs when I hit them with Glide then it didn't show the image. For example:

> http://2.bp.blogspot.com/_wOtGwObrPyI/SgbEunh78vI/AAAAAAAAAx4/UAk7SuQkUu8/s320/s%C3%BCt%C3%A9s+1146.jpg

The URL is UTF-8 encoded.

Usage of Glide:
```java
Glide.with(this.context).load(currentRecipe.getRecipeThumbnailUrl()).into(categoryIcon);
```

A part of the layout of the ImageView:
```xml
<ImageView
        android:id="@+id/categoryPic"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
```

Device: Xiaomi Redmi 1S
Android version: 4.4.4
Glide version: 3.7.0

**UPDATE**:

I found this entry in the console:
SkImageDecoder::Factory returned null

I've searched around but hadn't found any useful solution.

Thanks for any help! :)

**Comment by TWiStErRob** [comment] 2016-03-08 22:08
Possible duplicate of #867, and maybe related to #878.
It's possible that the Url encoding was a diversion, I couldn't get Glide to not accept that Uri:
```java
URL_BASE = "http://host.../path.../";
// original url, already url-encoded
URL_BASE + "s%C3%BCt%C3%A9s+1146.jpg", 
// raw url, nothing is escaped Glide receives "sütés"
Uri.decode(URL_BASE + "s%C3%BCt%C3%A9s+1146.jpg"),
// parse/url-decode the original url-encoded url and toString url-encodes it again
Uri.parse(URL_BASE + "s%C3%BCt%C3%A9s+1146.jpg").toString(),
// url-decoded url with ASCII text-encoding, utf-8 is not parsed properly
URL_BASE + "sĂĽtĂ©s+1146.jpg"
```
When you copied it, was it encoded? (e.g. Chrome displays the Unicode characters, but when you copy it it uses encoding.)

Try adding [logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) to see what's the error in your case. If it says `onResourceReady`, then ...

---

The more probable case is that your wrap-wrap XML doesn't play well with Glide. Try to change your layout to use at least one `match_parent` on one side, if you give context around that ImageView I can try to suggest different approaches.

**Comment by KarajkoGabor** [comment] 2016-03-09 20:08
Thanks for the fast answer :)

I got the URL encoded through Google Blogger API.

I've implemented the exception listener as you mentioned, here is what I got:
onException(null, http://2.bp.blogspot.com/_wOtGwObrPyI/SgbEunh78vI/AAAAAAAAAx4/UAk7SuQkUu8/s1600-h/s%C3%BCt%C3%A9s+1146.jpg, Target for: android.widget.ImageView{42bccd18 V.ED.... ......ID 0,74-0,74 #7f0e006f app:id/categoryPic}, true)

onResourceReady(com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable@429f7298, http://4.bp.blogspot.com/-zlCqi4iWQb8/Tk_iLyLnoVI/AAAAAAAAED4/egErzO8ARQ0/s1600/s%25C3%25BCti+4548.jpg, Target for: android.widget.ImageView{42bca6b0 V.ED.... ......ID 0,74-0,74 #7f0e006f app:id/categoryPic}, false, true)

...

What is strange to me is there are a lot of this kind of URLs and most of them are fine. For example this one loads fine : http://4.bp.blogspot.com/-zlCqi4iWQb8/Tk_iLyLnoVI/AAAAAAAAED4/egErzO8ARQ0/s1600/s%25C3%25BCti+4548.jpg
---
Also you mentioned the wrap_content in the ImageView. I've read somewhere else that Glide doesn't handle well the "double wrap_content" so I've tried several combinations but didn't got any luck. Btw here is my layout, maybe I missed something :)

`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:background="@drawable/selector"
    android:orientation="horizontal" >

    <ImageView
        android:id="@+id/categoryPic"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentLeft="true"
        android:layout_centerVertical="true"
        android:contentDescription="@string/imageString" />

    <TextView
        android:id="@+id/title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="10dip"
        android:layout_marginTop="10dip"
        android:layout_toRightOf="@+id/categoryPic"
        android:gravity="left|center"
        android:minHeight="?android:listPreferredItemHeight"
        android:textAppearance="?android:textAppearanceLarge"
        android:textColor="#ff040404"
        android:textStyle="bold" />
</RelativeLayout>`

**Comment by TWiStErRob** [comment] 2016-03-09 21:15
I found it! It's not the UTF-8 nor the url-encoding, though there's some weirdness going on here: compare `s%C3%BCt%C3%A9s` to `s%25C3%25BCti` and notice that the second one is double-escaped, the percent signs are encoded as `%25`. Strangely that's not the issue, the problem is the `-h` in the folder name. I downloaded both with and without `-h` with Total Commander and the `-h` is a HTML page referencing the image in an `<img`, while the other is the plain image. You can notice this in the browser too if you are perceptive to the page margin... also note that the original link you sent doesn't have that `-h` and has a different folder name, that's why it worked for me.

---

I also remembered what's wrong with double-wrapping the image view: Glide relies on the ImageView to provide dimensions for decoding, and wrap-wrap means "I don't care, I'll display anything", and Glide can't really do anything about that, there's a fallback to load a screen-sized image (see `SizeDeterminer#getSizeForParam`) which is wasteful. Since your title already defines the height you could use
```xml
		android:layout_width="?android:listPreferredItemHeight"
		android:layout_height="?android:listPreferredItemHeight"
``` 
on the ImageView so they are uniformly sized images. Add margin/padding as you see fit if it's too close to the edges. Alternatively you can leave it as double-wrapped and add an `.override()` call to your Glide load, based on some calculated value.

Also try out the tools namespace, it's really good for designing UIs in the IDE, if it looks good there, it should work on the phone:
```xml
<RelativeLayout xmlns:tools="http://schemas.android.com/tools" ...>
	<ImageView tools:src="@drawable/ic_launcher" ... />
	<TextView tools:text="Sample title for IDE" ... />
```

**Comment by KarajkoGabor** [comment] 2016-03-09 21:41
YES, you are right :) Where should I send the glorius beers? :beers:

Anyway, I started to go something like that way, I was very suspicious on the underscore at the beginning of the path.

And I promise I will try out the tools namespace sounds promising :)

Thanks again, I think this thread is closed from now.

**Comment by TWiStErRob** [comment] 2016-03-09 21:54
Great!
Re :beers: : holnap Szegeden leszek: http://www.meetup.com/I-Tech-Szeged-Meetup/events/228725178/

**Closed by TWiStErRob** 2016-03-09 21:54 UTC
Labels: question
