### ISSUE TITLE
StrictMode: resources leak (glide 4 with okhttp integration)

### ISSUE THREAD

**Issue by Happy-Neko** [bumptech/glide#2236] opened 2017-08-11 13:49 UTC
**Glide Version**: 4.0.0.
**Integration libraries**: okhttp3-integration

I am experiencing strict mode crashes both on emulator and real devices on Android versions from 4.2 to 7.1. Issue looks similar to now closed ticket #1996.

```Java
E/StrictMode: A resource was acquired at attached stack trace but never released.
See java.io.Closeable for information on avoiding resource leaks.
     java.lang.Throwable: Explicit termination method 'response.body().close()' not called
         at dalvik.system.CloseGuard.open(CloseGuard.java:184)
         at java.lang.reflect.Method.invokeNative(Native Method)
         at java.lang.reflect.Method.invoke(Method.java:525)
         at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:272)
         at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:138)
         at okhttp3.RealCall.captureCallStackTrace(RealCall.java:78)
         at okhttp3.RealCall.enqueue(RealCall.java:87)
         at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:45)
         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
         at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:252)
         at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
         at java.lang.Thread.run(Thread.java:841)
         at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
```
This happens a lot when fast-scrolling recycler view.
My RecyclerView.Adapter is simple:

```Java
final GlideRequests glideRequests = GlideApp.with(fragment);
// glideRequests is instance variable of adapter

@Override
public void onBindViewHolder(final ProductViewHolder holder, final int position) {
    glideRequests.asBitmap()
                 .priority(Priority.NORMAL)
                 .diskCacheStrategy(DiskCacheStrategy.ALL)
                 .centerCrop()
                 .thumbnail(0.25f)
                 .placeholder(R.drawable.placeholder)
                 .load(product)
                 .into(holder.cover);
}

@Override
public void onViewRecycled(final ProductViewHolder holder) {
     super.onViewRecycled(holder);
     glideRequests.clear(holder.cover);
}
```

**Comment by rubengees** [comment] 2017-08-11 13:57
I am also still experiencing this from time to time. The load lines and other config is like in my original ticket (#1996).

**Comment by sjudd** [comment] 2017-09-06 14:23
Duplicate of  #1996

**Closed by sjudd** 2017-09-06 14:23 UTC
