### ISSUE TITLE
java.io.FileNotFoundException: No content provider: https:***

### ISSUE THREAD

**Issue by Liberations** [bumptech/glide#3316] opened 2018-09-13 08:57 UTC
**Glide Version**:
 glide_version = '4.7.1'

**Integration libraries**:
 retrofit_version = '2.4.0'
    rxjava = '2.2.0'
    rxandroid = '2.0.2'

**Device/Android Version**:
all

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
only Glide.with(imageView.getContext()).load(url).into(imageView);
```

**Layout XML**:
```xml
val imageView = ImageView (this)
                val params = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,
                        LinearLayout.LayoutParams.WRAP_CONTENT)
                imageView.layoutParams = params
                ImageLoader.load(imageView, getRealUrl(it))
                ll_detail_activity_detail.addView(imageView)
```

**Stack trace / LogCat**:
```ruby
09-13 16:51:12.801 15465-15465/com.zhiguan.rebate W/Glide: Load failed for https://img.alicdn.com/imgextra/i4/2036357896/TB2GhVnwZtnpuFjSZFKXXalFFXa_!!2036357896.jpg with size [1008x1920]
                                                           class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                           There were 2 causes:
                                                           java.io.FileNotFoundException(https://img.alicdn.com/imgextra/i4/2036357896/TB2GhVnwZtnpuFjSZFKXXalFFXa_!!2036357896.jpg)
                                                           java.io.FileNotFoundException(No content provider: https://img.alicdn.com/imgextra/i4/2036357896/TB2GhVnwZtnpuFjSZFKXXalFFXa_!!2036357896.jpg)
                                                            call GlideException#logRootCauses(String) for more detail
                                                             Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
                                                           There was 1 cause:
                                                           java.io.FileNotFoundException(https://img.alicdn.com/imgextra/i4/2036357896/TB2GhVnwZtnpuFjSZFKXXalFFXa_!!2036357896.jpg)
                                                            call GlideException#logRootCauses(String) for more detail
                                                               Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                                           There was 1 cause:
                                                           java.io.FileNotFoundException(https://img.alicdn.com/imgextra/i4/2036357896/TB2GhVnwZtnpuFjSZFKXXalFFXa_!!2036357896.jpg)
                                                            call GlideException#logRootCauses(String) for more detail
                                                                 Cause (1 of 1): class java.io.FileNotFoundException: https://img.alicdn.com/imgextra/i4/2036357896/TB2GhVnwZtnpuFjSZFKXXalFFXa_!!2036357896.jpg
                                                             Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL
                                                           There was 1 cause:
                                                           java.io.FileNotFoundException(No content provider: https://img.alicdn.com/imgextra/i4/2036357896/TB2GhVnwZtnpuFjSZFKXXalFFXa_!!2036357896.jpg)
                                                            call GlideException#logRootCauses(String) for more detail
                                                               Cause (1 of 1): class java.io.FileNotFoundException: No content provider: https://img.alicdn.com/imgextra/i4/2036357896/TB2GhVnwZtnpuFjSZFKXXalFFXa_!!2036357896.jpg
09-13 16:51:12.802 15465-15465/com.zhiguan.rebate I/Glide: Root cause (1 of 2)
                                                           java.io.FileNotFoundException: https://img.alicdn.com/imgextra/i4/2036357896/TB2GhVnwZtnpuFjSZFKXXalFFXa_!!2036357896.jpg
                                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
                                                               at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                               at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                                                               at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
                                                               at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:150)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:144)
                                                               at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
                                                               at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                               at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
                                                               at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
                                                               at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                               at java.lang.Thread.run(Thread.java:761)
                                                               at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
09-13 16:51:12.803 15465-15465/com.zhiguan.rebate I/Glide: Root cause (2 of 2)
                                                           java.io.FileNotFoundException: No content provider: https://img.alicdn.com/imgextra/i4/2036357896/TB2GhVnwZtnpuFjSZFKXXalFFXa_!!2036357896.jpg
                                                               at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1135)
                                                               at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:986)
                                                               at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:909)
                                                               at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
                                                               at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
                                                               at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                                                               at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                               at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
                                                               at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:397)
                                                               at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailed(SourceGenerator.java:119)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:153)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:144)
                                                               at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:150)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:144)
                                                               at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
                                                               at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
                                                               at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                               at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
                                                               at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
                                                               at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                               at java.lang.Thread.run(Thread.java:761)
                                                               at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Comment by sjudd** [comment] 2018-09-14 16:33
Duplicate of #2894

**Closed by sjudd** 2018-09-14 16:33 UTC
