### ISSUE TITLE
Dependencies can NOT be found in Jcenter

### ISSUE THREAD

**Issue by googolmo** [bumptech/glide#2304] opened 2017-08-30 07:55 UTC
I can't download glide from jcenter, and there is no glide version 4 in jcenter.
Follow this link https://jcenter.bintray.com/com/github/bumptech/glide/glide/

**Comment by sjudd** [comment] 2017-08-31 14:21
I've never actually uploaded anything to jcenter. I've only ever uploaded to maven central. I was assuming jcenter was copying new versions over from maven central, but either that's stopped or I was incorrect.

It's kind of a pain to change the way uploads work. Is there some reason why you don't want to download from maven central?

**Comment by googolmo** [comment] 2017-09-01 03:16
@sjudd Sometimes maven central's server is very slow for my network.
In my option you can upload it to bintray and it can be sync to maven central.

**Comment by sjudd** [comment] 2017-10-07 06:06
Duplicate of #544

**Closed by sjudd** 2017-10-07 06:06 UTC
Labels: enhancement, non-library
