### ISSUE TITLE
Why is the picture like this?

### ISSUE THREAD

**Issue by Silnt** [bumptech/glide#2345] opened 2017-09-07 02:52 UTC
![image](https://user-images.githubusercontent.com/21040178/30143749-047667b4-93ba-11e7-9a38-eb04272e314d.png)
![image](https://user-images.githubusercontent.com/21040178/30143758-172ab068-93ba-11e7-8d67-0001dc037ae4.png)

![image](https://user-images.githubusercontent.com/21040178/30143844-61dd13e4-93ba-11e7-98bd-9f714d0307fe.png)

Is there anything wrong with my code?
Why is the picture like this?

**Comment by sjudd** [comment] 2017-09-07 04:24
What version of Glide are you using? Is this on a particular device or version of Android, or do you see this on multiple?

Have you tried it without the RoundedCorners transform?

**Comment by Silnt** [comment] 2017-09-07 04:42
compile 'com.github.bumptech.glide:glide:4.0.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'

**Comment by Silnt** [comment] 2017-09-07 04:46
Not using RoundedCorners normal

**Comment by Silnt** [comment] 2017-09-07 04:47
Not using RoundedCorners normal
![image](https://user-images.githubusercontent.com/21040178/30146434-a5d0db34-93ca-11e7-8f6d-76869492baca.png)

**Comment by Silnt** [comment] 2017-09-07 04:47
![image](https://user-images.githubusercontent.com/21040178/30146439-aeabcfde-93ca-11e7-9331-0a4ad557defa.png)

**Comment by Silnt** [comment] 2017-09-07 04:49
![image](https://user-images.githubusercontent.com/21040178/30146458-d351f4da-93ca-11e7-91dc-13a4bb7008ba.png)
![image](https://user-images.githubusercontent.com/21040178/30146465-d78973ac-93ca-11e7-872e-16ba86b3f881.png)

**Comment by sjudd** [comment] 2017-09-07 05:18
For the errors above, see #2347.

For rounded corners, if you can take a look at the code and send a pull request to fix the issue I'd definitely welcome the contribution: https://github.com/bumptech/glide/blob/35c28c28ca2a030e90df5aac67b0356c769cd623/library/src/main/java/com/bumptech/glide/load/resource/bitmap/TransformationUtils.java#L388

**Comment by Silnt** [comment] 2017-09-07 08:01
![image](https://user-images.githubusercontent.com/21040178/30152461-c197ee00-93e5-11e7-9df1-cd18965b55ae.png)

This problem is related to the order in which code is invoked

**Comment by Tolriq** [comment] 2017-09-07 10:10
@Silnt As a side note you should never (I mean really never) use findViewById like that in the bindView this is a slow call and you are doing it every time totally loosing the interest of viewholders.

Your viewholder should have a field that resolve this imageview on creation then use it in the bind. You'll see major performance gain.

**Comment by Silnt** [comment] 2017-09-08 01:43
@Tolriq Thank you.

**Comment by sjudd** [comment] 2017-09-12 05:54
@Silnt 
``centerCrop()`` in your example above is completely overridden by ``.transform(new RoundedCorners(15))``.

In Glide v4 transformations are not additive, they replace the previous transformation. To apply multiple transformations, see: http://bumptech.github.io/glide/doc/transformations.html#multiple-transformations

**Comment by AllenMeex** [comment] 2017-10-11 09:34
I have the same problem with Glide4.2.0

**Comment by sjudd** [comment] 2017-10-11 14:29
I'm not able to reproduce this. If you are, can you let me know what device and version of Android you're using, and consider attaching a sample app that reproduces the bug?

**Comment by sjudd** [comment] 2017-10-13 00:00
There's more information and a sample app in #2472, so let's mark this a duplicate of #2472

**Closed by sjudd** 2017-10-13 00:00 UTC
Labels: bug, repro-needed
