### ISSUE TITLE
Failed To load Webp animated Image into Imageview

### ISSUE THREAD

**Issue by varun7952** [bumptech/glide#2624] opened 2017-11-22 01:50 UTC
Glide Version 4.3.1
Device Nexus 5
 Trying to load webp Image via Glide 

` Glide.with(getActivity()).load("https://media0.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/200_d.webp ").into(holder.imageView);`

Log cat
` W/Glide: Load failed for https://media0.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/200_d.webp with size [300x390]
                                                                      class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, https://media0.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/200_d.webp
                                                                          Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                                          Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                                          Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                                        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, https://media0.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/200_d.webp
                                                                          Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                                          Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                                          Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                                        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, REMOTE, https://media0.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/200_d.webp
                                                                          Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                                            Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                          Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
                                                                            Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
11-22 07:11:35.686 13390-13390/com.example.com.pro_working1 I/Glide: Root cause (1 of 2)
                                                                      java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                          at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:133)
                                                                          at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:24)
                                                                          at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
                                                                          at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
                                                                          at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
                                                                          at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                                          at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:494)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:466)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:452)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:406)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                          at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:74)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:414)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                          at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:74)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:414)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                          at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:69)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                          at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
                                                                       Caused by: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                          at android.media.MediaMetadataRetriever.setDataSource(Native Method)
                                                                          at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:144)
                                                                          at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:123)
                                                                          at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:24) 
                                                                          at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67) 
                                                                          at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52) 
                                                                          at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43) 
                                                                          at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56) 
                                                                          at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:494) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:466) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:452) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:406) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
                                                                          at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:74) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:414) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
                                                                          at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:74) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:414) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
                                                                          at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:69) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                          at java.lang.Thread.run(Thread.java:818) 
                                                                          at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413) 
11-22 07:11:35.688 13390-13390/com.example.com.pro_working1 I/Glide: Root cause (2 of 2)
                                                                      java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                          at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:133)
                                                                          at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:24)
                                                                          at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:45)
                                                                          at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
                                                                          at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
                                                                          at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
                                                                          at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                                          at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:494)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:466)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:452)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:406)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                          at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:74)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:414)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                          at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:74)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:414)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                          at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:69)
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                          at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
                                                                       Caused by: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                          at android.media.MediaMetadataRetriever.setDataSource(Native Method)
                                                                          at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:144)
                                                                          at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:123)
                                                                          at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:24) 
                                                                          at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:45) 
                                                                          at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67) 
                                                                          at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52) 
                                                                          at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43) 
                                                                          at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56) 
                                                                          at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:494) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:466) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:452) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:406) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
                                                                          at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:74) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:414) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
                                                                          at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:74) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:414) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
                                                                          at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:69) 
                                                                          at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
                                                                          at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268) 
                                                                          at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                          at java.lang.Thread.run(Thread.java:818) 
                                                                          at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413) `

**Comment by sjudd** [comment] 2017-11-22 02:19
Duplicate of #571

**Closed by sjudd** 2017-11-22 02:19 UTC
