### ISSUE TITLE
regist too many Broadcast Receivers  Bug fix is error

### ISSUE THREAD

**Issue by moon2009** [bumptech/glide#4573] opened 2021-06-01 04:06 UTC
Error info
.......
Caused by: java.lang.IllegalArgumentException: regist too many Broadcast Receivers
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1838)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1794)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1788)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:489)
	at com.bumptech.glide.manager.DefaultConnectivityMonitor.register(DefaultConnectivityMonitor.java:60)
	at com.bumptech.glide.manager.DefaultConnectivityMonitor.onStart(DefaultConnectivityMonitor.java:106)
	at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:51)
............

**IllegalArgumentException**.java
```
class IllegalArgumentException extends RuntimeException {
..........
}

```
Glide version :4.12.0 
```
DefaultConnectivityMonitor.java
........
  private void register() {
    if (isRegistered) {
      return;
    }

    // Initialize isConnected.
    isConnected = isConnected(context);
    try {
      // See #1405
      context.registerReceiver(
          connectivityReceiver, new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));
      isRegistered = true;
    } catch (SecurityException e) {
      // See #1417, registering the receiver can throw SecurityException.
      if (Log.isLoggable(TAG, Log.WARN)) {
        Log.w(TAG, "Failed to register", e);
      }
    }
  }
.......
```
**SecurityException**.java
```
public class SecurityException extends RuntimeException {
......
}

```
you can change code like this
```
   try {
      // See #1405
      context.registerReceiver(
          connectivityReceiver, new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));
      isRegistered = true;
    } catch (RuntimeException e) {
      // See #1417, registering the receiver can throw SecurityException.
      if (Log.isLoggable(TAG, Log.WARN)) {
        Log.w(TAG, "Failed to register", e);
      }
    }
```
or 
```
    try {
      // See #1405
      context.registerReceiver(
          connectivityReceiver, new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));
      isRegistered = true;
    } catch (SecurityException e) {
        ........
    } catch (IllegalArgumentException e) {
       ............
    }
```

**Comment by sjudd** [comment] 2022-02-08 17:29
Duplicate of https://github.com/bumptech/glide/issues/1161

**Closed by sjudd** 2022-02-08 17:29 UTC
