### ISSUE TITLE
how to use glide in library

### ISSUE THREAD

**Issue by mohamadk** [bumptech/glide#2404] opened 2017-09-17 05:00 UTC
I want to use glide in a library and in my application.      
I know that I have to extends my glide module in the library from "LibraryGlideModule" but when I use that and build my library project this classes not generated "GlideRequest, GlideApp" . is there any example of using LibraryGlideModule in glide 4.x?
thanks.

**Comment by sjudd** [comment] 2017-09-18 14:00
Duplicate of #2393

**Closed by sjudd** 2017-09-18 14:00 UTC
