### ISSUE TITLE
Glide still depends on Support Libs so Jetifier Cannot be Turned Off

### ISSUE THREAD

**Issue by eygraber** [bumptech/glide#3788] opened 2019-07-28 03:52 UTC
According to https://github.com/plnice/can-i-drop-jetifier, Glide still references support libs and Jetifier cannot be turned off.

```
* com.github.bumptech.glide:glide:4.9.0
  \-- com.android.support:support-fragment:27.1.1
  \-- com.android.support:animated-vector-drawable:27.1.1
  \-- com.github.bumptech.glide:gifdecoder:4.9.0
   \-- com.android.support:support-annotations:27.1.1
```

**Comment by sjudd** [comment] 2019-08-01 15:16
Duplicate of #3184

**Closed by sjudd** 2019-08-01 15:16 UTC

**Comment by ZakTaccardi** [comment] 2019-08-05 19:52
@sjudd seems to me that this needs to be re-opened?

**Comment by TWiStErRob** [comment] 2019-08-11 17:04
@ZakTaccardi https://github.com/bumptech/glide/pull/3678/files?file-filters%5B%5D=.gradle#diff-0d1d9100a9b6813b8cb5c470bf313d00

AndroidX support is already merged and 4.10-SNAPSHOT should contain no support libs. Why are you suggesting to reopen?

**Comment by ZakTaccardi** [comment] 2019-08-15 16:00
I misread the issue - I thought it was referencing the 4.10 snapshot.

Hoping for a 4.10 release soon!
