### ISSUE TITLE
Glide shows greenish image

### ISSUE THREAD

**Issue by dementrock** [bumptech/glide#515] opened 2015-06-30 19:24 UTC
This is the original image:
![9k_](https://cloud.githubusercontent.com/assets/784063/8439742/bbe02ae8-1f22-11e5-8676-c7a1d525782d.jpg)

This is the image rendered using Glide and ImageView:
![screen shot 2015-06-30 at 12 16 04 pm]
(https://cloud.githubusercontent.com/assets/784063/8439751/cd1b0864-1f22-11e5-96c8-f3ee83b75f72.png)

I'm already using the ARGB_8888 option with the following initialization code:

```java
new GlideBuilder(this).setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
```

Switching to Picasso does seem to resolve the problem. What might be wrong here?

**Comment by sjudd** [comment] 2015-06-30 20:46
It might be JPEG compression artifacts. Try [``DiskCacheStrategy.SOURCE``][1] to avoid re-compression. I'd also be curious if you can reproduce this in a sample app by just compressing the Bitmap to a byte array using ``Bitmap.compress`` and then decoding it again with ``BitmapFactory``. 

[1]: http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/load/engine/DiskCacheStrategy.html#SOURCE

**Comment by sjudd** [comment] 2015-07-03 05:19
This looks like a duplicate of #305 and number #521 may also provide some additional help. Let us know if that doesn't fix the issue.

**Closed by sjudd** 2015-07-03 05:19 UTC

**Comment by YancyCool** [comment] 2015-07-14 06:25
I have the same issue,and now it's works perfect by adding diskCacheStrategy(DiskCacheStrategy.SOURCE)，thank you sjudd

**Comment by TWiStErRob** [comment] 2015-10-05 16:27
Crosslink: http://stackoverflow.com/q/31146685/253468
