### ISSUE TITLE
DrawableRequestBuilder#override works incorrectly for a custom target

### ISSUE THREAD

**Issue by floating-cat** [bumptech/glide#441] opened 2015-04-26 15:20 UTC
**Glide Version/Integration library (if any)**: 3.5.2
**Device/Android Version**: Android 5.0.2
**Issue details/Repro steps**:
The `DrawableRequestBuilder#override` works well if I use `DrawableRequestBuilder#into(ImageView)` without a custom target.
But If I use custom target (like `SimpleTarget` or `ViewTarget`) with `DrawableRequestBuilder#override`, the result resource's height and width looks incorrectly.
**Glide load line**:
```
// a large image (720x6347)
Glide.with(getActivity())
    .load(mUrl)
    .override(20,20)
    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
    // .into(new SimpleTarget<GlideDrawable>(20, 20) { behaves the same as #override
    .into(new SimpleTarget<GlideDrawable>() {
        @Override
        public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
            Log.d(TAG, String.valueOf(resource.getIntrinsicHeight()));
            Log.d(TAG, String.valueOf(resource.getIntrinsicWidth()));
            ((ImageView) view.findViewById(R.id.picture)).setImageDrawable(resource);
        }
    });
```

**Stack trace**:
```
04-26 23:04:30.702    3811-3811/com.example.app D/GalleryFragment﹕ 198
04-26 23:04:30.702    3811-3811/com.example.app D/GalleryFragment﹕ 22
```

**Comment by sjudd** [comment] 2015-04-26 18:29
This looks working as intended. Is the actual Bitmap that's loaded into a view any different than the size you've logged above? I'd guess they're actually identical?

By default Glide just downsamples so the smallest edge of the image you provide is between the requested size and 2x the requested size, maintaining the original aspect ratio. That's what appears to be happening here. If you want a more exact size, use ``fitCenter()`` or ``centerCrop()``, or a custom Transformation.

**Comment by sjudd** [comment] 2015-04-26 20:06
Since I'm pretty sure this is WAI, I'm going to close this for now. Definitely let me know if I'm missing something or if you still have questions.

**Closed by sjudd** 2015-04-26 20:06 UTC

**Comment by floating-cat** [comment] 2015-04-27 01:45
Thanks, I have seen `Downsampler` just now.
