### ISSUE TITLE
App Crash in StrictMode

### ISSUE THREAD

**Issue by SureshSc** [bumptech/glide#2326] opened 2017-09-04 08:36 UTC
**I am using Glide in my app to display the images (like photo app), when i do the lazy loading of images from server my app is getting crash.**

Pls find the crash log

`E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                          java.lang.Throwable: Explicit termination method 'close' not called
                                                              at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                              at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:103)
                                                              at java.net.Socket.createImpl(Socket.java:451)
                                                              at java.net.Socket.getImpl(Socket.java:517)
                                                              at java.net.Socket.setSoTimeout(Socket.java:1108)
                                                              at com.android.okhttp.Connection.connectSocket(Connection.java:195)
                                                              at com.android.okhttp.Connection.connect(Connection.java:172)
                                                              at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                                                              at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:101)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:53)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:95)
                                                              at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:252)
                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                              at java.lang.Thread.run(Thread.java:761)
                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)`

**Comment by sjudd** [comment] 2017-09-06 14:23
Duplicate of  #1996

**Closed by sjudd** 2017-09-06 14:23 UTC
