### ISSUE TITLE
Error:Module 'com.github.bumptech.glide:glide:4.4.0' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by ncworm** [bumptech/glide#2769] opened 2017-12-29 09:13 UTC
Error:Module 'com.github.bumptech.glide:glide:4.4.0' depends on one or more Android Libraries but is a jar

**Comment by ncworm** [comment] 2017-12-29 09:14
compile 'com.github.bumptech.glide:glide:4.4.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'

    repositories {
        jcenter()
        maven {
            url "http://repo.baichuan-android.taobao.com/content/groups/BaichuanRepositories/"
        }
        maven { url "https://jitpack.io" }
        mavenCentral()
        maven { url "https://maven.google.com"}
//        maven { url "https://dl.google.com/dl/android/maven2/"}
    }
}

**Comment by sjudd** [comment] 2017-12-29 20:57
Duplicate of #2318

**Closed by sjudd** 2017-12-29 20:57 UTC
