### ISSUE TITLE
RoundedCorner Transform not work perfectly with fitCenter (API level 17)

### ISSUE THREAD

**Issue by kenneth2008** [bumptech/glide#2315] opened 2017-09-01 09:56 UTC
With Glide 4.0, the RequestOptions seems affected by ordering in API level 17.
It makes rounded corners cannot exist with fitCenter at the same time.
The following code will have a perfect scaled image but no rounded corner.
(Work perfectly on other version.)

```
RequestOptions options = new RequestOptions();
options.transform(roundedCorners);
options.fitCenter();
```

**Comment by Tolriq** [comment] 2017-09-01 11:01
See documentation http://bumptech.github.io/glide/doc/transformations.html#multiple-transformations you need to use MultiTransformation

**Comment by sjudd** [comment] 2017-09-01 13:57
Duplicate of #2314

**Closed by sjudd** 2017-09-01 13:57 UTC
Labels: question
