### ISSUE TITLE
Image display exception when call transforms(new fitcenter(), new RoundedCorners(10)) 

### ISSUE THREAD

**Issue by yxcSini** [bumptech/glide#2511] opened 2017-10-24 07:41 UTC
**Glide Version**: 4.2

**Integration libraries**:OkHttp3 

**Device/Android Version**:all

**Issue details / Repro steps / Use case background**: 
image display: http://chuantu.biz/t6/110/1508830598x3708062762.png

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(this)
        .load(url)
        .transforms(new FitCenter(),new RoundedCorners(10))
        .into(iv);
```

**Comment by TWiStErRob** [comment] 2017-10-24 09:31
Looks like it's already fixed in https://github.com/bumptech/glide/commit/0b5d1bc127d5188fa2744848c4c4815166501dcc

Duplicate of #2472

**Closed by TWiStErRob** 2017-10-24 09:31 UTC
