### ISSUE TITLE
Imageview automatically zooming

### ISSUE THREAD

**Issue by karun2189** [bumptech/glide#656] opened 2015-09-28 12:39 UTC
If i am setting image to imageview from path image view is automatically zooming, can you tell me why this happen? My code is 
```java
Glide.clear(imageView);
Glide.with(mContext)
    .load(path)
    .asBitmap()
//                .animate(R.anim.activity_fade_in)
//                .dontAnimate()
//                .centerCrop()
    .signature(new StringSignature(noteGroup.getLastModifiedDate().toString()))
    .placeholder(bitmapDrawable)
    .skipMemoryCache(false)
    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
    .override(width, height)
```

**Comment by TWiStErRob** [comment] 2015-09-28 12:42
Possible duplicate of #363 if your placeholder is different aspect than your images.
Also default anim: crossFade and default transformation: fitCenter (if you didn't say otherwise in XML).
Please use the [template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues) in the future.

**Comment by karun2189** [comment] 2015-09-28 13:06
If i want to change placeholder size how can i achieve this?

**Comment by TWiStErRob** [comment] 2015-09-28 13:07
Change the drawable or at least its intrinsic size.

**Comment by karun2189** [comment] 2015-09-28 13:21
If i am update same imageview old image is displayed at that time how can i clear?

**Comment by TWiStErRob** [comment] 2015-09-28 13:33
But you have a clear there. What is `bitmapDrawable`? If that's the previous image and you use it as a placeholder, the the load probably failed, because then it leaves the placeholder. Add a listener and log in both methods.

**Comment by karun2189** [comment] 2015-09-28 13:42
"bitmapDrawable" is my own BitmapDrawable. I am getting bitmap from cache and then convert into drawable and set it.. If the bitmap is not available then i will set the custom drawable to placeholder

**Comment by TWiStErRob** [comment] 2015-09-28 16:02
Try with a listener to see what's going on.

*Tip: In case that cache is Glide cache, you can also try `.thumbnail()` to do "I am getting bitmap from cache and then convert into drawable and set it.", because it accepts another Glide load.*

**Comment by sjudd** [comment] 2015-09-30 16:04
Let us know if you need further input, I'm definitely inclined to say this is a dupe of #363

**Closed by sjudd** 2015-09-30 16:04 UTC
Labels: question
