### ISSUE TITLE
Animation gif performance on Android 6.0

### ISSUE THREAD

**Issue by matsuhiro** [bumptech/glide#2566] opened 2017-11-06 10:26 UTC
I ran giphy of glide version 4.3.0 on Android 6.0.
It seems that animation gif performance is slow on only Android 6.0.
I check on Android 4.4 and Android 7.0, then it seems that animation performance is good.
Is there some option to improve performance of animation of gif ?

**Comment by sjudd** [comment] 2017-11-06 15:11
Duplicate of #2471.

I don't have any immediate ideas on why GIFs would be worse on specific versions of Android, though it's possible the hardware you're comparing with is less capable on 6.0. Follow (or update) the duplicate issue.

**Closed by sjudd** 2017-11-06 15:11 UTC
