### ISSUE TITLE
Image background showing green/white 

### ISSUE THREAD

**Issue by raamkum** [bumptech/glide#817] opened 2015-12-14 21:06 UTC
I am trying to view image using Glide Library for some reason the background is coming up green/white.. I am checked the image URL the background is transparent. First time the images show up properly but when I open the APP again the images have green/white background. I am not sure why this is happening could be a bug?

Here are the code:

activityadapter.xml:

```xml
<RelativeLayout
    android:id="@+id/abcd"
    android:layout_width="120dp"
    android:layout_height="120dp"
    android:layout_centerHorizontal="true"
    android:gravity="center_vertical">

    <ImageView
        android:id="@+id/grid_item_image"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_centerInParent="true"
        tools:ignore="ContentDescription" />
</RelativeLayout>
```

activityAdapter.java: Put all the images inside listview:
Has glide details from aDapter:

```java
Glide.with(DetailActivity.this)
    .load(pd.getImage())
    .diskCacheStrategy(DiskCacheStrategy.ALL)
    .fitCenter()
    .dontTransform()
    .crossFade()
    .into(imageProduct);
```

Screenshot:

Check the black marks: They have green background - It should be transparent which happens the first time it loads.

![imageview](https://cloud.githubusercontent.com/assets/5735928/11793873/e8e53bc8-a262-11e5-928b-adae675d9cec.png)

Is this a bug or am I doing something wrong?

**Comment by TWiStErRob** [comment] 2015-12-14 21:15
Looks like exact duplicate of #515. Sam explained it best here: https://github.com/bumptech/glide/issues/305#issuecomment-112937571

I'm going to close this as a duplicate, but feel free to ask followup questions here.

**Closed by TWiStErRob** 2015-12-14 21:15 UTC
Labels: duplicate, question
