### ISSUE TITLE
Some Error about WebP

### ISSUE THREAD

**Issue by Juanjuanquanliu** [bumptech/glide#5291] opened 2023-09-23 14:05 UTC
**Glide Version**: 4.8.0

**Issue details / Repro steps / Use case background**: 

there has an Error about libwebp, I want to ask if this error affect glide to load image type WebP
https://github.com/webmproject/libwebp/commit/a486d800b60d0af4cc0836bf7ed8f21e12974129

**Comment by sjudd** [comment] 2023-09-26 04:31
Duplicate of #5280?

**Closed by sjudd** 2023-09-26 04:31 UTC
