### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by lepicekmichal** [bumptech/glide#3506] opened 2019-01-29 14:36 UTC
Is there any movement on complete migration to AndroidX? So I could turn off jetifier.

**Comment by alisonthemonster** [comment] 2019-02-06 07:02
Having problems with `GeneratedAppGlideModuleImpl` because of this, would love an update!

**Comment by sjudd** [comment] 2019-02-07 01:47
Duplicate of #3184

**Closed by sjudd** 2019-02-07 01:47 UTC
