### ISSUE TITLE
warning: Key com.sec.android.multiwindow.MINIMUM_SIZE_H expected String but value was a java.lang.Integer

### ISSUE THREAD

**Issue by gonemad** [bumptech/glide#324] opened 2015-01-29 04:14 UTC
I just updated to 3.5 and im getting a warning when i start my application.  My manifest sets the dimensions like so:

 <meta-data
            android:name="com.sec.android.support.multiwindow"
            android:value="true" />
        <meta-data
            android:name="com.sec.android.multiwindow.DEFAULT_SIZE_W"
            android:resource="@dimen/app_defaultsize_w" />
        <meta-data
            android:name="com.sec.android.multiwindow.DEFAULT_SIZE_H"
            android:resource="@dimen/app_defaultsize_h" />
        <meta-data
            android:name="com.sec.android.multiwindow.MINIMUM_SIZE_W"
            android:resource="@dimen/app_minimumsize_w" />
        <meta-data
            android:name="com.sec.android.multiwindow.MINIMUM_SIZE_H"
            android:resource="@dimen/app_minimumsize_h" />

Exception
01-28 23:09:37.913    2076-2076/gonemad.gmmp W/Bundle﹕ Key com.sec.android.multiwindow.MINIMUM_SIZE_H expected String but value was a java.lang.Integer.  The default value <null> was returned.
01-28 23:09:37.923    2076-2076/gonemad.gmmp W/Bundle﹕ Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
            at android.os.Bundle.getString(Bundle.java:1121)
            at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:29)
            at com.bumptech.glide.Glide.get(Glide.java:151)

**Comment by sjudd** [comment] 2015-01-29 04:18
Thanks for the report, this is a duplicate of #314.

**Closed by sjudd** 2015-01-29 04:18 UTC
