### ISSUE TITLE
GlideApp not generated

### ISSUE THREAD

**Issue by rodly** [bumptech/glide#2250] opened 2017-08-15 23:52 UTC
Hello, I'm trying to update from v3 to v4 and am running into an issue where GlideApp is not being generated.

I have followed the instructions located here http://bumptech.github.io/glide/doc/configuration.html and confirmed with a coworker that my implementation looks correct. We only have one AppGlideModule, I did override manifest parsing and return false, and my glide module is in Java (I originally had it in kotlin but `kapt` was giving me trouble, so I'm just using `annotationProcessor` instead and converted the file to Java. It's a very simple module as follows:

```java
@GlideModule
public class MyGlideModule extends AppGlideModule {

    @Inject
    @Named(DEFAULT)
    OkHttpClient client;

    public MyGlideModule() {
        MyApplication.getNetworkComponent().inject(this);
    }

    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        super.applyOptions(context, builder);
        builder.setDefaultRequestOptions(
                new RequestOptions().format(DecodeFormat.PREFER_ARGB_8888)
        );
    }

    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        super.registerComponents(context, glide, registry);
        registry.replace(
                GlideUrl.class,
                InputStream.class,
                new OkHttpProgressUrlLoader.Factory(client)
        );
    }

}
```

I don't see any errors pertaining to Glide and I can fully build (clean + build too) but I don't have any generated GlideApp and thus, my module is not being used to replace one of the components as you can see.

**Glide Version**: 4.0.0

**Integration libraries**: glide-okhttp3-integration-4.0.0

**Device/Android Version**: N/A

**Issue details / Repro steps / Use case background**: Noted Above

I was able to generate a GlideApp in a small sample project so I'm curious if anyone has any guesses as to why it's not working in a larger project.

**Comment by sjudd** [comment] 2017-08-15 23:58
Duplicate of #1939.

If you find something not mentioned in those issues that should be fixed on our end, please open a new issue with the request.

**Closed by sjudd** 2017-08-15 23:58 UTC

**Comment by rodly** [comment] 2017-08-16 18:44
@sjudd I've reviewed every issue pertaining to GlideApp not being generated. Most of the people didn't follow the instructions located here http://bumptech.github.io/glide/doc/configuration.html under Applications.

I'm not seeing any Glide errors in the gradle console or logcat so I'm honestly quite baffled. My application builds and runs fine but it's not using my glide module.

Is there another area I can find errors that can help me solve this problem?

**Comment by yweiquan** [comment] 2017-08-22 03:49
I ran into the same issue，followed all the instructions in Glide Doc, but still no GlideApp generated. 

It all because I put this dependencies in my submodule, not in app module.

``` 
annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'" 
```

Now,  GlideApp is generated.  Add this annotationProcessor in your app/build.gradle dependencies.

@rodly Hope it may helps you.

**Comment by dreinoso** [comment] 2019-09-25 05:06
For me solving this was run in terminal:

gradle assemble --stacktrace

and solve issues not related with Glide
