### ISSUE TITLE
Why .crossfade() is not available when we get image asBitmap()

### ISSUE THREAD

**Issue by manjunathc23** [bumptech/glide#903] opened 2016-01-19 05:40 UTC
Question : Is there any way we can `.crossFade()` image when we load image as  `.asBitmap()`?

```
            Glide.with(getContext())
                    .load(url)
                    .asBitmap()
                    .crossFade() --> Not possible. 
                    .into(imageView);
```
Or do we need to customize the animate ?

```
            Glide.with(imageView.getContext())
                    .load(url)
                    .animate("do something here") // TODO
                    .into(imageView);

```
Just curious why we lose `.crossFade()` when we load `.asBitmap()`?

Thanks!
Manju

**Comment by TWiStErRob** [comment] 2016-01-19 09:23
Duplicate of #840 (this time I'm sure ;)
Please subscribe to that issue (right column), as it may get included in a future version. Also see #605 for more discussion.

As to the why, the answer is simple: we call `image.setImageBitmap` which cannot receive a `TransitionDrawable` and the Animat-something interface has `Bitmap` as generic args with `asBitmap` which hides the potential of the worlaround I figured out.

**Closed** 2016-01-19 09:23 UTC
Labels: duplicate, question
