### ISSUE TITLE
i want to delete cached file with  imageUrl

### ISSUE THREAD

**Issue by funset** [bumptech/glide#997] opened 2016-02-24 10:37 UTC
i want to delete cached file or files  with  imageUrl

how can i to do?
thanks!

**Comment by TWiStErRob** [comment] 2016-02-24 11:15
Sounds like a duplicate of #624.
Why do you want to delete it?

**Comment by funset** [comment] 2016-02-25 02:12
when the image file  was changed of an imageUrl ,i want to update diskcache and refresh imageview

**Comment by TWiStErRob** [comment] 2016-02-25 09:39
Yes, it's the same as the second question in #624 and also read #996.

**Closed by TWiStErRob** 2016-02-25 09:39 UTC
Labels: duplicate, question
