### ISSUE TITLE
Glide 4.0.0-RC0: Duplicate method "as" in generated GlideRequests prevents compilation

### ISSUE THREAD

**Issue by igokoro** [bumptech/glide#1987] opened 2017-05-31 20:50 UTC
**Glide Version**: 4.0.0-RC0

**Integration libraries**: OkHttp3

**Issue details / Repro steps / Use case background**: 
I'm trying to migrate from v3 to v4. Most of the things looked good until I added `@GlideModule` into appropriate places and Glide's `annotationProcessor` to each of my Gradle modules.

Problematic pieces of generated code are in `GlideRequests` - 2 `as` methods:

```java
@Override
  public <ResourceType> GlideRequest<ResourceType> as(Class<ResourceType> resourceClass) {
    return new GlideRequest<>(glide, this, resourceClass);
  }

@Override
  public <ResourceType> GlideRequest<ResourceType> as(Class<ResourceType> resourceClass) {
    return (GlideRequest<ResourceType>) super.as(resourceClass);
  }
```

There are 3 glide modules in total: 
* 1 `AppGlideModule` that disables manifest parsing in the application Gradle module
* 1 `LibraryGlideModule` that configures OkHttp integration  in the application Gradle module
* 1 `LibraryGlideModule` that registers some `ModelLoader`s in one of the library Gradle modules

Do not use any `GlideExtention`s or `GlideType`s. 
Tried to only apply `annotationProcessor` in the main application Gradle module but didn't change anything. Also tried to exclude OkHttp3 integration - no luck as well.

**Compilation error**:
![image](https://cloud.githubusercontent.com/assets/2870939/26652423/e1b9cd68-461d-11e7-8175-4d9834bdfed0.png)

Totally lost on what may be causing the issue.

**Comment by TWiStErRob** [comment] 2017-05-31 21:02
Duplicate of #1971, fixed in https://github.com/sjudd/glide/commit/d94e99453734c72a74e393e765f7c56ccdf6d39a

**Closed by TWiStErRob** 2017-05-31 21:02 UTC
Labels: bug, duplicate

**Comment by igokoro** [comment] 2017-05-31 21:12
I should've looked better for duplicates :) Thank you!

**Comment by TWiStErRob** [comment] 2017-05-31 21:51
It's not your fault, I knew it was there and had to search 5 times with different terms to find it.

**Comment by bajicdusko** [comment] 2017-06-01 15:36
Hey @TWiStErRob, This fix isn't deployed yet, right?

**Comment by TWiStErRob** [comment] 2017-06-01 21:44
You can use it through the usual snapshot route: http://bumptech.github.io/glide/dev/snapshots.html
