### ISSUE TITLE
Custom Image transformation

### ISSUE THREAD

**Issue by niteshkhatri** [bumptech/glide#537] opened 2015-07-14 09:34 UTC
Hi guys, thanks for such a wonderful library. I want a special type of image transformation.

This custom transformation should scale the image down maintaining the original aspect ratio so that one dimension of the image is exactly equal to the target dimensions and the other dimension of the image is greater than the target dimensions.

Can I achieve this effect using `CENTER_CROP` or should I write custom transformation? Please help me out.

If I need to write custom transformation, please help me writing it.

**Comment by TWiStErRob** [comment] 2015-07-14 10:04
Sounds like you want centerCrop without the crop part :) You can't do that with defaults as far as I know since it's not optimal: the image dimension is bigger than what the user will ever see, that's why it's cropped. I guess you'll use the result in some pannable ImageView where this is not true.

Look at [how transformations work](https://github.com/bumptech/glide/wiki/Transformations) and the default [`CenterCrop` transformation](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/resource/bitmap/CenterCrop.java), you can probably use an almost oneliner [`Bitmap.createScaledBitmap` mentioned in the core of `centerCrop`](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/resource/bitmap/TransformationUtils.java#L44), since you don't need the translate matrix, nor the cut (drawBitmap).

**Comment by niteshkhatri** [comment] 2015-07-14 10:17
I have list of images in ListView. The ImageViews are being populated using Glide with CenterCrop transformation. At first images look fine. However. when I scroll up imageview goes out of screen then I scroll down , now the imageview is visible. Now the image seems like centerCropped again. It looks as if centercropped image is again centercropped.

**Comment by TWiStErRob** [comment] 2015-07-14 10:35
CenterCrop is an idempotent operation. The second time no cropping nor scaling happens because the sizes match exactly. Also Glide shouldn't transform twice.

Can you please open a new issue where you describe this bug you have; with the relevant parts from the adapter, item layout xml and screenshot(s)?
Please use the [issue template link in CONTRIBUTING.md](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md).

*Also take a look at [The XY problem](http://xyproblem.info), no worries though, it can happen to anyone :)*

**Comment by sjudd** [comment] 2015-07-21 21:34
Sounds like this might be the squaring drawable problem again? Try asBitmap() and see if that fixes it?

**Comment by TWiStErRob** [comment] 2015-10-16 16:06
Let's close this as duplicate of #613, the 2nd comment of @niteshkhatri sounds like that.
Feel free to reopen or create a new issue if you want.

**Closed by TWiStErRob** 2015-10-16 16:06 UTC
Labels: question
