### ISSUE TITLE
Background image loaded from cache

### ISSUE THREAD

**Issue by LinkOut** [bumptech/glide#305] opened 2015-01-15 09:20 UTC
Hi,
I guess, when images are loaded from cache, it sets a weird background color on a JPG wich have white background. This only happens on Samsung S3.

Thanks

**Comment by TWiStErRob** [comment] 2015-01-15 10:37
Hey, can you please help out by answering the following questions:
* Which version of Glide?
* Which version of Android on the S3?
* Can you please post a screenshot of what you're talking about?
* Could you maybe share the source image URL(s)?

Really the most helpful would be if you could reproduce it in a standalone mini app which only demonstrates this issue.

**Comment by LinkOut** [comment] 2015-01-15 10:57
Hello.
* I'm using the version 3.4 of Glide
* The S3 is running Android 4.3 (actually same problem on other devices except Nexus 5 (running Android L)
* No url, the images are loaded from res.

The images are in a ExpandableListView.
![test](https://cloud.githubusercontent.com/assets/4797287/5756239/86ce9d8c-9cad-11e4-9f66-686f5f66a0fc.jpg)
The "Color" on the image, is actually not the real color of the JPG, wich is White. May be a problem of the Image?
This happen only when Glide uses the image from cache, because when i remove cache from the phone settings, this problem disappear.

**Comment by sjudd** [comment] 2015-01-15 22:04
Are you saying the transparent sections of the images are sometimes not transparent but instead filled in with another color?

If so, if you add dontTransform() to your ``Glide.with(...)`` call and clear the cache for your application, does the problem still occur?

**Comment by LinkOut** [comment] 2015-01-16 07:42
Yes, the transparent sections of the images are filled with another color.
If i clear the cache of the application, from the device's settings, the problem will not happen, for few time, i guess untile Glide does not load the images from the cache. Then the images keep that color.
So, I ve cleared the cache of the application and applied dontTransform() to my Glide.with(...) and the problem is still there.

Wonder why this problem wont happen in android L.

Thanks.

**Comment by sjudd** [comment] 2015-01-20 20:55
Any chance you can attach a sample app which reproduces the issue? It's possible this was fixed by #301, although this would be a yet unreported symptom (I've seen issues with GIF frames similar to what you describe).

**Comment by sjudd** [comment] 2015-06-09 14:04
Let us know if you get the chance to try a sample app.

**Comment by LinkOut** [comment] 2015-06-10 06:45
I will provide a sample app ASAP.

Thanks.

**Comment by sjudd** [comment] 2015-06-10 14:08
Just to double check, you have a JPEG that you expect to be partially transparent? JPEGs don't support alpha. Are you sure the image is not a GIF or a PNG?

**Comment by LinkOut** [comment] 2015-06-10 14:40
Image was a JPEG, and when it was loaded from the Cache by the library, it's "white" color changed.

**Comment by tobalr** [comment] 2015-06-13 10:49
Hi. I have the same issue. I have tried using jpg as well as webp. When the image is loaded from diskcache its white background is no longe white but gray.
The issue dissapears when I disable diskCache.

Here is a sample app for testing. There is a folder with screenshots inside the project.
Image is loaded in MainActivity

https://www.dropbox.com/s/4edvuyvo7cd441k/GlideGrayBGSampleApp.rar?dl=0

**Comment by sjudd** [comment] 2015-06-17 20:20
Thanks for the sample app, very helpful! It looks like this is just due to jpeg compression. I can reproduce this when encoding jpeg at any quality level (including 100), but not when encoding PNGs. I'll look in to this a bit more, but since we rely on the framework for encoding, there's likely not much anyone can do to fix this.

That said, there are at least two work arounds I can think of:

1. Use DiskCacheStrategy.NONE (for local images) or DiskCacheStrategy.SOURCE (for remote images)  to prevent Glide from re-compressing the images
2. Use asBitmap() and a custom BitmapEncoder to always compress affected images as PNGs:

```java
Glide.with(this)
    .fromResource()
    .asBitmap()
    .encoder(new BitmapEncoder(Bitmap.CompressFormat.PNG,100))
    .load(R.drawable.testimg)
    .into(imageView);
```

Since I don't think there's anything actionable for us in the library, I'm going to close this for now. If anyone has any other suggestions or thoughts, I'm happy to revisit. If I find anything else out I'll update this issue.

**Closed by sjudd** 2015-06-17 20:20 UTC
Labels: bug

**Comment by sjudd** [comment] 2015-06-17 23:33
Ah, after some more experimentation, it looks like this affects RGB_565 much more significantly than ARGB_8888, so you may also want to switch the DecodeFormat to ARGB_8888 (see the [Configuration][1] wiki page).

[1]: https://github.com/bumptech/glide/wiki/Configuration#bitmap-format

**Comment by tobalr** [comment] 2015-06-25 10:02
Hi Sjudd.  Thank your for looking into the issue. 
Using a custom BitmapEncoder seems like the best solution in my case. 
Best regards

**Comment by giusecapo** [comment] 2017-11-13 15:52
Still having this issue. Images looks little darker. Why this? Please I followed all the steps as explained by @sjudd but still having this issue!
