### ISSUE TITLE
Placeholder and many other methods not available in 4.0.0 RC0

### ISSUE THREAD

**Issue by vish30** [bumptech/glide#2000] opened 2017-06-03 10:21 UTC
**Glide Version**:4.0.0 RC0

**Integration libraries**:No

**Issue details / Repro steps / Use case background**: I have just added the glide dependency in my gradle file. When I try to use methods like placeholder(), centerCrop(), crossFade(), etc. between load() and into(), it gives me syntax error like there is no such method. Are they removed in this release or am I missing something ?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this)
                        .load(imgUrl)
                        .placeholder(R.drawable.downloading)
                        .into(bikeImageView);
```
It gives error on placeholder() that the method doesn't exist.

**Comment by TWiStErRob** [comment] 2017-06-03 10:30
Yes, it's been removed, it's a major version change.
And, yes it is still available via APT, read http://bumptech.github.io/glide/doc/generatedapi.html and add
```gradle
annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC0'
```

Duplicate of #1939.

**Closed by TWiStErRob** 2017-06-03 10:30 UTC
Labels: bug, documentation, duplicate

**Comment by vish30** [comment] 2017-06-03 11:47
Can you please provide a link to an example which implements the new version ?

**Comment by TWiStErRob** [comment] 2017-06-03 12:03
Flickr, SVG, and contacturi [samples](https://github.com/bumptech/glide/tree/master/samples) all use APT. I'm working on an external example myself, I'm just trying out the APT.

**Comment by dw129** [comment] 2018-02-02 05:03
Glide 4.0 will not support this method. please check new implementation for placeholder

Glide.with(mContext).load(Uri.fromFile(loadedFile)).apply(new RequestOptions()
.placeholder(R.drawable.image_placeholder)).into(textImageTypeViewHolder.imgView);

**Comment by TWiStErRob** [comment] 2018-03-01 14:52
@dw129 Glide 4 supports this method since the first stable release, you just need to set up the annotation processor as described here: http://bumptech.github.io/glide/doc/generatedapi.html#java and use `GlideApp` instead of `Glide`.
