### ISSUE TITLE
How to show gif with glide 4.2.0 for it's slow for the moment?

### ISSUE THREAD

**Issue by lbx2015** [bumptech/glide#2496] opened 2017-10-18 08:44 UTC
My code is following and the gif animation is slow, can yo u correct me the usage of code in order to showing gif normally? you can email me the detail:1933772028@qq.com

RequestOptions o = new RequestOptions();
       Glide.with(h.imageView3.getContext())
.load("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1508322038285&di=e0c474540228565f1271de3b4b2c56e7&imgtype=0&src=http%3A%2F%2Fwww.lia-edu.com%2Fupload%2Fimage%2F20170717%2F20170717151619_8233.gif").apply(o.diskCacheStrategy(DiskCacheStrategy.RESOURCE)).into(h.imageView3);

**Comment by sjudd** [comment] 2017-10-18 14:30
Duplicate of #2471

**Closed by sjudd** 2017-10-18 14:30 UTC
Labels: question
