### ISSUE TITLE
Glide and YouTubeAndroidPlayerApi don't work together.

### ISSUE THREAD

**Issue by mucahitsidimi** [bumptech/glide#559] opened 2015-07-30 14:05 UTC
I added the glide-3.6.1.jar and YouTubeAndroidPlayerApi.jar to my project,
Before adding to glide , the youtube player was working clearly, when I added glide, something went wrong and when I try to open my YouTubePlayerFrag, onCreate() method I couldn't inflate my xml.

When I remove the glide, everything return normal.

**Comment by TWiStErRob** [comment] 2015-07-30 14:16
Please include a stack trace from LogCat.

**Comment by mucahitsidimi** [comment] 2015-08-03 06:39
08-03 09:35:56.584: E/AndroidRuntime(17585): FATAL EXCEPTION: main
08-03 09:35:56.584: E/AndroidRuntime(17585): Process: com.myapp.main, PID: 17585
08-03 09:35:56.584: E/AndroidRuntime(17585): android.view.InflateException: Binary XML file line #9: Error inflating class fragment
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at com.myapp.main.fragments.MyAppFrag.onCreateView(MyAppFrag.java:53)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:938)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:446)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.os.Handler.handleCallback(Handler.java:739)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.os.Looper.loop(Looper.java:135)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at java.lang.reflect.Method.invoke(Native Method)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at java.lang.reflect.Method.invoke(Method.java:372)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
08-03 09:35:56.584: E/AndroidRuntime(17585): Caused by: java.lang.IllegalStateException: Fragment com.google.android.youtube.player.YouTubePlayerSupportFragment did not create a view.
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:314)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
08-03 09:35:56.584: E/AndroidRuntime(17585): 	... 19 more


can not inflate, when I remove glide from my project, everything running fine on existing code.

**Comment by TWiStErRob** [comment] 2015-08-03 10:24
Aah, the key is "did not create view", read this: https://github.com/bumptech/glide/issues/518#issuecomment-118006124; hopefully you're just missing and id/tag.

**Comment by sjudd** [comment] 2015-08-04 14:21
Closing as a duplicate of #518

**Closed by sjudd** 2015-08-04 14:21 UTC
