### ISSUE TITLE
Allow multiple listeners in builder

### ISSUE THREAD

**Issue by cheXat** [bumptech/glide#2976] opened 2018-03-22 23:19 UTC
**Glide Version**:
4.2.0

**Integration libraries**:
okhttp3-integration:4.2.0@aar

**Device/Android Version**:
Pixel 2 (but i'd be surprised, if it weren't like that on all others as well)

**Issue details / Repro steps / Use case background**: 
I have a global LoggingListener set to my GlideApp and on some occasions wanna use an additional Listener to set the visibility of my View after loading is complete.
Sometimes i have to influence other Views depending on the outcome of an Image load.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
I assume, you can imagine that those RequestListener implementation do "anything"

```java
      GlideApp.with(view).load(url)
          .signature(new LongVersionSignature(pictureVersion))
          .listener(new VisibilitySettingListener<Drawable>(borderLayout))
          .listener(new TriggerLayoutNotifications<Drawable>())
          .listener(new LoggingListener<Drawable>())
          .diskCacheStrategy(DiskCacheStrategy.ALL)
          .into(image);
```

No error - just the last Listener fires, the rest seems to be overwritten in the builder already.

Change:
RequestListener<?> listener;
listener(RequestListener<?> listener) {this.listener = listener; return this;}

to

List<RequestListener<?>> listenerList = new ArrayList<>();
listener(RequestListener<?> listener) {this.listenerList.add(listener); return this;}

**Comment by sjudd** [comment] 2018-03-27 15:10
Let's call this a duplicate of #562. This wouldn't be too terrible to support if you're interested in sending a pull request. We already support an internal listener plus the normal listener for each request, so that would just have to be generalized. You'd also need to use an API other than chained `.listener()` callbacks to avoid breaking users who might be relying on the overriding behavior, but that's not especially difficult either.

**Closed** 2018-03-27 15:10 UTC
