### ISSUE TITLE
Reuse old image for Place Holder

### ISSUE THREAD

**Issue by karun2189** [bumptech/glide#688] opened 2015-10-16 17:33 UTC
I want to reuse the previous version image for place holder how can i achieve this?

**Comment by TWiStErRob** [comment] 2015-10-16 21:29
This is a duplicate of #527 please pick a solution from there.

**Closed by TWiStErRob** 2015-10-16 21:29 UTC
Labels: duplicate, question

**Comment by karun2189** [comment] 2015-10-17 09:54
Hi, It's won't work my scenario . I will explain my scenario , i will add image one by one manually to my gridview in 0'th position. If i am adding a new image at that time it showing previous image only. How can i resolve this here i am enclosed my code 
 Glide.with(mImageView.getContext())
                .load(path)
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override public boolean onException(
                            Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        return false;
                    }
                    @Override public boolean onResourceReady(
                            GlideDrawable resource, String model, Target<GlideDrawable> target,
                            boolean isFromMemoryCache, boolean isFirstResource) {  // execution order: 2
                        target.getSize(new SizeReadyCallback() {
                            @Override public void onSizeReady(int width, int height) {  // execution order: 3
                                Glide.with(mImageView.getContext()).load(path).preload(width, height);
                            }
                        });
                        return false;
                    }
                })
                .error(R.drawable.broken_img)
                .signature(new StringSignature(mLastModified))
                .dontAnimate()
                .into(mImageView);

**Comment by TWiStErRob** [comment] 2015-10-17 10:09
Adding an item at the beginning of a list shouldn't rebind the rest of the items. It sounds like your `getItemId()` is not playing nice. Can you please describe in more detail (for example actual behavior and expected behavior) what it is you're trying to achieve?

Is it possible that you're not preloading the correct image? Inside `onSizeReady` you have `path` and outside you also have `path`, in my original code it was `pathToLoad2` and `pathToLoad`. The solution you picked pre-loads the next image causing the next load to hit the memory cache. You can also try the thumbnail solution where the previous(current) image is re-used as a placeholder and the next on is loaded normally.

**Comment by karun2189** [comment] 2015-10-17 10:16
Ya your are correct at the time i dont have "pathToLoad2 " because i am loading at first time that's why i am giving same path. If i am using above code then i am getting repeated image. Some time it may work correctly

**Comment by karun2189** [comment] 2015-10-17 10:18
I think glide reuse the particular imageview instance.

**Comment by TWiStErRob** [comment] 2015-10-17 10:18
How about the `.signature()` there? You need to pass that for every load otherwise you may hit the cache.

**Comment by karun2189** [comment] 2015-10-17 10:20
i will pause every time based on my object

**Comment by TWiStErRob** [comment] 2015-10-17 10:21
You said you wanted to reuse the old image for placeholder, but now you say that you only have one path?

**Comment by karun2189** [comment] 2015-10-17 10:21
ya correct path is same but signature is different

**Comment by TWiStErRob** [comment] 2015-10-17 10:25
Then you don't have the future update time, that is the "next path", you'll have to try the thumbnail version from #527. Something like the below should hit the memory/disk cache:

```java
....load(path)
   .signature(currentLastModified)
   .fitCenter()
   .thumbnail(....load(path).signature(previousLastModified).fitCenter())
   .into(mimageView)
```
