### ISSUE TITLE
Load local gif green

### ISSUE THREAD

**Issue by YBill** [bumptech/glide#2157] opened 2017-07-21 05:42 UTC
**I loaded the local gif in the 3.7.0 version is normal, upgrade to version 4.0.0-RC1 local gif background turns green.Please help me find the problem**:

**Glide Version**: 4.0.0-RC1

**Glide load on onCreate()**:

**This is the java code in version 3.7.0**:
```java
Glide.with(this)
                    .load(R.drawable.pic_placeholder_3x)
                    .asGif()
                    .fitCenter()
                    .dontAnimate()
                    .skipMemoryCache(true)
                    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                    .into(imageView);
```
**This is the java code in version 4.0.0-RC1**:
```java
GlideApp.with(this)
                .load(R.drawable.pic_placeholder_3x)
                .fitCenter()
                .skipMemoryCache(true)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .into(placeholderImageView);
```

**Layout XML**:
```xml
<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#f6f6f6">

        <ImageView
            android:id="@+id/image"
            android:layout_width="144dp"
            android:layout_height="80dp"
            android:layout_gravity="center"
            android:scaleType="fitCenter" />
</FrameLayout>
```

**Comment by YBill** [comment] 2017-07-21 05:46
Picture effect and https://github.com/bumptech/glide/issues/2157 is the same, but I was gif

**Comment by YBill** [comment] 2017-07-21 05:48
Picture effect and [this problem](https://stackoverflow.com/questions/31146685/android-imageview-shows-greenish-image) is the same, but I was gif

**Comment by manishjss** [comment] 2017-07-31 13:55
Also have same problem.... pls help

**Comment by EngleVV** [comment] 2017-09-15 02:00
Same problem

**Comment by sjudd** [comment] 2017-09-15 02:39
Duplicate of #2396 I'd bet.

**Closed by sjudd** 2017-09-15 02:39 UTC

**Comment by HeSuxiang** [comment] 2017-09-15 09:08
Thanks,  but i  back using glide 3.7 at  lastnight
