### ISSUE TITLE
Image crossfading interrupted by placeholder

### ISSUE THREAD

**Issue by sigmabeta** [bumptech/glide#1617] opened 2016-11-25 20:35 UTC
**Glide Version**:
3.7.0

**Device/Android Version**:
Reproduced on Android 7.0 emulator and various 6.0 devices (Nexus 5, Galaxy Note 5, others)

**Issue details / Repro steps / Use case background**: 

Suppose you have two images you want to toggle between in a single, static `ImageView`. They're both memory-cached and so can theoretically display immediately upon toggle, but to create a nicer user experience, you'd like to fade out the previous image at the same time that you fade in the new image. The resulting animation - composed of two fade animations at the same time - is what most designers refer to as a "crossfade". It looks something like this:

https://gfycat.com/WillingInsignificantHypacrosaurus

Unfortunately, this is not the default behavior of Glide, although it does appear to be the intention. Consider the following Glide load call, where the `RequestListener` is used to enforce Glide's `.crossfade()` functionality is used every time (default functionality skips the `.crossfade()` animation once the image has been memory-cached) :

```java
    public static void loadWithCrossfadeAlways(@NonNull String path, @NonNull ImageView target) {
        Glide.with(target.getContext())
                .load(path)
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        ImageViewTarget imTarget = (ImageViewTarget) target;
                        return new DrawableCrossFadeFactory<>()
                                .build(false, isFirstResource)
                                .animate(resource, imTarget);
                    }
                })
                .into(target);
}
```

The result does not produce a true crossfade, but instead immediately removes the original image, and fades the new image in over the background of the View:

https://gfycat.com/UnfoldedVastAmurstarfish

The reason for this appears to be in `ImageViewTarget.onLoadStarted(Drawable placeholder)` and `ImageViewTarget.onLoadCleared(Drawable placeholder)`, both of which contain a single call to `ImageView.setImageDrawable(placeholder)`. The reasoning for this call's presence is self evident - it's how the specified placeholder image gets rendered - but it prevents a smooth crossfade from occurring, and worse yet, does so **even if `placeholder` is not specified - i.e, its value is `null`**.

Ideally, the placeholder would be crossfaded in (as the previous image fades out) and then crossfaded out (as the new image fades in), or in the case of a missing placeholder or memory-cached image, omitted altogether. 

In the meantime, it is possible to work around this by creating an `ImageViewTarget` subclass that suppresses the above-described `setImageDrawable()`:

```java
public class CrossfadeImageViewTarget extends GlideDrawableImageViewTarget {
    public CrossfadeImageViewTarget(ImageView view) {
        super(view);
    }

    @Override public void onLoadStarted(Drawable placeholder) {
        if (placeholder != null) {
            super.onLoadStarted(placeholder);
        }
    }

    @Override public void onLoadCleared(Drawable placeholder) {
        if (placeholder != null) {
            super.onLoadCleared(placeholder);
        }
    }
}
```

Using this subclass as the target in the above loader method produces the intended result.

**Comment by TWiStErRob** [comment] 2016-11-25 22:48
Wow, nice summary of what's happening. You're almost there.

Consider this: if Glide supported your wanted behavior out of the box, then how would lists behave? Just think about the most basic: `Glide.with(...).load(list.get(position)).crossFade().into(vh.image)` (`.crossFade()` is implicitly enabled anyway). If the cross-fade happened from the image that's already in the view, then the RecyclerView's trick to re-use list items would be revealed and would ruin the user's intuitive experience.

Since loading images into lists is much more frequent than swapping out images, I think Sam's choice of this behavior is well-backed. There's a way to achieve what you want, you're only missing the `thumbnail` trick: https://github.com/bumptech/glide/issues/527#issuecomment-148840717 (I'm going to dupe it against that).

Your workaround is not safe. If you don't adhere to the contract of `onLoadCleared` you may get an exception, because it's possible that Glide thinks your Bitmap is not used any more and re-uses it for the next load.

---

On a related note, you'll probably run into #943. You can combine your listener and the fix for #943 into a single class shown at https://github.com/TWiStErRob/glide-support/commit/052c9e8191bd28fd747fe40960223c377b7bb203; just copy it to your project and replace the `listener` with `.animate(new AlwaysCrossFade<GlideDrawable>(false))`. You'll need 3.8.0 for that method to be public!

**Comment by TWiStErRob** [comment] 2016-11-25 22:48
Actually, I think I see a feature request in here: exit animations. @sjudd what do you think about that?

@sigmabeta though it would still not fix your cross-fade issue, because you would still get a white flash, albeit a fancier one.

**Comment by sigmabeta** [comment] 2016-11-25 23:44
For clarity, I don't believe what I described should be *default* functionality at all. As you said, it would be catastrophic when used in recycling lists, which is definitely more common than the use-case I described.

I think the main issue is one of semantics - the term "crossfade" has a specific meaning, and the Glide `.crossfade()` method has an effect that's different from that specific meaning. It might be alleviated entirely by renaming the method to something more descriptive; perhaps `.fadeIn()` or something. (For example, I instinctively would not want to use `.crossfade()` on a list for the exact reasons you described above, even though it turns out it produces the expected behavior for a list.)

Having some sort of way to easily also do a *true* crossfade would be a nice-to-have, but there are other ways to achieve it so it's not a big deal.

I'll review the issues you linked to, thanks.

**Comment by TWiStErRob** [comment] 2016-11-25 23:59
Glide's `.crossFade()` does a cross-fade in this order: placeholder &rarr; thumbnail &rarr; full image, however if placeholder and thumbnail are missing, you get a fallback fade-in animation: see `DrawableCrossFadeViewAnimation` (the `defaultAnimation` in constructor is usually created by `DrawableCrossFadeFactory.DefaultAnimationFactory`).

I think source of the confusion here is that you're looking at the view and saying "I want to cross-fade that", but Glide scopes `crossFade()` on a per-request level instead of a per-view level. This is why you need the thumbnail trick in #527 to elevate the scope.

Here's one more link if you need to cycle more images nicely: https://github.com/bumptech/glide/issues/861#issuecomment-169490382.

**Comment by sjudd** [comment] 2016-12-07 16:07
I agree cross fade is misleading, I'd be happy to hear naming suggestions to avoid the confusion.

A simple ViewSwitcher is a great way to cross fade between two different images and works well with Glide (load into ImageView A, then into ImageView B, when the load for ImageView B finishes, flip the views).

**Comment by sigmabeta** [comment] 2016-12-07 16:09
This is in fact what I ended up doing.

**Comment by sjudd** [comment] 2017-11-19 19:52
Let's call this a duplicate of #2505

**Closed by sjudd** 2017-11-19 19:52 UTC
Labels: feature
