### ISSUE TITLE
Provide support for the latest API level

### ISSUE THREAD

**Issue by ebghrimtech** [bumptech/glide#3384] opened 2018-10-31 10:44 UTC
Hello,
We are currently using Glide in one of our application. Actually we need a confirmation from your side. According to the Google Play Policy, all apps have to provide support for at least API level 26. We are targeting API level 28. So just for a safer side, do we need to do anything for supporting API level 28?

**Comment by svenjacobs** [comment] 2018-11-06 09:40
In our project we target API level 28 and migrated the project to [AndroidX](https://developer.android.com/jetpack/androidx/) with [jetifier enabled](https://developer.android.com/jetpack/androidx/migrate). Everything works 👍 though I still hope that Glide will [natively support AndroidX](https://github.com/bumptech/glide/issues/3184) soon.

**Comment by ebghrimtech** [comment] 2018-11-12 08:06
Thank you @svenjacobs for your response.

**Comment by sjudd** [comment] 2018-11-15 23:37
Duplicate of #3184

**Closed by sjudd** 2018-11-15 23:37 UTC
