### ISSUE TITLE
[FEATURE]  I want some glide tint feature.

### ISSUE THREAD

**Issue by LiHanGuang** [bumptech/glide#1142] opened 2016-04-22 02:52 UTC
@TWiStErRob

Me again.   I also have a UI demand like [#1124](https://github.com/bumptech/glide/issues/1124)?

Can you give me some suggestion? Thanks.

Maybe like below,  but attention to **glide internal drawable animation**:  **.crossFade()**
```
Glide.with(mCOn)
     .load(model.url)
     .placeholder(R.drawable.inventory_placeholder)
     .diskCacheStrategy(DiskCacheStrategy.RESULT)
     .crossFade()
     .tint(Color.RED)  // <------------------   I am here!
     .into(holder.res_pic);
```

**Comment by TWiStErRob** [comment] 2016-04-22 07:50
Oh, I don't know why I didn't check that yet, sorry.
What should it tint exactly? If you want to tint just the result, you should just write a BitmapTransformation.
If you want to tint everything then this is likely a duplicate of #1142.

**Comment by LiHanGuang** [comment] 2016-04-23 02:38
@TWiStErRob 
First, thanks your suggest for tint **resut**.

but I want ro tint  **placeholder**  **fallback** and **resut**.

Maybe like below:

```java
Glide.with(mCOn)
     .load(model.url)
     .placeholder(R.drawable.inventory_placeholder)
     .diskCacheStrategy(DiskCacheStrategy.RESULT)
     .crossFade()
     .tintPlaceholder(Color.RED)  // <------------------   I am here!
     .tintFallback(Color.GREEN)  // <------------------   I am here!
     .tintResust(Color.BLUE) // <------------------   I am here!
     .into(holder.res_pic);

//or like blow

Glide.with(mCOn)
    .load(model.url)
                .bitmapTransform(transformation) // <------------------   I am here!
                .placeholderBitmapTransform(tintRedTransformation) // <------------------   I am here!
                .fallbackBitmapTransform(tintGreenTransformation) // <------------------   I am here!
                .placeholder(placeholder) 
                .error(error) // glideUrl != null, but download fail
                .fallback(fallback) // glideUrl == null
                .into(imageView);
```

**Comment by TWiStErRob** [comment] 2016-04-23 10:30
I don't think any API changes are necessary for this, unless there's high demand. What you want is possible with the current API and likely very specific thing to do. See the above linked commit for more details, the gist of it is here:
 * Pre-tint the drawables and use them in `placeholder()`/`fallback()`/`error()` and likely no need to tint result if it's a colored image.

	```java
	private Drawable placeholder; // same code applies to others, just copy-paste
	@Override public void onCreate(Bundle savedInstanceState) {
		...
		placeholder = getTinted(R.drawable.glide_placeholder, PLACEHOLDER_COLOR);
	}
	private @Nullable Drawable getTinted(@DrawableRes int res, @ColorInt int color) {
		// need to mutate otherwise all references to this drawable will be tinted
		Drawable drawable = ContextCompat.getDrawable(getContext(), res).mutate();
		return tint(drawable, ColorStateList.valueOf(color));
	}
	.placeholder(placeholder)
	.into(imageView)
	```

 * Create a custom target that does the tinting for you when needed. This is more resource-friendly and allows higher control:

	```java
	.placeholder(R.drawable.glide_placeholder)
	.error(R.drawable.glide_error)
	.fallback(R.drawable.glide_fallback)
	.into(new TintTarget(imageView,
			RESULT_COLOR, PLACEHOLDER_COLOR, model != null? ERROR_COLOR : FALLBACK_COLOR)
	)

	public class TintTarget extends ImageViewTarget<GlideDrawable> {
		private final ColorStateList placeholderColor;
		private final ColorStateList resultColor;
		private final ColorStateList errorColor;
		public TintTarget(ImageView view,
				ColorStateList placeholderColor, ColorStateList resultColor, ColorStateList errorColor) {
			super(view);
			this.placeholderColor = placeholderColor;
			this.resultColor = resultColor;
			this.errorColor = errorColor;
		}

		@Override public void setDrawable(Drawable drawable) {
			// don't tint, this is called with a cross-fade drawable,
			// and we need the inner drawables tinted, but not this
			super.setDrawable(drawable);
		}

		@Override public void onLoadStarted(Drawable placeholder) {
			super.onLoadStarted(tint(placeholder, placeholderColor));
		}
		@Override public void onLoadFailed(Exception e, Drawable errorDrawable) {
			super.onLoadFailed(e, tint(errorDrawable, errorColor));
		}
		@Override public void onLoadCleared(Drawable placeholder) {
			super.onLoadStarted(tint(placeholder, placeholderColor));
		}
		@SuppressWarnings("unchecked")
		@Override public void onResourceReady(GlideDrawable resource, GlideAnimation glideAnimation) {
			Drawable tinted = tint(resource, resultColor);
			// animate works with drawable likely because it's accepting Drawables, but declaring GlideDrawable as generics
			if (glideAnimation == null || !glideAnimation.animate(tinted, this)) {
				view.setImageDrawable(tinted);
			}
		}

		@Override protected void setResource(GlideDrawable resource) {
			throw new UnsupportedOperationException("onResourceReady is overridden, this shouldn't be called");
		}
	}
	```

And the `tint` method for both based on your code:
```java
public static Drawable tint(Drawable input, ColorStateList tint) {
	if (input == null) {
		return null;
	}
	Drawable wrappedDrawable = DrawableCompat.wrap(input);
	DrawableCompat.setTintList(wrappedDrawable, tint);
	DrawableCompat.setTintMode(wrappedDrawable, Mode.MULTIPLY);
	return wrappedDrawable;
}
```
Both of the solutions should work with your custom `ImageView` in case you want to change the tint later (e.g. for selection).

**Comment by TWiStErRob** [comment] 2016-04-23 10:31
I don't think any API changes are necessary for this, unless there's high demand. What you want is possible with the current API and likely very specific thing to do. See the above linked commit for more details, the gist of it is here:
 * Pre-tint the drawables and use them in `placeholder()`/`fallback()`/`error()` and likely no need to tint result if it's a colored image.

	```java
	private Drawable placeholder; // same code applies to others, just copy-paste
	@Override public void onCreate(Bundle savedInstanceState) {
		...
		placeholder = getTinted(R.drawable.glide_placeholder, PLACEHOLDER_COLOR);
	}
	private @Nullable Drawable getTinted(@DrawableRes int res, @ColorInt int color) {
		// need to mutate otherwise all references to this drawable will be tinted
		Drawable drawable = ContextCompat.getDrawable(getContext(), res).mutate();
		return tint(drawable, ColorStateList.valueOf(color));
	}
	.placeholder(placeholder)
	.into(imageView)
	```

 * Create a custom target that does the tinting for you when needed. This is more resource-friendly and allows higher control:

	```java
	.placeholder(R.drawable.glide_placeholder)
	.error(R.drawable.glide_error)
	.fallback(R.drawable.glide_fallback)
	.into(new TintTarget(imageView,
			RESULT_COLOR, PLACEHOLDER_COLOR, model != null? ERROR_COLOR : FALLBACK_COLOR)
	)

	public class TintTarget extends ImageViewTarget<GlideDrawable> {
		private final ColorStateList placeholderColor;
		private final ColorStateList resultColor;
		private final ColorStateList errorColor;
		public TintTarget(ImageView view,
				ColorStateList placeholderColor, ColorStateList resultColor, ColorStateList errorColor) {
			super(view);
			this.placeholderColor = placeholderColor;
			this.resultColor = resultColor;
			this.errorColor = errorColor;
		}

		@Override public void setDrawable(Drawable drawable) {
			// don't tint, this is called with a cross-fade drawable,
			// and we need the inner drawables tinted, but not this
			super.setDrawable(drawable);
		}

		@Override public void onLoadStarted(Drawable placeholder) {
			super.onLoadStarted(tint(placeholder, placeholderColor));
		}
		@Override public void onLoadFailed(Exception e, Drawable errorDrawable) {
			super.onLoadFailed(e, tint(errorDrawable, errorColor));
		}
		@Override public void onLoadCleared(Drawable placeholder) {
			super.onLoadStarted(tint(placeholder, placeholderColor));
		}
		@SuppressWarnings("unchecked")
		@Override public void onResourceReady(GlideDrawable resource, GlideAnimation glideAnimation) {
			Drawable tinted = tint(resource, resultColor);
			// animate works with drawable likely because it's accepting Drawables, but declaring GlideDrawable as generics
			if (glideAnimation == null || !glideAnimation.animate(tinted, this)) {
				view.setImageDrawable(tinted);
			}
		}

		@Override protected void setResource(GlideDrawable resource) {
			throw new UnsupportedOperationException("onResourceReady is overridden, this shouldn't be called");
		}
	}
	```

And the `tint` method for both based on your code:
```java
public static Drawable tint(Drawable input, ColorStateList tint) {
	if (input == null) {
		return null;
	}
	Drawable wrappedDrawable = DrawableCompat.wrap(input);
	DrawableCompat.setTintList(wrappedDrawable, tint);
	DrawableCompat.setTintMode(wrappedDrawable, Mode.MULTIPLY);
	return wrappedDrawable;
}
```
Both of the solutions should work with your custom `ImageView` in case you want to change the tint later (e.g. for selection).

**Closed** 2016-04-23 10:32 UTC
Labels: enhancement, wontfix

**Comment by LiHanGuang** [comment] 2016-04-25 01:21
thanks a lot!

**Comment by TWiStErRob** [comment] 2016-04-25 09:13
Sorry, it was just a copy-paste mistake. There's no trick there.

**Comment by 3mph4515** [comment] 2017-02-21 10:20
@TWiStErRob How can I tint the final image? Only with transformation?

**Comment by TWiStErRob** [comment] 2017-02-23 00:29
@3mph4515 yeah, transformation could work, but I think wrapping it in compat tint drawable is cheaper, see above code's `tint` method.

**Comment by peidongbiao** [comment] 2017-09-07 03:21
@TWiStErRob I have tried,but it's not work.i'm using glide 3.7.0.
