### ISSUE TITLE
There is a brief white screen when loading local images

### ISSUE THREAD

**Issue by MissMyDearBear** [bumptech/glide#1817] opened 2017-03-27 02:19 UTC
Use glide to load a local image with a brief white screen。

**Comment by MissMyDearBear** [comment] 2017-03-27 02:56
sory，
Glide.with(context).load(file).diskCacheStrategy(DiskCacheStrategy.NONE).dontAnimate().into(imageView);
 is solve  this issue

**Comment by TWiStErRob** [comment] 2017-04-02 13:09
Likely duplicate of #527 though you didn't say you're loading an image on top of an already loaded image.

Well done for using `.diskCacheStrategy(NONE)` for local files!

**Closed by TWiStErRob** 2017-04-02 13:09 UTC
Labels: duplicate, question
