### ISSUE TITLE
Loading an alias'd drawable.xml does not work

### ISSUE THREAD

**Issue by ZakTaccardi** [bumptech/glide#683] opened 2015-10-13 17:39 UTC
*homeview_appbar_background.xml* (my drawable alias)

```xml
<?xml version="1.0" encoding="utf-8"?>
<bitmap xmlns:android="http://schemas.android.com/apk/res/android"
  android:src="@drawable/homeview_appbar_background_port" />
```

Using this code to load does not work, because a drawable.xml alias file is used and not the original file itself.

```java
Glide.with(this)
     .load(R.drawable.homeview_appbar_background)
     .into(imageView);
```

However, this works, because glide directly references the .png drawable.

```java 
Glide.with(this)
     .load(R.drawable.homeview_appbar_background)
     .into(imageView);
```

Note: "does not work" means that nothing happens when the glide loading is called.

**Comment by TWiStErRob** [comment] 2015-10-13 19:30
There's no such thing as nothing happens, add a [`.listener()`](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) and log the `Exception`. I'm pretty sure it will be something like "Cannot decode imeage", isn't there `skia` log lines in LogCat already?

The problem with loading anything other than a real image file is that it can't be converted into a Bitmap with any methods other than drawing on a Canvas, which means the point of drawables is lost (e.g. with shapes). However in your case you may be right, a simple alias, or more techincally an [XML Bitmap](http://developer.android.com/guide/topics/resources/drawable-resource.html#Bitmap) could be supported, but since XML Bitmaps can have all those extra attributes that change the visuals it would be reinventing the wheel I think.

I think you'll need to use the normal `setImageResource` or force Glide to somehow do it in the background, with a custom [workflow](https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit?usp=sharing). See the [SVG sample](https://github.com/bumptech/glide/blob/3.0/samples/svg/src/main/java/com/bumptech/glide/samples/svg/MainActivity.java#L41) on how to override all bits and pieces in Glide.

Let me know what you find out and think.

**Comment by TWiStErRob** [comment] 2015-10-15 21:58
Duplicate of #350.

**Closed by TWiStErRob** 2015-10-15 21:58 UTC
Labels: bug, duplicate
