### ISSUE TITLE
support compose？

### ISSUE THREAD

**Issue by nianzixin** [bumptech/glide#4610] opened 2021-08-11 11:03 UTC
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by theapache64** [comment] 2021-08-17 06:13
Duplicate of https://github.com/bumptech/glide/issues/4459

**Comment by sjudd** [comment] 2022-09-23 20:15
Duplicate of #4459

**Closed by sjudd** 2022-09-23 20:15 UTC
