### ISSUE TITLE
GlideApp is not found , Is's  because of Butterknife ?

### ISSUE THREAD

**Issue by Dpuntu** [bumptech/glide#2358] opened 2017-09-08 06:36 UTC
In my App , It's write this：

        repositories {
            mavenCentral()
            maven { url 'https://maven.google.com' }
        }

        dependencies {
           compile 'com.github.bumptech.glide:glide:4.0.0'
           annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'

           compile 'com.jakewharton:butterknife:8.4.0'
           apt 'com.jakewharton:butterknife-compiler:8.4.0'
        }

And then new class ：

   @GlideModule
    public final class TastesGlideModule extends AppGlideModule {}

Then make project

But is not found GlideApp ， When I remove butterknife in dependencies  and try again , The GlideApp is  be create , It's because of Butterknife ?

**Comment by Tolriq** [comment] 2017-09-08 07:58
You should not mix apt and annotationProcessor, if your build target support annotationProcessor then use it also for Butterknife.

BTW Butterknife is at version 8.8.1 and glide 4.1.1
```
 compile 'com.github.bumptech.glide:glide:4.1.1'
       annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'

  compile 'com.jakewharton:butterknife:8.8.1'
  annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
```

**Comment by TWiStErRob** [comment] 2017-09-08 08:02
Duplicate of #2209, thanks @Tolriq

**Closed by TWiStErRob** 2017-09-08 08:02 UTC
Labels: question
