### ISSUE TITLE
Implement Glide library

### ISSUE THREAD

**Issue by HamidRezaRTM** [bumptech/glide#3830] opened 2019-08-13 15:06 UTC
Since I'm using androidx, I can't implement Glide library and get this error:

![error](https://user-images.githubusercontent.com/23734963/62952542-16e71b00-be01-11e9-856e-1a5255ef4e4c.png)

**Comment by Amit2286658** [comment] 2019-08-14 15:46
I'm having the same problem, i tried to use "android.enableJetifier=true", but it wasn't of any use either,

**Comment by sjudd** [comment] 2019-08-14 16:54
Duplicate of #3184

**Closed by sjudd** 2019-08-14 16:54 UTC
