### ISSUE TITLE
NPE on Glide 4.4 in com.bumptech.glide.load.engine.DecodeJob.runLoadPath

### ISSUE THREAD

**Issue by dadakkk** [bumptech/glide#2760] opened 2017-12-26 10:18 UTC
```
GlideExecutor: Request threw uncaught throwable
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'com.bumptech.glide.load.engine.Resource com.bumptech.glide.load.engine.LoadPath.load(com.bumptech.glide.load.data.DataRewinder, com.bumptech.glide.load.Options, int, int, com.bumptech.glide.load.engine.DecodePath$DecodeCallback)' on a null object reference
                                                                           at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:499)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:471)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:457)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:411)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
                                                                           at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
                                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:132)
                                                                           at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:51)
                                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                                           at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:273)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                           at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:445)
```

**Comment by sjudd** [comment] 2017-12-27 18:07
Hi @dadakkk,

It looks like you might not have included some important information when you filed this issue. To make sure we have all the information we need to help with your issue. Please take a look at the [Issue Template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md) and make sure you've filled out as many sections as possible.

In particular you **must** include:

* Glide Version
* Glide load line
* Issue details.

I'm marking this issue as requiring more information. Please understand that if you do not provide that information or update the issue within the next 7 days this issue will be automatically closed so that it doesn''t clutter the bug tracker.

Best regards,

~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by visiolink-android-dev** [comment] 2018-01-09 13:18
I got a slightly different one:

```
01-09 14:09:18.946 2175-2175/de.shzmain.areader W/Glide: Load failed for http://www.e-pages.dk/glueckstaedterfortuna/assets/glueckstaedterfortuna.png with size [1056x1776]
                                                         class com.bumptech.glide.load.engine.GlideException: Failed to load resource
01-09 14:09:18.947 2175-2349/de.shzmain.areader E/GlideExecutor: Request threw uncaught throwable
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'com.bumptech.glide.load.engine.Resource com.bumptech.glide.load.engine.LoadPath.load(com.bumptech.glide.load.data.DataRewinder, com.bumptech.glide.load.Options, int, int, com.bumptech.glide.load.engine.DecodePath$DecodeCallback)' on a null object reference
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:489)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:461)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:447)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:401)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:370)
                                                                     at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134)
                                                                     at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                     at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:69)
                                                                     at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:263)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)
```
Glide Version: 4.2.0
Glide load line:
`Glide.with(Application.getAppContext())
                        .load(region.getImageUrl())
                        .into(holder.mImageView);`
Issue details:
I am loading a list of images in a recycler view and only one of the images didn't load due to this exception. After recreating the activity, the image loaded fine.

**Comment by sjudd** [comment] 2018-01-09 15:07
@visiolink-android-dev let me know if you can reproduce on  4.5.0.

**Comment by visiolink-android-dev** [comment] 2018-01-12 15:00
I have updated to 4.5.0 and will report back here if I see the error again.

**Comment by KevinLeigh** [comment] 2018-01-16 13:36
@visiolink-android-dev Do you get the issue still on version `4.5.0`?

**Comment by visiolink-android-dev** [comment] 2018-02-02 12:34
@KevinLeigh No, haven't seen it. You can probably close the issue and then we can reopen if it happens again.

**Closed** 2018-02-02 14:59 UTC
Labels: bug, repro-needed
