### ISSUE TITLE
BitmapFactory.Options.inPreferQualityOverSpeed

### ISSUE THREAD

**Issue by BattleShipPark** [bumptech/glide#1048] opened 2016-03-10 05:52 UTC
Hi,
I'd like to access to Options.inPreferQualityOverSpeed to obtain higher quality image from bitmap.
I think it is in Downsampler.java, but I can't change options because it is private field.
How can I access and change it?
Thanks.

**Comment by TWiStErRob** [comment] 2016-03-10 10:45
You can use a custom Downsampler:
```java
Glide
        .with(context)
        .load(...)
        .asBitmap()
        .imageDecoder(new StreamBitmapDecoder(new Downsampler() {
            ...
        }, Glide.get(context).getBitmapPool(), DecodeFormat.PREFER_ARGB_8888))
        .into(imageView);
```
the problem is that all the downsampler methods are private so you can't just change a little bit of it.

I think @sjudd may accept a well-thought-out refactor PR of Downsampler that exposes some of it's private API as protected. It has came up before somewhere.

**Comment by sjudd** [comment] 2016-05-17 16:08
This would also be easy to expose as an Option in v4. If anyone is interested in implementing this I'd be happy to provide more direction.

**Comment by sjudd** [comment] 2017-10-07 06:05
This field is now deprecated and ignored on newer versions of Android, so I'm going to close this for now: https://developer.android.com/reference/android/graphics/BitmapFactory.Options.html#inPreferQualityOverSpeed

**Closed by sjudd** 2017-10-07 06:05 UTC
Labels: enhancement, question
