### ISSUE TITLE
Loading .webp images using thumbor

### ISSUE THREAD

**Issue by madamczewski** [bumptech/glide#403] opened 2015-04-13 15:41 UTC
**Glide Version/Integration library (if any): 3.5.2
Device/Android Version: Sony Xperia T / 4.1, Samsung S3 mini / 4.2
Issue details/Repro steps:**

Loading .webp images results in black image loaded. Images are loaded from Internet
using thumbor. If they are loaded from local file all works fine.
I am using Pollexor to create thumbor urls. Here is example code:

```java
final String format = Build.VERSION.SDK_INT >= Build.VERSION_CODES.ICE_CREAM_SANDWICH ? "webp" : "jpeg";

final String thumborUrl = Thumbor
        .create(ConstantsApi.THUMBOR_URL)
        .buildImage(imageUrl)
        .filter(String.format(Locale.US, "format(%s)", format))
        .filter(String.format(Locale.US, "quality(%d)", 50))
        .resize(downloadWidth, downloadHeight)
        .fitIn()
        .toUrl();

Glide.with(this)
        .load(thumborUrl)
        .into(imageView);
```

The problem only occurs on pre 4.4.2 devices.
Here is a sample thumbor image to test:
http://img.jafolders.com/unsafe/fit-in/1057x1500/filters:format(webp):quality(100)/http://jafolders.com/uploads/pages/551c0648733100679823e70a/normal_image_1427899988.jpg

I've tested it same way but using Picasso and it works.

I hope for quick response as it is very important bug for me that needs to be quickly repaired.

**Comment by sjudd** [comment] 2015-04-13 15:59
Thanks for the detail, this looks like a duplicate of  #392.

Can you try the 3.6.0-SNAPSHOT version and see if that fixes the issue for you?

**Closed by sjudd** 2015-04-13 15:59 UTC

**Comment by madamczewski** [comment] 2015-04-13 20:05
It is ok now, thanks for quick response
