### ISSUE TITLE
on image view set

### ISSUE THREAD

**Issue by amansatija** [bumptech/glide#480] opened 2015-06-01 16:34 UTC
the on resource ready gets me to the point where image has been loaded but it hasn't been set on image view yet , i need a function in the listener where i get a callback after the image has been set on the imageview ..
please help me with that

**Comment by TWiStErRob** [comment] 2015-06-01 16:49
Duplicate of #275, there's a pointer there on how to workaround this limitation:
```java
Glide.....into(new DrawableImageViewTarget(imageView) {
	@Override protected void setResource(Drawable resource) {
		super.setResource(resource);
		// drawable has been set on ImageView (animation may be in progress!)
	}
});
```

May I ask why you need this? There may be a simpler solution if you change your point of view and adapt to how Glide was designed.

**Comment by amansatija** [comment] 2015-06-01 16:56
I am inserting the imageview in a complex viewgroup that needs the appropriate height of the self wrapping imageview ,so that the viewgroup can appropriately place the header ...
just point me in the direction as to what's the right way , or the right place ,or time for my viewgroup to ask the imageview for it's height

**Comment by TWiStErRob** [comment] 2015-06-01 17:06
Is that a custom viewgroup? Because with the builtin layouts I was able to achieve almost anything, and most of the time without specifying any exact sizing. You can try with the custom target, but it's still asynchronous. I would rather suggest to re-thing your layout structure and make it more flexible and accomodating for a dynamic sized ImageView.

**Comment by amansatija** [comment] 2015-06-02 11:05
Yes it is a custom view group . let me see what can be done

**Comment by sjudd** [comment] 2015-06-08 13:42
Let us know if you still need help.

**Closed by sjudd** 2015-06-08 13:42 UTC
