### ISSUE TITLE
Image's height is less when loading for first time.

### ISSUE THREAD

**Issue by dudhatparesh** [bumptech/glide#1295] opened 2016-06-29 05:12 UTC
**Glide Version**:
Glide version:3.7.0

**Integration libraries**:
okhttp:2.7.0

**Device/Android Version**:
All Devices

**Issue details / Repro steps / Use case background**: 
When Image is loaded for the first time it shows compressed with less height.
Once it gets cached it shows perfect.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context).load(gallery.getPath()).placeholder(R.drawable.logo)
                .override(512, 512)
                .transform(new CenterCrop(context))
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(holder.img);.
```

**Layout XML**:
```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="@dimen/column_width"
    android:layout_height="@dimen/column_width"
    android:orientation="vertical">

    <android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:cardCornerRadius="4dp"
        app:contentPadding="4dp">
        <ImageView
            android:id="@+id/img"
            android:layout_width="122dp"
            android:layout_height="122dp"
            tools:src="@drawable/logo" />
    </android.support.v7.widget.CardView>
</LinearLayout>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by dudhatparesh** [comment] 2016-06-29 05:15
![screenshot_2016-06-29-10-34-25 1](https://cloud.githubusercontent.com/assets/4783878/16441262/9c72a5da-3de6-11e6-96c9-2945c6f736a3.jpg)

**Comment by TWiStErRob** [comment] 2016-07-08 14:56
Hi, sorry, I missed this one. I think this is a duplicate of #363.

The first time the image loads the default `.crossFade()` kicks in and your placeholder aspect ratio is not matching the loaded images' ratio. The second time the image is loaded from memory cache and the animations are skipped in that case, resulting in just loading the image properly. You can disable animations via `.dontAnimate()`, or force a fade-in animation `.animate(R.anim.fade_in)`, or find a placeholder that matches the image's ratio (i.e. square).

Tip: you should remove `.override()` as Glide will figure out the best image size based on the `ImageView`'s defined size, which is hardcoded into the layout anyway. Hardcoding once should be enough, and I think it's better in the view (dp) than in code (px).

Tip 2: you can move `.transform(new CenterCrop(context))` in Java to `scaleType="centerCrop"` in XML, unless you want to add blur or other transformations later.

**Closed by TWiStErRob** 2016-07-08 14:56 UTC
Labels: duplicate, question
