### ISSUE TITLE
Glide 4.6.1 Gif is really slow

### ISSUE THREAD

**Issue by tjouin** [bumptech/glide#2992] opened 2018-03-28 14:51 UTC
Hey I know there are a lot of issue related but none on 4.6.1.

The gif is really slow. I get it from direct file not an Url.

`Glide.with(context).asGif().load(R.raw.update_needed).into(imageView);`

Some idea?

**Comment by sjudd** [comment] 2018-03-30 15:53
Duplicate of #2471

**Closed by sjudd** 2018-03-30 15:53 UTC
Labels: question
