### ISSUE TITLE
java.lang.IllegalArgumentException in glide 4.3.0

### ISSUE THREAD

**Issue by minas90** [bumptech/glide#2568] opened 2017-11-06 16:55 UTC
I got few dozen crashes of a new type with 4.3.0
The crash log from Play dashboard is:

```
java.lang.IllegalArgumentException: 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java)
  at <OR> com.bumptech.glide.manager.RequestManagerRetriever.get (RequestManagerRetriever.java)
  or                     .assertNotDestroyed (RequestManagerRetriever.java)
  or                     .getRequestManagerFragment (RequestManagerRetriever.java)
  or                     .getSupportRequestManagerFragment (RequestManagerRetriever.java)
  at com.bumptech.glide.manager.RequestManagerRetriever.get (RequestManagerRetriever.java)
  or                     .assertNotDestroyed (RequestManagerRetriever.java)
  or                     .getRequestManagerFragment (RequestManagerRetriever.java)
  or                     .getSupportRequestManagerFragment (RequestManagerRetriever.java)
  at com.bumptech.glide.Glide.get (Glide.java)
  or                     .getAnnotationGeneratedGlideModules (Glide.java)
  or                     .with (Glide.java)
  at com.armeniatoday.rss.ui.ArticleActivity.loadSourceData (ArticleActivity.java)
  or                     .access$300 (ArticleActivity.java)
  or                     .access$1200 (ArticleActivity.java)
  at com.armeniatoday.rss.ui.ArticleActivity$$Lambda$5.run (ArticleActivity.java)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
```

**Comment by sjudd** [comment] 2017-11-06 20:04
Duplicate of #803

**Closed by sjudd** 2017-11-06 20:04 UTC
