### ISSUE TITLE
StateVerifier throw if needed 4.4.0

### ISSUE THREAD

**Issue by lam-amsiq** [bumptech/glide#2689] opened 2017-12-06 11:46 UTC
Stack:
```
Fatal Exception: java.lang.IllegalStateException: Already released
       at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(StateVerifier.java:44)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:518)
       at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:217)
       at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:322)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

[Fabric](http://crashes.to/s/77a94a0d3c4)

**Comment by lam-amsiq** [comment] 2017-12-11 12:28
We managed to reproduce the error with that additional information:
```
12-11 13:18:36.540 9220-9220/? W/Bitmap: Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
12-11 13:18:36.540 9220-9220/? W/Bitmap: Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
12-11 13:18:36.540 9220-9220/? W/Bitmap: Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
12-11 13:18:36.719 1429-8786/? W/MdnsClient: Socket thread is null
12-11 13:18:36.823 9220-9220/? W/Glide: Load failed for https://www.soudfa.com/content/portraits-thumb/072/0723544.jpg with size [216x216]
                                        class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                          Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
                                            Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                              Cause (1 of 1): class java.net.UnknownHostException: Unable to resolve host "www.soudfa.com": No address associated with hostname
12-11 13:18:36.823 9220-9220/? I/Glide: Root cause (1 of 1)
12-11 13:18:37.236 9220-9220/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.soudfa, PID: 9220
                                                 java.lang.IllegalStateException: Already released
                                                     at com.bumptech.glide.g.a.b$a.b(StateVerifier.java:44)
                                                     at com.bumptech.glide.request.SingleRequest.a(SingleRequest.java:518)
                                                     at com.bumptech.glide.load.engine.j.c(EngineJob.java:217)
                                                     at com.bumptech.glide.load.engine.j$b.handleMessage(EngineJob.java:322)
                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

The problem appears when going offline while glide is loading a remote resource

**Comment by sjudd** [comment] 2017-12-11 15:22
Can you provide the set of steps that you used to reproduce the error? What load line are you using? How often does it reproduce?

**Comment by lam-amsiq** [comment] 2017-12-11 15:34
Happened 255 times as seen in [Fabric](http://crashes.to/s/77a94a0d3c4)

It happens various place in the code
A load example where we know it can crash: 
```
Glide.with(getContext())
                    .load(account.getProfilePictureThumbUrl())
                    .apply(new RequestOptions()
                            .fitCenter()
                            .centerCrop())
                    .apply(RequestOptions.bitmapTransform(new RoundedCorners(getContext().getResources().getDimensionPixelSize(R.dimen.corner_radius))))
                    .error(getOfflineRequest(R.drawable.as_shared_default_picture_offline, RequestOptions.bitmapTransform(new RoundedCorners(getContext().getResources().getDimensionPixelSize(R.dimen.corner_radius)))))
                    .listener(new RequestListener<Drawable>() {
                        @Override
                        public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                            if (picture == null || progress == null) return false;
                            picture.setVisibility(View.VISIBLE);
                            progress.setVisibility(View.INVISIBLE);
                            if (runnableSuccess != null) { runnableSuccess.run(); }
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                            if (picture == null || progress == null) return false;
                            picture.setVisibility(View.VISIBLE);
                            progress.setVisibility(View.INVISIBLE);
                            if (runnableSuccess != null) { runnableSuccess.run(); }
                            return false;
                        }
                    })
                    .into(picture);
```

To reproduce:
Start many remote loads with Glide and go offline before Glide is done loading

**Comment by sjudd** [comment] 2017-12-11 20:32
Do you have an ``AppGlideModule`` or are you otherwise registering any components? Can you provide the implementation if you are?

**Comment by lam-amsiq** [comment] 2017-12-12 07:44
GlideModule:
```
@com.bumptech.glide.annotation.GlideModule
public class GlideModule extends AppGlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        builder.setIsActiveResourceRetentionAllowed(false);
    }
}
```

Usage:
```
ublic class DefaultImageLoader implements ImageLoader {

    @Override
    public void loadImage(String path, ImageView imageView, ImageType imageType) {
        GlideApp.with(imageView.getContext())
                .load(path)
                .apply(RequestOptions.centerCropTransform()
                        .placeholder(imageType == ImageType.FOLDER ? R.drawable.folder_placeholder : R.drawable.image_placeholder)
                        .error(imageType == ImageType.FOLDER ? R.drawable.folder_placeholder : R.drawable.image_placeholder)
                )
                .into(imageView);
    }
}
```

GlideApp is only used for managing local images and therefor it should not be related to this issue

**Comment by sjudd** [comment] 2017-12-20 06:20
Maybe if you're able to attach a sample app where this is reproducible? I don't see anything obviously wrong with your code.

**Comment by sjudd** [comment] 2017-12-20 06:21
Also are you using any networking libraries? Or just Glide's default?

**Comment by sjudd** [comment] 2017-12-20 06:53
Internal bug is b/70869251

**Comment by trr-amsiq** [comment] 2017-12-23 06:02
We are not able to reproduce on every devices. 
The one that can be crashed manually is an LG G3.
 Glide's default, we use Retrofit and okHTTP for RestAPI calls only.

**Comment by trr-amsiq** [comment] 2018-01-08 14:50
@sjudd Seems to be fixed in 4.5.0

**Comment by sjudd** [comment] 2018-01-08 15:07
Great then I think this was a duplicate of #2767.

**Closed by sjudd** 2018-01-08 15:07 UTC
Labels: bug, repro-needed

**Comment by camino2007** [comment] 2018-02-05 15:05
Still occurs in Glide 4.6.1 

Only on devices below Android 5, it's the same error log how it is already posted. I can reproduce in this way:
I have a ViewPager with Fragments which contains lists with images. When I start a fling on one Fragment and then switch to another Fragment the crash happens.

**Comment by sjudd** [comment] 2018-02-05 15:19
@camino2007 please do file a new issue. If you're using a custom ``Target`` please include that as well.
