### ISSUE TITLE
In glide 4.7  ,Do I have to use reflect if I want a callback for GIF play?

### ISSUE THREAD

**Issue by Everlastingsmile** [bumptech/glide#3070] opened 2018-05-04 02:09 UTC
Glide 4.7 :
public GifDrawable(Context context, GifDecoder gifDecoder, BitmapPool bitmapPool, Transformation frameTransformation, int targetFrameWidth, int targetFrameHeight, Bitmap firstFrame) {
this(context, gifDecoder, frameTransformation, targetFrameWidth, targetFrameHeight, firstFrame);
}

public GifDrawable(Context context, GifDecoder gifDecoder, Transformation frameTransformation, int targetFrameWidth, int targetFrameHeight, Bitmap firstFrame) {
this(new GifDrawable.GifState(new GifFrameLoader(Glide.get(context), gifDecoder, targetFrameWidth, targetFrameHeight, frameTransformation, firstFrame)));
}

GifDrawable：
In these two Constructor，How to get GifDecoder without reflection ?
Or，Do I have to use reflect if I want a callback for GIF play?

**Comment by sjudd** [comment] 2018-05-07 17:15
Duplicate of #1872

**Closed by sjudd** 2018-05-07 17:15 UTC
