### ISSUE TITLE
setting large .placeholder() leads to vertically stretched image

### ISSUE THREAD

**Issue by bluevoidnl** [bumptech/glide#1269] opened 2016-06-14 13:03 UTC
**Glide Version**:3.7.0

**Integration libraries**:

**Device/Android Version**:multiple devices, Samsung Galaxy Tab 3SM-T320, 4.4.2 

**Issue details / Repro steps / Use case background**: 

i have a placeholder of 400 by 507 (X x Y) pixels, most images loaded are this size, some are less wide, some less tall. 
Problem is with the less tall (oblong) images: 400 by 300 pixels. Sometimes (not always!) these are stretched to the full size (507 by 400 pixels). The problem seems to be in the animation code as setting .dontAnimate() resolves the problem. Also removing the placeholder resolves the problem. 

It is like the size of the place holder is used for the animated image. I checked this by loging the size of the drawable that is set on the imageview (by subclassing and logging the method setDrawable()) The drawable that is inserted is 507 pixels high when it is shown wrong (streched) and 300 pixels high when it is shown correct.

The problem does not occur on our less wide images. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**: RecyclerView.Adapter
```java
Glide.with(navigationActivity)
                .load(url) //string url
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .placeholder(R.drawable.cover_placeholder) 
                .into(holder.myImageView); // RecyclerView.ViewHolder with imageview

```

**Layout XML**:
```xml
 <ImageView
            android:id="@+id/fragment_overview_my_image_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:layout_gravity="center"
            android:scaleType="fitCenter"
            />
```

**Stack trace / LogCat**:
```ruby
none
```

**Comment by TWiStErRob** [comment] 2016-06-14 13:08
Dupe of #363, caused by Android's `TransitionDrawable`, different workarounds in comments there.

**Closed by TWiStErRob** 2016-06-14 13:08 UTC
Labels: bug, duplicate, enhancement
