### ISSUE TITLE
gif is slow

### ISSUE THREAD

**Issue by KwonDoby** [bumptech/glide#3272] opened 2018-08-17 09:20 UTC
i use v4.7.1

gif is slow.. help me.

**Comment by githubzjh** [comment] 2018-08-20 02:30
i meet too.    for   large  gif  ,showing is slow, help

**Comment by perracolabs** [comment] 2018-08-22 17:44
See #2471

**Comment by KwonDoby** [comment] 2018-08-22 22:58
There is no answer there.

**Comment by perracolabs** [comment] 2018-08-22 23:07
Is an ongoing issue, currently no solution yet.

**Comment by githubzjh** [comment] 2018-08-22 23:31
@sjudd how to handle ?      Do you have some plans to fix this?

**Comment by KwonDoby** [comment] 2018-08-23 05:33
@sjudd Help!

**Comment by sjudd** [comment] 2018-08-28 15:36
Duplicate of #2471

**Closed by sjudd** 2018-08-28 15:36 UTC

**Comment by KwonDoby** [comment] 2018-08-29 03:45
There is no answer there. - #2471

**Comment by Zhuinden** [comment] 2018-12-06 16:23
There is no answer there.

But it is possible to use a different image loader for GIFs.

What I did is add Fresco:

```
    implementation 'com.facebook.fresco:fresco:1.9.0'
    // For animated GIF support
    implementation 'com.facebook.fresco:animated-gif:1.9.0'
    // For WebP support, including animated WebP
    implementation 'com.facebook.fresco:animated-webp:1.9.0'
    implementation 'com.facebook.fresco:webpsupport:1.9.0'
```

And the `Fresco.initialize(context)` call and stuff that it needs, and also

``` kotlin
class GifDraweeView : SimpleDraweeView {
    private var drawableResource = 0

    constructor(context: Context) : super(context) {
        init(context, null, 0)
    }

    constructor(context: Context, attrs: AttributeSet) : super(context, attrs) {
        init(context, attrs, 0)
    }

    constructor(context: Context, attrs: AttributeSet, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {
        init(context, attrs, defStyleAttr)
    }

    private fun init(context: Context, attributeSet: AttributeSet?, defStyle: Int) {
        if (attributeSet != null) {
            val a: TypedArray? = when {
                defStyle != 0 -> context.obtainStyledAttributes(attributeSet, R.styleable.GifDraweeView, defStyle, 0)
                else -> context.obtainStyledAttributes(attributeSet, R.styleable.GifDraweeView)
            }
            drawableResource = a!!.getResourceId(R.styleable.GifDraweeView_gifResourceDrawable, 0)
            a.recycle()


            if (!isInEditMode) {
                if (drawableResource != 0) {
                    val controller = Fresco.newDraweeControllerBuilder()
                        .setUri(UriUtil.getUriForResourceId(drawableResource))
                        .setAutoPlayAnimations(true)
                        .build()
                    setController(controller)
                }
            }
        }
    }
}
```

and

```
<declare-styleable name="GifDraweeView">
        <attr name="gifResourceDrawable" format="reference"/>
</declare-styleable>
```

And Fresco GIF rendering is not slow, so it's ok
