### ISSUE TITLE
nullpointerexception

### ISSUE THREAD

**Issue by anshul1235** [bumptech/glide#364] opened 2015-03-09 10:17 UTC
```
java.lang.NullPointerException
1at android.graphics.Rect.<init>(Rect.java:72)
2at android.graphics.drawable.ShapeDrawable.mutate(ShapeDrawable.java:377)
3at android.widget.ImageView.applyColorMod(ImageView.java:1033)
4at android.widget.ImageView.updateDrawable(ImageView.java:611)
5at android.widget.ImageView.setImageDrawable(ImageView.java:359)
6at com.bumptech.glide.request.target.ImageViewTarget.void onLoadCleared(android.graphics.drawable.Drawable)(SourceFile:70)
7at com.bumptech.glide.request.GenericRequest.void clear()(SourceFile:312)
8at com.bumptech.glide.GenericRequestBuilder.com.bumptech.glide.request.target.Target into(com.bumptech.glide.request.target.Target)(SourceFile:603)
9at com.bumptech.glide.GenericRequestBuilder.com.bumptech.glide.request.target.Target into(android.widget.ImageView)(SourceFile:647)
10at com.bumptech.glide.BitmapRequestBuilder.com.bumptech.glide.request.target.Target into(android.widget.ImageView)(SourceFile:486)
11at com.app.Utils void loadImage(android.content.Context,ImageView,java.lang.String,size,drawable)(SourceFile:657)
```

happening sometimes

**Comment by sjudd** [comment] 2015-03-09 14:00
Thanks for the report, can you fill out the rest of the [issue template][1], including the version of Glide you're using and any repro steps?

[1]: https://github.com/bumptech/glide/issues/new?body=**Glide%20Version/Integration%20library%20(if%20any)**:%0A**Device/Android%20Version**:%0A**Issue%20details/Repro%20steps**:%0A%0A**Glide%20load%20line**:%0A%60%60%60%0AGlide.with(context)...%3B%0A%60%60%60%0A%0A**Stack%20trace**:%0A%60%60%60%0Apaste%20stack%20trace%20here%0A%60%60%60

**Comment by anshul1235** [comment] 2015-03-15 10:07
I get this error in bugsense.. can't reproduce it, it occurs sometimes.. 
this is the dependency i am using
    compile 'com.github.bumptech.glide:glide:3.5.1'

**Comment by TWiStErRob** [comment] 2015-03-15 11:49
From the stack trace we can see only the following: "you started a load with a placeholder (`ShapeDrawable` or subclass) into an ImageView and the placeholder for some reason can't mutate", so as you see any more relavant info may also help:

 * bugsense should also tell you which phone it occurred on on what android.
 * you said sometimes, how often is that? Is it in a frequented place in your app, or like "about" which barely ever opens?
 * `com.app.Utils` contains the Glide line which greatly affects how we even start to think about solving a bug.
 * try to think if `loadImage` has any known parameters, which are kind of constants, e.g. that drawable is probably a local placeholder from resources.
 * the ImageView's XML layout declaration may also help
 * and if you suspect what may have been in that ImageView prior to the call to `loadImage`.
 * Do you use color filters, alpha, transformations on that ImageView?

You know your app, you can find these things, please help us by sharing them instead of letting us guess blindly.

Thank you in advance!

**Comment by anshul1235** [comment] 2015-03-15 13:20
java.lang.NullPointerException
1at android.graphics.Rect.<init>(Rect.java:72)
2at android.graphics.drawable.ShapeDrawable.mutate(ShapeDrawable.java:377)
3at android.widget.ImageView.applyColorMod(ImageView.java:1033)
4at android.widget.ImageView.updateDrawable(ImageView.java:611)
5at android.widget.ImageView.setImageDrawable(ImageView.java:359)
6at com.bumptech.glide.request.target.ImageViewTarget.void onLoadCleared(android.graphics.drawable.Drawable)(SourceFile:70)
7at com.bumptech.glide.request.GenericRequest.void clear()(SourceFile:312)
8at com.bumptech.glide.GenericRequestBuilder.com.bumptech.glide.request.target.Target into(com.bumptech.glide.request.target.Target)(SourceFile:603)
9at com.bumptech.glide.GenericRequestBuilder.com.bumptech.glide.request.target.Target into(android.widget.ImageView)(SourceFile:647)
10at com.bumptech.glide.BitmapRequestBuilder.com.bumptech.glide.request.target.Target into(android.widget.ImageView)(SourceFile:486)
11at packageName.utils.Utils. loadCircularImage(someparams)
13at android.support.v7.widget.RecyclerView$Adapter.void bindViewHolder(android.support.v7.widget.RecyclerView$ViewHolder,int)(SourceFile:4138)
14at android.support.v7.widget.RecyclerView$Recycler.android.view.View getViewForPosition(int,boolean)(SourceFile:3448)
15at android.support.v7.widget.RecyclerView$Recycler.android.view.View getViewForPosition(int)(SourceFile:3340)
16at android.support.v7.widget.LinearLayoutManager$LayoutState.android.view.View next(android.support.v7.widget.RecyclerView$Recycler)(SourceFile:1810)
17at android.support.v7.widget.LinearLayoutManager.void layoutChunk(android.support.v7.widget.RecyclerView$Recycler,android.support.v7.widget.RecyclerView$State,android.support.v7.widget.LinearLayoutManager$LayoutState,android.support.v7.widget.LinearLayoutManager$LayoutChunkResult)(SourceFile:1306)
18at android.support.v7.widget.LinearLayoutManager.int fill(android.support.v7.widget.RecyclerView$Recycler,android.support.v7.widget.LinearLayoutManager$LayoutState,android.support.v7.widget.RecyclerView$State,boolean)(SourceFile:1269)
19at android.support.v7.widget.LinearLayoutManager.void onLayoutChildren(android.support.v7.widget.RecyclerView$Recycler,android.support.v7.widget.RecyclerView$State)(SourceFile:523)
20at android.support.v7.widget.RecyclerView.void dispatchLayout()(SourceFile:1988)
21at android.support.v7.widget.RecyclerView.void onLayout(boolean,int,int,int,int)(SourceFile:2237)
22at android.view.View.layout(View.java:11315)
23at android.view.ViewGroup.layout(ViewGroup.java:4314)
24at android.support.v4.widget.SwipeRefreshLayout.void onLayout(boolean,int,int,int,int)(SourceFile:543)
25at android.view.View.layout(View.java:11315)
26at android.view.ViewGroup.layout(ViewGroup.java:4314)
27at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1633)
28at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1491)
29at android.widget.LinearLayout.onLayout(LinearLayout.java:1404)
30at android.view.View.layout(View.java:11315)
31at android.view.ViewGroup.layout(ViewGroup.java:4314)
32at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
33at android.view.View.layout(View.java:11315)
34at android.view.ViewGroup.layout(ViewGroup.java:4314)
35at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
36at android.view.View.layout(View.java:11315)
37at android.view.ViewGroup.layout(ViewGroup.java:4314)
38at android.support.v4.view.ViewPager.void onLayout(boolean,int,int,int,int)(SourceFile:1594)
39at android.view.View.layout(View.java:11315)
40at android.view.ViewGroup.layout(ViewGroup.java:4314)
41at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
42at android.view.View.layout(View.java:11315)
43at android.view.ViewGroup.layout(ViewGroup.java:4314)
44at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
45at android.view.View.layout(View.java:11315)
46at android.view.ViewGroup.layout(ViewGroup.java:4314)
47at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
48at android.view.View.layout(View.java:11315)
49at android.view.ViewGroup.layout(ViewGroup.java:4314)
50at android.widget.RelativeLayout.onLayout(RelativeLayout.java:925)
51at android.view.View.layout(View.java:11315)
52at android.view.ViewGroup.layout(ViewGroup.java:4314)
53at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1633)
54at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1491)
55at android.widget.LinearLayout.onLayout(LinearLayout.java:1404)
56at android.view.View.layout(View.java:11315)
57at android.view.ViewGroup.layout(ViewGroup.java:4314)
58at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
59at android.view.View.layout(View.java:11315)
60at android.view.ViewGroup.layout(ViewGroup.java:4314)
61at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1633)
62at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1491)
63at android.widget.LinearLayout.onLayout(LinearLayout.java:1404)
64at android.view.View.layout(View.java:11315)
65at android.view.ViewGroup.layout(ViewGroup.java:4314)
66at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
67at android.view.View.layout(View.java:11315)
68at android.view.ViewGroup.layout(ViewGroup.java:4314)
69at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1633)
70at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1491)
71at android.widget.LinearLayout.onLayout(LinearLayout.java:1404)
72at android.view.View.layout(View.java:11315)
73at android.view.ViewGroup.layout(ViewGroup.java:4314)
74at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
75at android.view.View.layout(View.java:11315)
76at android.view.ViewGroup.layout(ViewGroup.java:4314)
77at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1625)
78at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2642)
79at android.os.Handler.dispatchMessage(Handler.java:99)
80at android.os.Looper.loop(Looper.java:154)
81at android.app.ActivityThread.main(ActivityThread.java:4624)
82at java.lang.reflect.Method.invokeNative(Native Method)
83at java.lang.reflect.Method.invoke(Method.java:511)
84at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
85at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
86at dalvik.system.NativeStart.main(Native Method)


above is the whole stack trace.. Below is the loadImageView function 

 Glide.with(context)// errors shows at this line
                .load(imageUrl)
                .asBitmap()
                .animate(R.anim.fade_in)
                .placeholder(drawable)
                .transform(AvatarBitmapTransformation.transformationFor(context, avatarSize))
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .error(drawable)
                .into(imageView);


model details(i have not covered all)

OS	Android 4.0.4
App Version	1.0.3
Device	Lenovo A390_ROW
Country	IN
sysMemAvail	0.0
sysMemLow	false
wifi_on	1
mobile_net_on	2
rooted	false
internal_version	32
screen_dpi(x:y)	240.0:240.0
locale	English
brand	unknown
ms_from_start	4849
gps_on	0
appMemTotal	15.757781982421875
sysMemThreshold	0.0
apps_running	no_permissions
sdk_version	3.6.1
screen:height	800
screen:orientation	normal
appMemMax	64.0
screen:width	480
appMemAvail	0.1052093505859375

**Comment by sjudd** [comment] 2015-03-24 14:24
Is it possible this is a duplicate of #349? This looks somewhat similar. You could check by trying the snapshot version and seeing if you can still reproduce the issue.

Thanks!

**Comment by sjudd** [comment] 2015-03-31 13:44
Let us know if you can still reproduce this...

**Closed by sjudd** 2015-03-31 13:44 UTC
