### ISSUE TITLE
java.lang.NoSuchMethodError: No static method getFont

### ISSUE THREAD

**Issue by jonneymendoza** [bumptech/glide#2796] opened 2018-01-09 16:28 UTC
Hi

i am getting the error below using this library.

java.lang.NoSuchMethodError: No static method getFont

it crashes as soon as i open up a UI.

If i remove //    implementation 'com.github.bumptech.glide:glide:4.5.0'
//    annotationProcessor 'com.github.bumptech.glide:compiler:4.5.0' it works fine

Its something to do with the library using vversion 27 of the support library while i am using version 26

**Comment by sjudd** [comment] 2018-01-10 01:35
Duplicate of #2730

**Closed by sjudd** 2018-01-10 01:35 UTC
