### ISSUE TITLE
[Compose] Modifier is applied twice

### ISSUE THREAD

**Issue by ln-12** [bumptech/glide#5307] opened 2023-10-04 08:39 UTC
**Glide Version**: 4.16.0 / 1.0.0-alpha.5

**Device/Android Version**: compose preview, Pixel 7, Emulator (both API 33)

**Issue details / Repro steps / Use case background**: 

I noticed that modifiers which are applied to a `GlideImage`, are applied twice. In the example shown below, you can see that the padding as well as the background modifier are applied two times. The expected behavior is that each modifier is only applied once so that the padding is actually only `10.dp` and that the background is only visible once too.

<img width="301" alt="image" src="https://github.com/bumptech/glide/assets/36760115/3cff4360-dbf5-4f37-a024-5c00327f9b58">

My code example looks like this: 
```kotlin
Column(
        modifier = Modifier.background(Color.Red)
) {
    GlideImage(
            model = R.drawable.lb_background,
            contentDescription = null,
            modifier = Modifier
                .padding(10.dp)
                .background(Color.Green)
                .height(150.dp)
                .fillMaxWidth()
                .clip(RoundedCornerShape(10.dp))
                .background(Color.Yellow),
            contentScale = ContentScale.Crop,
    )
}
```

As far as I can tell, the issue is related to this code block: https://github.com/bumptech/glide/blob/b1c6076bbbc3cc46d45f35924070cb11be44ff90/integration/compose/src/main/java/com/bumptech/glide/integration/compose/GlideImage.kt#L120-L153

The modifier that is provided to `GlideImage` is passed on to both `GlideSubcomposition` and each of the child composables which causes the duplication. The solution would be to either use the modifier  on the `GlideSubcomposition` **OR** use it one the child composables.

**Comment by sjudd** [comment] 2023-10-04 23:46
Thanks, I think your bug is a duplicate of #5272 because I don't see you using `GlideSubcomposition` or providing a composable placeholder, so you won't hit the codepath in `GlideImage` you pointed out.

That said, It may still be a bug that the modifier is applied twice, so I'll leave this open. If we do submit #5306, then this will be "fixed" (as in deleted) as well.

**Closed** 2023-10-17 04:08 UTC
Labels: bug, Compose
