### ISSUE TITLE
SupportRequestManagerFragment.onLowMemory(SupportRequestManagerFragment.java) #NoSuchElementException

### ISSUE THREAD

**Issue by glenfordshadowfernandes** [bumptech/glide#1494] opened 2016-10-03 10:08 UTC
```
java.util.NoSuchElementException
at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:350)
at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:376)
at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:374)
at com.bumptech.glide.util.LruCache.trimToSize(LruCache.java:157)
at com.bumptech.glide.util.LruCache.clearMemory(LruCache.java:146)
at com.bumptech.glide.Glide.clearMemory(Glide.java:370)
at com.bumptech.glide.RequestManager.onLowMemory(RequestManager.java:95)
at com.bumptech.glide.manager.SupportRequestManagerFragment.onLowMemory(SupportRequestManagerFragment.java:156)
```

**Issue occurs in Glide version 3.6.1**

**Comment by TWiStErRob** [comment] 2016-10-03 11:42
Duplicate of #722, can you reproduce it?

**Closed** 2017-09-09 06:54 UTC
Labels: bug, duplicate
