### ISSUE TITLE
Feature Request: Hooks to know when image loading finished for all requests

### ISSUE THREAD

**Issue by agrvaibhav** [bumptech/glide#3595] opened 2019-04-03 09:49 UTC
Glide 3.8.0

Is there a callback provided by `Glide` library when loading of all the images are completed for an `Activity` or `Fragment`? We want to take certain actions when that is done.

If not, any pointers how to get that callback.

I have seen https://github.com/bumptech/glide/issues/1440, but I would like to completely avoid reflection since it will be part of shipped code within APK.

**Comment by sjudd** [comment] 2019-04-05 14:14
There is no such API in 3.8.

**Comment by agrvaibhav** [comment] 2019-04-06 14:38
@sjudd Is there a way to find it out? Any suggestions?

**Comment by sjudd** [comment] 2019-04-09 14:11
For Glide 3, I think this is an exact duplicate of #1440, all of the ideas anyone has had are there.

**Closed by sjudd** 2019-04-09 14:11 UTC
