### ISSUE TITLE
Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by waynell** [bumptech/glide#894] opened 2016-01-15 08:14 UTC
```ruby
java.lang.InternalError:Thread starting during runtime shutdown
at java.lang.Thread.nativeCreate(Thread.java)
at java.lang.Thread.start(Thread.java:1063)
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:989)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.DefaultThreadFactory$1.run(SourceFile:118)
```

I got this exception when loading image, please take a look.

Glide Version: 3.6.1
Device: Nexus 6P
OS: Android 6.0

Thanks

**Comment by TWiStErRob** [comment] 2016-01-15 08:58
Where were you loading that image (life cycle event or async)? What is your Glide line?

**Comment by waynell** [comment] 2016-01-15 09:04
@TWiStErRob 
loading image in RecyclerView.Adapter.onBindViewHolder()

**Glide load line**:
```java
Glide.with(fragment)
     .load(url)
     .dontAnimate()
     .placeholder(R.drawable.placeholder)
     .override(itemWidth, itemWidth)
     .into(imageView);
```

**Comment by TWiStErRob** [comment] 2016-01-15 09:23
How is the adapter set to the recycler view?

What I'm trying to get with these questions is that you may be calling Glide after stuff has been started to finish already. You may need to check for `isFinishing()` or `isDestroyed`. or clear your adapter (null it in recycler view) in some of the teardown life cycle events.

**Comment by waynell** [comment] 2016-01-15 11:41
I set adapter when fragment onCreateView(), then use Glide to load my image in adapter. The image size is about 720*720(a half of screen width) and many images to load. I think it's OOM, but not throw it    immediately.

**Comment by TWiStErRob** [comment] 2016-01-15 11:43
Can you consistently reproduce this? Could you make a repro app?

**Comment by waynell** [comment] 2016-01-16 07:30
I can't consistently reproduce it, it happened only once.
Following pictures show this bug's status that I captured from Fabirc.
To reproduce it, please download our app from google play. [download link](https://play.google.com/store/apps/details?id=com.roidapp.photogrid)

![1](https://cloud.githubusercontent.com/assets/1710119/12371111/6121d708-bc63-11e5-9fef-605e64365de2.png)

![2](https://cloud.githubusercontent.com/assets/1710119/12371166/8945f1a4-bc65-11e5-9f1f-9a12e8608d15.png)

![3](https://cloud.githubusercontent.com/assets/1710119/12371167/8edec53c-bc65-11e5-8b2c-da63e9b08222.png)

**Comment by TWiStErRob** [comment] 2016-01-16 08:49
*The OOM is from a different device, they are highly likely not related. OOM can surface anywhere (usually not at the cause), and can be caused by anything (usually memory leak, rarely excessive memory usage).*

Back to this issue: it is probably something like the user started the app and then immediately stopped it/the app finished itself, check possible orderings between: `Fragment.onCreateView`, `Activity.finish`, `Adapter.onBind`, recent apps swipe (or force stop)

**Comment by waynell** [comment] 2016-01-16 09:06
Okay, thank you very much. I want to make a simple app to reproduce this, but it's too difficult. If I have any good idea to reproduce it, I will tell you as soon as possible.

**Comment by TWiStErRob** [comment] 2016-01-16 09:15
It's OK if the repro is long/complex/hard as long as it consistently produces a result.

**Comment by TWiStErRob** [comment] 2016-03-19 00:11
Did you have time to think about this?

**Comment by waynell** [comment] 2016-03-19 05:59
yes, I did. I made a simple app for reproduce it, but no result as I expected.   Sorry I couldn't help you.  :-(

**Comment by TWiStErRob** [comment] 2016-03-19 10:00
Thanks! I'll close it now, because it's unlikely we can make any progress without a repro. If **anyone** has any extra info please comment!

**Closed by TWiStErRob** 2016-03-19 10:00 UTC
Labels: bug, repro-needed

**Comment by erossssssss** [comment] 2017-12-21 08:21
I encountered this problem recently, it happened two times on one device. So I thought it may appear in Adapter.onBind which is called after activity is destroyed. But I failed to reproduce it .
