### ISSUE TITLE
How to get the cache file from disk cache by using url？ 

### ISSUE THREAD

**Issue by JackLiaoJH** [bumptech/glide#695] opened 2015-10-19 03:56 UTC
I have to load the data to the cache, but I find  that I didn't find such a method that I want to find the cache source path by using the url, like this: `File file = .get(url);`
Only find that:
```java
future = Glide.with(mContext).downloadOnly().load(sticker.getPictureUrl()).submit();

File cacheFile = future.get();
```

How i do it?

**Comment by TWiStErRob** [comment] 2015-10-19 11:01
There's no sync method for that, because it requires blocking I/O.

This is a duplicate of #509, please press subscribe on the right column on that issue if you want to get updates.

**Comment by JackLiaoJH** [comment] 2015-10-19 14:23
Thanks!

**Closed** 2015-10-19 14:28 UTC
Labels: duplicate, question, v4
