### ISSUE TITLE
GifDecoder

### ISSUE THREAD

**Issue by squm** [bumptech/glide#2874] opened 2018-02-05 08:37 UTC
**Glide Version**:
4.6.0

**Integration libraries**:
```
implementation 'com.github.bumptech.glide:glide:4.6.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.6.0'
```

**Stack trace / LogCat**:
```
E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider;
E AndroidRuntime: 	at com.bumptech.glide.Glide.<init>(Glide.java:338)
E AndroidRuntime: 	at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:472)
E AndroidRuntime: 	at com.bumptech.glide.Glide.initializeGlide(Glide.java:264)
E AndroidRuntime: 	at com.bumptech.glide.Glide.initializeGlide(Glide.java:219)
E AndroidRuntime: 	at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:180)
E AndroidRuntime: 	at com.bumptech.glide.Glide.get(Glide.java:164)
E AndroidRuntime: 	at com.bumptech.glide.Glide.getRetriever(Glide.java:670)
E AndroidRuntime: 	at com.bumptech.glide.Glide.with(Glide.java:709)



Warning: com.bumptech.glide.load.resource.gif.GifBitmapProvider: can't find superclass or interface com.bumptech.glide.gifdecoder.GifDecoder$BitmapProvider
Warning: com.bumptech.glide.Glide: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache$Value
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache$Editor
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache$Editor
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache$Editor
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache$Value
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache$Editor
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache$Value
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache$Value
Warning: com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper: can't find referenced class com.bumptech.glide.disklrucache.DiskLruCache$Editor
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeader
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeader
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeader
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeader
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeader
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder$BitmapProvider
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeader
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeader
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifHeader
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifDecoderFactory: can't find referenced class com.bumptech.glide.gifdecoder.StandardGifDecoder
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifDecoderFactory: can't find referenced class com.bumptech.glide.gifdecoder.StandardGifDecoder
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifDecoderFactory: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder$BitmapProvider
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifDecoderFactory: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifDecoderFactory: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder$BitmapProvider
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifDecoderFactory: can't find referenced class com.bumptech.glide.gifdecoder.GifHeader
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifDecoderFactory: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifDecoderFactory: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder$BitmapProvider
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifDecoderFactory: can't find referenced class com.bumptech.glide.gifdecoder.GifHeader
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifHeaderParserPool: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifHeaderParserPool: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifHeaderParserPool: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifHeaderParserPool: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifHeaderParserPool: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifHeaderParserPool: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifHeaderParserPool: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifHeaderParserPool: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder$GifHeaderParserPool: can't find referenced class com.bumptech.glide.gifdecoder.GifHeaderParser
Warning: com.bumptech.glide.load.resource.gif.GifBitmapProvider: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder$BitmapProvider
Warning: com.bumptech.glide.load.resource.gif.GifBitmapProvider: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifDrawable: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifDrawable: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifDrawable: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifDrawable: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifDrawable: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifDrawable: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifDrawable: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameLoader: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Warning: com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder: can't find referenced class com.bumptech.glide.gifdecoder.GifDecoder
Note: com.bumptech.glide.Glide: can't find dynamically referenced class com.bumptech.glide.GeneratedAppGlideModuleImpl
```

**Comment by sjudd** [comment] 2018-02-05 15:24
Duplicate of #2863

**Closed by sjudd** 2018-02-05 15:24 UTC
