### ISSUE TITLE
ava.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by xy348735514** [bumptech/glide#3051] opened 2018-04-26 00:26 UTC
Process: com.jtv.androidframeworkdemo, PID: 23997
                                                                              java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.jtv.androidframeworkdemo-1/base.apk)
                                                                                  at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
                                                                                  at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:208)
                                                                                  at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:110)
                                                                                  at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
                                                                                  at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
                                                                                  at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
                                                                                  at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1024)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1081)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                  at android.view.View.inflate(View.java:21164)
                                                                                  at com.jtv.android.activity.BaseActivity.onCreate(BaseActivity.java:48)
                                                                                  at com.jtv.androidframeworkdemo.HomeActivity.onCreate(HomeActivity.java:49)
                                                                                  at android.app.Activity.performCreate(Activity.java:6813)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2802)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2921)
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1647)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:159)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6355)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
04-25 21:48:19.975 1372-1408/? E/ActivityManager: handleShowAppErrorUi proc ProcessRecord{7db9670 23997:com.jtv.androidframeworkdemo/u0a457} died showBackground=false
04-25 21:48:19.975 1372-1408/? E/ActivityManager: handleShowAppErrorUi isBackground=false mDebuggable=falseshowBackground=false
04-25 21:48:19.984 536-536/? E/lowmemorykiller: Error writing /proc/23997/oom_score_adj; errno=22

**Comment by sjudd** [comment] 2018-04-26 16:09
Duplicate of #2730

**Closed by sjudd** 2018-04-26 16:09 UTC
