### ISSUE TITLE
how to load bitmap for imageview without url, uri, drawable, asset with this library?

### ISSUE THREAD

**Issue by DoaiNguyen** [bumptech/glide#1178] opened 2016-05-03 08:42 UTC
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment] 2016-05-03 09:35
`ImageView.setImageBitmap(bitmap)`?
What are you trying to gain by using Glide in this case?

Possible duplicate of #122 or http://stackoverflow.com/a/31940058/253468.

**Closed** 2016-07-07 19:36 UTC
Labels: invalid, question
