### ISSUE TITLE
SocketTimeoutException sometimes thrown on loading image

### ISSUE THREAD

**Issue by alexfacciorusso** [bumptech/glide#433] opened 2015-04-21 20:21 UTC
**Glide Version/Integration library (if any)**: Glide 3.5.2, no integration library
**Device/Android Version**: Nexus 5 8GB, Lollipop 5.1
**Issue details/Repro steps**: When I load images (i.e. into a RecyclerView's adapter), sometimes it throws SocketTimeoutException, not loading some images. 

**Glide load line**:
```
Glide.with(this).load(mThumbnail).into(new SimpleTarget<GlideDrawable>() {...});
```

**Stack trace**:
```
04-21 22:06:41.021    3315-3315/******************* D/GenericRequest﹕ load failed
    java.net.SocketTimeoutException
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
            at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
            at com.android.okio.Okio$2.read(Okio.java:113)
            at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:147)
            at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:94)
            at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
            at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
            at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
            at com.bumptech.glide.load.a.f.a(SourceFile:68)
            at com.bumptech.glide.load.a.f.b(SourceFile:40)
            at com.bumptech.glide.load.a.f.a(SourceFile:17)
            at com.bumptech.glide.load.c.g.b(SourceFile:70)
            at com.bumptech.glide.load.c.g.a(SourceFile:53)
            at com.bumptech.glide.load.b.a.e(SourceFile:170)
            at com.bumptech.glide.load.b.a.c(SourceFile:128)
            at com.bumptech.glide.load.b.u.f(SourceFile:122)
            at com.bumptech.glide.load.b.u.d(SourceFile:101)
            at com.bumptech.glide.load.b.u.run(SourceFile:58)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at com.bumptech.glide.load.b.c.c.run(SourceFile:52)
```

**Comment by TWiStErRob** [comment] 2015-04-22 19:13
This looks like a duplicate of #432.

**Comment by sjudd** [comment] 2015-04-23 03:03
Yup, closing as a duplicate, feel free to follow up there if you have questions.

**Closed by sjudd** 2015-04-23 03:03 UTC
