### ISSUE TITLE
Use glide v4.6.1 error

### ISSUE THREAD

**Issue by YukiExcalibur** [bumptech/glide#2973] opened 2018-03-22 09:34 UTC
Press the delete key on the keyboard or the return key app crashes.
What I used before was that v3.6.1 app did not crash.
this log :
 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/view/KeyEventCompat;
                                                                at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:526)
                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
                                                                at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
                                                                at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:320)
                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4377)
                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4348)
                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3892)
                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3945)
                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3911)
                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4038)
                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3919)
                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4095)
                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3892)
                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3945)
                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3911)
                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3919)
                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3892)
                                                                at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6263)
                                                                at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6237)
                                                                at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6198)
                                                                at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3687)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:163)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6348)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.view.KeyEventCompat" on path: DexPathList[[zip file "/data/app/com.rm.tcart-2/base.apk"],nativeLibraryDirectories=[/data/app/com.rm.tcart-2/lib/arm, /data/app/com.rm.tcart-2/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:526) 
                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59) 
                                                                at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319) 
                                                                at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:320) 
                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4377) 
                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4348) 
                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3892) 
                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3945) 
                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3911) 
                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4038) 
                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3919) 
                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4095) 
                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3892) 
                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3945) 
                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3911) 
                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3919) 
                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3892) 
                                                                at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6263) 
                                                                at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6237) 
                                                                at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6198) 
                                                                at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3687) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                at android.os.Looper.loop(Looper.java:163) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:6348) 
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by songj056** [comment] 2018-03-22 09:50
666

**Comment by sjudd** [comment] 2018-03-22 16:02
Probably a duplicate of #2730

**Closed by sjudd** 2018-03-22 16:02 UTC
