### ISSUE TITLE
Question: HEIF support?

### ISSUE THREAD

**Issue by gajicm93** [bumptech/glide#2975] opened 2018-03-22 17:01 UTC
Can we expect HEIF support anytime soon, and do you know if Google plans to backport decoding natively and efficiently back to API 14+? I see they have HeifWriter in support libs for writing and encoding, but what about decode and Glide support?

**Comment by sjudd** [comment] 2018-03-27 15:06
Duplicate of #2534

**Closed by sjudd** 2018-03-27 15:06 UTC
