### ISSUE TITLE
Glide 4.1.0 - Can't compile with android studio 3.0 Beta 4

### ISSUE THREAD

**Issue by wezley98** [bumptech/glide#2328] opened 2017-09-04 16:32 UTC
Getting the following error in Android Studio 3.0 Beta 4 with the following deps:

implementation 'com.github.bumptech.glide:glide:4.1.0'
implementation 'com.github.bumptech.glide:okhttp3-integration:4.1.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.1.0'

Gradle file:
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 26
...............

gradle.properties as follows:
android.enableAapt2=true
#android.enableD8=true
#org.gradle.caching=true
org.gradle.jvmargs=-Xmx1536m

Tried multiple cleans and rebuilds. Dropping back down to Glide 4.0.0 on all deps and everything works again. Any ideas?

> :app:transformClassesWithAndroidGradleClassShrinkerForDebug
-allowaccessmodification is ignored by the built-in class shrinker.
com/bumptech/glide/integration/okhttp/R$integer references unknown class: com/bumptech/glide/integration/okhttp/R
com/bumptech/glide/integration/okhttp/R$style references unknown class: com/bumptech/glide/integration/okhttp/R
com/bumptech/glide/integration/okhttp/R$color references unknown class: com/bumptech/glide/integration/okhttp/R
com/bumptech/glide/integration/okhttp/R$string references unknown class: com/bumptech/glide/integration/okhttp/R
com/bumptech/glide/R$drawable references unknown class: com/bumptech/glide/R
com/bumptech/glide/R$layout references unknown class: com/bumptech/glide/R
com/bumptech/glide/integration/okhttp/R$layout references unknown class: com/bumptech/glide/integration/okhttp/R
com/bumptech/glide/R$bool references unknown class: com/bumptech/glide/R
com/bumptech/glide/integration/okhttp/R$bool references unknown class: com/bumptech/glide/integration/okhttp/R
com/bumptech/glide/R$string references unknown class: com/bumptech/glide/R
com/bumptech/glide/integration/okhttp/R$drawable references unknown class: com/bumptech/glide/integration/okhttp/R
com/bumptech/glide/R$color references unknown class: com/bumptech/glide/R
com/bumptech/glide/R$style references unknown class: com/bumptech/glide/R
com/bumptech/glide/R$integer references unknown class: com/bumptech/glide/R
:app:transformClassesWithAndroidGradleClassShrinkerForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithAndroidGradleClassShrinkerForDebug'.
> Warnings found during shrinking, please use -dontwarn or -ignorewarnings to suppress them.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s

39 actionable tasks: 15 executed, 24 up-to-date

**Comment by wezley98** [comment] 2017-09-04 16:34
related to #2322 ?

**Comment by sjudd** [comment] 2017-09-04 20:48
Duplicate of #2322

**Closed by sjudd** 2017-09-04 20:49 UTC
