### ISSUE TITLE
The method setLoopCount()  doesn't work?

### ISSUE THREAD

**Issue by eggcaker** [bumptech/glide#1824] opened 2017-03-29 11:34 UTC
does  the setLoopCount() method working in 3.7.1  or not release yet ??
**Glide Version**: 3.7.1
**Device/Android Version**: Nexus 6p
**Glide load :
```java
@Override public boolean onResourceReady(GifDrawable resource, Integer model, Target<GifDrawable> target,
              boolean isFromMemoryCache, boolean isFirstResource) {
            if (resource != null)
              resource.setLoopCount(2);

            return false;
          }
```

**Layout XML**:
```xml
<ImageView
              android:id="@+id/level2_icon"
              android:src="@drawable/level2_holder"
              android:layout_marginTop="25dp"
              android:layout_marginRight="25dp"
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"/>

```

**Comment by TWiStErRob** [comment] 2017-03-29 11:58
Don't use a listener, use `.fitCenter().into(new GlideDrawableImageViewTarget(imageView, 3))`.
Dupe of #860

**Closed by TWiStErRob** 2017-03-29 11:58 UTC
