### ISSUE TITLE
how can retry when image loading failed 

### ISSUE THREAD

**Issue by pawarlalit29** [bumptech/glide#520] opened 2015-07-02 08:26 UTC
how can retry when image loading failed

**Comment by TWiStErRob** [comment] 2015-07-02 11:51
This is a duplicate of #348. There's no Glide API for that, but you can replace the networking layer and set up retry there. For how to add Okhttp see #519, the wiki and also look at 432 and 513 for more info.

**Comment by sjudd** [comment] 2015-07-03 05:17
Let us know if you have more specific questions. I believe Volley is the only library that explicitly retries failed requests more than once and allows you to configure the number of retries, but I'm not as familiar with OkHttp so it's possible they have some retry semantics as well.

**Closed by sjudd** 2015-07-03 05:17 UTC

**Comment by pawarlalit29** [comment] 2015-07-03 11:56
heavy size image are not loading at first time ,
they cached first then load its take to much time

**Comment by TWiStErRob** [comment] 2015-07-03 12:04
Are those heavy images GIFs?

**Comment by pawarlalit29** [comment] 2015-07-03 12:06
no its jpeg image

**Comment by TWiStErRob** [comment] 2015-07-03 12:13
How do you know it's cached? If the load takes a lot of time it's probably loading it from the network...

**Comment by pawarlalit29** [comment] 2015-07-03 12:14
ya sure but when recall that image then they quickly appear bcoz of they previously cached

**Comment by TWiStErRob** [comment] 2015-07-03 17:39
Discussion is continued in #522.
