### ISSUE TITLE
When I setup the is PREFER_RGB_565，gif image display abnormal 

### ISSUE THREAD

**Issue by wangrunxiang** [bumptech/glide#3087] opened 2018-05-14 09:13 UTC
**Glide Version**:4.7.1

**Integration libraries**:

**Device/Android Version**:xiaomi 6 Android8.0

**Issue details / Repro steps / Use case background**: 

the gif url is http://emyfs.bs2cdn.yy.com/Zjk0MDVmYTItNThlYi00MzdkLWJmNWYtNzZkYmUzY2Y1YmUw.jpg

the gif is has alapha channel

glide load display effect
![image](https://user-images.githubusercontent.com/10829860/39988662-8668670a-579a-11e8-858a-2822af930a6c.png)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(MainActivity.this.getApplicationContext()).load(strs[0]).into(mIv);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
2018-05-14 22:01:13.205 16693-16693/com.wangrunxiang.glidedemo I/MyGlideModule: applyOptions
2018-05-14 22:01:13.275 16693-16952/com.wangrunxiang.glidedemo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2018-05-14 22:01:13.359 16693-16701/com.wangrunxiang.glidedemo I/zygote64: Do partial code cache collection, code=30KB, data=21KB
2018-05-14 22:01:13.360 16693-16701/com.wangrunxiang.glidedemo I/zygote64: After code cache collection, code=29KB, data=20KB
2018-05-14 22:01:13.360 16693-16701/com.wangrunxiang.glidedemo I/zygote64: Increasing code cache capacity to 128KB
2018-05-14 22:01:17.229 16693-16701/com.wangrunxiang.glidedemo I/zygote64: Do partial code cache collection, code=61KB, data=45KB
2018-05-14 22:01:17.230 16693-16701/com.wangrunxiang.glidedemo I/zygote64: After code cache collection, code=54KB, data=43KB
2018-05-14 22:01:17.230 16693-16701/com.wangrunxiang.glidedemo I/zygote64: Increasing code cache capacity to 256KB
2018-05-14 22:01:17.796 16693-16701/com.wangrunxiang.glidedemo I/zygote64: Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()
```

**Comment by sjudd** [comment] 2018-05-14 15:44
Duplicate of #3023

**Closed by sjudd** 2018-05-14 15:44 UTC

**Comment by hufeiyang** [comment] 2020-06-09 12:13
这个是怎么解决的啊？
