### ISSUE TITLE
we all urgently need glide support loading animate webp, there is any update plan about it?

### ISSUE THREAD

**Issue by ShamsChu** [bumptech/glide#2597] opened 2017-11-14 03:40 UTC
We found that Glide did not work well when loading some larger GIFs, and in order to optimize it, we converted the GIF to webp, but it's a surprise that glide does not support loading it, There are someone trying to embed Fresco's webp-animite module in Glide now, but there are some uncontrollable issues. Hopefully glide will support it soon. If there is any intention, let us know thank you.

**Comment by sjudd** [comment] 2017-11-14 05:31
Duplicate of #571.

I'll add an update there.

**Closed by sjudd** 2017-11-14 05:31 UTC
Labels: enhancement

**Comment by ShamsChu** [comment] 2017-11-15 02:39
Really thanks! Looking forward to updating.

**Comment by ShamsChu** [comment] 2017-11-15 02:42
Is there any way that the current glide version can support animated webp?  we are grateful if there is a solution.

**Comment by sjudd** [comment] 2017-11-15 05:08
@ShamsChu You can always define your own ``ResourceDecoder`` if you have a library available that can decode animated webps and play them. There is no out of the box solution available at the moment.

**Comment by ShamsChu** [comment] 2017-11-15 06:34
@sjudd OK thank you i will try.
