### ISSUE TITLE
Is there a way to load GradientDrawable with Glide (and with crossfade animation)?

### ISSUE THREAD

**Issue by skrrgh** [bumptech/glide#2357] opened 2017-09-08 00:08 UTC
**Glide Version**: 3.8.0

**Integration libraries**: none

**Device/Android Version**: any

**Issue details / Repro steps / Use case background**: 

I try to load a gradient, which is defined as `my_gradient.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <gradient
        android:type="linear"
        android:angle="0"
        android:startColor="#f6ee19"
        android:endColor="#115ede" />
</shape>
```
Loading code:
```java
Glide.with(context).load(R.id.my_gradient).crossFade().into(imageView);
```
But the ImageView is still empty.

If I  create GradientDrawable programmatically I get the following exception:
```java
GradientDrawable gd = new GradientDrawable(
            GradientDrawable.Orientation.TOP_BOTTOM, new int[] {0xFF616261, 0xFF131313});
gd.setCornerRadius(0f);
Glide.with(context).load(gd).crossFade().into(imageView);
```

```
java.lang.IllegalArgumentException: Unknown type class android.graphics.drawable.GradientDrawable. You must provide a Model of a type for which there is a registered ModelLoader, if you are using a custom model, you must first call Glide#register with a ModelLoaderFactory for your custom model class
                                                                           at com.bumptech.glide.RequestManager.loadGeneric(RequestManager.java:629)
                                                                           at com.bumptech.glide.RequestManager.load(RequestManager.java:598)
```

Do I something wrong or there is no way to load gradients with Glide?

**Comment by TWiStErRob** [comment] 2017-09-08 00:27
Duplicate of #122

`load(R.drawable.foo)` should work too (note: not `R.id`)

Check out https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling to see why the view ends up empty.

**Closed by TWiStErRob** 2017-09-08 00:27 UTC
