### ISSUE TITLE
Images dont load in recycler view

### ISSUE THREAD

**Issue by vavan4567** [bumptech/glide#964] opened 2016-02-05 19:30 UTC
Hello guys! Have an issue with image displaying.

here is my onBindViewHolder code 
```java
public void onBindViewHolder(ImagesViewHolder holder, int position) {
    ImageEntity image = list.get(position);
    ImageView imageView =  holder.imageView;
    imageView.setImageDrawable(null);
    Glide.with(context)
            .load(image.simpleUrl)
            .centerCrop()
            .diskCacheStrategy(DiskCacheStrategy.ALL)
            .listener(new RequestListener<String, GlideDrawable>() {
                @Override
                public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                    Log.e("IMAGE_EXCEPTION", "Exception " + e.toString());
                    return false;
                }

                @Override
                public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                    return false;
                }
            })
            .into(imageView);
}
```

but after I scroll recyclerView up I got this 
![image](https://cloud.githubusercontent.com/assets/8720664/12856865/af4a61d8-cc4f-11e5-9d58-625610043373.png)
Please help me, thanks

**Comment by TWiStErRob** [comment] 2016-02-05 21:51
Remove `setImageDrawable`, Glide clears the view automatically: read the code of `into(ImageView)`.

**Comment by vavan4567** [comment] 2016-02-05 22:34
Removed, but didn't help. Images continue disapearing

**Comment by TWiStErRob** [comment] 2016-02-05 22:50
Do you have any other interactions with `holder.`ImageView`? Is it possible that `image.simpleUrl` is null for that position? (worth a quick debug or log)

Also a tip to get more info if something goes wrong:
```java
Log.e("IMAGES", "Failed to load " + model, e);
```
With this overload you get the model and the full stack trace.

**Comment by vavan4567** [comment] 2016-02-05 23:07
Urls are not null. Logs show nothing, and images load but after I scroll back they are disapearing. Maybe it is because I updated my recycler view to version 23.1.1? Also attaching here the whole code of the Adapter 

`public class RecyclerViewAdapter extends RecyclerView.Adapter<RecyclerViewAdapter.ImagesViewHolder>{

    private static final int TYPE_HEADER = 2;
    private static final int TYPE_ITEM = 1;
    private Activity context;

    private List<ImageEntity> list;
    public RecyclerViewAdapter(Activity context, List<ImageEntity> list) {
        this.list = list;
        this.context = context;
    }


    @Override
    public ImagesViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        LayoutInflater inflater = LayoutInflater.from(context);
        View convertView = inflater.inflate(R.layout.image_item, parent, false);

        int widthOfColumn = Utils.GetScreenWidth(context)/Utils.NUM_OF_COL;
        ImageView imageView = (ImageView) convertView.findViewById(R.id.imageView);
        imageView.getLayoutParams().width = widthOfColumn;
        imageView.getLayoutParams().height = widthOfColumn;
        imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
        ImagesViewHolder holder =  new ImagesViewHolder(convertView);
        holder.imageView = imageView;
        return holder;
    }

    @Override
    public int getItemCount() {
        return list == null ? 0 : list.size();
    }

    @Override
    public void onBindViewHolder(ImagesViewHolder holder, int position) {

        ImageEntity image = list.get(position);
        ImageView imageView =  holder.imageView;
     //   imageView.setImageDrawable(null);
        Glide.with(context)
                .load(image.simpleUrl)
                .centerCrop()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        Log.e("IMAGE_EXCEPTION", "Exception " + e.toString());
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        return false;
                    }
                })
                .into(imageView);
    }

    static class ImagesViewHolder extends RecyclerView.ViewHolder{
        ImageView imageView;
        public ImagesViewHolder(View itemView) {
            super(itemView);
        }
    }
}
`

**Comment by vavan4567** [comment] 2016-02-05 23:33
I think the problem is inside RecyclerView because the issue happened when there were only 27 images. After Ive added more it has disapeared

**Comment by vavan4567** [comment] 2016-02-06 07:18
But still, I need load few images too

**Comment by vavan4567** [comment] 2016-02-06 11:13
Hi again, sorry please.
I found the issue. It is not related to the lib. Inside my custom ImageView I am override onDetachedFromWindow 
`@Override
    protected void onDetachedFromWindow () {
        setImageDrawable(null);
        if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.JELLY_BEAN) {
            setBackgroundDrawable(null);
        } else {
            setBackground(null);
        }
        setImageBitmap(null);
        System.gc();
        super.onDetachedFromWindow();
    }`
I removed it and everything works.
Also I think few month ago I got this issue and created same issue here :) Now I remember. Hope will be usefull for someone

**Comment by TWiStErRob** [comment] 2016-02-06 11:46
Wow, you really made sure everything is cleared out :) You can leave the `setBackground*` calls, those don't affect Glide, but any Glide-managed `ImageView`s should not call `setImage*` between calls to `Glide....into(imageView)` and `Glide.clear(imageView)`; that's when Glide targets assume ownership over the image contents. Using the correct scope in `Glide.with` also clears the views when they're not used any more.

Closing as duplicate of #715 (the issue you mentioned).

Just out of curiosity: what is that circle-line-circle-line-circle on your screenshot?

**Closed by TWiStErRob** 2016-02-06 11:46 UTC
Labels: duplicate, question

**Comment by vavan4567** [comment] 2016-02-06 12:18
When I am presing 'alt' + 'print screen' to make SS it appears on the emulator. I think it is multytouch emulation in new android emulator. B t w new emulator is very good, much better even than Genymotion
