### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Activity has been destroyed

### ISSUE THREAD

**Issue by shawnlinboy** [bumptech/glide#850] opened 2015-12-29 10:55 UTC
My Glide version is 3.6.1 and here I got a IllegalStateException.
Should Glide handle this problem internally?

```
java.lang.RuntimeException: Unable to destroy activity {MY PACKAGE NAME}: java.lang.IllegalStateException: Activity has been destroyed
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4097)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4115)
    at android.app.ActivityThread.access$1400(ActivityThread.java:177)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5771)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
Caused by: java.lang.IllegalStateException: Activity has been destroyed
    at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1383)
    at android.app.BackStackRecord.commitInternal(BackStackRecord.java:745)
    at android.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:725)
    at com.bumptech.glide.manager.RequestManagerRetriever.getRequestManagerFragment(SourceFile:159)
    at com.bumptech.glide.manager.RequestManagerFragment.onAttach(SourceFile:117)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:865)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1079)
    at android.app.BackStackRecord.run(BackStackRecord.java:852)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1485)
    at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1929)
    at android.app.Fragment.performDestroy(Fragment.java:2279)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1079)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1061)
    at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1930)
    at android.app.Activity.performDestroy(Activity.java:6297)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1151)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4084)
    ... 10 more
```

**Comment by TWiStErRob** [comment] 2015-12-29 11:34
Something probably needs to be done as it comes up sometimes, but we need a consistent repro to figure out what's going on. Can you consistently repro this? Can you make a mini project that demonstrates? Are you doing anything Glide related in the teardown methods or async task? Or more generally can you share the relevant bits of the code?

Can you please read #795 and #803 to see where we stand around onDestroy, yours it not necessarily a dupe, but those two should give you ideas.

For what I can decipher from the stack: there was a load started earlier (say, `onCreate`), then `finish()` was called on the activity destroying everything, but the Glide load still trying to finish. So the problem is that the activity terminated too early. These are just guesses, it would be nice to debug this.

**Comment by shawnlinboy** [comment] 2015-12-29 11:46
Thanks 4 your reply @TWiStErRob .

This Stack trace was reported by my app's built-in User Behavior Collector and I've noticed it because this crash was frequently happened in these days.

I think I'll follow your advice to have a try and will provide you with a  consistent repro if I need your further help.

**Comment by TWiStErRob** [comment] 2015-12-29 12:01
Please report back even if you found the problem and fixed it, because it may help others in the future.

**Comment by alashow** [comment] 2015-12-30 21:32
I also saw this exception several times. Usually it causes when activity closes and in the same time recyclerView/listView adapter tries to draw views, which uses glide.

I fixed this with creating glide wrapper.

```java
public static void networkImage(Context context, String imageUrl, ImageView targetView, RequestListener requestListener, Drawable imagePlaceholder) {
        if (context instanceof Activity) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1 && ((Activity) context).isDestroyed()) {
                return;
            }
        }

        if (context != null) {
            Logger.d("Loading network image: %s", imageUrl);
            DrawableRequestBuilder requestBuilder = Glide.with(context)
                .load(imageUrl)
                .diskCacheStrategy(DiskCacheStrategy.ALL);

            if (requestListener != null) {
                requestBuilder.listener(requestListener);
            }

            if (imagePlaceholder != null) {
                requestBuilder.placeholder(imagePlaceholder);
            }

            requestBuilder.into(targetView);
        }
    }
```

But after, i realised that if i use context from targetView, this exception don't thrown

```java
public static void networkImage(String imageUrl, ImageView targetView, RequestListener requestListener, Drawable imagePlaceholder) {
        if (targetView != null) {
            Logger.d("Loading network image: %s", imageUrl);
            DrawableRequestBuilder requestBuilder = Glide.with(targetView.getContext())
                .load(imageUrl)
                .diskCacheStrategy(DiskCacheStrategy.ALL);

            if (requestListener != null) {
                requestBuilder.listener(requestListener);
            }

            if (imagePlaceholder != null) {
                requestBuilder.placeholder(imagePlaceholder);
            }

            requestBuilder.into(targetView);
        }
    }
```

**Comment by TWiStErRob** [comment] 2015-12-30 21:53
Huh, that `getContext` is weird. I thought that's the same as the activity. You should remember that automatic resource freeing is only done if you give Fragment or Activity to Glide.

It sounds like we need to clear the adapter (`list.setAdapter(null)`) in onStop or somewhere relevant to prevent loads starting after teardown of the activity started. This should prevent further bind calls, even if the list is scrolling when the back button {or similar) is pressed.

**Comment by shawnlinboy** [comment] 2016-01-10 11:16
I'd like to share what I'm trying to do with this problem in these days.

In my app, I was trying to load a pic in a fragment, let's call it MyMainFragment, the MyMainFragment's attached activity maintained a AsyncTask object and I was trying to add this fragment inside its onPostExecute() method, and the example code was like: 

```java 
private class FireUpTask extends AsyncTask<Void, Void,Void> {

        @Override
        protected Void doInBackground(Void... params) {
            handleIntent();
            return null;
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);
            initFragment();
        }
    }

    private void initFragment() {
        if (!isDestroyed()) {
            FragmentTransaction fragmentTransaction = getFragmentManager().beginTransaction();
            fragmentTransaction.add(R.id.main_container, MyMainFragment.newInstance());
            fragmentTransaction.commitAllowingStateLoss();
        }
    }
```

I was trying to execute FireUpTask inside Activity's onCreate() method no matter what the activity's state is, and this may cause the problem above.

I looked up AOSP, and I was wondering if this should be the proper way to update your ui or your fragment. http://androidxref.com/6.0.0_r1/xref/packages/apps/Dialer/src/com/android/dialer/calllog/ClearCallLogDialog.java#74

So maybe I should modify my code like this:

```java 
private class FireUpTask extends AsyncTask<Void, Void,Void> {

        @Override
        protected Void doInBackground(Void... params) {
            handleIntent();
            return null;
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);
            if (isDestroyed() || isFinishing()) {
                return;
            }
            initFragment();
        }
    }

    private void initFragment() {
            FragmentTransaction fragmentTransaction = getFragmentManager().beginTransaction();
            fragmentTransaction.add(R.id.main_container, MyMainFragment.newInstance());
            fragmentTransaction.commitAllowingStateLoss();
    }
```

I've pushed this change to my git repository, the result still not been tested but I think this should be a solution.

**Comment by TWiStErRob** [comment] 2016-01-10 11:37
Thabks for the details, that looks reasonable.

You could also leverage [`AsyncTask.cancel`](http://developer.android.com/reference/android/os/AsyncTask.html#cancel(boolean)): execute the task in onStart, and cancel in onStop (check  the activity life cycle diagram). This way `initFragment` won't be called if its result is not used. Didn't test this, but sounds logical.

**Comment by Jayvd** [comment] 2016-01-19 07:33
Is this gonna be fixed in the future release? @TWiStErRob @shawnlinboy . I have one of these random crashes too.

**Comment by shawnlinboy** [comment] 2016-01-19 07:48
@Jayvd Try to review your code, make sure your entrance of using glide is safe. I've got no idea if Glide will fix this in future release. Looks like we can avoid this by ourself.

**Comment by Jayvd** [comment] 2016-01-19 08:10
@shawnlinboy Yes we could fix it ourselves, but then our code would pretty damn ugly.

**Comment by TWiStErRob** [comment] 2016-01-19 09:41
@Jayvd I think it is just bad practice to swallow everything. There are some cases when you need to figure out a better way of doing things. I hate that my devices live one day on battery and I think this is one example which is a potential for drain. You want to do something that the user doesn't want to and won't ever see, so why bother the CPU/network/I/O usage -> battery drain?

> code would pretty damn ugly

From personal experience, sadly, that's when you're entering the real world of Android, and advanced framework usage.

@sjudd what do you think, would it be reasonable to check the condition ourselves?

**Comment by sjudd** [comment] 2016-01-19 19:38
When the Activity is destroyed, Glide is unable to start a new load (if an application context or fragment context is provided). We can't start a new load because we're unable to obtain a valid Context. We can either silently ignore the request, or we can throw an exception.

Typically this error is a developer error that occurs because someone is misusing AsyncTasks (allowing them to finish after an Activity is destroyed) or otherwise attempting to start loads that will never complete. That said, I think we also found a case where it occurs due to weirdness in the framework or support libraries around nested Fragments.

There is a work around for the nested Fragment case where there is no developer error where you can simply acquire RequestManager early in OnCreate using Glide.with() and pass it around rather than calling Glide.with() for every new load. 

I'm still not convinced that we're better off silently not starting a load, given that the common case is a developer error and that a workaround exists.

**Comment by shawnlinboy** [comment] 2016-03-07 07:38
I'm afraid I have to reopen this issue cuz it was sadly happened again.

```
java.lang.RuntimeException: Unable to destroy activity {com***date/c***Activity}: java.lang.IllegalStateException: Activity has been destroyed
   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4177)
   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4195)
   at android.app.ActivityThread.-wrap5(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614)
   at android.os.Handler.dispatchMessage(Handler.java:111)
   at android.os.Looper.loop(Looper.java:207)
   at android.app.ActivityThread.main(ActivityThread.java:5881)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:918)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.IllegalStateException: Activity has been destroyed
   at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1468)
   at android.app.BackStackRecord.commitInternal(BackStackRecord.java:692)
   at android.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:672)
   at com.bumptech.glide.manager.n.a(SourceFile:159)
   at com.bumptech.glide.manager.RequestManagerFragment.onAttach(SourceFile:117)
   at android.app.Fragment.onAttach(Fragment.java:1391)
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:945)
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1161)
   at android.app.BackStackRecord.run(BackStackRecord.java:800)
   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1570)
   at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2015)
   at android.app.Fragment.performDestroy(Fragment.java:2446)
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1111)
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1161)
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1143)
   at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2016)
   at android.app.FragmentController.dispatchDestroy(FragmentController.java:218)
   at android.app.Activity.performDestroy(Activity.java:6535)
   at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1172)
   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4164)
... 9 more
```

**Comment by shawnlinboy** [comment] 2016-03-07 07:47
@sjudd This error occurs in a high probability while our testers running monkey test, though real users may not encounter this problem, but i still believe that there must be something wrong.

**Comment by TWiStErRob** [comment] 2016-03-07 10:20
Can you acquire a recording of the monkey to see what's happening? (Logs/screenshots)
Is this the same activity, or another that you may have not fixed up yet?

**Comment by sonique6784** [comment] 2016-05-17 01:34
I do have the same issue. It happens when I moved from fragment support to "native" Fragment

**Comment by LiHanGuang** [comment] 2016-05-27 07:24
Hello @TWiStErRob:

I want to ask you a question, thanks.

```java
@TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
    RequestManagerFragment getRequestManagerFragment(final android.app.FragmentManager fm) {
        RequestManagerFragment current = (RequestManagerFragment) fm.findFragmentByTag(FRAGMENT_TAG);   <----  line: 153
        if (current == null) {
            current = pendingRequestManagerFragments.get(fm);
            if (current == null) {
                current = new RequestManagerFragment();
                pendingRequestManagerFragments.put(fm, current);
                fm.beginTransaction().add(current, FRAGMENT_TAG).commitAllowingStateLoss();  <-----  (2)   line:  159
                handler.obtainMessage(ID_REMOVE_FRAGMENT_MANAGER, fm).sendToTarget();
            }
        }
        return current;
    }
```

```ruby
Caused by: java.lang.IllegalStateException: Activity has been destroyed
    at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1383)
    at android.app.BackStackRecord.commitInternal(BackStackRecord.java:745)
    at android.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:725)
    at com.bumptech.glide.manager.RequestManagerRetriever.getRequestManagerFragment(SourceFile:159)  <---  (2)
    at com.bumptech.glide.manager.RequestManagerFragment.onAttach(SourceFile:117)  <----- (1)
```


see **(1)**,   **RequestManagerFragment instance**  is already  exist!

at this moment,  why still can run into **line: 159**?  That means ** fm.findFragmentByTag(FRAGMENT_TAG);  in line: 153**  return false?

**Comment by TWiStErRob** [comment] 2016-05-27 08:46
@LiHanGuang huh interesting. So you're expecting `fm` to give you `this` of `onAttach`. I have two possibilities for you: either the fragment manager only returns already attached fragments (or something even later in their lifecycle), or the fragment manager is the children for that `this` so `this` itself is not included there. And looking at the [code](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/manager/RequestManagerFragment.java#L123) shows it a third option: the fragment is trying to register itself with the activity's root manager and that exception is caught.

**Comment by LiHanGuang** [comment] 2016-05-30 02:18
@TWiStErRob 

I just see that [code](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/manager/RequestManagerFragment.java) that glide dev commit  after version  glide 3.6.1.

```java 
// after version 3.6.1
    private void registerFragmentWithRoot(Activity activity) {
    unregisterFragmentWithRoot();
    rootRequestManagerFragment = RequestManagerRetriever.get()
        .getRequestManagerFragment(activity.getFragmentManager(), null);
    if (rootRequestManagerFragment != this) {
      rootRequestManagerFragment.addChildRequestManagerFragment(this);
    }
  }

  @Override
  public void onAttach(Activity activity) {
    super.onAttach(activity);
    try {
      registerFragmentWithRoot(activity);
    } catch (IllegalStateException e) {
      // OnAttach can be called after the activity is destroyed, see #497.
      if (Log.isLoggable(TAG, Log.WARN)) {
        Log.w(TAG, "Unable to register fragment with root", e);
      }
    }
  }
```

### Q1 ###
Is the **fix about (#497)[https://github.com/bumptech/glide/issues/497]**  and this issue?

---

Additionly, 

> either the fragment manager only returns already attached fragments (or something even later in their lifecycle)

can I avoid this problem like below?

```java
// RequestManagerRetriever.java

RequestManagerFragment getRequestManagerFragment(
      final android.app.FragmentManager fm, android.app.Fragment parentHint) {
    RequestManagerFragment current = (RequestManagerFragment) fm.findFragmentByTag(FRAGMENT_TAG);
    if (current == null) {
      current = pendingRequestManagerFragments.get(fm);
      if (current == null) {
        current = new RequestManagerFragment();
        current.setParentFragmentHint(parentHint);
        pendingRequestManagerFragments.put(fm, current);
        fm.beginTransaction().add(current, FRAGMENT_TAG).commitAllowingStateLoss();
        fm.executePendingTransactions(); // <-------  add this line......
        handler.obtainMessage(ID_REMOVE_FRAGMENT_MANAGER, fm).sendToTarget();
      }
    }
    return current;
  }
```

**Comment by TWiStErRob** [comment] 2016-05-30 09:31
That part you quoted is not valid. That was my hypothesis, but it was debunked when I looked at the code.
I'm not sure execute pending would be a good idea. It changes how fragments work. Imagine you are adding some fragments with a normal transaction in onCreate, if we add that line, then a Glide load at the end of onCreate will possibly try to execute the commit of those other fragments as well.

Do you have a consistent repro so you can test the behaviour of this modification?

**Comment by sjudd** [comment] 2016-05-30 15:28
You can't use executePendingTransactions, see #117.

**Comment by rajibhasan11** [comment] 2016-08-17 08:35
I this exception will happen if happens any leak in the view (activity, fragment or dialog etc). So need to check that view is not destroyed before to load image from a URL.

**Comment by electrolobzik** [comment] 2016-10-27 16:47
I have also got this issue when used solution from #1337 for clearing views in fragment's `onDestroyView()`. I want to describe the source of my issue maybe it will help somebody. This was my code:

```java
private RequestManager imageLoader;

@Override
public void onDestroyView() {
	super.onDestroyView();
	getImageLoader().onDestroy();
}

protected RequestManager getImageLoader() {
	if (imageLoader == null) {
		imageLoader = Glide.with(this);
	}
	return imageLoader;
}
```

If `Glide` was used somewhere in the fragment everything worked fine. But if the fragment didn't call `getImageLoader()` during it's normal work the app crashed during `onDestroy()`. And this is what happened: 
1. when fragment called `getImageLoader()` in `onDestroyView()` Glide tried to create his `RequestManagerFragment` and attach it to the main fragment.
2. fragment transaction was queued but not executed
3. in `onDestroy()` fragment executed pending transactions and attaches glide's `RequestManagerFragment`
4. `RequestManagerFragment` tries to do it's business and gets this error

So my solution was to avoid creating of `RequestManagerFragment` in destroy flow of the fragment. I just replaced `getImageLoader()` with `if (imageLoader != null)` and the issue gone:

```java
@Override
public void onDestroyView() {
	super.onDestroyView();

	if (imageLoader != null) {
		imageLoader.onDestroy();
	}
}
```

**Comment by jt-gilkeson** [comment] 2016-11-11 20:21
The above solution is not a fix-all.  If you have fragments in a viewpager, the onDestroyView code will kill all of the images in the other fragments in the viewpager when one of them is destroyed.

**Comment by TWiStErRob** [comment] 2016-11-11 22:20
@jt-gilkeson hmm, that's an interesting issue. I think that shouldn't happen if you use the fragment's `this` on the UI thread. Take a look at `RequestManagerRetriever#get(Fragment)` and you should see that it uses `getChildFragmentManager` whenever available. Are you on an old device perhaps with non-support Fragments?

**Comment by jt-gilkeson** [comment] 2016-11-11 23:10
@TWiStErRob That may be my problem, I was using getContext() in the fragment, not this.

**Comment by alashow** [comment] 2016-11-11 23:18
Maybe someone will find this useful:
https://gist.github.com/alashow/2e131591994d8499be02a4c0bb648cfb

**Comment by TWiStErRob** [comment] 2016-11-11 23:23
@jt-gilkeson Yep, if you destroy the activity manager everything loaded with the activity manager is cleared: http://stackoverflow.com/a/32887693 Remember that manually calling `onDestroy` is not how the API was designed.

**Comment by jt-gilkeson** [comment] 2016-11-11 23:35
@TWiStErRob I imagine having to do any of this stuff to not crash your app, is not how the API was intended to be designed :)

**Comment by TWiStErRob** [comment] 2016-11-11 23:41
True that, but https://github.com/bumptech/glide/issues/850#issuecomment-172962304. Also this is likely not fixed yet, because there's no consistent repro that is not coming from a weird Glide usage (starting a load after destroy).

**Comment by jt-gilkeson** [comment] 2016-11-11 23:51
Gotcha, so maybe we don't need any of this cleanup stuff if we would have correctly passed in the fragment's this pointer in the first place?  It looks like the original implementation we had was passing in getActivity() (which, when we saw the crash show up, we mistakenly changed to getContext() from the fragment - thinking it would use the fragment).  Sorry for all the confusion - when we saw the crash we looked for issues containing the crash and ended up down this path - which now sounds like a red herring, when the real issue for us was not using the right with() param.

**Comment by jt-gilkeson** [comment] 2016-11-15 01:07
OK I've got a reproducible instance of the original issue, which may help track down the issue (I'm just using the with(fragment),  not doing the onDestory cleanup):

We have a tablet layout which in landscape has a fragment with a master / detail layout.  

The master fragment (retained instance) has on the left hand side a list of items, and a frame on the right hand side where an embedded fragment gets loaded.  If you rotate to portrait, only the master view is shown and clicking on the list selection launches an individual activity.  

The landscape detail view can contain a UserReviewsFragment fragment (if selected in the list) where we care calling:

`	Glide.with(this).load(pictureUrl).crossFade().into(holder.reviewRowImage);`

We switch the fragment in the detail view via:

```
	FragmentManager fm = getChildFragmentManager();
	FragmentTransaction ft = fm.beginTransaction();
	ft.replace(R.id.profile_fragment_holder, frag, null);
	ft.commitAllowingStateLoss();
```

Where frag may be UserReviewsFragment.newInstance(); or another fragment created via newInstance();

If we rotate to portrait (which does not have the detail fragment), then rotate back to landscape, when we try to select the UserReviewsFragment  (which has the glide call in it), it crashes with the following:  

```
Fatal Exception: java.lang.IllegalStateException: Activity has been destroyed
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(SourceFile:1515)
       at android.support.v4.app.BackStackRecord.commitInternal(SourceFile:638)
       at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(SourceFile:621)
       at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(SourceFile:187)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SourceFile:116)
       at android.support.v4.app.Fragment.onAttach(SourceFile:1165)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1019)
       at android.support.v4.app.BackStackRecord.setLastIn(SourceFile:779)
       at android.support.v4.app.BackStackRecord.calculateFragments(SourceFile:802)
       at android.support.v4.app.BackStackRecord.run(SourceFile:660)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(SourceFile:1617)
       at android.support.v4.app.FragmentManagerImpl$1.run(SourceFile:517)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

**Comment by jt-gilkeson** [comment] 2016-11-17 01:22
I've created a new item for this, since my repro steps are very specific. 
https://github.com/bumptech/glide/issues/1592

**Comment by sjudd** [comment] 2017-11-12 20:07
Duplicate of #1592

**Closed by sjudd** 2017-11-12 20:07 UTC
Labels: bug, question, repro-needed, v3
