### ISSUE TITLE
Glide Activity has been destroyed

### ISSUE THREAD

**Issue by KgdFnYpeu** [bumptech/glide#1418] opened 2016-08-17 07:35 UTC
my app get more the exception, from data statistics Occurrence times:580 
Affect the number of users:350，I think is background thread load img,but click backKey, the activity is destroy,and load imageview。i want glide add method on Activity/Fragment onDestroy  Glide.cancel(Activity/Fragment) , cancel this activity all load request, thank you help!

- 1. java.lang.RuntimeException: Unable to destroy activity {xxx.xxx.xxx.MainActivity}: java.lang.IllegalStateException: Activity has been destroyed
- 2. 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3988)
- 3. 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4006)
- 4. 	at android.app.ActivityThread.access$1400(ActivityThread.java:178)
- 5. 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1524)
- 6. 	at android.os.Handler.dispatchMessage(Handler.java:111)
- 7. 	at android.os.Looper.loop(Looper.java:194)
- 8. 	at android.app.ActivityThread.main(ActivityThread.java:5644)
- 9. 	at java.lang.reflect.Method.invoke(Native Method)
- 10. 	at java.lang.reflect.Method.invoke(Method.java:372)
- 11. 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1079)
- 12. 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
- 13. Caused by: java.lang.IllegalStateException: Activity has been destroyed
- 14. 	at android.support.v4.app.al.a(FragmentManager.java:1515)
- 15. 	at android.support.v4.app.s.a(BackStackRecord.java:638)
- 16. 	at android.support.v4.app.s.i(BackStackRecord.java:621)
- 17. 	at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
- 18. 	at com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SupportRequestManagerFragment.java:116)
- 19. 	at android.support.v4.app.Fragment.onAttach(Fragment.java:1165)
- 20. 	at android.support.v4.app.al.a(FragmentManager.java:1019)
- 21. 	at android.support.v4.app.al.a(FragmentManager.java:1252)
- 22. 	at android.support.v4.app.s.run(BackStackRecord.java:742)
- 23. 	at android.support.v4.app.al.j(FragmentManager.java:1617)
- 24. 	at android.support.v4.app.al.w(FragmentManager.java:2082)
- 25. 	at android.support.v4.app.Fragment.performDestroy(Fragment.java:2198)
- 26. 	at android.support.v4.app.al.a(FragmentManager.java:1196)
- 27. 	at android.support.v4.app.al.a(FragmentManager.java:1252)
- 28. 	at android.support.v4.app.al.a(FragmentManager.java:1234)
- 29. 	at android.support.v4.app.al.w(FragmentManager.java:2083)
- 30. 	at android.support.v4.app.Fragment.performDestroy(Fragment.java:2198)
- 31. 	at android.support.v4.app.al.a(FragmentManager.java:1196)
- 32. 	at android.support.v4.app.al.a(FragmentManager.java:1252)
- 33. 	at android.support.v4.app.al.a(FragmentManager.java:1234)
- 34. 	at android.support.v4.app.al.w(FragmentManager.java:2083)
- 35. 	at android.support.v4.app.ai.o(FragmentController.java:244)
- 36. 	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:369)
- 37. 	at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:193)
- 38. 	at com.fxtv.framework.frame.BaseToolBarActivity.onDestroy(BaseToolBarActivity.java:104)
- 39. 	at android.app.Activity.performDestroy(Activity.java:6292)
- 40. 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1148)
- 41. 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3975)
- 42. 	... 10 more
- 43. java.lang.IllegalStateException: Activity has been destroyed
- 44. 	at android.support.v4.app.al.a(FragmentManager.java:1515)
- 45. 	at android.support.v4.app.s.a(BackStackRecord.java:638)
- 46. 	at android.support.v4.app.s.i(BackStackRecord.java:621)
- 47. 	at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
- 48. 	at com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SupportRequestManagerFragment.java:116)
- 49. 	at android.support.v4.app.Fragment.onAttach(Fragment.java:1165)
- 50. 	at android.support.v4.app.al.a(FragmentManager.java:1019)
- 51. 	at android.support.v4.app.al.a(FragmentManager.java:1252)
- 52. 	at android.support.v4.app.s.run(BackStackRecord.java:742)
- 53. 	at android.support.v4.app.al.j(FragmentManager.java:1617)
- 54. 	at android.support.v4.app.al.w(FragmentManager.java:2082)
- 55. 	at android.support.v4.app.Fragment.performDestroy(Fragment.java:2198)
- 56. 	at android.support.v4.app.al.a(FragmentManager.java:1196)
- 57. 	at android.support.v4.app.al.a(FragmentManager.java:1252)
- 58. 	at android.support.v4.app.al.a(FragmentManager.java:1234)
- 59. 	at android.support.v4.app.al.w(FragmentManager.java:2083)
- 60. 	at android.support.v4.app.Fragment.performDestroy(Fragment.java:2198)
- 61. 	at android.support.v4.app.al.a(FragmentManager.java:1196)
- 62. 	at android.support.v4.app.al.a(FragmentManager.java:1252)
- 63. 	at android.support.v4.app.al.a(FragmentManager.java:1234)
- 64. 	at android.support.v4.app.al.w(FragmentManager.java:2083)
- 65. 	at android.support.v4.app.ai.o(FragmentController.java:244)
- 66. 	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:369)
- 67. 	at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:193)
- 68. 	at com.fxtv.framework.frame.BaseToolBarActivity.onDestroy(BaseToolBarActivity.java:104)
- 69. 	at android.app.Activity.performDestroy(Activity.java:6292)
- 70. 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1148)
- 71. 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3975)
- 72. 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4006)
- 73. 	at android.app.ActivityThread.access$1400(ActivityThread.java:178)
- 74. 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1524)
- 75. 	at android.os.Handler.dispatchMessage(Handler.java:111)
- 76. 	at android.os.Looper.loop(Looper.java:194)
- 77. 	at android.app.ActivityThread.main(ActivityThread.java:5644)
- 78. 	at java.lang.reflect.Method.invoke(Native Method)
- 79. 	at java.lang.reflect.Method.invoke(Method.java:372)
- 80. 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1079)
- 81. 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

**Comment by Teovald** [comment] 2016-08-19 17:05
It looks like a duplicate of https://github.com/bumptech/glide/issues/497  
It will be published with Glide 3.8
In the meantime, you can just catch the exception yourself in onAttach

**Comment by TWiStErRob** [comment] 2016-08-19 17:27
Thanks @Teovald, good catch.

Alternatively: https://github.com/bumptech/glide/wiki/Snapshots

**Closed by TWiStErRob** 2016-08-19 17:27 UTC
Labels: bug, duplicate
