### ISSUE TITLE
4.5.0的bug反馈(4.5.0 bug feedback):

### ISSUE THREAD

**Issue by azxcffdgadf** [bumptech/glide#3554] opened 2019-03-07 01:52 UTC
bug如下(bug E.g):文件大小有300M(File size is 300M)
W/Glide: Load failed for http://192.168.1.2/SD/AMBA/190305000/094223AA.MP4 with size [203x130]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException(No content provider: http://192.168.1.2/SD/AMBA/190305000/094223AA.MP4)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL, DataCacheKey{sourceKey=http://192.168.1.2/SD/AMBA/190305000/094223AA.MP4, signature=EmptySignature}
    There was 1 cause:
    java.io.FileNotFoundException(No content provider: http://192.168.1.2/SD/AMBA/190305000/094223AA.MP4)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class java.io.FileNotFoundException: No content provider: http://192.168.1.2/SD/AMBA/190305000/094223AA.MP4
谁能帮助我解决这个问题?谢谢(Can anyone help me solve this problem? Thank you!)

**Comment by sjudd** [comment] 2019-03-08 15:22
Duplicate of #2894

**Closed by sjudd** 2019-03-08 15:22 UTC
