### ISSUE TITLE
GifFrameLoader:NEP Crash When call android.graphics.Bitmap.getWidth() 

### ISSUE THREAD

**Issue by scau-beyondboy** [bumptech/glide#3082] opened 2018-05-11 05:12 UTC
Glide Version: 4.2.0
Integration libraries: OkHttp3
Device/Android Version: SM-G5510;Android 6.0.1,level 23

Wrap Code:

```
public void onlyLoadAsGifBitmap(Context context, final View imageView, final String url, int width, int height, final int placeHoldId){
        if(isActivityDestroy(context)){
            return;
        }
        GlideApp.with(context).asGif().load(url).override(width, height).into(new SimpleTarget<GifDrawable>() {
            @Override
            public void onResourceReady(GifDrawable resource, Transition<? super GifDrawable> transition) {
                if(resource==null){
                    imageView.setBackgroundResource(placeHoldId);
                    return;
                }
                if(imageView instanceof  ImageView){
                    ((ImageView) imageView).setImageDrawable(resource);
                }else {
                    imageView.setBackground(resource);
                }
            }
            @Override
            public void onLoadFailed( Drawable errorDrawable) {
                imageView.setBackgroundResource(placeHoldId);
            }
        });
    }
```

Called Code:

`onlyLoadAsGifBitmap(LauncherUI.this,
                                        tiaImageView, imageUrl, UITools.getWidth(), UITools.getHeight(),
                                        R.drawable.flash);`

Crash Report:

`java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference 
com.bumptech.glide.load.resource.gif.GifFrameLoader.int getWidth()(SourceFile:126) 
com.bumptech.glide.load.resource.gif.GifDrawable.int getIntrinsicWidth()(SourceFile:215) 
android.widget.ImageView.invalidateDrawable(ImageView.java:243) 
android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:844) 
android.graphics.drawable.Drawable.setVisible(Drawable.java:1575) 
com.bumptech.glide.load.resource.gif.GifDrawable.boolean setVisible(boolean,boolean)(SourceFile:210) 
android.widget.ImageView.onDetachedFromWindow(ImageView.java:1511) 
android.view.View.dispatchDetachedFromWindow(View.java:15916) 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3377) 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3377) 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3377) 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3377) 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3377) 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3377) 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3377) 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3377) 
android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3838) 
android.view.ViewRootImpl.doDie(ViewRootImpl.java:7087) 
android.view.ViewRootImpl.die(ViewRootImpl.java:7060) 
android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:424) 
android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:379) 
android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:140) 
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5190) 
android.app.ActivityThread.access$1700(ActivityThread.java:229) 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1880) 
android.os.Handler.dispatchMessage(Handler.java:102) 
android.os.Looper.loop(Looper.java:148) 
android.app.ActivityThread.main(ActivityThread.java:7410) 
java.lang.reflect.Method.invoke(Native Method) 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) `

now the crash occurs less,only affecting  two users.when readed #2282 and #2231 ,i find not same like  those,i only load gifDrawable for the view,instead of using cross-fade animation. i read this [answer](https://stackoverflow.com/questions/40450023/caused-by-java-lang-nullpointerexception-attempt-to-invoke-virtual-method-int) and souce code related to gifDrawable ,but i still do'nt kown detail reason..

**Comment by sjudd** [comment] 2018-05-14 15:54
Probably a duplicate of #2555.

You should also implement [``onLoadCleared][1] on remove the drawable from the view when it's called.

[1]: http://bumptech.github.io/glide/javadocs/470/com/bumptech/glide/request/target/BaseTarget.html#onLoadCleared-android.graphics.drawable.Drawable-

**Closed by sjudd** 2018-05-14 15:54 UTC

**Comment by wangrunxiang** [comment] 2018-11-26 09:52
how can i remove the drawable

**Comment by shahidgeek** [comment] 2019-08-29 15:20
https://github.com/bumptech/glide/issues/3082#issuecomment-388867763

how can I remove the drawable?
