### ISSUE TITLE
no find GlideApp

### ISSUE THREAD

**Issue by 2Exception** [bumptech/glide#2784] opened 2018-01-03 01:54 UTC
GlideApp
    .with(myFragment)
    .load(url)
    .centerCrop()
    .placeholder(R.drawable.loading_spinner)
    .into(myImageView);

implementation 'com.github.bumptech.glide:glide:4.4.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'

no find GlideApp

**Comment by sjudd** [comment] 2018-01-03 03:50
Duplicate of #1939

**Closed by sjudd** 2018-01-03 03:50 UTC
