### ISSUE TITLE
java.lang.IllegalArgumentException: Bad position (limit 917504): 917634

### ISSUE THREAD

**Issue by anilshar** [bumptech/glide#1282] opened 2016-06-22 18:00 UTC
I was trying to load a jpeg image which had frames like gif.  
The library failed to decode the below images
 http://img0.ropose.com/story/BcjX_1466616614110_d6cbd61b-e288-40ae-90d1-e5742af50c27.jpeg
http://img0.ropose.com/story/wPqT_1466617581389_b8ce67d3-38dd-4795-96bf-df955fdb2969.jpeg

**Glide Version**: Glide 3.7.0 

**Integration libraries**: Using okhttp 3.0

```
0 = {StackTraceElement@6571} "java.nio.Buffer.positionImpl(Buffer.java:351)"
1 = {StackTraceElement@6572} "java.nio.Buffer.position(Buffer.java:345)"
2 = {StackTraceElement@6573} "com.bumptech.glide.gifdecoder.GifHeaderParser.skip(GifHeaderParser.java:319)"
3 = {StackTraceElement@6574} "com.bumptech.glide.gifdecoder.GifHeaderParser.skipImageData(GifHeaderParser.java:309)"
4 = {StackTraceElement@6575} "com.bumptech.glide.gifdecoder.GifHeaderParser.readBitmap(GifHeaderParser.java:202)"
5 = {StackTraceElement@6576} "com.bumptech.glide.gifdecoder.GifHeaderParser.readContents(GifHeaderParser.java:93)"
6 = {StackTraceElement@6577} "com.bumptech.glide.gifdecoder.GifHeaderParser.parseHeader(GifHeaderParser.java:67)"
7 = {StackTraceElement@6578} "com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:69)"
8 = {StackTraceElement@6579} "com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:61)"
9 = {StackTraceElement@6580} "com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:26)"
10 = {StackTraceElement@6581} "com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeGifWrapper(GifBitmapWrapperResourceDecoder.java:101)"
11 = {StackTraceElement@6582} "com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:87)"
12 = {StackTraceElement@6583} "com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)"
13 = {StackTraceElement@6584} "com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)"
14 = {StackTraceElement@6585} "com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)"
15 = {StackTraceElement@6586} "com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)"
16 = {StackTraceElement@6587} "com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)"
17 = {StackTraceElement@6588} "com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)"
18 = {StackTraceElement@6589} "com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)"
19 = {StackTraceElement@6590} "com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)"
20 = {StackTraceElement@6591} "com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)"
21 = {StackTraceElement@6592} "java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)"
22 = {StackTraceElement@6593} "java.util.concurrent.FutureTask.run(FutureTask.java:237)"
23 = {StackTraceElement@6594} "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)"
24 = {StackTraceElement@6595} "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)"
25 = {StackTraceElement@6596} "java.lang.Thread.run(Thread.java:818)"
26 = {StackTraceElement@6597} "com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)"
```

**Comment by TWiStErRob** [comment] 2016-06-22 18:07
You gotta give more info than this.
Based on this though: the GIF file is invalid/partial and a frame/header cannot be decoded see #1253

**Comment by anilshar** [comment] 2016-06-22 18:09
I have update the above comment. Please have a look.

**Comment by TWiStErRob** [comment] 2016-06-22 20:59
Yep, it's the same issue. JPEG doesn't have frames it's a single image. Both of those files are GIF files, highly likely partial ones, missing some bytes from the end. Closing as a duplicate of #1145

Try peeking at it with a text or hex editor to see the file format.

**Closed by TWiStErRob** 2016-06-22 20:59 UTC
Labels: duplicate
