### ISSUE TITLE
RoundedCorners have problem on lower divice

### ISSUE THREAD

**Issue by weidongjian** [bumptech/glide#2479] opened 2017-10-13 01:20 UTC
**Glide Version**:4.2.0 , No problem on Glide 4.1.1

**Integration libraries**:okhttp 4.2.0

**Device/Android Version**:Smartisam SM901 android 6.0.1

**Issue details / Repro steps / Use case background**: 
Image display error on this devices.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(this)
 .load(imageUrl)
 .placeholder(LoadingColorManager.getHotItemDrawable())
 .centerCrop()
  .transform(new RoundedCorners(20))
 .into(imageView);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:app="http://schemas.android.com/apk/res-auto"
             android:layout_width="match_parent"
             android:layout_height="210dp"
             android:foreground="?android:attr/selectableItemBackground">

    <ImageView
        android:id="@+id/iv_cover"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />

    <LinearLayout
        android:layout_gravity="bottom"
        android:layout_margin="8dp"
        android:gravity="center_vertical"
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <ImageView
            android:id="@+id/iv_user_head"
            android:layout_width="28dp"
            android:layout_height="28dp" />

        <TextView
            android:id="@+id/tv_user_name"
            android:textSize="12dp"
            android:singleLine="true"
            android:maxLines="1"
            android:ellipsize="end"
            android:textColor="@android:color/white"
            android:layout_marginLeft="4dp"
            android:layout_marginRight="4dp"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1" />

        <TextView
            android:id="@+id/tv_like_count"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/white"
            android:textSize="12dp" />

    </LinearLayout>

    <ImageView
        android:id="@+id/iv_video_flag"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="right|top"
        android:layout_marginRight="5dp"
        android:src="@drawable/community_icon_video"
        android:visibility="gone"/>
</FrameLayout>
```

![device-2017-10-12-172201](https://user-images.githubusercontent.com/6983015/31526143-8c891382-aff7-11e7-97c6-cde291a4ac31.png)

**Comment by sjudd** [comment] 2017-10-13 01:45
Duplicate of #2472

**Closed by sjudd** 2017-10-13 01:45 UTC
