### ISSUE TITLE
Frame + ViewPager + Glide  memory leak

### ISSUE THREAD

**Issue by huanting** [bumptech/glide#1563] opened 2016-11-02 14:02 UTC
**Glide Version**:
3.7

**Integration libraries**:
okhttp3

**Device/Android Version**:
Galaxy Nexus 4.1.1 API 16 720X1250 on Genymotion emulator

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```
I download the image from network by glide. The ui has a viewpager. The viewPager contains some fragments.  When I exit from activity some times, I view the memory from device motiors ( I click the GC some  times), the activity exists. 
  If I remove the glide, test as above, the activity doesn't exist.

In adapter, I call Glide.with(Fragment). When I debug, it call RequestManager.onDestroy(). 

I find that when call removeCallback() in EngineJob, the hasResource is true. so it can't be removed.

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
* com.energysh.drawshow.activity.MainActivity has leaked:
* GC ROOT thread com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.<Java Local> (named 'fifo-pool-thread-0')
* references com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$LoadTask.sync
* references java.util.concurrent.FutureTask$Sync.callable
* references java.util.concurrent.Executors$RunnableAdapter.task
* references com.bumptech.glide.load.engine.EngineRunnable.manager
* references com.bumptech.glide.load.engine.EngineJob.cbs
* references java.util.ArrayList.array
* references array java.lang.Object[].[0]
* references com.bumptech.glide.request.GenericRequest.target
* references com.bumptech.glide.request.target.GlideDrawableImageViewTarget.view
* references android.support.v7.widget.AppCompatImageView.mParent
* references android.widget.RelativeLayout.mContext
* leaks com.energysh.drawshow.activity.MainActivity instance

* Reference Key: 8d2d5a37-792b-4483-b624-0e9591d16137
* Device: Genymotion generic Google Galaxy Nexus - 4.1.1 - API 16 - 720x1280 vbox86p
* Android Version: 4.1.1 API: 16
* Durations: watch=5032ms, gc=118ms, heap dump=185ms, analysis=10329ms
```

**Comment by TWiStErRob** [comment] 2016-11-02 15:01
Possible duplicate of #616, please check that.

Non-removal of the callback shouldn't be a problem, because the job will be removed when the manager dies.

**Comment by huanting** [comment] 2016-11-02 15:59
i think the problem is same as issue #1044. When i dump,i click the gc 10 times. In hprof, there more than one mainActivity exist. I will try on device with android ver 6.0. And update the result later.

**Comment by huanting** [comment] 2016-11-02 17:04
I test on android  Nexus 6.0 and Nexus 5.0 on Genymotion. There is no this problem. 
![problem](https://cloud.githubusercontent.com/assets/4354923/19938417/d198a26e-a15f-11e6-9eec-d2d10c3ab5fb.png)

**Comment by TWiStErRob** [comment] 2016-11-02 17:35
Ah, yes, that too. In either case, we can't do much about it.

**Closed** 2016-11-02 17:35 UTC
Labels: duplicate, question
