### ISSUE TITLE
GIF animations playing very slow, only in 4.3.0 / 4.3.1

### ISSUE THREAD

**Issue by perracolabs** [bumptech/glide#2613] opened 2017-11-20 01:28 UTC
Test Devices: **Nexus 6. API 23 (M)**
Tested Glide versions: **4.2.0 / 4.3.0 / 4.3.1**

Issue only seen with Glide **4.3.0** & **4.3.1**
No problems with Glide **4.2.0**

Tested these 3 Glide versions on the same device, and only when using Glide 4.2.0 the GIFs framerate plays correctly.

In Glide **4.3.0/4.3.1**, GIFs animations play at very slow framerate. Around 1 FPS.

Next is one of the GIFs I've tested which plays correctly in 4.2.0. And a recording on how it actually plays when using the 4.3.0/4.3.1

(Please wait till your browser fully loads both GIF files to see correctly the actual framerate)

Original,:
![test](https://user-images.githubusercontent.com/7354233/32998237-988505b4-cd99-11e7-87c1-119a987efda3.gif)

Recording showing slow framerate, with 4.3.0:
![recording](https://user-images.githubusercontent.com/7354233/32998242-a10e3e26-cd99-11e7-8800-1d73af053450.gif)

**Comment by sjudd** [comment] 2017-11-20 01:51
Can you attach the original GIF?

**Comment by perracolabs** [comment] 2017-11-20 01:59
Next is the original  GIF.  In 4.2.0, it plays at the correct framerate.

![test](https://user-images.githubusercontent.com/7354233/32998802-6473bdba-cd9e-11e7-993b-d50ebb5c2f9e.gif)

**Comment by sjudd** [comment] 2017-11-20 05:47
I'm not able to reproduce any particular slow down in 4.3.0 or 4.3.1 with that GIF. I hard coded it into the Giphy sample in place of the Giphy logo and increased the size. On 4.2.0 and 4.3.0/4.3.1 I see roughly the same frame and overall decoding times. That's not to say there isn't room for improvement, but I don't see that anything got worse in 4.3.0.

The largest change in 4.3.0 was c4db04ed1998b7252ca4621321bcf8664be42a03 which causes GIF frames to be decoded on a separate thread pool from most of Glide's other requests. GIFs are especially sensitive to CPU contention and the new GIF only executor has fewer threads than the original executor. If you're decoding enough GIFs in parallel and have cores to spare, it's possible that you're seeing the effects of a reduction in the number of available cores. You could test that by reducing the number of GIFs you load to just the GIF in question and seeing if the performance improves.

If you have a sample app where you see the performance change substantially by changing from 4.2.0 to 4.3.0 or 4.3.1 please attach it here. For now I'm going to call this a dupe of #2471

**Closed by sjudd** 2017-11-20 05:47 UTC
Labels: needs triage

**Comment by perracolabs** [comment] 2017-11-20 20:37
Debugging Glide to figure out the issue, I’ve noticed that GIF frames never get cached, and these are continuously decoded none-stop. Is this the correct expected behavior? Shouldn’t each GIF frame be cached into a Bitmap Pool once decoded?

I’ve found that the next method is the one that slows down the framerate: 

`StandardGifDecoder.decodeBitmapData()`

It is called continuously none-stop when the GIF is playing. I would had thought that it would be called only while frames are being decoded “to be cached???”, but I couldn’t find if frames should be cached or not.

**Comment by sjudd** [comment] 2017-11-21 03:58
We avoid keeping every GIF decoded to avoid blowing out memory usage or our memory cache, so each frame is decoded on the fly. 

It's possible we could add an option that would allow you to cache all frames, but it would be very memory intensive.

**Comment by perracolabs** [comment] 2017-11-21 18:30
I don't think that adding a new option to cache frames would be a good idea. If the current behavior hasn't changed from previous versions, then adding such option would only help to mask the problem. I will keep on investigating the issue and post my findings if I can figure out why is happening.

**Comment by sjudd** [comment] 2017-11-21 18:50
Thanks, if you find anything, please post them to #2471.

I've posted a couple of ideas there already.
